### DISCUSSION TITLE
Support for top level async await when using esbuild.

### DISCUSSION THREAD

**Discussion by MattBidewell** [aws/aws-sam-cli#4611] [Questions] [answered]
Hi there!

Currently using sam cli and esbuild combo for a project and would like to make use of top level await for some initialisation work.

I've got an example project here - https://github.com/MattBidewell/sam-cli-esbuild-top-level-await

Has anyone got this working when using the esbuild and sam cli together?

I suspect the issue is because the target is es2020 but I get the same issue when targeting es2022/1 as well.

**Comment by mildaniel** [comment, marked as answer]
Hey @MattBidewell,

Thanks for providing an example, made it really quick to reproduce. I was able to getting it working by changing the target to `node16` and changing the format from `cjs` to `esm`. 

```
Metadata: # Manage esbuild properties
   BuildMethod: esbuild
   BuildProperties:
      Target: "node16"
      Format: esm
      Sourcemap: true
      EntryPoints:
        - src/handler.ts
 ```
