### DISCUSSION TITLE
SAM Typescript Lambda Beta Feature - How to Enable Local Debugging?

### DISCUSSION THREAD

**Discussion by patricktran** [aws/aws-sam-cli#4806] [Questions]
I am trying to debug my TS Lambda, but my breakpoints never hit.  Can someone please help?

I am using the SAM CLI beta feature as described here: 
https://aws.amazon.com/blogs/compute/building-typescript-projects-with-aws-sam-cli/

nodejs14.x – TypeScript
Hello World Example

```
Resources:
  HelloWorldFunction:
    Type: AWS::Serverless::Function 
    Properties:
      CodeUri: hello-world/
      Handler: app.lambdaHandler
      Runtime: nodejs14.x
      Architectures:
        - x86_64
      Environment:
        Variables:
          NODE_OPTIONS: "--enable-source-maps"
      Events:
        HelloWorld:
          Type: Api 
          Properties:
            Path: /hello
            Method: get
    Metadata: 
      BuildMethod: esbuild
      BuildProperties:
        Minify: true
        Target: "es2020"
        Sourcemap: true 
        EntryPoints:
          - app.ts
 ```

VSCode launch.json
```
{
  "configurations": [
    {
      "type": "aws-sam",
      "request": "direct-invoke",
      "invokeTarget": {
        "target": "template",
        "logicalId": "HelloWorldFunction",
        "templatePath": "/Volumes/projects/ts-lambda/template.yaml"
      },
      "lambda": {
        "runtime": "nodejs14.x"
      },
      "sam": {
        "containerBuild": false,
        "skipNewImageCheck": false
      },
      "api": {
        "httpMethod": "get"
      },
      "name": "hello-world:app.lambdaHandler (nodejs14.x)"
    }
  ]
}
```
