### DISCUSSION TITLE
Add command for appending new resources based from custom-defined templates

### DISCUSSION THREAD

**Discussion by allanchua101** [aws/aws-sam-cli#4921] [Ideas]
It would be really cool to have another cli-based command that enables developers to easily append serverless resources in their SAM templates based from their own templates. If we think about it, each team has their own expectation and standards of how a resource should be defined in their SAM templates. By providing this new set of commands, developers would be able to:

1. Easily define their templates inside the project.

```sh
sam add boilerplate --path ./templates/eb-reactor.yaml --name "EBReactor"

sam add boilerplate --path ./templates/rest-function.yaml --name "RestFunction"
```

`rest-function.yaml`

```yaml
Parameters:
 - Name
 - Handler
 - ApiPath
Resource:
 ${Name}RestFunction:
    Type: AWS::Serverless::Function
    Properties:
        Handler: src/handlers/${Handler}.handler
        Runtime: nodejs18.x
        Architectures:
            - x86_64
        MemorySize: 128
        Events:
             Api:
               Type: Api
               Properties:
                 Path: /${ApiPath}
                 Method: GET
```

2. Easily append instances of the defined templates inside their SAM files:

```sh
sam add --template "RestFunction" --name "GetFooByID" \
   --handler "/foo/get/index" \
   --api-path "/foo/get" \
   --sam-file "./rest-functions.sam.yaml"
```

By having this capability, developers would have a supercharged way of appending resource configuration without leaving their terminals and reduce amount of time required to copy paste and search patterns over large sam files.

### How is this different from sam init?

`sam init` command is mainly used for bootstrapping fresh projects, this command is dedicated for appending resources of any type under SAM. If we think about it, appending resources to a SAM file is done more often compared to setting up a fresh stack from the ground in real projects.
