### DISCUSSION TITLE
`sam local invoke` always use same image even I run `sam build` first when I update the source code.

### DISCUSSION THREAD

**Discussion by 0417taehyun** [aws/aws-sam-cli#5118] [Questions]
`sam local invoke` always use same image even I run `sam build` first when I update the source code.

- Mac OS: Pro 2019, Intel Core i7, Ventuar 13.3.1
- Docker: Docker Desktop for Mac 23.0.5
- AWS SAM CLI: 1.82.0
- Runtime: Python3.9

Here is my `template.yaml` file.

```YAML
Transform: AWS::Serverless-2016-10-31
Description: A simple AWS Lambda

Resources:
  SimpleAWSLambda:
    Type: AWS::Serverless::Function
    Properties:
      Runtime: python3.9
      PackageType: Image
      ImageUri: simpleawslambda
      Timeout: 600
      MemorySize: 1024
      Environment:
        Variables:
          SLACK_BOT_TOKEN: "SLACK_BOT_TOKEN"
    Metadata:
      Dockerfile: Dockerfile
      DockerContext: ./
      DockerTag: v1
```

I run like the one below.

```Bash
sam build -t template.yaml --use-container && \
sam local invoke -t template.yaml -e events/event.json --env-vars env.json
```

`sam build` create a new image when I change the source code. However, `sam local invoke` build a image which tag is `rapid-x86_64`, and I understand that this image is for lambda execution, which is made by `sam local invoke` command. But, I think if the `sam build` builds a new image, a followed `sam local invoke` builds a new `rapid-x86_64` image. However, it didn't in my local environment.

Did I miss something? I want to invoke the AWS Lambda function on my local environment with my local Docker when I change my source code.
