### DISCUSSION TITLE
'provided' runtime is not a supported runtime

### DISCUSSION THREAD

**Discussion by koote** [aws/aws-sam-cli#6583] [Questions]
HI AWS SAM CLI folks,
I am migrating Go lambda runtime from go1.x to provided.al2, hit this error, I am using SAM CLI v1.23.0, does it mean this version is too old doesn't have provided runtime support? Which version of SAM CLI started to support provided.al2 runtime?

error log:
```
 SAM CLI, version 1.23.0

 Building codeuri: /tmp/project/helloworld runtime: provided.al2 metadata: {'BuildMethod': 'go1.x'} functions: ['HelloFunction']
 'provided' runtime is not a supported runtime

 Build Failed
 Error: GoModulesBuilder:Validation - Binary validation failed for go, searched for go in following locations  : [] which did not satisfy constraints for runtime: provided. Do you have go for runtime: provided on your PATH?
```
My template.yml:
```
  HelloFunction:
    Type: AWS::Serverless::Function
    Metadata:
      BuildMethod: go1.x
    Properties:
      FunctionName: HelloFunction
      CodeUri: helloworld/
      Handler: bootstrap
      Runtime: provided.al2
     ....
```

Also I have another question, when upgrading to `provided.al2` runtime, must I specify `BuildMethod`? What is difference between `BuildMethod: go1.x` and `BuildMethod: makefile` with a makefile explicitly calls `go build`? Thanks!
