### DISCUSSION TITLE
How to add a layer in for my Lambda that containes all the Python dependencies

### DISCUSSION THREAD

**Discussion by massimiliano96** [aws/aws-sam-cli#7562] [Questions]
Hi all!

I'm working on a multiple Lambda functions project, I would like to add to my Sam template a layer that contains all the dependencies fo my Lambda functions.
I'm trying with the following code:

```
DependenciesLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      ContentUri: .
      CompatibleRuntimes:
        - python3.12
      RetentionPolicy: Retain
    Metadata:
      BuildMethod: python3.12

  # Lambda Function for Managing Users and Coaches
  ManageUsersFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: handlers.user.lambda_handler
      Runtime: python3.12
      Layers:
        - !Ref DependenciesLayer
      CodeUri: services/
```

where `requirements` folder contains my `requirements.txt`.
When I run `sam build --use-container` it actually build my DependenciesLayer, however when I run `sam local start-api` I have dependencies import errors.

How can I solve this issue?
