### ISSUE TITLE
Wrong lambda function called when running local

### ISSUE THREAD

**Issue by liuxh0** [aws/aws-sam-cli#1064]
### Description

The lambda function with `method: any` will always be called when running locally using `sam local start-api`, even though there are concrete methods (for example `get`) defined. It works properly after deploying to AWS.

### Steps to reproduce

Example template (excerpt):
```
Resources:
  AnyFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: lambda
      Handler: index.any
      Events:
        ApiEvent:
          Type: Api
          Properties:
            Path: /foo
            Method: any
  GetFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: lambda
      Handler: index.get
      Events:
        ApiEvent:
          Type: Api
          Properties:
            Path: /foo
            Method: get
```

With the template I'm describing: call `GetFunction` if `GET /foo`; call `AnyFunction` if any methods on `/foo` except `GET` (for example `POST /foo`).

### Observed result

When running locally, `GET /foo` will call `AnyFunction`. When deploying to AWS, `GET /foo` will call `GetFunction`. 

### Expected result

`GET /foo` should call `GetFunction`.

### Additional environment details (Ex: Windows, Mac, Amazon Linux etc)

1. OS: Mac
2. `sam --version`: SAM CLI, version 0.13.0

**Comment by moelasmar** [comment]
This feature is supported now.

- create a new project using `sam init`
- update the template file to be something like the following
```
AWSTemplateFormatVersion: 2010-09-09
Transform: AWS::Serverless-2016-10-31

Resources:
  HelloWorldFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: hello_world/
      Handler: app.lambda_handler
      Runtime: python3.7
      Events:
        ApiEvent:
          Type: Api
          Properties:
            Path: /foo
            Method: any
  HelloWorldFunction2:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: hello_world/
      Handler: app.lambda_handler2
      Runtime: python3.7
      Events:
        ApiEvent:
          Type: Api
          Properties:
            Path: /foo
            Method: get
  HelloWorldFunction3:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: hello_world/
      Handler: app.lambda_handler3
      Runtime: python3.7
      Events:
        ApiEvent:
          Type: Api
          Properties:
            Path: /foo
            Method: post
```
- update the lambda function handlers to something as following
```
import json
  
def lambda_handler(event, context):
    return {
        "statusCode": 200,
        "body": json.dumps({
            "message": "hello world",
        }),
    }

def lambda_handler2(event, context):
    return {
        "statusCode": 200,
        "body": json.dumps({
            "message": "hello world2",
        }),
    }

def lambda_handler3(event, context):
    return {
        "statusCode": 200,
        "body": json.dumps({
            "message": "hello world3",
        }),
    }
```
- run `sam local start-api`
- The expected lambda function will be invoked, when you call the rest api /foo with the concrete method
```
% curl -X GET http://127.0.0.1:3000/foo
{"message": "hello world2"}%
curl -X POST http://127.0.0.1:3000/foo
{"message": "hello world3"}%
% curl -X DELETE http://127.0.0.1:3000/foo
{"message": "hello world"}%
% curl -X OPTIONS http://127.0.0.1:3000/foo
{"message": "hello world"}%
```
