### ISSUE TITLE
Defaulting to 'application/json' for 202 Accepted with empty body causes Postman parse error.

### ISSUE THREAD

**Issue by anishkny** [aws/aws-sam-cli#1183]
### Description

SAM Local start-api adds a `Content-Type: application/json` if none is present. This causes Postman parse error when loading a 202 with empty body.

https://github.com/awslabs/aws-sam-cli/blob/43a7c37ed340070be2c81c5bf14cf13f122c5312/samcli/local/apigw/local_apigw_service.py#L232

### Steps to reproduce

```js
// index.js
const express = require('express');
const awsServerlessExpress = require('aws-serverless-express');

const app = express();
app.post('/:hi', (req, res) => {
  res.status(202);
  res.end();
});

const server = awsServerlessExpress.createServer(app);
exports.handler = async (event, context) => {
  console.log(`handler called`);
  const res = await (awsServerlessExpress.proxy(server, event, context, 'PROMISE').promise);
  console.log(res);
  return res;
}
```

```
// package.json
{
  "scripts": {
    "start": "sam local start-api"
  },
  "dependencies": {
    "aws-serverless-express": "^3.3.6",
    "express": "^4.16.4"
  }
}
```

```yaml
# template.yml
AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Globals:
  Function:
    Timeout: 180

Resources:
  Handler:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: .
      Handler: index.handler
      Runtime: nodejs8.10
      Events:
        GetIt:
          Type: Api
          Properties:
            Path: /{any+}
            Method: any
```

### Observed result

```bash
$ curl -v -X POST http://localhost:3000/hi
*   Trying ::1...
* TCP_NODELAY set
* Connection failed
* connect to ::1 port 3000 failed: Connection refused
*   Trying 127.0.0.1...
* TCP_NODELAY set
* Connected to localhost (127.0.0.1) port 3000 (#0)
> POST /hi HTTP/1.1
> Host: localhost:3000
> User-Agent: curl/7.54.0
> Accept: */*
>
* HTTP 1.0, assume close after body
< HTTP/1.0 202 ACCEPTED
< x-powered-by: Express
< date: Thu, 16 May 2019 09:50:17 GMT
< connection: close
< content-length: 0
< Content-Type: application/json    <---- this fails Postman
< Server: Werkzeug/0.15.2 Python/3.7.3
<
* Excess found in a non pipelined read: excess = 7 url = /hi (zero-length body)
* Closing connection 0
```

When loading this from Postman, it fails. 

### Expected result

If I run this as a regular Express server, no `Content-Type: application/json` is added and Postman is happy.

### Additional environment details (Ex: Windows, Mac, Amazon Linux etc)

1. OS: MacOS 10.14.4
2. `sam --version`: SAM CLI, version 0.15.0

`Add --debug flag to command you are running`

Edit: Added `template.yml` file
