### ISSUE TITLE
502 BAD GATEWAY for file upload through SAM with local API Gateway

### ISSUE THREAD

**Issue by smpeters** [aws/aws-sam-cli#1216]
### Description

When attempting to upload a photo to a local Lambda running using `sam local start-api --debug`, it fails with a 502 BAD GATEWAY.  No code within the Lambda is executed.

### Steps to reproduce

I used curl to do the upload.

`curl -v -X POST   'http://localhost:3000/v1/photo-gallery' -F 'uploadedFile=@IMG_5071.JPG`

This Lambda uses Flask to handle multiple endpoints and the others are working as expected.

### Observed result

Please provide command output with `--debug` flag set. 

SAM does not display any debug output.  It just logs the request with the response set as a 502.

### Expected result

I would expect that the lambda would be executed.

### Additional environment details (Ex: Windows, Mac, Amazon Linux etc)

1. OS: Mac
2. `sam --version`: SAM CLI, version 0.17.0

`Add --debug flag to command you are running`

**Comment by RuNpiXelruN** [comment]
Getting the same problem here. 

Have tried adding a `BinaryMediaTypes` key to our `template.yaml` but no luck.
```
  Api:
    BinaryMediaTypes:
      - image~1png
      - image~1jpeg
      - image~1jpg
      - image~1pdf
```

**Comment by Checkroth** [comment]
I have the same issue, though I am sending a small `.wav` file, not an image.

Local output with `--debug` gives no extra information, it just returns a 502 before attempting to execute anything.

With the same configuration actually deployed to AWS, I can send a file without issue. The issue only occurs with the local api.

**Comment by cmorgia** [comment]
Same here with Python3.7 runtime, very annoying...

**Comment by arnelcabinti** [comment]
Is there any solution for this??

**Comment by TiS** [comment]
I concur. Is there any solution of this?

**Comment by yehorb** [comment]
This one is strange, because it only fails on image types for me. Like `.jpg` or `.png` (tested this ones). If I `base64` encode my data prior to sending (e.g. `base64 image.jpg > image64; curl ... -F 'image64=@image64'`) works perfectly and I can retrieve the data as a `multipart`-blob in the `event['body']` in my function.

**Comment by geofflancaster** [comment]
I'm having the same issue. I also see the same thing as @yehorb that if i create a txt file contents of the base64 encoding of an image then it works just fine.

**Comment by joain946** [comment]
I had the same issue with SAM CLI 0.19.0. I managed to resolve it by adding "application/octet-stream" to "BinaryMediaTypes" in the SAM yaml file. So now my entry looks like this:
`    Properties:
      BinaryMediaTypes: [image/*, application/octet-stream]`
With my Java Lambda I can now get the binary data in a "byte[]" input object.
I haven't verified this in a deployed version yet.

**Comment by geofflancaster** [comment]
@joain946 Thanks! I made the change and I'm able to hit my Node app but the event body is null. Dumping it to the console, there doesn't appear to be anything relevant in the payload.

**Comment by canvaspixels** [comment]
Have added BinaryMediaTypes but no joy :(

**Comment by ruodingt** [comment]
I had same issue here I am using SAM CLI 0.40.0. Is b64 encoding the only way?

**Comment by zhaozhongming** [comment]
I tried BinaryMediaTypes: [image/*, application/octet-stream] , but it does not work neither
- nodejs 12

**Comment by k3vur** [comment]
Any news on this?

**Comment by pyrabbit** [comment]
`/` need to be written as `~1` as per the [documentation](https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/sam-resource-api.html). I had to set the following global.

```
Globals:
  Api:
    BinaryMediaTypes: ['*~1*']
```

**Comment by smpeters** [comment]
The fact that this bug has been open for ten months before this was mentioned makes this sounds like a workaround for a bug.

**Comment by hdgone** [comment]
it still doesn't work for images, moreover, I've found an odd behaviour: if I don't specify BinaryMediaTypes it returns 502 without even invoking the function but if I do, it invokes it and returns 502 after a 30 seconds delay

**Comment by tdhulster** [comment]
> it still doesn't work for images, moreover, I've found an odd behaviour: if I don't specify BinaryMediaTypes it returns 502 without even invoking the function but if I do, it invokes it and returns 502 after a 30 seconds delay

Same issue here, did you find any solution @hdgone ?

**Comment by hdgone** [comment]
@tdhulster unfortunately no, switched to Kubernetes instead 😃

**Comment by benjaminfiliatrault** [comment]
same issue here when uploading a `.txt` file it's working fine but I'm trying a `.zip` file which throw an 502 BAD GATEWAY error. 
API Gateway binary type set is
```
BinaryMediaTypes:
    - "application/zip"
    - "application/octet-stream"
```

**Comment by prenx4x** [comment]
Based on my investigation I have not found any bugs here. 
The way it works is that you mention BinaryMediaTypes in your template file and then also pass Content-type which matches the BinaryMediaTypes e.g.
In template.yaml -
```
BinaryMediaTypes:
    - "application/zip"
    - "application/octet-stream"
```
and then use - 
`curl -v -X POST 'http://localhost:3000/v1/photo-gallery' -F 'uploadedFile=@IMG_5071.JPG' -H 'Content-Type: application/octet-stream'`

This will work. If you don't pass Content-type the POST data is treated as multipart/form-data. So you can put that in your BinaryMediaTypes to treat it as Binary data or use `*/*`.

Closing this issue...

**Comment by oleh-kobzar** [comment]
@prenx4x actually, there is still a problem if one uses HttpApi events for lambdas.

I tried to set
```
Globals:
  Api:
    BinaryMediaTypes:
      - '*~1*'
      - '*/*'
      - 'multipart~1form-data'
      - 'multipart/form-data'
      - 'application~1octet-stream'
      - 'application/octet-stream'
```

as well as
```
Resources:
  CrudDebug:
    Type: AWS::Serverless::Function
    Properties:
      Handler: dist/api/functions/crud/index.debug
      Runtime: nodejs14.x
      Timeout: 10
      Environment: *ENV
      Events:
        HttpGet:
          Type: HttpApi
          Properties:
            Path: /crud-debug
            Method: any
            BinaryMediaTypes:
              - '*~1*'
              - '*/*'
              - 'multipart~1form-data'
              - 'multipart/form-data'
              - 'application~1octet-stream'
              - 'application/octet-stream'
```

But no luck, still getting 502 (BAD GATEWAY) while trying to send files to this lambda.

I need especially `HttpApi` type of event insteand of `Api` because the platform for which I am developing requires lambdas to process `APIGatewayProxyEventV2`. Everything been set up so far, but now I am struggling to create a lambda with the file upload and test it locally.

BTW, I am trying to test file sending by putting this code into my Chrome Dev Tools:
```
let formData = new FormData();
formData.append('file', (await (await fetch(`https://placekitten.com/300/225?_=${+new Date()}`)).blob()));
formData.append('file', (await (await fetch(`https://placekitten.com/400/300?_=${+new Date()}`)).blob()));
await (await fetch('http://127.0.0.1:3000/crud-debug', {
  method: 'post',
  body: formData,
//   processData: false,
//   contentType: false,
  headers: {
//     'Content-Type': 'application/octet-stream',
  },
})).json();
```
(changing headers didn't help too when there was single file; also my app is required to be able to upload multiple files at once).

Maybe I should create separate issue for this? Thanks.

**Comment by anton-khodak** [comment]
Solved it by having a template like this one
```
Resources:
  AssetsUploadFunction:
    Type: AWS::Serverless::Function 
    Properties:
      CodeUri: assets/
      Handler: handler
      Runtime: go1.x
      Tracing: Active # https://docs.aws.amazon.com/lambda/latest/dg/lambda-x-ray.html
      Events:
        CatchAll:
          Type: Api 
          Properties:
            Path: /
            Method: PUT
            RestApiId: AssetsAPI

  AssetsAPI:
    Type: AWS::Serverless::Api
    Properties:
      StageName: sandbox
      BinaryMediaTypes:
        - '*~1*'
```
