### ISSUE TITLE
ClassNotFoundException in package that works fine on Lambda

### ISSUE THREAD

**Issue by feinstein** [aws/aws-sam-cli#1253]
I have a Lambda + API Gateway deployment working fine, but when I try to invoke the same ZIP file locally I get a `ClassNotFoundException`  for the same handler string as the one in the Lambda Console.

I am invoking it with: 

```
>sam local start-api --template sam.yaml
```

My sam.yaml is:

```
AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Users API Endpoint
Globals:
  Api:
    EndpointConfiguration: REGIONAL

Resources:
  UsersFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: com.myproject.users.StreamLambdaHandler::handleRequest
      Runtime: java8
      CodeUri: lambda/build/distributions/lambda-1.0.0-SNAPSHOT
      MemorySize: 320
      Policies: AWSLambdaVPCAccessExecutionRole
      Timeout: 20
      Events:
        GetResource:
          Type: Api
          Properties:
            Path: /users/{proxy+}
            Method: any

Outputs:
  UsersApi:
    Description: URL for application
    Value: !Sub 'https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/users'
    Export:
      Name: UsersApi
```

1. OS: Windows 
2. `sam --version`: 0.17.0
