### ISSUE TITLE
sam build exception when trying to use dynamic resources

### ISSUE THREAD

**Issue by chizou** [aws/aws-sam-cli#1293]
Due to my issues with https://github.com/awslabs/aws-sam-cli/issues/1292, I tried to ditch `Ref`ing the SSM value and use dynamic resources to access the value instead. My template snippet looks like this:
```
  CfDeployer:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: lambdas/cf_deployer/
      Layers: '{{resolve:ssm:/layers/orgfunctions:1}}'
      Policies:
        - Version: "2012-10-17"
          Statement:
            - Effect: Allow
              Action: "sts:AssumeRole"
              Resource: "*"
      Timeout: 300
```
Running `sam build` gives me the this error: `samcli.commands.validate.lib.exceptions.InvalidSamDocumentException: [InvalidResourceException('CfDeployer', "Type of property 'Layers' is invalid.")] ('CfDeployer', "Type of property 'Layers' is invalid.")`

Running `sam package` does seem to work correctly
