### ISSUE TITLE
Feature Request: API Gateway Authorizer support in SAM Local

### ISSUE THREAD

**Issue by bitforth** [aws/aws-sam-cli#137]
I'm using the tool to spin up locally an API gateway and run my lambda functions. However, I don't know how to configure an authorizer in `template.yml`

In my `template.yml` file, I have the following configuration:

```
JwtAuthorizerFunction:
    Type: AWS::Serverless::Function
    Properties:
      Environment:
        Variables:
          JWT_SECRET: '<<secret>>'
      Handler: authorizers.jwt
      Runtime: nodejs6.10
      Role:
        Fn::ImportValue:
          !Join ['-', [!Ref 'ProjectId', !Ref 'AWS::Region', 'LambdaTrustRole']]
```

If I understand the [authorizers documentation](http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-apigateway-authorizer.html) correctly, I should be able to add the following configurations in order to configure my authorizer

```
Authorizer: 
  Type: "AWS::ApiGateway::Authorizer"
  Properties: 
    AuthorizerCredentials: 
      Fn::GetAtt: 
        - "LambdaInvocationRole"
        - "Arn"
    AuthorizerResultTtlInSeconds: "300"
    AuthorizerUri: "arn:aws:lambda:us-east-1:<<myarn>>:function:<<lambda function arn>>"
    Type: "TOKEN"
    IdentitySource: "method.request.header.Authorization" 
    Name: "DefaultAuthorizer"
    RestApiId: 
      Ref: "RestApi"
```

Everything up until that point works fine. If I run
`sam validate` the output is `Valid!` 
`sam local start-api`  executes without a problem. 

However, I don't know how to configure the custom authorizer in my lambda functions. I've read the [AWS::Serverless::Function documentation](http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-lambda-function.html) but I couldn't find anything relevant to my issue. Furthermore, there are [two issues about adding support for AuthorizationType to the API](https://github.com/awslabs/serverless-application-model/issues/49) but it's unclear whether this support will ever be added, or if it has been added already. 

Any help pointing in the right direction is greatly appreciated!

**Comment by PaulMaddox** [comment]
Hi @alanchavez88,

Currently configuring a custom authorizer isn't supported when running locally with SAM Local.

I'll leave this issue open as a feature request for our backlog.

Thanks

**Comment by alanchavez88** [comment]
Thanks @PaulMaddox for the response!

If I understand the model correctly, it shouldn't matter if my custom authorizer does not run locally, right? In AWS, only authorized requests can trigger the lambda function, correct?

**Comment by sanathkr** [comment]
Yes, an authorization request should trigger the Lambda in AWS cloud

**Comment by MagdaleneLee** [comment]
I'm wondering how I may use a Cognito Authorizer, is there sample for that? I've gone through all the 5 samples of SAM template.ymls on the internet and am not able to see how I may do so. 

Should I just rely on the swagger export? I am migrating an existing hand-build API Gateway to SAM. Thanks for help!

**Comment by bradwoods** [comment]
I'm also looking for examples of how to integrate a Cognito Authorizer with lambdas made via SAM templates.

**Comment by mohithg** [comment]
This is a good to have feature in SAM Local, so we can test the authorization functions before deploying

**Comment by sujithsnair86** [comment]
Hi is there a resolution yet for including Custom Authoriser lambda over SAM template itself or is this still a feature request AWS SAM Team is working on?

**Comment by ThomasSmWatson** [comment]
My database url will not work as it contains '=' and other special characters, int he env variables.
How would I get around this? This is a reliant to my company

**Comment by gregaeq** [comment]
Interested in this feature as well. Attempting to use sam-local to auth with Cognito before making subsequent requests.

**Comment by kanchen** [comment]
Same here. Anyone knows the timeline to support SAM local custom authorizer ?

**Comment by margic** [comment]
@alanchavez88 did you ever figure out how to configure an authorizer, I notice that the question was never answered. It went off on a tangent about Sam local.

**Comment by alanchavez88** [comment]
@margic no, I never figured it out. I ended up assuming that it worked and moved on :( If you find a way to do it please post it here.

**Comment by kind3r** [comment]
Hi, I wrote a small tutorial about how I use custom authorizers. While this does not work when running locally, it does work when being deployed. Hope it helps.

# Add an API Gateway custom authorizer

## Resource summary:  
**ApiGateway** - AWS::Serverless::Api - The API definition  
**ApiGatewayAuthorizerRole** - AWS::IAM::Role - Role for API Gateway to be able to invoke our custom authorizer function  
**CustomAuthorizerFunction** - AWS::Serverless::Function - The Authorizer function  
**CustomAuthorizerFunctionRole** - AWS::IAM::Role - Role of the custom authorizer function to be able to be invoked and access needed resources

**ApiGateway** invokes **CustomAuthorizerFunction** which returns a policy that will allow or deny the further invocation of your path function. For more details see [Introducing custom authorizers in Amazon API Gateway
](https://aws.amazon.com/blogs/compute/introducing-custom-authorizers-in-amazon-api-gateway/)

## Step by step

* You must define an **AWS::Serverless::Api** resource that must include the swagger API definition in the **DefinitionBody**. You cannot use **DefinitionUri** as CloudFormation will only reference the external file, but not do any of it's variable replacement magic, so you have to include the full swagger API definition inside the aws-sam template.

```yaml
ApiGateway:
  Type: AWS::Serverless::Api
  Properties:
    StageName: prod
    DefinitionBody:
      swagger: "2.0"
      info:
        title: 
          Ref: AWS::StackName
        description: My API that uses custom authorizer
        version: 1.0.0
      securityDefinitions:
        ...
      paths:
        ...
```

* Add a security definition to your API definition for your custom authorizer. This should include the reference to your custom authorizer function **CustomAuthorizerFunction** and the role assumed by API Gateway when it will invoke the authorizer function **ApiGatewayAuthorizerRole**. In our example we define that header variable **Authorization** will hold the authorization token needed for our custom authorizer to work.

```yaml
securityDefinitions:
  CustomAuthorizer:
    type: apiKey
    name: Authorization
    in: header
    x-amazon-apigateway-authtype: custom
    x-amazon-apigateway-authorizer:
      type: token
      authorizerUri:
        Fn::Sub: arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${CustomAuthorizerFunction.Arn}/invocations
      authorizerCredentials:
        Fn::Sub: ${ApiGatewayAuthorizerRole.Arn}
      authorizerResultTtlInSeconds: 60
```

* Add security requirement for each of the path you want to protect with your custom authorizer. Adding a global security requirement does not seem to work.

```yaml
paths:
  ...
  "/somepath":
    post:
      security:
        - CustomAuthorizer: []
      ...
```

* Create your authorizer function resource just like you would for any regular function.

```yaml
CustomAuthorizerFunction:
  Type: AWS::Serverless::Function
  Properties:
    Runtime: nodejs6.10
    Handler: index.handler
    ...
    Role:
      Fn::Sub: ${CustomAuthorizerFunctionRole.Arn}
```

* Create a role for API Gateway to be able to invoke the authorizer function.

```yaml
ApiGatewayAuthorizerRole:
  Type: AWS::IAM::Role
  Properties:
    AssumeRolePolicyDocument: 
      Version: "2012-10-17"
      Statement: 
        - 
          Effect: "Allow"
          Principal: 
            Service: 
              - "apigateway.amazonaws.com"
          Action: 
            - sts:AssumeRole
    Policies: 
      - 
        PolicyName: "InvokeAuthorizerFunction"
        PolicyDocument: 
          Version: "2012-10-17"
          Statement: 
            - 
              Effect: "Allow"
              Action:
                - lambda:InvokeAsync
                - lambda:InvokeFunction
              Resource:
                Fn::Sub: ${CustomAuthorizerFunction.Arn}
```

* Create a role for your authorizer function to be able to be invoked and access the resources you need.

```yaml
CustomAuthorizerFunctionRole:
  Type: AWS::IAM::Role
  Properties:
    AssumeRolePolicyDocument: 
      Version: "2012-10-17"
      Statement: 
        - 
          Effect: "Allow"
          Principal: 
            Service: 
              - "lambda.amazonaws.com"
          Action: 
            - sts:AssumeRole
    ManagedPolicyArns:
      - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
    Policies:
      ...
```

**Comment by Jun711** [comment]
Is there any example for cognito authorizer?

**Comment by sanathkr** [comment]
@kind3r  This is an excellent tutorial. Something a lot of people will find it very useful. Will you be interested in submitting this as a pull request to the SAM Repo docs please? https://github.com/awslabs/serverless-application-model/tree/develop/docs

**Comment by nk2580** [comment]
given that the swagger support is for version 2 and not OpenAPI 3 i would expect this feature to come out in the next release. seems like a HUGE oversight in terms of API definition to not allow authorisation in SAM templates.

have spent the last two days trying to get the version 2 swagger def to work in SAM, long story short. i may as well write a full cloudformation stack.

i will infidelity be looking into other services soon if this feature isn't implemented.

**Comment by setuk** [comment]
@kind3r @sanathkr I have followed these instructs and i the only part i cannot make work is mapping the authoriser to the API path. Any guidance on that?

**Comment by setuk** [comment]
Got this working - thanks!

**Comment by OndeVai** [comment]
I can't find a simple example of using a Cognito authorizer in an Api event event of a lambda function

**Comment by abiodunjames** [comment]
None of the examples given here worked for me. I finally followed this https://github.com/awslabs/serverless-application-model/blob/master/examples/2016-10-31/api_lambda_request_auth/template.yaml and i got it working

**Comment by nk2580** [comment]
For those playing at home, this relies on the idtoken which cannot be explicitly invalidated. If you never want to log a user out by invalidating the token then it’s a great fit. But if you’re needing to invalidate a token on behalf of a user then you should implement a custom authoriser that checks the access token

**Comment by GeekOnGadgets** [comment]
Does anyone know if we can harcode function arn in FunctionArn?

**Comment by nk2580** [comment]
Not sure why you would want to do that.. are you defining an authoriser in the same Sam template as the inline swagger markup?

FWIW I found the best way to manage a custom authoriser was to make a separate cloudformation or Sam stack with that function on its own and then output the ARN. Then reference it in the Sam templates that have swagger definitions for authorisation

**Comment by GeekOnGadgets** [comment]
@nk2580 thanks for replying. Sorry that was pure for testing purpose. I have a separate sam stack for custom authoriser which gets deployed and then a separate stack for functions. But somehow it was not working and was unable to find any example. So decided to give a try with hardcode one. 

custom autoriser sam template.yml

```
AWSTemplateFormatVersion: "2010-09-09"
Transform: "AWS::Serverless-2016-10-31"

Description: >-   
  A custom authoriser to verify JWT token.

Globals:
  Function:
    Runtime: nodejs8.10

Resources:
  Authoriser:
    Type: "AWS::Serverless::Function"
    Properties:
      FunctionName: test-authoriser
      CodeUri: src/
      Handler: index.handler

Outputs:
  AuthoriserArn:
    Description: The Arn of the created autoriser
    Value: !GetAtt Authoriser.Arn
```

and below is my another stack where I want to reference the custom authoriser

```
AWSTemplateFormatVersion: "2010-09-09"
Transform: "AWS::Serverless-2016-10-31"

Globals:
  Function:
    Runtime: nodejs8.10
  Api:
    Cors:
      AllowMethods: "'*'"
      AllowHeaders: "'*'"
      AllowOrigin: "'*'"

Resources:
  TestApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: dev
      Auth:
        DefaultAuthorizer: Test-Authorizer
        Authorizers:
          Test-Authorizer:
            FunctionArn: arn:aws:lambda:region:account-number:function:function-name
            Identity:
              Header: Authorizer
              ValidationExpression: ^Bearer [-0-9a-zA-Z\._]*$
              ReauthorizeEvery: 30 # seconds
  Test:
    Type: "AWS::Serverless::Function"
    Properties:
      FunctionName: test-function
      CodeUri: src/test
      Handler: index.test
      Events:
        EndPoint:
          Type: Api
          Properties:
            RestApiId: !Ref TestApi
            Path: /test
            Method: get
            Auth:
              Authorizer: Test-Authorizer
```

And this where i have very limited knowledge how to achieve this. Any help would be highly appreciated. Thanks

**Comment by nk2580** [comment]
I’ve basically done the same but I’ve used swagger to define my api gateway resources.. it’s a little easier than using cloudformation and it reduces the size of your files

**Comment by mgrissa** [comment]
Could someone please tell me whether configuring a custom authorizer when running locally with SAM Local is supported?

**Comment by joeythomaschaske** [comment]
@mgrissa I'm running into this issue and I'm assuming running it locally is not supported. It completely bypasses the authorizer and hits your function which is not ideal when your api is user focussed

**Comment by nk2580** [comment]
Worse still there’s no way to have the data passed through cognito back to the lambda after authorisation. Basically it’s an unsuitable solution for API security

**Comment by joeythomaschaske** [comment]
@nk2580 I'm working around it by starting my local api with an environment variable. If I see that environment variable in my lambda then I use the email I pass into the request otherwise I use whats in the `event.requestContext.authorizer` object

**Comment by mgrissa** [comment]
@joeythomaschaske I would recommend using the **Serverless Offline** plugin of the **Serverless Framework**. I am able to run an API Gateway with a Lambda Authorizer and a Lambda Proxy locally thanks to this plugin.

**Comment by joeythomaschaske** [comment]
@mgrissa I'm not using Serverless Framework. I want to use 1st party tooling if it's available and this is a viable work around.

**Comment by jqdurham** [comment]
Any update on this?  Best I can grok from the docs, this should be working.  

  ```
MyServerlessAPI:
    Type: AWS::Serverless::Api
    Properties:
      StageName: Dev
      Auth:
        DefaultAuthorizer: VerifyIAMAuthorizer
        Authorizers:
          VerifyIAMAuthorizer:
            FunctionArn: !GetAtt IamAuthorizerFunction.Arn

  IamAuthorizerFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./cmd/authorizer

  TestFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./cmd/test
      Events:
        APIRequest:
          Type: Api
          Properties:
            RestApiId: !Ref MyServerlessAPI
            Path: /
            Method: get
```
I'm just looking for the minimal configuration to make it work for PoC.

**Comment by nk2580** [comment]
So far the only way I can get the authoriser to take effect is to use the inline swagger feature of SAM. It’s actually not as cumbersome as I originally thought but it does end up making your template.yml file bloated.

**Comment by jqdurham** [comment]
@nk2580 - Would you mind sharing a working example?

**Comment by djfabrix** [comment]
Any update on this? When local custom authorizers will be supported?

**Comment by woozay** [comment]
Ditto ^

**Comment by opmftw** [comment]
I have a hard time figuring out what doesn't work with sam local, for example custom authorizers, is there any place where one can read the current known limitations?

**Comment by aaronwht** [comment]
I contacted AWS support (Business support) regarding this issue and received a reply stating that testing the authorizers for API resources locally is not available currently.  I was told it's a known issue open with the SAM team and the SAM team will be working on it based on the priority they assigned it - no ETA on when this will be available.  I've attached a very slimmed down version of the code to this reply.

[aws-sam-authorizer.zip](https://github.com/awslabs/aws-sam-cli/files/4060208/aws-sam-authorizer.zip)

**Comment by rikenpatel20** [comment]
> @joeythomaschaske I would recommend using the **Serverless Offline** plugin of the **Serverless Framework**. I am able to run an API Gateway with a Lambda Authorizer and a Lambda Proxy locally thanks to this plugin.

I would agree for a local debugging.

**Comment by aidan-plenert-macdonald** [comment]
> So far the only way I can get the authoriser to take effect is to use the inline swagger feature of SAM. It’s actually not as cumbersome as I originally thought but it does end up making your template.yml file bloated.

@nk2580 Hey, do you have an example you'd be open to sharing?

**Comment by utiliware** [comment]
Here is a patch that supports swagger based Authorizers right now...
[aws-sam-cli-feature-jwt.patch.txt](https://github.com/awslabs/aws-sam-cli/files/4536003/aws-sam-cli-feature-jwt.patch.txt)

**Comment by destinybonavita** [comment]
Any update on getting this to work locally? I'm surprised after 3 years it wasn't implemented

**Comment by LennyDuan** [comment]
SAM doesn't support custom authorizers when you run locally now (SAM version 0.48). So you can't test it by using "sam local start-api".

But it supports in SAM YAML template and you can use SAM CLI to build and deploy custom authorizers to you AWS cloud Api Gateway. It can work well if your YAML setup is correct.

**Comment by rikenpatel20** [comment]
As per @joeythomaschaske recommended, you can make it work by running `Serverless Offline` plugin using [Serverless Framework](http://serverless.com/).
### I am able to run API GW with Lamda Custom Authorizer locally.

**Comment by shane-js** [comment]
The current highly decorated response to this open issue from 2017 is unrelated and clearly states it does not work locally.

Can an AWS employee please comment on the main obstacles faced in implementing this core functionality? Perhaps if more was shared besides that it is not currently supported we could get the community to help with a PR.

Relying on a 3rd party's framework to be able to test code locally is surprising. As it stands now, if one is using a Lambda Custom Authorizer (I'd venture to guess a large portion of the community does) any local test of anything related to authorization is impossible using AWS provided tools to my knowledge. The current "in ecosystem" solution is to deploy to a dev/test environment which massively slows down the development process.

**Comment by iaforek** [comment]
> opened this issue on 24 Sep 2017

3 years and stil no luck.... no comment.

**Comment by nk2580** [comment]
FWIW I ended up moving all my compute to GCP’s Cloud Run because at least in that product I can test everything locally with extreme ease.

**Comment by aidan-plenert-macdonald** [comment]
@nk2580 Can you point me to GCP documentation for how to test REST API's locally?

**Comment by nk2580** [comment]
@aidan-plenert-macdonald Cloud run is a serverless docker container runtime so you test your API locally the same way you would any non serverless application. The only caveat to the platform is that the application needs to be stateless as there’s no guarantee of the same instance serving all HTTP traffic. 

To run your application locally you just run ‘docker run’ using the dockerfile for your application

**Comment by ethanpeterson** [comment]
+1

**Comment by sunhak-hout** [comment]
I'm new to SAM and I've been stuck for quite a long stressful time testing Authorizer locally and finally found this is not working. Surprisingly, this has been opened since 2017 and there is no even work-around solution? 😳

**Comment by nk2580** [comment]
The only workaround is to deploy and test in a dev account

**Comment by lrcry** [comment]
I'm recently trying out SAM as well for using Cognito user pool to authorise and found [this example](https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/sam-property-api-cognitoauthorizer.html#sam-property-api-cognitoauthorizer--examples) provided by AWS SAM document.

Basically, the example says

```
Auth:
  Authorizers:
    MyCognitoAuth:
      AuthorizationScopes:
        - scope1
        - scope2
      UserPoolArn:
        Fn::GetAtt:
          - MyCognitoUserPool
          - Arn
      Identity:
        Header: MyAuthorizationHeader
        ValidationExpression: myauthvalidationexpression

```

Another example can be viewed [here](https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/serverless-controlling-access-to-apis-cognito-user-pool.html).

If you need to expose any particular path(s) to public (not to apply the authorisation), in `AWS::Serverless::Functions - Events - Api` you can specify `Auth` as `NONE`. See [this](https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/sam-property-function-apifunctionauth.html). 

Anyway the doc seems to present the authorisation part in a relatively discrete way which requires deeper digging. I tried the above and it worked for me when deployed to the cloud. I didn't try it locally so don't know whether it supports local run or not. Please try it if you have the need for doing so.

Hope that helps...

**Comment by OGoodness** [comment]
Any update on this in regards to "REQUEST" Lambda authenticators for Api Gateway?

**Comment by tawheedmanzoor** [comment]
Is this in the plan?

**Comment by stevenlafl** [comment]
Seriously, this breaks my ability to test things without making two separate local and prod templates to maintain. It's really annoying.

**Comment by erashdan** [comment]
+1

**Comment by OGoodness** [comment]
@awsjeffg 
Any luck with the review?

**Comment by sapessi** [comment]
What type of authorization strategy do you use - Lambda authorizers, OpenID Connect, or something else?

**Comment by OGoodness** [comment]
> What type of authorization strategy do you use - Lambda authorizers, OpenID Connect, or something else?

Our team uses lambda authorizers

**Comment by sky-lord1** [comment]
Initially, I was AWS SAM API connected with my react project using the below command.
`sam local start-api`

After deployment, I integrated Cognito.  I can no longer use sam locally api since,  claims (request?.requestContext?.authorizer?.claims) is empty.

**Is there a workaround to change the event object, without updating the lambda code received in the lambda function handler?**

**Comment by daveagill** [comment]
@sky-lord1  I know you said "Without updating the lambda code" but on the off chance that **one time only** code change would be acceptable to you...

My workaround is to check for the `AWS_SAM_LOCAL` env-var. If it's present it means code is running locally in AWS SAM so I just return some faked claim properties, otherwise I grab the real ones.

This at least means I can use the same code locally and in AWS with no _futher_ changes needed.

**Comment by sky-lord1** [comment]
@daveagill Thanks. I was thinking the same thing, but i thought it would be kind of hack.

It does not make any sense to keep some code which has nothing to do with the functionality. I was hoping, for a way to change event object before it is reeaches the lambda handler otherwise, i would have to go with the solution you suggested.

**Comment by jonathanroques** [comment]
Same issue using SAM 1.22.0 with HttpApi or Api. Very surprised this is not implemented yet, no answers, not planned, nothing ... It's kind of a blocking thing for tests

**Comment by Rolfchen** [comment]
@sapessi , for me it's the JWT Authorizers / OIDC

**Comment by alexei-moneyr** [comment]
+1

**Comment by riley-clarkson** [comment]
+1, this feature would be very useful

**Comment by DevonYarbrough** [comment]
+1

**Comment by thomasaudo** [comment]
+1

**Comment by bryantqo** [comment]
+1

**Comment by jhechtf** [comment]
+1

**Comment by nandunbandara** [comment]
+1 this would be really useful. I was just trying to test an authorizer function.

**Comment by bryantqo** [comment]
I ended up testing mine by associating the function to a new API event. Once I got it to where I wanted it to be I deleted the events section for that function.

**Comment by lg9302** [comment]
+1 This would be a game changer, please someone make this happen!!

**Comment by maqboolayaz** [comment]
We are waiting for you. :-)

**Comment by omarccube** [comment]
+1

**Comment by crc-sstubbs** [comment]
Please add this.

**Comment by zwezheng** [comment]
Please add this

**Comment by michal-turzynski** [comment]
Please add this.

**Comment by rexuli** [comment]
Please add this.

**Comment by tigato-brian** [comment]
+1 
Authentication is a basic requirement for APIs and web applications

**Comment by KarthikSundariTR** [comment]
For us, this is making a very bad dev experience & eventually leading to an insecure workaround. Please prioritise this.

**Comment by navarrodiego** [comment]
Please add this.

**Comment by hvhoan1502** [comment]
Please add this, it very important.

**Comment by melvincaraangJC** [comment]
+1

**Comment by yuhe00** [comment]
Please add!

**Comment by 4ruslan-k** [comment]
+1

**Comment by Emillos** [comment]
+1

**Comment by laprus** [comment]
+1

**Comment by rkulla** [comment]
+1

**Comment by amersaw** [comment]
+1

**Comment by jamil-kahil** [comment]
+1

**Comment by danros** [comment]
+1 or, allow the ability to alter request context in start-api

**Comment by mrl24730** [comment]
if SAM Local is not yet supported authorizer. Is there any workaround for this?

**Comment by danros** [comment]
You have to run each function individually with first start-lambda to create a simulated lambda api then call the lambda api.

It's a very slow process unfortunately.

**Comment by Buzzology** [comment]
+1

**Comment by irongineer** [comment]
+1

**Comment by alexberriman** [comment]
+1

**Comment by CeccoCQ** [comment]
+1

**Comment by c4c4c4** [comment]
+1

**Comment by risurina** [comment]
+1

**Comment by medicm** [comment]
+1

**Comment by Azkron** [comment]
+1

**Comment by eduardocque** [comment]
+1

**Comment by pablo-albaladejo** [comment]
+1

**Comment by stevehaneytrailblazer** [comment]
+1

**Comment by Rami-J** [comment]
+1

**Comment by jonaspohren** [comment]
+1

**Comment by derdeka** [comment]
+1

**Comment by thomas-yaa** [comment]
+1

**Comment by kristchen** [comment]
+1

**Comment by Gadzy** [comment]
+1

**Comment by Gadzy** [comment]
+1
@mildaniel any update on this one ?

**Comment by gregoriogerardi-reflektion** [comment]
+1

**Comment by blwsh** [comment]
+1

**Comment by Oliyy** [comment]
+1

**Comment by agunn-rs** [comment]
+1

**Comment by vishwaefor** [comment]
+1

**Comment by rodrigomartin** [comment]
+1

**Comment by Solly5310** [comment]
+1

**Comment by Mousterian** [comment]
+1 I would very much like to use this feature for local dev if it were supported

**Comment by simy307** [comment]
+1 This really needs to become a thing.

**Comment by joshua-lafever** [comment]
This issue has been open for nearly 5 years. Are there any updates on this?

**Comment by AndySemenov** [comment]
The only valid behaviour for the whole SAM CLI is to raise an error telling '{FEATURE_NAME} is not supported in local' every time one tries to bring a local environment up with anything not supported in the template. That would save days of one's time on investigating some bypasses or some inconsistent behaviour of the local environment just because something was silently ignored by SAM.

**Comment by PlemonsBrett** [comment]
Or even an easier solution would be to just put in the Documentation that Local SAM does not support Authorizer testing through API Gateway.

**Comment by AndySemenov** [comment]
I do not agree that putting just a notice in the docs would be enough. Raising an exception with an URL to the documentation page/anchor would be the best solution since that provides an error report on what does not work and an explanation on why it doesn't.

**Comment by c-mysec** [comment]
Maybe as an alternative:
Allow specify a file with additional properties added to the lambda event parameter when running in local environment.
With this feature I will be able to debug functions which depends on authorization claims for example.

**Comment by eldimious** [comment]
+1
Would love to have this feature added to AWS SAM, to be able to test Cognito locally.

**Comment by peyman-se** [comment]
5 years and still nothing. I wonder how many companies rely on lambda but there's still such big feature missing.

**Comment by stnor** [comment]
Please print a **WARNING MESSAGE** when running ```sam local``` when there is an Authorizer in the template. Would have saved me four hours I'll never get back.

**Comment by abelmcelroy** [comment]
+1 I basically desperately want this feature. I'm using cdk, and SAM is the only tool I've found with a fart's chance of shortening my feedback loop (please don't respond with suggestions, I've done very thorough research/testing). But, without this feature I would say that SAM is granting me less than half the utility it could be.

**Comment by abelmcelroy** [comment]
> Thanks @PaulMaddox for the response!
> 
> If I understand the model correctly, it shouldn't matter if my custom authorizer does not run locally, right? In AWS, only authorized requests can trigger the lambda function, correct?

Unfortunately it does matter. Authorizers can create/alter request context, which in many cases is important input to the lambda being invoked.

**Comment by edwardkcyu** [comment]
+1 Really need this feature to test out a modified request context passing to my backend lambda.

**Comment by jmcaree-gp** [comment]
Out of curiosity, is it possible to run your authorizer function locally using `sam local invoke "FunctionName" -e event.json`? I'd like to test the function is working ok before deploying up, just to eliminate the possibility that it's not correct.

**Comment by cyrfer** [comment]
The only reason I'm using SAM is to run locally. It's unfortunate such a critical piece does not work locally.

**Comment by tawheedmanzoor** [comment]
This may be a useful workaround for some of us here:
[https://medium.com/@TawheedM/aws-sam-cli-advanced-testing-running-locally-when-authorizer-is-enabled-9a328d275b7]

Allows you to test locally with hardcoded values for authorizer-injected elements.

**Comment by fabianorodrigo** [comment]
More than a half decade has passed since the original post ... :/

**Comment by lucashuy** [comment]
Hi, thanks for raising your concerns. While I unfortunately do not have a date for when this will be complete, implementation of custom Lambda authorizer support for `sam local start-api` is currently underway.

**Comment by alb3rtuk** [comment]
Would love to see this when it's built and ready to use. @lucashuy Please keep us updated :)

**Comment by lucashuy** [comment]
Hi all, custom Lambda authorizer support for `sam local start-api` has been released as of [SAM CLI v1.80.0](https://github.com/aws/aws-sam-cli/releases/tag/v1.80.0). Feel free to create new issues or discussion threads if there are any problems or features that would fit for SAM CLI.

**Comment by nickls** [comment]
For anyone trying to get this working:
* You'll need to explicitly add `FunctionPayloadType: TOKEN` even though that is the default value.
* Alias function ARN do not work for the `FunctionArn` as they fail a format sanity check.

**Comment by ChronosMasterOfAllTime** [comment]
@lucashuy nice work! Can we please get a usage tutorial on this new feature? I have tried getting this to work and am referencing a local authorizer, yet it is still "not found". Usage details would be great 👍

**Comment by supagu** [comment]
Is there a proper example on how to do this?

**Comment by ChronosMasterOfAllTime** [comment]
> Is there a proper example on how to do this?

There isn't. I requested documentation in issue #5172

**Comment by le0kar0ub1** [comment]
Hi, for those which are struggling to make the thing works, I just found how to after some long hours. 
The problems seems to be that: 
  - you **MUST NOT** provide a `FunctionName` field in your lambda authorizer.
  - you **MUST** provide `FunctionPayloadType: TOKEN` in the API Auth despite the fact that it's the default value.

Minimal example:

```
ApiGateway:
    Type: AWS::Serverless::Api
    Properties:
      StageName: dev
      Auth:
        AddDefaultAuthorizerToCorsPreflight: false
        DefaultAuthorizer: Authorizer
        Authorizers:
          Authorizer:
            FunctionPayloadType: TOKEN
            FunctionArn: !GetAtt Authorizer.Arn
            Identity:
              Header: Authorization
              ReauthorizeEvery: 300

Authorizer:
    Type: AWS::Serverless::Function
    Properties:
      Runtime: nodejs18.x
      CodeUri: path/to/Authorizer
      Handler: app.handler
      Timeout: 5
```

SAM CLI version 1.97.0
AWS CLI version 2.7.21

Hope this can save some hours of many !
