### ISSUE TITLE
Changes to DynamoDB event properties are not deployed

### ISSUE THREAD

**Issue by gavincornwell** [aws/aws-sam-cli#1748]
### Description

Making changes to the [DynamoDB event](https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#dynamodb) properties are not deployed.

### Steps to reproduce

Deploy the following template using "sam deploy --guided"

```
AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: Example to show issue with updating event source mapping

Resources:

  TestTable:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions: 
        - AttributeName: id
          AttributeType: S
      KeySchema: 
        - AttributeName: id
          KeyType: HASH
      BillingMode: PAY_PER_REQUEST
      StreamSpecification:
        StreamViewType: NEW_AND_OLD_IMAGES

  HelloWorldFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: hello_world/
      Handler: app.lambda_handler
      Runtime: python3.7
      Timeout: 10
      Events:
        Stream:
          Type: DynamoDB
          Properties:
            Stream: !GetAtt TestTable.StreamArn
            StartingPosition: TRIM_HORIZON
            BatchSize: 5
            MaximumRetryAttempts: 3
            MaximumBatchingWindowInSeconds: 10
            MaximumRecordAgeInSeconds: 60

```

The Lambda function referenced by the template is very simple:

```
def lambda_handler(event, context):
    
    print("Received event: {}".format(event))

    return {}
```

Once the deployment has completed Examine the DynamoDB trigger in the Lambda console (see screenshot below):

<img width="758" alt="lambda-console-trigger" src="https://user-images.githubusercontent.com/1194868/73092525-b17d7700-3ed4-11ea-980b-3dcc3f27af19.png">

Change the `MaximumRetryAttempts` value to `5` and re-deploy using "sam deploy".

### Observed result

The retry attempts value on the Lambda console remains 3. In fact, changing any of the values or adding an SQS queue as a destination does not take effect.

I have to delete the whole CloudFormation stack and deploy again to get the changes applied.

### Expected result

I would expect the updates to the underlying `AWS::Lambda::EventSourceMapping` to take effect and show on the Lambda console using "sam deploy".

### Additional environment details (Ex: Windows, Mac, Amazon Linux etc)

1. OS: Mac 10.14.6
2. `sam --version`: 0.40.0
