### ISSUE TITLE
Headers are received in Camel-Case

### ISSUE THREAD

**Issue by jiaming10** [aws/aws-sam-cli#1860]
When running `sam local start-api`, I'm getting headers in Camel-Case, (see **X-Api-Key** and **X-User-Id**), however. the deployed lambda function is receiving the headers in lower-case (**x-api-key** and **x-user-id**).

My local code is working as of 2020-03-09 17:00 GMT+8, and I'm trying to understand why the behaviour is different now.

In `sam local`:
```python
{
  'headers': {
    'X-Api-Key': '<redacted>',
    'X-User-Id': '<redacted>',
    'User-Agent': 'PostmanRuntime/7.22.0',
    'Accept': '*/*',
    'Cache-Control': 'no-cache',
    'Host': 'localhost:3000',
    'Accept-Encoding': 'gzip, deflate, br',
    'Connection': 'keep-alive',
    'X-Forwarded-Proto': 'http',
    'X-Forwarded-Port': '3000'
  },
  'multiValueHeaders': {
    'X-Api-Key': ['<redacted>'],
    'X-User-Id': ['<redacted>'],
    'User-Agent': ['PostmanRuntime/7.22.0'],
    'Accept': ['*/*'],
    'Cache-Control': ['no-cache'],
    'Host': ['localhost:3000'],
    'Accept-Encoding': ['gzip, deflate, br'],
    'Connection': ['keep-alive'],
    'X-Forwarded-Proto': ['http'],
    'X-Forwarded-Port': ['3000']
  }
}
```

In AWS Lambda:
```python
{
  'headers': {
    'Accept': '*/*',
    'Accept-Encoding': 'gzip, deflate, br',
    'Cache-Control': 'no-cache',
    'Host': '<redacted>',
    'User-Agent': 'PostmanRuntime/7.22.0',
    'X-Amzn-Trace-Id': 'Root=1-5e6739e1-d6161c849faa6e9a369f680c',
    'x-api-key': '<redacted>',
    'X-Forwarded-For': '175.143.101.237',
    'X-Forwarded-Port': '443',
    'X-Forwarded-Proto': 'https',
    'x-user-id': '<redacted>'
  },
  'multiValueHeaders': {
    'Accept': ['*/*'],
    'Accept-Encoding': ['gzip, deflate, br'],
    'Cache-Control': ['no-cache'],
    'Host': ['<host>'],
    'User-Agent': ['PostmanRuntime/7.22.0'],
    'X-Amzn-Trace-Id': ['Root=1-5e6739e1-d6161c849faa6e9a369f680c'],
    'x-api-key': ['<redacted>'],
    'X-Forwarded-For': ['<IP address>'],
    'X-Forwarded-Port': ['443'],
    'X-Forwarded-Proto': ['https'],
    'x-user-id': ['<redacted>']
  }
}
```

Snippet of `template.yaml` I'm using.
```yml
Resources:
  BasePythonLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      LayerName: pythonBaseLayer
      ContentUri: /app/LambdaCodes/LambdaLayers/PythonLayer
      CompatibleRuntimes:
        - python3.7
  VendorFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: vendor-function
      Handler: vendorFunction.lambda_handler
      Runtime: python3.7
      Timeout: 120
      CodeUri: ./VendorFunction/
      Layers:
        - !Ref BasePythonLayer
      Events:
        Vendor:
          Type: Api
          Properties:
            Path: /vendor
            Method: ANY
```

1. OS: Using docker, `python:alpine`
2. `sam --version`: SAM CLI, version 0.40.0
