### ISSUE TITLE
Local Deployment does not obey stage of the api-gateway

### ISSUE THREAD

**Issue by stevenj** [aws/aws-sam-cli#1904]
I am working on a SAM deployment template.  And I need to be able to test locally and also in AWS.  But the event which is passed from the local API gateway to the lambda function is different enough to the one passed in AWS that it breaks my code.

Marked Differences:
The Local API Gateway does not respect stage.  I have a stage called dev.  I call the API for testing like this:

AWS Cloud Deployment:
```url
https://9999999999.execute-api.us-east-1.amazonaws.com/dev/v1/bounce
```

Local Deployment:
```url
http://127.0.0.1:3000/dev/v1/bounce
```

 in AWS, the event has this:

```json
{
    "resource": "/{proxy+}",
    "path": "/v1/bounce",

    "pathParameters": {
        "proxy": "v1/bounce"
    },

    "requestContext": {
        "path": "/dev/v1/bounce",
        "stage": "dev",
}
```

BUT local deployment gives:

```json
{
    "resource": "/{proxy+}",
    "path": "/dev/v1/bounce",

    "pathParameters": {
        "proxy": "dev/v1/bounce"
    },

    "requestContext": {
        "path": "/{proxy+}",
        "stage": "Prod", 
}
```

So the deployment stage is still in the path, it hasn't been accepted from the URL.  The stage is kept on "Prod" for local deployment.  And the requestContext path is wrong.

Its not possible to make my clients I need to test aware of this difference, they should be able to call the local deployment or the cloud deployment with the same URI, but only a difference host name.

**Comment by c2tarun** [comment]
Hi @stevenj,

Thanks for reporting the issue. I am trying to reproduce it. I created a simple hello world lambda and logged the event passed.

1. curl `http://127.0.0.1:3000/hello` gives following resource and path:
```
resource: '/hello',
path: '/hello/'
```

2. curl `https://xxxxxxxx.execute-api.us-east-1.amazonaws.com/Prod/hello/` gives following resource and path:
```
  resource: '/hello',
  path: '/hello/',
```

My AWS URL does have stage at the end, but API is still the same. Can you please help me understand your issue a bit? Is it not possible to simple replace `https://xxxxxxxx.execute-api.us-east-1.amazonaws.com/Prod` with `http://127.0.0.1:3000` for AWS vs local testing?

**Comment by stevenj** [comment]
The issue is our lambdas check the stage, we allow some things if the stage is "dev" to ease with testing and development, but those things are blocked for any other stage.

As it is, local deployment is inconsistent with aws deployment.  They do not behave the same.

Try deploying to any stage other than "Prod". i never tried deploying to "Prod" our production stage isn't called "Prod" in any event.  Maybe the local gateway checks for "Prod" specifically?

**Comment by c2tarun** [comment]
Hi @stevenj,

I tried with stagename as `NotProd` with following template:
```
...
Resources:
  HelloWorldFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: hello-world/
      Handler: app.lambdaHandler
      Runtime: nodejs12.x
      Events:
        HelloWorld:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            RestApiId: !Ref HelloWorldApi
            Path: /hello
            Method: get
  HelloWorldApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: NotProd
...
```
[Full template file](https://paste.ubuntu.com/p/ftmC2XvsxG/)

1. curl `https://xxxxxxxx.execute-api.us-east-1.amazonaws.com/NotProd/hello/` gives following resource path:

```
resource: '/hello'
path: '/hello'
resourcePath: '/hello'
```

2. curl `http://127.0.0.1:3000/hello`

```
resource: '/hello'
path: '/hello'
resourcePath: '/hello'
```

I am still not able to reproduce the issue. I might be missing something here, can you please share your template.yaml (or a dummy template similar to yours).

Thanks
Tarun
