### ISSUE TITLE
[0.47.0] Template with Cloudwatch Rule Enable/Disable Parameter does not override the status

### ISSUE THREAD

**Issue by lmayorga1980** [aws/aws-sam-cli#1948]
I am trying to deploy a `sam` template that has a Cloudwatch Rule that is supposed to be enabled in prod account but disabled in a sandbox account.

```yaml
AWSTemplateFormatVersion: 2010-09-09
Transform: 'AWS::Serverless-2016-10-31'
Description: |
  MY LAMBDA FUNCTION
Parameters:
  EnableCWRule:
    Description: Enable Cloudwatch Rule.
    Default: 'false'
    Type: String
    AllowedValues:
      - 'true'
      - 'false'
Conditions:
  EnableCloudWatchRule: !Equals
    - !Ref EnableCWRule
    - 'true'

Globals:
  Function:
    Timeout: 60
Resources:
  MYLAMBDAROLE:
    Type: 'AWS::IAM::Role'
    Properties:
      Path: /MY-LAMBDAS/
      RoleName: MYLAMBDAROLE
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
                - events.amazonaws.com
            Action: 'sts:AssumeRole'
      Policies:
        - PolicyName: MYLAMBDAPOLICY
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action:
                  - 'logs:CreateLogGroup'
                  - 'logs:CreateLogStream'
                  - 'logs:PutLogEvents'
                Resource: 'arn:aws:logs:*:*:log-group:/aws/lambda/*:*:*'
              - Effect: Allow
                Action:
                  - 'ec2:ModifyImageAttribute'
                Resource: '*'
  MYFUNCTION:
    Type: 'AWS::Serverless::Function'
    Properties:
      CodeUri: src/
      Handler: myfunction.lambda_handler
      Runtime: python3.7
      Role: !GetAtt MYLAMBDAROLE.Arn
      Events:
        TRIGGERCWRULE:
          Properties:
            Schedule: cron(0 4 * * ? *)
            Enabled: !If EnableCloudWatchRule
          Type: Schedule

Outputs:
  MYFUNCTIONOUTPUT:
    Description: MY FUNCTION
    Value: !GetAtt
      - MYFUNCTION
      - Arn
```

**sam deploy**
```
sam deploy --s3-bucket myfunctions-bucket --stack-name my-function-stack --profile myprofile --region us-east-1 --capabilities CAPABILITY_NAMED_IAM --parameter-overrides EnableCWRule=false
```

Currently, the Cloudwatch Rule is `enabled=true` and when I run the `sam-cli` command, it should switch to `enable=false`.  Instead I am getting the following...

```
        Deploying with following values
        ===============================
        Stack name                 : My-function-stack
        Region                     : us-east-1
        Confirm changeset          : False
        Deployment s3 bucket       :  myfunctions-bucket
        Capabilities               : ["CAPABILITY_NAMED_IAM"]
        Parameter overrides        : {'EnableCWRule': 'false'}

Initiating deployment
=====================

Waiting for changeset to be created..
No changes to deploy. Stack my-function-stack is up to date
```

🤔 Is there a workaround to pass boolean parameters to my sam deployment process.

Thanks.
