### ISSUE TITLE
ClassNotFoundException when running SAM in Docker container using Java class files

### ISSUE THREAD

**Issue by nholt321** [aws/aws-sam-cli#2046]
# Description

I tried looking through the other issues that describe ClassNotFoundException but they all seem to be related to using jar/zip files as the artifact.

I'm having an issue when attempting to point SAM directly to compiled Java class files in my template.yml instead of using a jar/zip file, but only when running inside Docker. I'm on a Windows machine, and when I run SAM directly on my host machine pointing to the class files it works perfectly. This is much better than pointing to the jar file because it allows me to pick up changes in my function much quicker/easier. However, when I try to run the exact same thing inside a Docker container I keep getting ClassNotFoundException, even though I can see the files are all there in the image that's being mounted when running the lambda function. I also directly ran the lambci/lambda image on my host and mounted the class files and that worked perfectly as well. So it seems to be something special about running inside the container. I am able to run successfully with jar file inside container, and had to mount "/tmp:/tmp" for this to work. Wondering if there's some special mount that I'm missing or some other special config?

### Steps to reproduce

1. Create hello-world project from SAM template
```console
sam init --dependency-manager maven --runtime java11 --name hello-world --app-template hello-world
```
2. Run sam build to build Java class files into .aws-sam/build folder
```console
sam build
```
3. Template.yaml in /.aws-sam/build pointing to function
```yaml
Resources:
  HelloWorldFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: HelloWorldFunction
      Handler: helloworld.App::handleRequest
      Runtime: java11
      MemorySize: 512
      Environment: # More info about Env Vars: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#environment-object
        Variables:
          PARAM1: VALUE
      Events:
        HelloWorld:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /hello
            Method: get
```
4. Dockerfile with compiled files copied into image (shortened)
``` dockerfile
FROM amazoncorretto:11 as start_api
#install aws-sam-cli from homebrew (removed for brevity)

#move built class files into image
WORKDIR /usr/src/app
COPY ./.aws-sam/build/template.yaml ./template.yaml
COPY ./.aws-sam/build/HelloWorldFunction ./HelloWorldFunction/

EXPOSE 3000

CMD ["sam", "local", "start-api", "--template", "./template.yaml", "--profile", "default",  "--debug", "--host", "0.0.0.0"]
```
5. Docker build
```console
docker build -f docker/Dockerfile -t hello-world .
```
6. Docker run
```console
docker run -it --rm -v /var/run/docker.sock:/var/run/docker.sock -p 3000:3000 --name hello-world hello-world
```
7. hit endpoint _http://localhost:3000/hello_
```console
curl http://localhost:3000/hello
```

### Observed result
ClassNotFoundException from lambci/lambda:java11 container

```console
Found one Lambda function with name 'HelloWorldFunction'
Invoking helloworld.App::handleRequest (java11)
Environment variables overrides data is standard format
Loading AWS credentials from session with profile 'default'
Resolving code path. Cwd=/usr/src/app, CodeUri=HelloWorldFunction
Resolved absolute path to code is /usr/src/app/HelloWorldFunction
Code /usr/src/app/HelloWorldFunction is not a zip/jar file
Skipping building an image since no layers were defined

Fetching lambci/lambda:java11 Docker container image......
Mounting /usr/src/app/HelloWorldFunction as /var/task:ro,delegated inside runtime container
Starting a timer for 20 seconds for function 'HelloWorldFunction'
START RequestId: 7bcfb00c-a433-15e7-5aa0-c25475a40c50 Version: $LATEST
Class not found: helloworld.App: java.lang.ClassNotFoundException
java.lang.ClassNotFoundException: helloworld.App
        at java.base/java.net.URLClassLoader.findClass(Unknown Source)
        at java.base/java.lang.ClassLoader.loadClass(Unknown Source)
        at java.base/java.lang.ClassLoader.loadClass(Unknown Source)
        at java.base/java.lang.Class.forName0(Native Method)
        at java.base/java.lang.Class.forName(Unknown Source)

END RequestId: 7bcfb00c-a433-15e7-5aa0-c25475a40c50
REPORT RequestId: 7bcfb00c-a433-15e7-5aa0-c25475a40c50  Init Duration: 118.28 ms        Duration: 57.75 ms      Billed Duration: 100 ms Memory Size: 512 MB     Max Memory Used: 64 MB
Lambda returned empty body!
Invalid API Gateway Response Keys: {'errorType', 'errorMessage'} in {'errorType': 'java.lang.ClassNotFoundException', 'errorMessage': 'Class not found: helloworld.App'}
<class 'samcli.local.apigw.local_apigw_service.LambdaResponseParseException'>
```

Contents of mounted paths in image:
```console
/usr/src/app
|-- HelloWorldFunction
|   |-- helloworld
|   |   |-- App.class
|   |   `-- GatewayResponse.class
|   `-- lib
|       `-- aws-lambda-java-core-1.2.0.jar
`-- template.yaml
```

### Expected result

Successful 200 response with "hello world" message.

### Additional environment details (Ex: Windows, Mac, Amazon Linux etc)

1. OS: Windows 10 (but running inside Linux containers)
2. `sam --version: SAM CLI, version 0.52.0`
3. `docker --version: Docker version 19.03.8, build afacb8b`
