### ISSUE TITLE
sam local start with custom template is not working as expected

### ISSUE THREAD

**Issue by swamigmv** [aws/aws-sam-cli#2073]
I have a custom template created and i gave below command to start sam locally
sam local start-api --template .\templates\new-template.yaml

in this case, I am getting no module name *** error. Basically some problem with the deployment
Observed below while using template
******************
Building image...
Requested to skip pulling images ...

Mounting <path to project>\<folder containing lambda> as /var/task:ro,delegated inside runtime container
*******************

while if i have the same template as "template.yml" and start the same with "sam local start-api".
I observe below 
******************
Building image...
Requested to skip pulling images ...

Mounting <path to project>**\.aws-sam\build**\<lambda_name> as /var/task:ro,delegated inside runtime container
*******************

I have a windows 10 machine and using 0.52 version of sam.

**Comment by c2tarun** [comment]
Hi @swamigmv,

Can you please share your template with us? I tried same thing and it worked for me. Please see my logs below:

```
❯ sam build -t templates/new-template.yaml                                                                                                                                               
Building function 'HelloWorldFunction'
Running PythonPipBuilder:ResolveDependencies
Running PythonPipBuilder:CopySource

Build Succeeded

Built Artifacts  : .aws-sam/build
Built Template   : .aws-sam/build/template.yaml

Commands you can use next
=========================
[*] Invoke Function: sam local invoke
[*] Deploy: sam deploy --guided
                                                                                                             
❯ sam local start-api -t templates/new-template.yaml                                                                                                                                     
Mounting HelloWorldFunction at http://127.0.0.1:3000/hello [GET]
You can now browse to the above endpoints to invoke your functions. You do not need to restart/reload SAM CLI while working on your functions, changes will be reflected instantly/automatically. You only need to restart SAM CLI if you update your AWS SAM template
2020-07-17 14:08:32  * Running on http://127.0.0.1:3000/ (Press CTRL+C to quit)
```

My `templates/new-template.yaml`:

```
AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  issue-2073

  Sample SAM Template for issue-2073

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 3

Resources:
  HelloWorldFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: ../hello_world/
      Handler: app.lambda_handler
      Runtime: python3.8
      Events:
        HelloWorld:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /hello
            Method: get
```
