### ISSUE TITLE
sam build --use-container not working correctly with v1.0.0 

### ISSUE THREAD

**Issue by ORDEP81** [aws/aws-sam-cli#2133]
### Description

While trying to run `sam build --use-container` I get the following error. 
`Build Failed Error: Docker is unreachable. Docker needs to be running to build inside a container.` even though docker is installed and running. It breaks when trying to build the Function. If you introduce a typo to the end of `Type:AWS::Serverless::Functionc` this works for some reason and the get the "Build Succeeded" message. Once you deploy then you come across error `Unresolved resource dependencies [ServerlessRestApi] in the Outputs block of the template`
this is fixed by placing the full path to the functions folder in the .aws-sam/build template.yaml file. This file also contains other errors and the typo for the function at this point will also have to be corrected.
```
Resources:
  S3Bucket:
    Type: AWS::S3::Bucket
  TestFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: Lambda/
      Handler: app.lambda_handler
      Runtime: python3.8

```
### Steps to reproduce
`sam build --use-container` with the following teamplate.yaml
```
AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: 'test'
Resources:
  S3Bucket:
    Type: AWS::S3::Bucket
  TestFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri:Lambda/
      Handler: app.lambda_handler
      Runtime: python3.8
      Events:
        test:
          Type: Api
          Properties:
            Path: /hello
            Method: get
Outputs:
  testApi:
    Description: "API Gateway endpoint URL for Prod stage for Hello World function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/hello/"

```

### Observed result
`Build Failed Error: Docker is unreachable. Docker needs to be running to build inside a container.` 

### Expected result

Describe what you expected.
"Build Succeeded"
### Additional environment details (Ex: Windows, Mac, Amazon Linux etc)

1. OS: Ubuntu 18/04
2. `sam --version`: SAM CLI version 1.0.0

`Add --debug flag to command you are running`
