### ISSUE TITLE
Unable to POST json to lambda via start-api

### ISSUE THREAD

**Issue by CABellamy** [aws/aws-sam-cli#2183]
### Description

When trying to invoke a lambda via curl POST the event data is not coming through to the lambda. If I invoke using sam cli invoke and passing the json this works fine, but using the same payload as a curl request when using sam cli start-api this payload is not getting through the lambda. 
### Steps to reproduce

lambda code:
```
type Event struct {
	Field string `json:"field"`
}

func main() {
	lambda.Start(handler)
}

func handler(_ context.Context, input Event) (interface{}, error) {
	fmt.Print(input)
}
```
template:
```
AWSTemplateFormatVersion : '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Globals:
  Function:
    Runtime: go1.x
Resources:
  nannyDynamodbTransaction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: app/lambdas/nanny_dynamodb_transaction/
      Handler: nanny_dynamodb_transaction
      Runtime: go1.x
      Events:
        Transaction:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /transaction
            Method: POST
```

post request: 
```
curl -X POST -H "Content-Type: application/json" -d '{"field": "test"}' https://localhost:3000/transaction
```
Provide steps to replicate.

### Observed result

result is {} as if the struct is never populated from the post event.

Please provide command output with `--debug` flag set.

### Expected result

I expect the payload to be printed out

### Additional environment details (Ex: Windows, Mac, Amazon Linux etc)

1. OS: OS X
2. `sam --version`: 0.52.0
