### ISSUE TITLE
FAILED. Reason: Invalid template property or properties [Schedule]

### ISSUE THREAD

**Issue by mooperd** [aws/aws-sam-cli#2185]
Hi, the following template passes `sam validate` but sam build gives me an error:

```
Waiting for changeset to be created..
Error: Failed to create changeset for the stack: meow-tronik, ex: Waiter ChangeSetCreateComplete failed: Waiter encountered a terminal failure state Status: FAILED. Reason: Invalid template property or properties [Schedule]
```

Am I doing something stupid?

```
AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: A starter AWS Lambda function.
Parameters: 
    IdentityNameParameter: 
      Type: String
Resources:
  helloworldpython:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: lambda_function.lambda_handler
      Runtime: python2.7
      CodeUri: .
      Description: A starter AWS Lambda function.
      MemorySize: 128
      Timeout: 3
      Policies:
        - SESSendBouncePolicy:
            IdentityName: !Ref IdentityNameParameter
      Events:
        CWSchedule:
          Type: Schedule
          Properties:
            Schedule: rate(1 minute)
            Name: TestSchedule
            Description: test schedule
            Enabled: True
```
