### ISSUE TITLE
Nested Stacks 

### ISSUE THREAD

**Issue by AgentGoldenPaw** [aws/aws-sam-cli#2197]
### Describe your idea/feature/enhancement

I wish SAM CLI would allow !Sub on a Serverless::Function.Layers. 

I use nested stacks pretty heavily and I am trying to use a global layer described in the master template and pass the ARN to a nested stack and then attach to a function.

### Proposal

https://github.com/aws/aws-sam-cli/blob/develop/samcli/lib/providers/sam_function_provider.py#L271

Can add code right here, at least I think. I attempted to figure out as much as I could. As far as a full proposal, I will look at how !Sub is handled in other places.

**Comment by th3g3ntl3men** [comment]
I looked into, I would love to learn more about the inner workings and contribute. But I am having trouble figuring out where parsing of the template occurs. (Not a python developer.)

**Comment by mndeveci** [comment]
Hi @th3g3ntl3men , can you explain your feature request in a little bit detail, giving some examples with it?

**Comment by th3g3ntl3men** [comment]
template A: 
```yaml
AWSTemplateFormatVersion: 2010-09-09
Transform: AWS::Serverless-2016-10-31
Resources:
  layercto:
    Type: AWS::Serverless::LayerVersion
    Properties:
      Description: !Sub
        - Stack ${StackTagName} Environment ${EnvironmentTagName} Layer ${ResourceName}
        - ResourceName: layer
      ContentUri: src/layer
      RetentionPolicy: Delete
      CompatibleRuntimes:
        - nodejs12.x
    Metadata:
      BuildMethod: nodejs12.x
  Stack:
    Type: AWS::Serverless::Application
    Properties:
      Location: ./templateB.yaml
      Parameters:
           Layer: !Ref Layer
```

template b: 
```yaml
AWSTemplateFormatVersion: 2010-09-09
Transform: AWS::Serverless-2016-10-31
Resources:
  createCustomer:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub ${AWS::StackName}-createCustomer
      Description: !Sub
        - Stack ${StackTagName} Environment ${EnvironmentTagName} Function ${ResourceName}
        - ResourceName: Function
      CodeUri: src/Function
      Handler: index.handler
      Runtime: nodejs12.x
      MemorySize: 3008
      Timeout: 30
      Tracing: Active
      Policies:
        - AWSXrayWriteOnlyAccess
      Layers:
        - !Sub ${Layer}
Parameters: 
Layer:
    Type: String
    Description: Log destination for apis.
```

Template B breaks because If the value for a layer is a string, the code assumes it's a ARN. Basically I want my layer managed by my root stack, but be able to share the ARN dynamically across my nested stacks. 

Does that make sense?
