### ISSUE TITLE
API gateway: variabilize a openapi file and pass arguments to it

### ISSUE THREAD

**Issue by ahafid1** [aws/aws-sam-cli#2199]
According to the documentation (link below), we can recover the three variables in the openapi file  (AWS::AccountId, AWS::Partition & AWS::Region).

Is this list frozen or we can use other custom variables ?

I use AWS CLI for import Openapi file.

https://docs.aws.amazon.com/apigateway/latest/developerguide/import-api-aws-variables.html

Thank you

**Comment by mndeveci** [comment]
Hi @ahafid1 , the variables that you pointed is exported by the CFN/SAM to substitute some of the internal information with the running stack.

If you want to use custom variables in your template, both SAM and CFN has parameters in the template definitions. See documentation here; https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/sam-specification-template-anatomy.html

**Comment by rostskadat** [comment]
Hello @mndeveci, @wchengru 

I think this question has not been "properly" answered. As I understand it @atigm  was referring to using variables within the OpenAPI template, rather than the CloudFormation template. I assume that the rational behind that is to be able to get the Lambda function ARN dynamically without having to specify the function name. For instance given the following CloudFormation template:

```yaml
  Api:
    Type: AWS::Serverless::Api
    Properties:
      DefinitionUri: ./api.yaml

  Function:
    Type: AWS::Serverless::Function 
    Properties:
      CodeUri: lambdas/Function
```
The Open API template could be written like this:
```yaml
...
      x-amazon-apigateway-integration:  
        uri: "arn:${AWS::Partition}:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${Function.Arn}/invocations"
...
```
Which would make keeping everything in sync so much easier, especially with *un-named* lambda functions
