### ISSUE TITLE
SAM Local Not Loading ARN Layer

### ISSUE THREAD

**Issue by moderatelyfunctional** [aws/aws-sam-cli#2216]
### Description
AWS Sam Local fails to find statically built `FFmpeg` ARN Layer. 

### Relevant Details
The relevant section in the `template.yaml` is shown below.
```
  FfmpegLayer:
    Type: AWS::Serverless::Function
    Properties:
      Handler: app.lambda_handler
      Runtime: Python3.8
      Layers:
        - arn:aws:lambda:us-xxxx-1:xxxxxxxxxxxx:layer:ffmpeg:1
``` 

In `lambda_handler` function, the relevant section is `subprocess.call(['/opt/bin/ffmpeg', '-i'])`. 

#### Other Details
The `/opt` directory is empty which suggests the ARN isn't loaded.
However, I can add the ARN to the Lambda in the AWS Console and the same `subprocess` call works. 

Thanks for the help!
