### ISSUE TITLE
Environment.Variables not being passed to functions

### ISSUE THREAD

**Issue by aprilmintacpineda** [aws/aws-sam-cli#2220]
### Description

I want to set `process.env.SYSTEM_EMAIL`.

```yaml
# This is the SAM template that represents the architecture of your serverless application
# https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/serverless-sam-template-basics.html

# The AWSTemplateFormatVersion identifies the capabilities of the template
# https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/format-version-structure.html
AWSTemplateFormatVersion: 2010-09-09
Description: >-
  rn-cost-trail-sls

# Transform section specifies one or more macros that AWS CloudFormation uses to process your template
# https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/transform-section-structure.html
Transform:
- AWS::Serverless-2016-10-31

Parameters:
  Stage:
    Description: Required staged of the current build
    Type: String
    Default: dev

Globals:
  Function:
    MemorySize: 128
    Timeout: 60
    Environment:
      Variables:
        SYSTEM_EMAIL: "test@test.com"
  Api:
    OpenApiVersion: 3.0.1

# Resources declares the AWS resources that you want to include in the stack
# https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/resources-section-structure.html
Resources:
  # Each Lambda function is defined by properties:
  # https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction

  login:
    Type: AWS::Serverless::Function
    Properties:
      Handler: src/functions/login.handler
      Runtime: nodejs12.x
      Layers:
        - !Ref dependencies
      Events:
        ApiEvent:
          Type: Api
          Properties:
            Method: post
            Path: /login
            RestApiId:
              Ref: mainBackendApi
  register:
    Type: AWS::Serverless::Function
    Properties:
      Handler: src/functions/register.handler
      Runtime: nodejs12.x
      Layers:
        - !Ref dependencies
      Events:
        ApiEvent:
          Type: Api
          Properties:
            Method: post
            Path: /register
            RestApiId:
              Ref: mainBackendApi
  dependencies:
    Type: AWS::Serverless::LayerVersion
    Properties:
      CompatibleRuntimes:
        - nodejs12.x
      ContentUri: src/dependencies
      LayerName: rn-cost-trail
      RetentionPolicy: Retain
  mainBackendApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: !Ref Stage
```

### Steps to reproduce

- Please see yaml file above.
- do sam local start-api

### Observed result

`console.log(process.env.SYSTEM_EMAIL);` is undefined

### Expected result

`console.log(process.env.SYSTEM_EMAIL);` should be what was set on yaml file

### Additional environment details (Ex: Windows, Mac, Amazon Linux etc)

1. OS: Mac
2. `sam --version`: SAM CLI, version 1.2.0

`Add --debug flag to command you are running`
