### ISSUE TITLE
Unable to define IAM Authorizer for HttpApi

### ISSUE THREAD

**Issue by robertsosinski** [aws/aws-sam-cli#2233]
### Description

I would like to define an `AWS_IAM` Authorizer on an `HttpApi` Integration for a `AWS::Serverless::Function` in the Event Source.  I currently have this:

```
Events:
    HttpApiEvent:
        Type: HttpApi 
        Properties:
            ApiId: !Ref HttpApiGateway
            Method: ANY
            Path: /v1/{proxy+}
            Auth:
                Authorizer: AWS_IAM
```

My HttpApi Gateway definition looks like this:

```
HttpApiGateway:
    Type: AWS::Serverless::HttpApi
    Properties:
        StageName: !Ref StageName
```

I've also tried IAM, and "IAM (built-in)".  The error I always get is ` Unable to set Authorizer [IAM] on API method [any] for path [/v1/{proxy+}] because the related API does not define any Authorizers.`

I am unable to define an IAM Authorizer in my HttpApi because it is a built-in and there by default.  I've looked at the docs, and have found this https://github.com/aws/serverless-application-model/blob/master/versions/2016-10-31.md#function-auth-object but this seems to be for an `Api`, not an `HttpApi`.

### Steps to reproduce

Define a template.yml with the above specifications for an HttpApi and Function.  Then attempt to do a `sam deploy`.  You will get the error above.

### Observed result

Unable to define an IAM Authorizer for an HTTP API integration with template.yml

### Expected result

Being able to define an IAM Authorizer for an HTTP API integration with template.yml

### Additional environment details (Ex: Windows, Mac, Amazon Linux etc)

1. OS: Windows 10
2. `sam --version`: SAM CLI, version 1.1.0
3. Python 3.8.3

If I'm doing something wrong, please let me know.

Appreciate the help!
