### ISSUE TITLE
HttpApiStage | CREATE_FAILED | Internal Failure

### ISSUE THREAD

**Issue by stlimtat** [aws/aws-sam-cli#2237]
### Describe your idea/feature/enhancement

When running `sam deploy` with the following configuration
```
  HttpApi:
    Type: AWS::Serverless::HttpApi
    Properties:
      AccessLogSettings:
        DestinationArn:
          Fn::GetAtt: AccessLogs.Arn
        Format: '{"requestId":"$context.requestId","ip":"$context.identity.sourceIp","caller":"$context.identity.caller", "user":"$context.identity.user","requestTime":$context.requestTimeEpoch,"httpMethod":"$context.httpMethod","status":$context.status,"protocol":"$context.protocol","responseLength":$context.responseLength}'
      Domain:
        CertificateArn: arn:aws:acm:ap-southeast-1:<accountId>:certificate/<some account number>
        DomainName:
          Ref: DomainName
        Route53:
          HostedZoneId: ABCDE
          EvaluateTargetHealth: True
          IpV6: True
      # DefaultRouteSettings:
      #   DetailedMetricsEnabled: True
      #   LoggingLevel: DEBUG
      #   DataTraceEnabled: False
      # FailOnWarnings: True
      StageName:
        Ref: StageName
      StageVariables:
        StageVar: Value
      Tags:
        env:
          Ref: StageName
        service: testme
```
I get stuck in 

```
testme-staging | ROLLBACK_IN_PROGRESS | The following resource(s) failed to create: [HttpApiStage]. . Rollback requested by user.
-- | -- | --
2020-09-22 10:35:20 UTC+0800 | HttpApiStage | CREATE_FAILED | Internal Failure
```

Any idea what is causing this since internal failure is too vague for me.

### Proposal

Add details of how to add this to the product.

Things to consider:
1. Will this require any updates to the [SAM Spec](https://github.com/awslabs/serverless-application-model)
