### ISSUE TITLE
Can I only deploy Lambda function source with duplication?

### ISSUE THREAD

**Issue by mikezang** [aws/aws-sam-cli#2243]
### Describe your idea/feature/enhancement

When I create Lambda function on AWS console, one function with one file as below:
![LambdaFunctionSingle](https://user-images.githubusercontent.com/1030268/94001945-31e1d800-fdd4-11ea-99e2-f2ba43109596.jpg)

But when I use SAM deploy, I defined four functions, but all source files are copied into these four functions, like this:
![LambdaFunction](https://user-images.githubusercontent.com/1030268/94001786-fb0bc200-fdd3-11ea-890a-8fcf70e5eb9b.jpg)

### Proposal

May I only upload function source itself without other function's source?

Things to consider:
1. Can I do it with cuurent version AWS or SAM?
2. Will this require any updates to the [SAM Spec](https://github.com/awslabs/serverless-application-model)

**Comment by hawflau** [comment]
It looks like there are two issues here:
1. The deployed Lambda function contains files like `EventS3.json` or `samconfig.toml`, which I believe are not needed for your lambda function to work.
2. Your question - May I only upload function source itself without other function's source?

For the first one, you can update the `CodeUri` under your function definition in the SAM template to point to the exact path of your lambda function source code.
For your question, you can place your function source code into separate directories, and update `CodeUri` in each function definition in the SAM template to point to corresponding path.

For example, if I want to deploy two lambda functions `HelloWordFunctionA` and `HelloWorldFunctionB`, and their source codes are independent of each other but want to deploy them into one stack, I can structure the SAM project like this:
```
sam-app/
   ├── README.md
   ├── events/
   │   └── event.json
   ├── hello_world_a/
   │   ├── __init__.py
   │   ├── app.py            #Contains AWS Lambda handler logic for HelloWordFunctionA.
   │   └── requirements.txt  #Contains any Python dependencies the application requires, used for sam build
   ├── hello_world_b/
   │   ├── __init__.py
   │   ├── app.py            #Contains AWS Lambda handler logic for HelloWordFunctionA.
   │   └── requirements.txt  #Contains any Python dependencies the application requires, used for sam build
   ├── template.yaml         #Contains the AWS SAM template defining your application's AWS resources.
```

In `template.yaml`, define `CodeUri` for each function resource to point to the right path:
```
...
Resources:
  HelloWorldFunctionA:
    Type: AWS::Serverless::Function 
    Properties:
      CodeUri: hello_world_a/
      Handler: app.lambda_handler
      Runtime: python3.8
      Timeout: 900

  HelloWorldFunctionB:
    Type: AWS::Serverless::Function 
    Properties:
      CodeUri: hello_world_b/
      Handler: app.lambda_handler
      Runtime: python3.8
      Timeout: 900
```

Hope this helps. Please reopen if it doesn't solve your issue.
