### ISSUE TITLE
Parameter overrides as a first class section in samconfig.toml

### ISSUE THREAD

**Issue by benkehoe** [aws/aws-sam-cli#2253]
The `parameter_overrides` field in `[default.deploy.parameters]` consists of space-separated `Key=Value` pairs. While [toml supports multiline strings](https://toml.io/en/v1.0.0-rc.2#string), it causes an error because it does not process newlines as whitespace. Fixing that would be an improvement, but what I'd really prefer is that these key-value pairs get their own proper section. Say my `samconfig.toml` would look like:

```toml
version=0.1
[default.deploy.parameters]
stack_name = "my-app-stack"
s3_bucket = "my-source-bucket"

[default.deploy.parameters.template_parameters]
TemplateInput1 = "Value1"
TemplateInput2 = "Value2"
```

equivalent to

```toml
version=0.1
[default.deploy.parameters]
stack_name = "my-app-stack"
s3_bucket = "my-source-bucket"
parameter_overrides = "TemplateInput1=Value1 TemplateInput2=Value2"
```

One of the things this would make easier is updating the values in this file programmatically.
