### ISSUE TITLE
Odd parameter overrides quoting parameter

### ISSUE THREAD

**Issue by abrooksv** [aws/aws-sam-cli#2299]
### Description

This is a follow up to https://github.com/aws/aws-toolkit-jetbrains/pull/2027 and https://github.com/aws/aws-toolkit-jetbrains/issues/2135

### Steps to reproduce

Template:
```
AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Parameters:
  config:
    Type: String

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 20

Resources:
  HelloWorldFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: HelloWorldFunction
      Handler: helloworld.App::handleRequest
      Runtime: java8
      MemorySize: 512
      Environment: # More info about Env Vars: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#environment-object
        Variables:
          PARAM1: VALUE
      Events:
        HelloWorld:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /hello
            Method: get
```

Deploy using:

`config -> {"hello": "world"}

### Observed result

The IDE generates the following CLI:
```
/Users/<user>/.pyenv/versions/samcli/bin/samdev deploy --template-file /Users/<user>/IdeaProjects/untitled3/.aws-sam/build/packaged-template.yaml --stack-name TestJsonParams --s3-bucket <user>-hello-world --capabilities CAPABILITY_IAM CAPABILITY_NAMED_IAM --no-execute-changeset --parameter-overrides "\"config\"=\"{\"hello\": \"world!\"}\""
```

SAM claims that config's value is "{":

```

	Deploying with following values
	===============================
	Stack name                   : TestJsonParams
	Region                       : us-east-1
	Confirm changeset            : False
	Deployment s3 bucket         : <user>-hello-world
	Capabilities                 : ["CAPABILITY_IAM", "CAPABILITY_NAMED_IAM"]
	Parameter overrides          : {'config': '{'}
```

### Expected result

We should be able to deploy the json string as a parameter.

The IDE's generated quoted string seems correct to me based on the requirements on the quoting / space handling.

### Additional environment details (Ex: Windows, Mac, Amazon Linux etc)

1. OS: OSX
2. `sam --version`: 1.4.0
