### ISSUE TITLE
Running sam template with Event Source of MSK

### ISSUE THREAD

**Issue by stlimtat** [aws/aws-sam-cli#2308]
### Description

```
An event source mapping with event source arn ("arn:aws:kafka:ap-southeast-1:"), function ("arn:aws:lambda:ap-southeast-1::function:TestMskFunction-staging:live") and topics ("test_topic") already exists. Please update or delete the existing mapping with UUID (Service: Lambda, Status Code: 409, Request ID: 48e13f8e-bb8d-4c97-91b8-14f37a4714c6, Extended Request ID: null)
```

### Steps to reproduce

I use a template file with the following snippet:
```
  TestMskFunction:
    Type: AWS::Serverless::Function
    Properties:
      AutoPublishAlias: live
      CodeUri: test_msk/
      FunctionName: TestMskFunction-staging
      Handler: app.lambda_handler
      Runtime: python3.8
      Tracing: Active
      Environment:
        Variables:
          env:
            Ref: StageName
          service: test_msk
          KAFKA_BOOTSTRAP:
            Ref: KafkaBootStrap
      VpcConfig:
        SecurityGroupIds:
          Ref: MskClientSecurityGroupIds
        SubnetIds:
          Ref: MskClientSubnetIds
      Events:
        TestTopicEvent:
          Type: MSK
          Properties:
            StartingPosition: LATEST
            Stream:
              Ref: MskClusterArn
            Topics:
              - test_topic
```

when running on the command line on my own machine, `sam build; sam deploy` works fine.  When running on my CD server, I get the error provided above in my cloudformation logs.

sam deploy --template-file /opt/atlassian/pipelines/agent/build/.bitbucket/pipelines/generated/pipeline/pipes/atlassian/aws-sam-deploy/packaged.yml --stack-name <YOUR STACK NAME>

```
An event source mapping with event source arn ("arn:aws:kafka:ap-southeast-1:"), function ("arn:aws:lambda:ap-southeast-1::function:TestMskFunction-staging:live") and topics ("test_topic") already exists. Please update or delete the existing mapping with UUID (Service: Lambda, Status Code: 409, Request ID:, Extended Request ID: null)
```

Is there something I am missing?

### Observed result

Please provide command output with `--debug` flag set.

### Expected result

I should be able to run the command on the CD platform which should achieve the same effect as what I get on my desktop.

### Additional environment details (Ex: Windows, Mac, Amazon Linux etc)

1. OS: Mac on my personal host, CD platform OS: python:3.8.5
2. `sam --version`: 

`Add --debug flag to command you are running`
