### ISSUE TITLE
States.Format does not appear to work with AWS::Serverless::StateMachine

### ISSUE THREAD

**Issue by milesgranger** [aws/aws-sam-cli#2315]
### Description

Given this:
```yaml
          SendNotification:
            Type: Task
            Resource: arn:aws:states:::sns:publish
            Parameters:
              TopicArn: !Ref SnsTopic
              Message.$: |
                States.Format('Some special message about {} and {}', $.foo, $.bar)
              Subject: "Super duper"
            Next: DoSomethingElse
```
I have tried other variations, such as converting everything in "Parameters" to be JSON rather than YAML; the same error occurs.

### Observed result

CloudFormation gives an error:
```
Invalid State Machine Definition:                
'SCHEMA_VALIDATION_FAILED: 
The value for the field 'Message.$' must be a      
valid JSONPath at /States/SendNotification/Parameters' 
(Service: AWSStepFunctions; Status   
Code: 400; Error Code:InvalidDefinition
...
```

### Expected result

I expected it to follow the behavior outlined in the [Step Functions Intrinsic Functions](https://docs.aws.amazon.com/step-functions/latest/dg/amazon-states-language-intrinsic-functions.html) documentation.
