### ISSUE TITLE
Set messageAttribute in an SNS Notification when --notification-arns is populated

### ISSUE THREAD

**Issue by dwardu89** [aws/aws-sam-cli#2321]
### Describe your idea/feature/enhancement

I am using the command below to deploy, and I want to be able to filter SNS notifications depending on the message attributes. However no attributes are provided, this requires me to make another lambda to just create message attributes then send that notification again.
``` sam deploy \
		--template-file serverless-output.yaml \
		--capabilities CAPABILITY_IAM \
		--region $(REGION) \
		--notification-arns $(NOTIFICATION_ARNS) \
		--stack-name $(STACK_NAME)```

### Proposal

Add details of how to add this to the product.

In order to make this easier, have the deploy function populate the messageAttributes field in the specificed sns notification ARNs.

Things to consider:
1. Will this require any updates to the [SAM Spec](https://github.com/awslabs/serverless-application-model)

### Additional Details

**Comment by Bradleywboggs** [comment]
Maybe I'm not understanding your use case, but It seems like you're wanting to add configuration to the lambda itself by adding a sam deploy flag? 

I'd think it would be preferable to configure your lambda's SNS subscription  to have a `FilterPolicy`  in your template .
(Apologies if you know all this, and I'm just misunderstanding!)
If you have a lambda `MyLambdaFunc1` and you want it triggered by `SomeSNSTopic` when the SNS Message has a `MessageAttribute` of `theAnswerToLifeTheUniverseAndEverything` whose value is `FortyTwo`, it would look like this.
``` 
 MyLambdaFunc1:
    Type: 'AWS::Serverless::Function'
    Properties:
          ....Insert Properties here
      Events:
        SNSPayloadsSent:
          Type: SNS
          Properties:
            Topic: !Ref SomeSNSTopic
            FilterPolicy:
              theAnswerToLifeTheUniverseAndEverything:
                - "FortyTwo"
```
And then whatever code is responsible to send messages to the topic would define the MessageAttribute when the SNS message is created.
