### ISSUE TITLE
Setting ApiId on HttpApi Event prevent reoute from being added

### ISSUE THREAD

**Issue by mrgleba** [aws/aws-sam-cli#2322]
### Description

```
AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  Sample SAM Template for sam-app

Parameters: 
  ApiTypeParameter: 
    Type: String
    Default: prod
    AllowedValues: 
      - prod
      - local

Globals:
  Function:
    Timeout: 30

Conditions:
  LocalDevCondition:
    !Equals 
      - !Ref ApiTypeParameter
      - local
  ProdDevCondition:
    !Equals 
      - !Ref ApiTypeParameter
      - prod


Resources:
  HelloWorldHttpApi:
    Type: AWS::Serverless::HttpApi
    Properties:
      Auth:
        Authorizers:
          xxx:
            IdentitySource: Authorization
            JwtConfiguration: 
              issuer: ###
              audience: 
                - ###
        DefaultAuthorizer: xxx      

  HelloWorldFunctionHttp:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Condition: ProdDevCondition
    Properties:
      CodeUri: ./src/HelloWorld/
      Handler: HelloWorld::Test.LambdaEntryPointHTTP::FunctionHandlerAsync
      Runtime: dotnetcore3.1
      Events:
        HelloWorld:
          Type: HttpApi # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /{proxy+}
            Method: ANY
            ApiId: !Ref HelloWorldHttpApi
```

### Steps to reproduce

sam deploy

### Observed result

With the last line ```ApiId: !Ref HelloWorldHttpApi``` present no routes get created in API gateway.

### Expected result

Routes created with the autorizer set.
Removing the last line brings back the routes but without the authorizer

### Additional environment details (Ex: Windows, Mac, Amazon Linux etc)

1. OS: Ubuntu 20 under Win10 WSL2
2. SAM CLI, version: 1.6.2
