### ISSUE TITLE
Local lambda with source code "Runtime.ImportModuleError: Unable to import module..., No Module Name..."

### ISSUE THREAD

**Issue by DallasP9124** [aws/aws-sam-cli#2335]
I started a new python project to host the source code for all my lambda functions represented in different directories of the project. The ides is to have a directory/module for each set of lambda handler code and a module for 'shared' code that will be packaged for a layer.

The project structure is:

```
.
|__src
|    |__shared
|    |    |__common.py
|    |    |__requirements.txt
|    |__function_a
|    |    |__function_a_handler.py
|    |    |__requirements.txt
|    |__function_b
|         |__function_b_handler.py
|         |__requirements.txt
|__template.yml
```

And the `template.yml` file is:
```yaml
Transform: AWS::Serverless-2016-10-31
Globals:
  Function:
    Timeout: 180
    Runtime: python3.8
    
Resources:
  SharedLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      CompatibleRuntimes:
        - python3.8
      ContentUri: src/shared
      Description: Provides the base backend shared library and dependencies
      LayerName: shared-layer
      
  FunctionA:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/function_a
      FunctionName: function-a
      Handler: function_a_handler.handler
      Layers:
        - !Ref SharedLayer

  FunctionB:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/function_b
      FunctionName: function_b
      Handler: function_b_handler.handler
      Layers:
        - !Ref SharedLayer
      Events:
        Api:
          Type: Api
          Properties:
            Path: /function-a
            Method: post
```

I placed everything into one template file so that local development can be done without having to have functions and layers deployed and would like to keep everything local.

To start I ran 
```sam local start-lambda```
to bring up the invoke endpoint. No problem there. 
I next do 
```sam local invoke -d 3001 FunctionA -e <path_to_event>.json```
to invoke the function with the reference to the shared layer. I get the following output

```
Invoking function_a.handler(python3.8)
SharedLayer is a local Layer in the template
Building image.............
Skip pulling image and use local one: samcli/lambda:python3.8-ea35a2dafa693f01cf9de8ed7.

Mounting /mnt/e/project/src/function_a as /var/task:ro,delegated inside runtime container
START RequestId: fa8d378b-5bcf-1909-91a8-3012924872bf Version: $LATEST
[ERROR] Runtime.ImportModuleError: Unable to import module 'function_a_handler': No module named 'shared'
END RequestId: fa8d378b-5bcf-1909-91a8-3012924872bf
REPORT RequestId: fa8d378b-5bcf-1909-91a8-3012924872bf  Init Duration: 132.24 ms                                                                                          Duration: 2.67 ms        Billed Duration: 100 ms Memory Size: 128 MB     Max Memory Used: 29 MB

{"errorType":"Runtime.ImportModuleError","errorMessage":"Unable to import module 'function_a_handler': No module named 'shared'"}
```

the `function_a_handler.py` is
```python

import shared.common as common

def function_a_handler(event, context):
  common.function()
  return "success"
```

System Info:
`Ubuntu 20.04`
`aws-sam-cli 1.6.2`
`python 3.8`

I'm not sure where the problem is: if its my template, project structure, sam, or just don't get the concept for local invokes.

Any help or advice is appreciated.

**Comment by mndeveci** [comment]
Hi @DallasP9124 ,

I was able to run `sam local invoke` for a lambda which uses a layer with following project structure;

`template.yaml`
```
Resources:
  SharedLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      CompatibleRuntimes:
        - python3.8
      ContentUri: src/shared
      Description: Provides the base backend shared library and dependencies
      LayerName: shared-layer

  HelloWorldFunction:
    Type: AWS::Serverless::Function 
    Properties:
      CodeUri: src/hello_world
      Handler: app.lambda_handler
      Layers:
        - !Ref SharedLayer
```

`src/hello_world/app.py`
```
import json
import common as common

def lambda_handler(event, context):
    print(sys.path)
    return {
        "statusCode": 200,
        "body": json.dumps({
            "message": "hello world",
            "sum": common.sum(5, 3)
        }),
    }
```

`shared/python/common.py`
```
def sum(a, b):
    return a + b
```

For the layers, lambda exports layer into `/opt` folder and in the `PATH` environment variable there is one folder with `/opt/python` location. Moving layer contents into a `python` folder should work for your case.

Please let us know if you have other issues

Thanks!
