### ISSUE TITLE
Command start-api does not update environment variable changes in template.yaml

### ISSUE THREAD

**Issue by byrro** [aws/aws-sam-cli#2341]
### Description

Hot reloading in `start-api` does not update environment variables when they are changed in `template.yaml` **after** the API has been started. Requires restarting the API for the changes to reflect in Function's environment variables.

### Steps to reproduce

1. Create a template with a function resource, an API event source, and set an environment variable:

```yaml
Resources:
  DummyFunction:
    Type: AWS::Serverless::Function
    Properties:
      ...
      Environment:
        Variables:
          DUMMY: "ABC"
      Events:
        DummyAPI:
          Type: Api
          Properties:
            Path: /dummy
            Method: get
```

2. In the function code, get the `DUMMY` environment variable and print to stdout or include in the Lambda response body.
3. Run a local API Gateway `sam local start-api` and trigger the API endpoint locally: http://localhost:3000/dummy
4. Verify that the `DUMMY` is set and has the expected value `ABC`.
5. Now change `DUMMY` value to "XYZ", run `sam build` and trigger the API again in the browser.

### Observed result

The environment variable changes are **NOT** reflected in the local API.

The API needs to be terminated and started again for the changes to reflect.

### Expected result

Environment variables are updated using the [hot reloading](https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/serverless-sam-cli-using-start-api.html) feature, without having to restart the API.

### Additional environment details (Ex: Windows, Mac, Amazon Linux etc)

1. OS: Ubuntu 18.04.2 LTS (running in WSL2 on a Windows 10.0.19041 machine)
2. `sam --version`: 1.6.2
