### ISSUE TITLE
Integrate sam with Bitbucket Pipeline

### ISSUE THREAD

**Issue by picolloo** [aws/aws-sam-cli#2342]
Hi there, I'm learning how to use SAM to build an application that consists basically in:

* AWS Lambda - python 3.8
* SQS 
* SQS DeadLetter

My _template.yml_ looks like this: 

```yml
AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: Kabuto Function for handling Linkedin interactions.

Parameters:
  EnvironmentParameter:
    Type: String
    Default: production
    AllowedValues:
      - production
      - staging
    Description: Environment of the application execution
  MarketplaceRdsHost:
    Type: String
  MarketplaceDbName:
    Type: String
  MarketplaceDbUser:
    Type: String
  MarketplaceDbPwd:
    Type: String

Resources:
  GeekhunterKabuto:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub kabuto-sqs-queue-process-${EnvironmentParameter}
      CodeUri: geekhunter-kabuto/
      Handler: lambda.lambda_handler
      Runtime: python3.8
      Timeout: 50
      Environment:
        Variables:
          MARKETPLACE_RDS_HOST: !Sub ${MarketplaceRdsHost}
          MARKETPLACE_DB_NAME: !Sub ${MarketplaceDbName}
          MARKETPLACE_DB_USER: !Sub ${MarketplaceDbUser}
          MARKETPLACE_DB_PWD: !Sub ${MarketplaceDbPwd}
      Events:
        KabutoQueue:
          Type: SQS
          Properties:
            Queue: !GetAtt KabutoQueue.Arn
            BatchSize: 10
  KabutoQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: !Sub kabuto-queue-${EnvironmentParameter}
      FifoQueue: True
      VisibilityTimeout: 55
      RedrivePolicy:
        DeadLetterTargetArn: !GetAtt KabutoDeadLetterQueue.Arn
        MaxReceiveCount: 1
  KabutoDeadLetterQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: !Sub dead-letter-kabuto-queue-${EnvironmentParameter}
      FifoQueue: True
```

When I deploy it locally everything works just fine, but when it comes to the pipeline I have some serious problems that make the CI/CD unviable.
I've found this [Bitbucket Pipeline step](https://bitbucket.org/atlassian/aws-sam-deploy) that makes the deployment from the CI really easy, but it **does not have the building step**. So when the pipeline runs, my code is deployed to AWS but without its dependencies.

My _bitbucket-pipeline.yml_ looks like this:

```yml
image: python:3.8

definitions:
  steps:
    - step: &build-lambda
        name: "Create/update lambda"
        script:
          - pipe: atlassian/aws-sam-deploy:0.5.2
            variables: &base-script-variables
              CAPABILITIES: ["CAPABILITY_IAM", "CAPABILITY_AUTO_EXPAND"]
              S3_BUCKET: geekhunter-sam
              STACK_PARAMETERS: >
                [{
                  "ParameterKey": "MarketplaceRdsHost",
                  "ParameterValue": $MARKETPLACE_RDS_HOST
                },
                {
                  "ParameterKey": "MarketplaceDbName",
                  "ParameterValue": $MARKETPLACE_DB_NAME
                },
                {
                  "ParameterKey": "MarketplaceDbUser",
                  "ParameterValue": $MARKETPLACE_DB_USER
                },
                {
                  "ParameterKey": "MarketplaceDbPwd",
                  "ParameterValue": $MARKETPLACE_DB_PWD
                }]

pipelines:
  branches:
    staging:
      - step:
          <<: *build-lambda
          deployment: staging
          script:
            - pipe: atlassian/aws-sam-deploy:0.5.2
              variables:
                <<: *base-script-variables
                STACK_NAME: geekhunter-kabuto-staging
    master:
      - step:
          <<: *build-lambda
          deployment: production
          script:
            - pipe: atlassian/aws-sam-deploy:0.5.2
              variables:
                <<: *base-script-variables
                STACK_NAME: geekhunter-kabuto-production
```

I really don't know what to do in this case, should I build it manually? If so, how can I pass the _.aws-sam_ directory to the deployment step?

Hope somebody can help me, currently I'm deploying from my local machine but it just does not scale.

**Comment by loscil06** [comment]
Hi! My company uses Bitbucket and AWS SAM CLI for deployment, here's a sample that might help you:
```yaml
image: python:3.8

pipelines:
  branches:
    master:
      - step:
          name: Project deployment
          caches:
            - pip
          script:
            - pip install awscli
            - pip install aws-sam-cli
            - aws configure --profile deployment set aws_access_key_id ${AWS_ACCESS_KEY_ID}
            - aws configure --profile deployment set aws_secret_access_key ${AWS_SECRET_ACCESS_KEY}
            - sam build --profile deployment --region ${AWS_DEFAULT_REGION} --build-dir .aws-sam/build
            - sam package --profile deployment --region ${AWS_DEFAULT_REGION} --template-file .aws-sam/build/template.yaml --output-template-file package.yaml --s3-bucket yourcompany-west
            - sam deploy --template-file package.yaml --stack-name project_name --capabilities CAPABILITY_IAM --parameter-overrides 'ParameterKey=ExampleValueEndpoint,ParameterValue="https://example.org/" ParameterKey=ExampleSecretToken,ParameterValue="Bearer xxxxx.xxxx.xxx" ParameterKey=AnotherExampleEndpoint,ParameterValue="https://example.org/2/" ParameterKey=AnotherSecretExampleToken,ParameterValue="Bearer xxxx.yyyy.zzzz"'
      - step:
          name: Notification
          image: alpine:3
          script:
            - apk add curl
            - sed -i 's@BB_PN@'"$BITBUCKET_REPO_FULL_NAME"'@' ./config/slack_message.json
            - sed -i 's@BB_BUILD@'"$BITBUCKET_BUILD_NUMBER"'@' ./config/slack_message.json
            - sed -i 's@BB_BRANCH@'"$BITBUCKET_BRANCH"'@' ./config/slack_message.json
            - sed -i 's@BB_COMMIT@'"$BITBUCKET_COMMIT"'@' ./config/slack_message.json
            - curl -s -X POST -d @config/slack_message.json -H "Content-Type:application/json" ${SLACK_WEBHOOK}

```
