### ISSUE TITLE
VpcEndpointIds getting removed from private APIs post stack update. Stack shows drifted.

### ISSUE THREAD

**Issue by saurabhshri** [aws/aws-sam-cli#2353]
### Description:

I have a private API that is being provisioned using SAM. Here's how it looks 

```
PrivateApiResource:
    Type: AWS::Serverless::Api
    Tags:
      Application: !Ref Application
    Properties:
      Name: !Sub ${Env}-${Application}-PrivateApiResource
      StageName: prod
      EndpointConfiguration:
        Type: PRIVATE
        VPCEndpointIds:
          - !FindInMap [ EnvConfig, !Ref Env, VPCEndpointAPI ]
      Auth:
        ResourcePolicy:
          CustomStatements:
            - Effect: Allow
              Principal: '*'
              Action: execute-api:Invoke
              Resource: "arn:aws:execute-api:${AWS::Region}:${AWS::AccountId}:*/*/*/*"
            - Effect: Deny
              Principal: '*'
              Action: execute-api:Invoke
              Resource: "arn:aws:execute-api:${AWS::Region}:${AWS::AccountId}:*/*/*/*"
              Condition:
                StringNotEquals:
                  aws:SourceVpce: !FindInMap [ EnvConfig, !Ref Env, VPCEndpointAPI ]
```

I have a lambda that has the above API as event resource : 

```
SayHelloPrivately:
    Type: AWS::Serverless::Function
    Properties:
      Handler: ./target/index.sayHelloPrivatelyHandler
      Runtime: nodejs12.x
      CodeUri:
        Bucket: !Ref Bucket
        Key: !Sub ${Application}/latest-lambda.zip
      Events:
        SayHelloApi:
          Type: Api
          Properties:
            Path: /hello
            Method: GET
            RestApiId: !Ref PrivateApiResource
```

This worked and I was able to access /hello endpoint when on VPC and it times out when not in VPC.

Now anytime stack updates and there's a related update to the API resource, like adding a new lambda with different endpoint, the VPCEndpointIds and Tags seems to be getting removed randomly. I am not exactly sure what exact event triggers it. But most recently, doing as little adding a third lambda lead to removal of both tags and VPCe.

CloudFormation stack's template tab shows that the template still has VPCe. Stack shows it's drifted and both are removed. 

- template, as it appears in CloudFormation stack tab

<img width="584" alt="Screenshot 2020-11-05 at 12 28 52 PM" src="https://user-images.githubusercontent.com/12415700/98208380-310b9c80-1f63-11eb-8d0e-a177d5363a90.png">

- Stack drift : 

<img width="1323" alt="Screenshot 2020-11-05 at 12 30 07 PM" src="https://user-images.githubusercontent.com/12415700/98208428-454f9980-1f63-11eb-8706-a8a2fe4bbec1.png">

- VPCe removed 

<img width="1265" alt="Screenshot 2020-11-05 at 12 28 18 PM" src="https://user-images.githubusercontent.com/12415700/98208478-5d271d80-1f63-11eb-8519-2fd0c2ac12a0.png">

Nothing related to VPCEndpointIds/Tags were done. Even the API resource was untouched in stack update. Only a new lambda was created which added a new endpoint to the API resource, similar to how it's done in `SayHelloPrivately` above.

### Steps to reproduce:

Follow the steps in description.

### Observed result:

VPCEndpointIds from private API and tags are removed. Stack shows drifted.

### Expected result:

Nothing should have changed with this aspect. 

**NOTE** :  This has happened more than once.

### Additional environment details (Ex: Windows, Mac, Amazon Linux etc)

1. OS: Amazon Linux 2
2. `sam --version`: 1.1.0

Almost forgot to tag @awsjeffg ! Let me know if I can provide any other information. Thanks!
