### ISSUE TITLE
TOML Alternative

### ISSUE THREAD

**Issue by mousedownmike** [aws/aws-sam-cli#2379]
I was initially going to place this as a comment on #2253 but I fear it might sidetrack efforts there so I'm opening a separate ticket.

The issue in #2253 highlights a point of friction I found while trying to learn SAM.  The use of TOML for the samconfig file seems unique and arbitrary in the scope of AWS utilities that I've worked with.  With the exception of credential files which seem to be TOML-like, I'm not familiar with any other AWS tools that use TOML to the extent that SAM does.  In an environment where JSON and YAML are abundant, is it necessary to introduce an additional (and somewhat incompatible) file format?  As someone new to SAM, here are my initial observations:

- The required conversion of hyphens to underscores seems onerous, under-documented and unnecessary.
- Having configuration data on the CLI, in JSON, YAML and TOML that are all **VERY** similar looking (parameter_-overrides being a prime example) yet incompatible among formats (i.e. I can't copy and paste) introduces error-prone and time-consuming processes depending on the tasks being worked on.
- Simple things like maps and lists are made complex and difficult to read in TOML.
- To the extent TOML is being used in SAM, it isn't clear what benefits it offers over normal JSON and YAML syntax.  

Is this a technical decision that is open to review in future CLI revisions?  Is it possible to support JSON syntax as an alternative?

I'm enjoying the benefits that I'm getting from adopting SAM in my project but I'm concerned that the developer friction will slow/stall adoption.  The YAML heavy format of CloudFormation is already a high hurdle, adding TOML to that seems to introduce more difficulties than it solves.

**Comment by zadowsmash** [comment]
+1 to this.
It would be great to see JSON and YAML support for config files

**Comment by ClubSeal** [comment]
+1

Agree with everything mousedownmike mentioned, and have had many of the same experiences myself.

**Comment by tf-chris-cottingham** [comment]
+1

**Comment by Rabadash8820** [comment]
I'll also add that TOML, being more of a niche config language, has somewhat worse tooling around it. JSON and YAML have great extensions for syntax highlighting, intellisense, validation, etc. in editors like VS Code. TOML less so.

**Comment by c2tarun** [comment]
Thanks for raising this feature request. We prioritize features based on 👍's on a request. If this feature impacts you please 👍 the issue instead of adding comment.

Thanks.

**Comment by solarmosaic-kflorence** [comment]
The way the TOML configuration works right now makes it practically unusable unless every configuration value you have is static.

**Comment by alessandrobologna** [comment]
I completely agree and I can't understand a rationale for using TOML instead of yaml (or even JSON). For fun, this is how the example at https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/serverless-sam-cli-config.html would look like in YAML:
```
default:
   global:
     parameters:
       stack_name: common-stack
 
   deploy:
     parameters:
       stack_name: my-app-stack
       s3_bucket: my-source-bucket 
       s3_prefix: my-s3-prefix
       image_repositories: 
         my-function-1: image-repo-1
         my-function-2: image-repo-2
       region: us-west-2
       confirm_changeset: true
       capabilities: CAPABILITY_IAM
       tags:
         project: my-application
         stage: production

    build:
      parameters:
        container_env_var: 
           Function1.GITHUB_TOKEN: TOKEN1
           Function2.GITHUB_TOKEN: TOKEN2
      container_env_var_file: env.json
      no_beta_features: true
  ``` 
 For someone who working with SAM has to use yaml every day, why adding a completely different syntax with a niche config language?
