### ISSUE TITLE
Allow samconfig properties like `stack_name` to apply to all commands

### ISSUE THREAD

**Issue by mhart** [aws/aws-sam-cli#2382]
### Description:

EDIT: I had previously misunderstood how samconfig.toml works. I thought by providing the stack name in `sam deploy --guided`, it should use that stack name for all commands (like `sam logs`). Turns out that only applies to the `sam deploy` command specifically.

You currently have to specify `stack_name=mystack` for each command you want it to apply to – it would be nice if there would be a way for it to apply to all commands.

I also think that `sam deploy --guided` should apply settings like stack, region, etc to all commands that need them (unless they've already been set)

### Additional environment details (Ex: Windows, Mac, Amazon Linux etc)

1. OS: macOS
2. `sam --version`: 1.10.0

**Comment by awood45** [comment]
This actually works for me, can you share your samconfig.toml file, specifically the section you have for the “logs” command?

**Comment by mhart** [comment]
What do you mean the section I have for the "logs" command?

**Comment by mhart** [comment]
I did a `sam deploy --guided` to create the `samconfig.toml`, it looks like this:

```
version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "mystack"
s3_bucket = "mybucket"
s3_prefix = "mystack"
region = "us-east-1"
capabilities = "CAPABILITY_IAM"
```

**Comment by awood45** [comment]
This is definitely something we can document in more detail - the samconfig.toml file acts as “default arguments” per method. For a farther afield example, you can create a “build” command section to turn on “use_container” for all builds.

For stack_name to be picked up for logs, you’d want to add a “logs” section to your samconfig.toml file and try again. This currently requires a manual edit.

**Comment by awood45** [comment]
I’ll post my samconfig in a moment when I get to my laptop. The key is that this will only provide parameters for the “deploy” command.

**Comment by mhart** [comment]
Ah. Will `stack_name` apply to all commands if I put it under `[default]`? Duplicating it for each command that needs it seems wasteful.

I can update the issue title if that's not currently possible

**Comment by awood45** [comment]
I can test in a bit, but I believe at best you'd run into an issue where now every command will expect that parameter to exist and will fail if it does not, which would be a problem for build, etc.

I do think that making that a bit smarter to allow for a cross-command default is a good feature request.

**Comment by mhart** [comment]
Updated title and description to make it a feature request 👍

**Comment by awood45** [comment]
Just to close the loop for anybody reading, this is an example of how, today, you might handle multiple commands in one config file:

```toml
version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "my-stack"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-123456789"
s3_prefix = "my-stack"
region = "us-east-2"
capabilities = "CAPABILITY_IAM"

[default.build]
[default.build.parameters]
use_container = true

[default.logs]
[default.logs.parameters]
region = "us-east-2"
stack_name = "my-stack"
```

**Comment by gnomeria** [comment]
This actually just resolves my issue because I tried to use the `[default]` as an environment config like this:
```toml
[development]
[development.deploy]
[development.deploy.parameters]
```
This caused the sam deploy always asking the same parameters to be set

**Comment by ConnorKirk** [comment]
I would also find this useful. Currently I have many repeated keys across different tables. Being able to declare global keys (or keys scoped to all commands for a particular environment) would make the `samconfig.toml` more readable.

i.e. something like this
```toml
version = 0.1

[global]
# global keys

[dev]
region="us-east-1"

[dev.package.parameters]
s3_bucket = "bucket name"

[dev.deploy.parameters]
# more stuff here


```
