### ISSUE TITLE
Support different build configuration for different resources

### ISSUE THREAD

**Issue by solarmosaic-kflorence** [aws/aws-sam-cli#2397]
### Describe your idea/feature/enhancement

I have a build that uses a python lambda function which depends on a local lambda layer. The python lambda function requires `--use-container` to build properly, but the lambda layer fails to build properly inside the container (it uses `docker run` to install linux binaries with `yum`). Ideally, I could configure `sam build` in such a way that it could build the lambda layer first outside of the container, and then build the lambda function. Unfortunately, I can't do this with multiple `sam build` calls either, because each call deletes the contents of the build folder.

### Proposal

Either allow build-specific configuration for each resource which can be built with `sam build` (for example, by introducing a section for the resource name into the TOML), or allow a build to happen in multiple steps (e.g. `sam build [layer_name] && sam build [function_name] --use-container`).

### Additional Details

The `template.yaml` looks like:

```yaml
AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: description
Resources:
  MyLayer:
    Type: AWS::Serverless::LayerVersion
    Metadata:
      BuildMethod: makefile
    Properties:
      CompatibleRuntimes:
        - provided
      ContentUri: layer/
      Description: my layer
  MyFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/
      FunctionName: MyFunction
      Handler: app.lambda_handler
      Layers:
        - Ref: MyLayer
      Runtime: python3.8
```

The lambda function code is in `/src` and the `/layer` directory contains only a `Makefile`.
