### ISSUE TITLE
AWS::ServerLess::HttpApi "Auth" property does not create authorizer

### ISSUE THREAD

**Issue by baxterjo** [aws/aws-sam-cli#2410]
I am attempting to secure my serverless application using AWS Cognito as a JWT issuer. When I use the built in `Auth` property as shown below, no authorizer resource is made.
```yaml
HttpApi:
    Type: AWS::Serverless::HttpApi
    Properties:
      Auth:
        Authorizers:
          CognitoAuthorizer:
            IdentitySource: "$request.header.Authorization"
            JwtConfiguration:
              Audience:
                - !Ref UserPoolClient
              Issuer: !GetAtt CognitoUserPool.ProviderURL
        DefaultAuthorizer: CognitoAuthorizer
``` 
When this builds and deploys using AWS SAM after changing any of the settings, there are no logs to communicate that the gateway is being changed, and the authorizer does not appear in the list of authorizers attached to the API in the AWS console. I instead have to manually create the authorizer using the underlying resource of the `Serverless::HttpApi`, the `AWS::ApiGatewayV2::Authorizer` as shown below:
```yaml
HttpApi:
    Type: AWS::Serverless::HttpApi
      DefaultRouteSettings:
        ThrottlingBurstLimit: 200
      StageName: 
        !If 
          - ProdEnvironment
          - prod
          - !If
            - StageEnvironment
            - stage
            - dev

  CognitoAuthorizer:
    Type: AWS::ApiGatewayV2::Authorizer
    Properties: 
      ApiId: !Ref HttpApi
      AuthorizerType: JWT
      IdentitySource: 
        - "$request.header.Authorization"
      JwtConfiguration: 
        Audience: 
        - !Ref UserPoolClient
        Issuer: !GetAtt CognitoUserPool.ProviderURL
      Name: CognitoAuthorizer
```
This successfully creates the authorizer under the API. I have not attempted to attach this to any routes, but this in itself is an issue that should prompt an investigation into the authorizer deployment process in SAM.

**Comment by baxterjo** [comment]
# Problem Update
After reading [this issue](https://github.com/aws/serverless-application-model/issues/155) and setting the `FailOnWarnings` property in the `AWS::Serverless::HttpApi` resource to `true` I got some debugging info. It seems like the URL that is passed to the `Issuer` property of the `JwtConfiguration` of the authorizer does not make it to the underlying `AWS::ApiGatewayV2::Authorizer` resource when it is being created. 

Here is the resource deployment:
```yaml
HttpApi:
    Type: AWS::Serverless::HttpApi
    Properties:
      Auth:
        Authorizers:
          CognitoAuthorizer:
            IdentitySource: "$request.header.Authorization"
            JwtConfiguration:
              Audience:
                - !Ref UserPoolClient
              Issuer: !GetAtt CognitoUserPool.ProviderURL
        DefaultAuthorizer: CognitoAuthorizer
      FailOnWarnings: true
```
And this is the response I receive:
```
Warnings found during import: Unable to create Authorizer 'CognitoAuthorizer': Invalid issuer: Issuer can not be empty for JWT 
Authorizer.. Ignoring. Unable to put method 'POST' on resource at path '/authtest': Invalid authorizer definition. Setting the 
authorization type to JWT requires a valid authorizer. Ignoring. Unable to put method 'POST' on resource at path '/subscription': 
Invalid authorizer definition. Setting the authorization type to JWT requires a valid authorizer. Ignoring. (Service: 
AmazonApiGatewayV2; Status Code: 400; Error Code: BadRequestException; Request ID: cb6e1ba2-791c-4327-9c56-
c7efe29e8abd; Proxy: null) (Service: null; Status Code: 404; Error Code: BadRequestException; Request ID: null; Proxy: null)
```
At first I thought this was a problem with the CloudFormation `!GetAtt` intrinsic function, so I made that function an output of the template and pasted it in the `Issuer` property. But I get the same response.

# Temporary Workaround 
The good news is that I was able to get the authorizers attached to my routes by tricking SAM into creating the Authorizer resource in one deployment, and attaching the routes in a second.

In the first deployment, you will have to set up the authorizer as follows:
```yaml
HttpApi:
    Type: AWS::Serverless::HttpApi
    Properties:
      Auth:
        Authorizers:
          CognitoAuthorizer:
            IdentitySource: "$request.header.Authorization"
            JwtConfiguration:
              Audience:
                - !Ref UserPoolClient
              Issuer: !GetAtt CognitoUserPool.ProviderURL
        DefaultAuthorizer: CognitoAuthorizer
      # FailOnWarnings: true

  CognitoAuthorizer:
    Type: AWS::ApiGatewayV2::Authorizer
    Properties:
      ApiId: !Ref HttpApi
      AuthorizerType: JWT
      IdentitySource:
        - "$request.header.Authorization"
      JwtConfiguration:
        Audience:
          - !Ref UserPoolClient
        Issuer: !GetAtt CognitoUserPool.ProviderURL
      Name: CognitoAuthorizer
AuthTest:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./src/auth_test_pkg
      Handler: auth_test_lambda.lambda_handler
      Runtime: python3.8
      Timeout: 30
      MemorySize: 128
      Events:
        ReceiverAPI:
          Type: HttpApi
          Properties:
            ApiId: !Ref HttpApi
            Method: POST
            Path: /authtest
            TimeoutInMillis: 30000
            PayloadFormatVersion: "2.0"
           # Auth:
           #   Authorizer: CognitoAuthorizer
```

Notice that all of the settings and names of the authorizers are **exactly the same** the Authorizer defined in the `AWS::Serverless::HttpApi` resource is merely symbolic, this ensures that SAM is able to use these names/resources to set up routes in the second deployment. The authorizer set up in `AWS::ApiGatewayV2::Authorizer` resource is where it is actually deployed in AWS.

On the second deployment, uncomment all lines that are currently commented in the first deployment. This will establish the routes to the lambda functions and ensure they are authorized.

**Comment by baxterjo** [comment]
# Problem Update 2 (Solved, needs documentation update)

This problem was solved by using [this example](https://github.com/aws-samples/sessions-with-aws-sam/blob/master/http-api/template.yaml) and deploying the cognito user pool and user pool client as a separate stack with the following resources and outputs:

```yaml
Resources:
  #######################################################################
  ##                    AUTH FLOW SETUP
  #######################################################################
  CognitoUserPool:
    Type: AWS::Cognito::UserPool
    Properties:
      AccountRecoverySetting:
        RecoveryMechanisms:
          - Name: verified_email
            Priority: 1
      AdminCreateUserConfig:
        AllowAdminCreateUserOnly: true
      AutoVerifiedAttributes:
        - email
      UsernameAttributes:
        - email
      UserPoolName: "CognitoUserPool"

  UserPoolClient:
    Type: AWS::Cognito::UserPoolClient
    Properties:
      AccessTokenValidity: 24
      ExplicitAuthFlows:
        - ALLOW_USER_PASSWORD_AUTH
        - ALLOW_REFRESH_TOKEN_AUTH
      ClientName: "CognitoUserPoolClient"
      GenerateSecret: false
      UserPoolId: !Ref CognitoUserPool
      IdTokenValidity: 24
      SupportedIdentityProviders:
        - COGNITO

Outputs:
  CognitoPoolClientID:
    Description: Client ID used to build the issuer url.
    Value: !Ref UserPoolClient
    Export:
      Name: CognitoPoolClientID
  CognitoPoolID:
    Description: User pool ID used to get the bearer token.
    Value: !Ref CognitoUserPool
    Export:
      Name: CognitoPoolID
```
And then referencing the cognito pool and client in the http api gateway like so:
```yaml
HttpApi:
    Type: AWS::Serverless::HttpApi
    Properties:
      Auth:
        Authorizers:
          GeneralAuth:
            IdentitySource: "$request.header.Authorization"
            JwtConfiguration:
              issuer:
                !Join [
                  "",
                  [
                    https://cognito-idp.us-west-2.amazonaws.com/,
                    !ImportValue CognitoPoolID,
                  ],
                ]
              audience:
                - !ImportValue CognitoPoolClientID
      DefaultRouteSettings:
        ThrottlingBurstLimit: 200
```
The only difference in string input to the API gateway is that instead of using the `!GetAtt CognitoUserPool.ProviderURL` I am manually building the url using the `!Join` function and the `!Ref CognitoUserPool` (through an export/import between stacks).

# Recommended Fix
- Add an example output string for the !GettAtt <AWS::Cognito::UserPool>.ProviderURL to highlight the difference between this string and the string that is built up in the above example.
- Add an example to the `AWS::Serverless::HttpApi` for deploying the api with a cognito authorizer. Like below or a paired down version of below.
```yaml
CognitoUserPool:
  Type: AWS::Cognito::UserPool
  Properties:
    AccountRecoverySetting:
      RecoveryMechanisms:
        - Name: verified_email
          Priority: 1
    AdminCreateUserConfig:
      AllowAdminCreateUserOnly: true
    AutoVerifiedAttributes:
      - email
    UsernameAttributes:
      - email
    UserPoolName: "CognitoUserPool"

UserPoolClient:
  Type: AWS::Cognito::UserPoolClient
  Properties:
    AccessTokenValidity: 24
    ExplicitAuthFlows:
      - ALLOW_USER_PASSWORD_AUTH
      - ALLOW_REFRESH_TOKEN_AUTH
    ClientName: "CognitoUserPoolClient"
    GenerateSecret: false
    UserPoolId: !Ref CognitoUserPool
    IdTokenValidity: 24
    SupportedIdentityProviders:
      - COGNITO
 
HttpApi:
    Type: AWS::Serverless::HttpApi
    Properties:
      Auth:
        Authorizers:
          GeneralAuth:
            IdentitySource: "$request.header.Authorization"
            JwtConfiguration:
              issuer:
                !Join [
                  "",
                  [
                    https://cognito-idp.us-west-2.amazonaws.com/,
                    !Ref CognitoUserPool,
                  ],
                ]
              audience:
                - !Ref UserPoolClient
```
