### ISSUE TITLE
Layers with python build (3.7) cannot be imported

### ISSUE THREAD

**Issue by ivandjuricic** [aws/aws-sam-cli#2443]
### Description:
Not necessarily a bug, but I would like some clarifications here. 
When specified python3.7 Layer as code with Pyhton3.7 BuildMethod for lambda in CF template, it cannot be imported in the lambda. 
I would expect to code inside `python` folder under specified `ContentUri` to be available on path just like zipping the folder and upload it manually works. 

### Steps to reproduce:
Given this project structure:

```
├── __init__.py
├── dependencies
│   ├── python
│   │   └── printer.py
│   └── requirements.txt
├── hello_world
│   ├── __init__.py
│   ├── app.py
│   └── requirements.txt
└── template.yaml
```

Where `template.yaml` is defined with:
```
AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: "My Description"

Globals:
  Function:
    Timeout: 3

Resources:
  HelloWorldFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: hello_world/
      Handler: app.lambda_handler
      Runtime: python3.7
      Layers:
        - !Ref MyLayer
      Events:
        HelloWorld:
          Type: Api
          Properties:
            Path: /hello
            Method: get

  MyLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      LayerName: MyLayer
      Description: Dependencies for sam app [sam-with-layers]
      ContentUri: dependencies/
      CompatibleRuntimes:
        - python3.7
    Metadata:
      BuildMethod: python3.7

Outputs:
  HelloWorldApi:
    Description: "API Gateway endpoint URL for Prod stage for Hello World function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/hello/"
  HelloWorldFunction:
    Description: "Hello World Lambda Function ARN"
    Value: !GetAtt HelloWorldFunction.Arn
  HelloWorldFunctionIamRole:
    Description: "Implicit IAM Role created for Hello World function"
    Value: !GetAtt HelloWorldFunctionRole.Arn
```

`hello_world/app.py`:
```
import json
import printer


def lambda_handler(event, context):
    printer.print_hello()

    return {
        "statusCode": 200,
        "body": json.dumps({
            "message": "hello world"
        }),
    }
```

and `dependecies/python/printer.py`
```
def print_hello():
    print("hello")
```

Build the app inside container:
`sam build --use-container`

And deploy:
`sam deploy --guided`  (--guided flag used only the first time)

Build shoud pass

### Observed result:
When invoked the function I get observed in CloudWatch logs: 
```
[ERROR] Runtime.ImportModuleError: Unable to import module 'app': No module named 'printer'
```
And the APIGateway because of it returns 502 error. 

This points to that there is no `printer.py` module available on path. 

If I, on the other hand, zip the python directory, create a layer version myself in the console and add it to lambda, the module is resolved without issues.

I've read that modules would be put into `/opt` or `/opt/python` so I tried `sys.path.append` before importing but the results are the same. 

### Expected result:
Get 200 response from lambda or get clarification on steps that I'm missing. If there's some manual things to be done, then the question is asked what does this python build method actually does.

### Additional environment details (Ex: Windows, Mac, Amazon Linux etc)

1. OS: MacOS Catalina 10.15.7
2. `sam --version`: SAM CLI, version 1.3.2

`Add --debug flag to command you are running`
