### ISSUE TITLE
Sam Package/Deploy --image-repository Behavior

### ISSUE THREAD

**Issue by metaskills** [aws/aws-sam-cli#2447]
Many of the process I put in place for both open source and in company deploy pipelines take advantage of SAM CLI and the AWS CLI using conventions like AWS_PROFILE. I've been very happy that SAM CLI has followed these patterns. Today when working with the new container features I was surprised by this odd behavior of [sam package](https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/sam-cli-command-reference-sam-package.html) when using the `--image-repository` option. Here is an example of my usage where the new image repo was added to my process.

```shell
sam package \
  --region ${AWS_DEFAULT_REGION} \
  --template-file ./.aws-sam/build/template.yaml \
  --output-template-file ./.aws-sam/build/packaged.yaml \
  --image-repository  "lambyc-starter" \
  --s3-bucket "${CLOUDFORMATION_BUCKET}" \
  --s3-prefix "lambyc-starter-${RAILS_ENV}"
```

These commands are run as either the default AWS_PROFILE or with specific ENV overrides. Given this was set and that the `--region` was set here, my expectation was this command was going to find and publish to the ECR repo within my AWS account. Instead, it tried to push to docker.io and failed with a user password. Digging into some guides and published SAM examples I can see what you expect folks to do is:

```shell
sam package \
  --region ${AWS_DEFAULT_REGION} \
  --template-file ./.aws-sam/build/template.yaml \
  --output-template-file ./.aws-sam/build/packaged.yaml \
  --image-repository  "123456789.dkr.ecr.us-east-1.amazonaws.com/lambyc-starter" \
  --s3-bucket "${CLOUDFORMATION_BUCKET}" \
  --s3-prefix "lambyc-starter-${RAILS_ENV}"
```

This feels like the wrong interface to me and against the grain of how the CLI operates given all my previous experiences. I can work around this if y'all disagree by adding more `aws` CLI commands to find the account ID and use the `AWS_DEFAULT_REGION` env and/or look that up as well. But it would cool if SAM did this. Thoughts?

**Comment by sriram-mv** [comment]
Thanks for reporting this!

For the issue it trying to upload to dockerhub: there is a fix out for that: https://github.com/aws/aws-sam-cli/pull/2439

One of the things that makes it harder to figure out the full URI with just a name is to construct the neccessary accountid, the way to do that would sts get-caller-identity (or what if you wanted to do cross account), which is additional permissions for users.

We are definitely exploring ways of making this better and a simpler experience! what did you have in mind?

**Comment by metaskills** [comment]
Thanks! For now I am doing this in my scripts wrapping sam package and deploy.

```
AWS_ACCOUNT_ID=$(aws sts get-caller-identity --query Account --output text)
IMAGE_REPOSITORY="${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_DEFAULT_REGION}.amazonaws.com/myapp"
```

**Comment by stephenbawks** [comment]
The thing I was going to add here since I am little confused on the workflow.  I was hoping to just create an ECR repository along with my Lambda but I do not see a way I can create that before it tries to upload the container when I do a build.  So I guess I am just wondering with the way this works, do I need to have ECR created beforehand?

**Comment by sriram-mv** [comment]
@stephenbawks yes you need to have created, we are definitely looking at ways of making this better, what did you have in mind? ECR repos per function? or one ECR repo for your entire stack?

**Comment by metaskills** [comment]
Right, a find/create on the ECR repository would be kind of helpful too.

**Comment by stephenbawks** [comment]
> @stephenbawks yes you need to have it created. we are definitely looking at ways of making this better, what did you have in mind? ECR repos per function? or one ECR repo for your entire stack?
@sriram-mv  We typically do a repo per app.  Or in this case I guess I would use Stack or Function interchangeably.

**Comment by BR0kEN-** [comment]
Right now I found only this workflow operable:

```bash
aws ecr create-repository --repository-name my/repo || true
docker build
docker login
docker push
# For a function defined as a container image, Lambda
# resolves the image tag to an image digest. In Amazon
# ECR, if you update the image tag to a new image, Lambda
# does not automatically update the function.
# See https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/lambda.html#Lambda.Client.update_function_code
aws lambda update-image --function-name APP-FUNC-NAME --image-uri 123459.dkr.ecr.eu-west-1.amazonaws.com/my/repo:latest
# Wait for the `LastUpdateStatus` to be `Successful`
sam package
sam deploy
```

**Comment by mndeveci** [comment]
New option `--image-repositories` have been released with [v1.14](https://github.com/aws/aws-sam-cli/releases/tag/v1.14.0), resolving the issue.

**Comment by metaskills** [comment]
Thanks @mndeveci but I looked over that work and it seems neat but does not address any of the points I brought up there. Instead it looked to focus on mapping multiple functions to a distinct ECR repository. Perhaps re-open this one?

**Comment by metaskills** [comment]
> I was hoping to just create an ECR repository along with my Lambda but I do not see a way I can create that before it tries to upload the container when I do a deploy.

I'm not sure that will work. I just discovered today that creating an ECR repo takes a few minutes till it can be deployed to. So my original request still stands... hoping for a short hand version to be supported where it assumes the same account and maybe region. That would satisfy this issues point.

**Comment by PikaChokeMe** [comment]
I found this issue after trying to make a docker image and being told I need to specify a `--image-repository`. I was hoping to be able to use something as simple as `--resolve-image-repository` similar to the `--resolve-s3` option, but it seems to be much much more difficult than that. 

I tried to make a script which does the following
```
aws ecr create-repository --repository-name "my-project" || true

AWS_ACCOUNT_ID=$(aws sts get-caller-identity --query Account --output text)
AWS_DEFAULT_REGION=us-west-2
IMAGE_REPOSITORY="${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_DEFAULT_REGION}.amazonaws.com/my-project"
```

and then specified `--image-repository "$IMAGE_REPOSITORY"`, which only leaves me lost, confused, and frustrated with the following error 
```
Error: Unable to upload artifact None referenced by ImageUri parameter of CustomLambdaFunction resource.
Image not found for ImageUri parameter of ManageOktaAppsLambdaFunction resource.
```

All I really have to add is that I agree that all the extra setup/requirements to get this all up and running seems very anti SAM. So far SAM has done an extremely good job at being easy for even a novice with limited AWS cloud formation knowledge like me to figure out. This is the first time I feel like SAM doesn't just work, and it's been very frustrating.

**Comment by tuliocasagrande** [comment]
@PikaChokeMe Are you running `sam build` followed by `sam deploy` without `--guided`?

I was facing the same error when trying to run `sam deploy --template-file template.yaml ...` instead of the using the built/packaged template `sam deploy --template-file .aws-sam/build/template.yaml ...`

**Comment by solarmosaic-kflorence** [comment]
I am confused by `--image-repository` as well. In some contexts, it seems like it should be optional (for example, when you are using `sam deploy` with a packaged template that already includes the full `ImageUri` to a tagged ECR image).

**Comment by JamesDougherty** [comment]
I posted this in the other issue as well, but just in case someone runs across this looking for help on the `--image-repositories` mentioned...

Hopefully this will help someone and save them time. There is no documentation on this as @metaskills mentioned and no examples on how to use it. So after spending more time than needed on it and looking through the source code on this, I was able to figure out what they intended.

Let's say you have two functions in your template file that use the Image package type, like the following:

```
FooFunction:   # <------------------This is a functions logical ID, take note of this.
  Type: AWS::Serverless::Function
  Properties:
    PackageType: Image
    ...
  Metadata:
    DockerTag: latest
    DockerContext: ./opt/dist/functions/foo-function/        # Wherever your Dockerfile is
    Dockerfile: Dockerfile

BarFunction:   # <------------------This is a functions logical ID, take note of this.
  Type: AWS::Serverless::Function
  Properties:
    PackageType: Image
    ...
  Metadata:
    DockerTag: latest
    DockerContext: ./opt/dist/functions/bar-function/        # Wherever your Dockerfile is
    Dockerfile: Dockerfile
```

After you run the `sam build` command it will add the following `ImageUri` to the template it generates in the .aws-sam/build directory. The ImageUri consists of the image repository name (functions logical ID in all lower case) and DockerTag concatenated. Here is an example of what it will add for the functions defined above:

```
FooFunction:
  Type: AWS::Serverless::Function
  Properties:
    PackageType: Image
    ImageUri: foofunction:latest  # <------------- Added by SAM Build
    ...
  Metadata:
    DockerTag: latest
    DockerContext: ./opt/dist/functions/foo-function/
    Dockerfile: Dockerfile

BarFunction:
  Type: AWS::Serverless::Function
  Properties:
    PackageType: Image
    ImageUri: barfunction:latest  # <------------- Added by SAM Build
    ...
  Metadata:
    DockerTag: latest
    DockerContext: ./opt/dist/functions/bar-function/
    Dockerfile: Dockerfile
```

Now when you run the `sam deploy` command you need to add the `--image-repositories` in the following format:

```
--image-repositories <Function Logical ID>=<Function Image Repository>, <Function Logical ID>=<Function Image Repository>, ...
```

Where:
**Function Logical ID** = The functions logical ID as defined in the SAM template
**Function Image Repository** = The functions ECR image repository that SAM created in ECR URL format

So using the above example we would call `sam deploy` using the following:

```
sam deploy ... --image-repositories FooFunction=<account id>.dkr.ecr.<region>.amazonaws.com/foofunction, BarFunction=<account id>.dkr.ecr.<region>.amazonaws.com/barfunction
```

Where:
**Account ID** = Your AWS account ID
**Region** = Your AWS region (like us-east-1)

I have this automated using a PowerShell script so you will just need to figure out how to handle it using your tooling / use case.

Enjoy.
