### ISSUE TITLE
Rust example not working

### ISSUE THREAD

**Issue by danjenson** [aws/aws-sam-cli#2452]
Custom build command does not run and can't invoke rust function locally, using this example in the documentation: https://docs.amazonaws.cn/en_us/serverless-application-model/latest/developerguide/building-custom-runtimes.html. 

`template.yaml`
```yaml
AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: sam-app

Globals:
  Function:
    Timeout: 3

Resources:
  HelloRustFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: HelloRust
      Handler: bootstrap.is.real.handler
      Runtime: provided
      MemorySize: 512
      CodeUri: hello_rust/
    Metadata:
      BuildMethod: makefile

Outputs:
  HelloRustFunction:
    Description: "Hello Rust Lambda Function ARN"
    Value: !GetAtt HelloRustFunction.Arn
```

`makefile`
```
build-HelloRustFunction :
	cargo build --release --target x86_64-unknown-linux-musl
	cp ./target/x86_64-unknown-linux-musl/release/bootstrap $(ARTIFACTS_DIR)
```

`hello_rust/Cargo.toml`
```rust
[package]
name = "hello_rust"
version = "0.1.0"
authors = ["Daniel Jenson <daniel.a.jenson@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
lambda_http = { version = "0.2.0-beta.1", git = "https://github.com/awslabs/aws-lambda-rust-runtime" }
rusoto_core = { version = "0.45.0", default-features=false, features=["rustls"] }
rusoto_lambda = { version = "0.45.0", default-features=false, features=["rustls"] }
tokio = { version = "0.3.4", features = ["full"] }
tokio-compat-02 = "0.1.2"
```

`hello_rust/src/main.rs`
```rust
use lambda_http::{
    handler,
    lambda::{self, Context},
    Request, Response,
};
use tokio_compat_02::FutureExt;

pub type GenericError = Box<dyn std::error::Error + Send + Sync + 'static>;

#[tokio::main]
async fn main() -> Result<(), GenericError> {
    lambda::run(handler(func)).compat().await?;
    Ok(())
}

async fn func(
    _req: Request,
    _: Context,
) -> Result<Response<String>, GenericError> {
    Response::builder()
        .header("Content-Type", "application/json")
        .body("{\"a\": 1}".to_string())
        .map_err(|e| e.into())
}
```

SAM CLI, version 1.13.2
