### ISSUE TITLE
Allow Globals to be ignored by Functions and not applied.

### ISSUE THREAD

**Issue by brysontyrrell** [aws/aws-sam-cli#2478]
### Describe your idea/feature/enhancement

I'm experimenting with using the `PackageType: Image` option for Functions and came across this error when I attempted to deploy my test app:

```
Error: Failed to create changeset for the stack: *****, ex: Waiter ChangeSetCreateComplete failed: Waiter encountered a terminal failure state Status: FAILED. Reason: Transform AWS::Serverless-2016-10-31 failed with: Invalid Serverless Application Specification document. Number of errors found: 1. Resource with id [*****] is invalid. Runtime, Handler, Layers cannot be present when PackageType is of type `Image`
```

Example template:

```yaml
AWSTemplateFormatVersion: 2010-09-09
Transform: AWS::Serverless-2016-10-31

Globals:

  Function:
    Runtime: python3.8
    Handler: index.lambda_handler
    MemorySize: 128

  ZipFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./src/zip

  ImageFunction:
    Type: AWS::Serverless::Function
    Properties:
      PackageType: Image
    Metadata:
      Dockerfile: Dockerfile
      DockerContext: ./src/image

```

If I have a template of Zip and Image type Functions I can no longer use Globals because this error is thrown. I will have to define these properties on each Zip type individually.

### Proposal

Either an addition to Globals or AWS::Serverless::Function that prevents globals from being applied to the resource(s).

### Additional Details

SAM CLI, version 1.13.2
