### ISSUE TITLE
Using geolocation on lambda functions

### ISSUE THREAD

**Issue by aprilmintacpineda** [aws/aws-sam-cli#2498]
### Description:

According to https://aws.amazon.com/about-aws/whats-new/2020/07/cloudfront-geolocation-headers/ geolocation is already supported and CloudFront returns with the geolocation headers; example:

```
CloudFront-Viewer-Country-Name: United States
CloudFront-Viewer-Country-Region: MI
CloudFront-Viewer-Country-Region-Name: Michigan
CloudFront-Viewer-City: Ann Arbor
CloudFront-Viewer-Postal-Code: 48105
CloudFront-Viewer-Time-Zone: America/Detroit
CloudFront-Viewer-Latitude: 42.30680
CloudFront-Viewer-Longitude: -83.70590
CloudFront-Viewer-Metro-Code: 505
```

I am able to get the `CloudFront-Viewer-Country-Name` except it's named `CloudFront-Viewer-Country`, how can I get the rest?

Consider the following template:

```yaml
Parameters:
  Stage:
    Description: Required staged of the current build
    Type: String
    Default: dev

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    MemorySize: 1024
  Api:
    OpenApiVersion: 3.0.1

Resources:
  login:
    Type: AWS::Serverless::Function
    Properties:
      Handler: src/functions/login.handler
      Runtime: nodejs12.x
      Layers:
        - !Ref dependencies
      Events:
        ApiEvent:
          Type: Api
          Properties:
            Method: post
            Path: /login
            RestApiId:
              Ref: mainBackendApi
  dependencies:
    Type: AWS::Serverless::LayerVersion
    Properties:
      CompatibleRuntimes:
        - nodejs12.x
      ContentUri: src/dependencies
      LayerName: proj-pronetplat-aa
      RetentionPolicy: Retain
  mainBackendApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: !Ref Stage
```

### Observed result:
The rest of CloudFront geolocation headers are missing

### Expected result:
I should get the rest of CloudFront geolocation headers

### Additional environment details (Ex: Windows, Mac, Amazon Linux etc)

1. OS: Developing on MacOS, deploying on GitHub actions using `ubuntu-latest`
2. `sam --version`: GitHub actions ubuntu-latest is using 1.13.2

`Add --debug flag to command you are running`
