### ISSUE TITLE
Multiple Functions in Stack Assume DockerContext is Unique

### ISSUE THREAD

**Issue by metaskills** [aws/aws-sam-cli#2514]
For Ruby on Rails with AWS Lambda using the Zip deployment package, we promoted using the same code with different function handlers. For example, one for Web and another for Jobs. This was easy to do with the and we even leveraged the Makefile build method to avoid building the same code twice. Tho this was not necessary. See here for details. https://lamby.custominktech.com/docs/activejob_and_lambda#3-new-jobslambda

Now that we have switched to containers I just realized a major bug with SAM that has stopped my work. Basically you can not do what SAM and the Zip package format did using Image. You can reproduce this issue by following this guide (https://aws.amazon.com/blogs/compute/using-container-image-support-for-aws-lambda-with-aws-sam/) and simply changing the `DockerContext` of the `HolaWorldFunction` to be the same `./hello-world` used in the `HelloWorldFunction`. When you do this, you end up with one of a few errors depending on you method, guided, not, etc.

```
Error: No images found to deploy, try running sam build
Error: Unable to upload artifact None referenced by ImageUri parameter of HolaWorldFunction resource.
```

For Rails we will end up using the PWD so `DockerContext: .` vs a directory, but the error is still the same. We need to have the same image for multiple functions in the stack so we can allocate memory and timeouts differently for our "web" function or "job" functions. Hope that makes sense.

**Comment by metaskills** [comment]
For my initial documentation I can work around this by having the "web" function handle both events. 

```yaml
Events:
  HttpApiProxy:
    Type: HttpApi
    Properties:
      ApiId: !Ref RailsHttpApi
  SQSJobs:
    Type: SQS
    Properties:
      Queue: !GetAtt JobsQueue.Arn
      BatchSize: 1
```

But this is not going to scale for our production usage. We need the same image for both functions like we had in the Zip format.

**Comment by metaskills** [comment]
Was chatting with @singledigit online. He had called out:

> The --image-repository flag uses the same repo for all Lambda function container images. But still a separate image for each function. The --image-repositories flag allows you to separate the images into multiple repositories. Not what you are looking for but wanted to clarify.

CORRECT. I fell back to `--image-repositories` because of this bug thinking it would help with the error(s) above. But technically I do want `--image-repository` to share the same repo. This was not the cause of the bug, it still exists but wanted to clear that up.

**Comment by metaskills** [comment]
OK, so testing the `ImageUri` that @singledigit suggested leads to a dead end because the packaged.yml will end up like this. Note how the second `ImageUri` is not processed. 

```yaml
Resources:
  WebLambda:
    Type: AWS::Serverless::Function
    Metadata:
      Dockerfile: Dockerfile
      DockerContext: .
    Properties:
      ImageUri: 012345678901.dkr.ecr.us-east-1.amazonaws.com/helloworldfunction:weblambda-6b6f5d9b54ab-latest
  JobLambda:
    Type: AWS::Serverless::Function
    Metadata:
      Dockerfile: Dockerfile
      DockerContext: .
    Properties:
      ImageUri: helloworldfunction:latest
```

So my next attempt was to use a simple symlink like so.

```shell
lrwxr-xr-x   1 kencollins  staff     1B Jan  5 16:17 jobs -> .
```

And then point my jobs resource to:

```yaml
  JobLambda:
    Type: AWS::Serverless::Function
    Metadata:
      Dockerfile: Dockerfile
      DockerContext: ./jobs
```

This actually works but I'm still testing now.
