### ISSUE TITLE
SAM CLI should support CodeUri.Bucket for existing lambda functions

### ISSUE THREAD

**Issue by superwese** [aws/aws-sam-cli#2520]
SAM CLI should support CodeUri.Bucket for existing lambda functions.

In my company we have some lambda functions that we used to share in CF stacks (e.g. a function to requeue messages from a dead letter queue to the original queue ).
When I try to define a function in my stack with a CodeUri that refers to an existing bucket I get this warning from `sam build`:
_`Lambda function 'TaskExecutionRequeueFunction' has specified S3 location for CodeUri which is unsupported. Using default value of '.' instead`_ and the whole project directory is build an uploaded.
my sam cli version is currently 1.11.0

I'd like to have the ability to use these external functions also in my SAM stacks.

### Proposal

This should be possible:
```yaml
   RequeueFunction:
    Type: AWS::Serverless::Function
    Properties:
      Timeout: 120
      Handler: requeue.handler
      CodeUri:
        Bucket: !Ref 'LambdaFunctionsBucket'
        Key: 'sqs/requeue.zip'
      Policies:
        - SQSSendMessagePolicy:
            QueueName: !GetAtt Queue.QueueName
        - SQSPollerPolicy:
            QueueName: !GetAtt DeadletterQueue.QueueName

      Environment:
        Variables:
          DEAD_LETTER_QUEUE_URL: !Ref DeadletterQueue
          ACTIVE_QUEUE_URL: !Ref Queue
      Runtime: python3.8
```

Things to consider:
1. Will this require any updates to the [SAM Spec](https://github.com/awslabs/serverless-application-model)?

No. This is already defined behaviour and SAM CLI should implement it
