### ISSUE TITLE
Unable to set authorizer on AWS::Serverless::HttpApi

### ISSUE THREAD

**Issue by rockey5520** [aws/aws-sam-cli#2526]
### Description:
Unable to set OAuth2 authorizer on API method [x-amazon-apigateway-any-method] for path [$default]

### Steps to reproduce:
Below is template.Yaml file used and when run sam deploy gives errror as 

Waiting for changeset to be created..
"Error: Failed to create changeset for the stack: finapi, ex: Waiter ChangeSetCreateComplete failed: Waiter encountered a terminal failure state Status: FAILED. Reason: Transform AWS::Serverless-2016-10-31 failed with: Invalid Serverless Application Specification document. Number of errors found: 1. Resource with id [XXX] is invalid. Event with id [HttpApiEvent] is invalid. Unable to set Authorizer [MyOauth2Authorizer] on API method [x-amazon-apigateway-any-method] for path [$default] because the related API does not define any Authorizers."

AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Parameters:
  StageName:
    Type: String
    Default: Prod
Description: XXX

Globals:
  Api:
    EndpointConfiguration: REGIONAL
  Function:
    Timeout: 180

Resources:
  Api:
    Type: AWS::Serverless::HttpApi
    Properties:
      StageName: !Ref StageName
      Auth:
        Authorizers:
          MyOauth2Authorizer:
            IdentitySource: $request.header.Authorization
            JwtConfiguration:
              audience:
                - https://aws-api-gateway
              issuer: "https://xxxx.eu.auth0.com/"
        DefaultAuthorizer: MyOauth2Authorizer

  FinApiFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: com.StreamLambdaHandler::handleRequest
      Runtime: java11
      CodeUri: api
      MemorySize: 2048
      Environment: # More info about Env Vars: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#environment-object
        Variables:
          PARAM1: VALUE
      Events:
        HttpApiEvent:
          Type: HttpApi
          Properties:
            TimeoutInMillis: 20000
            PayloadFormatVersion: '2.0'
            Auth:
              Authorizer: MyOauth2Authorizer

Outputs:
  FApiFunctionApi:
    Description: URL for application
    Value: !Sub 'https://${ServerlessHttpApi}.execute-api.${AWS::Region}.amazonaws.com/pets'
    Export:
      Name: FApiFunctionApi

### Observed result:
Waiting for changeset to be created..
Error: Failed to create changeset for the stack: finapi, ex: Waiter ChangeSetCreateComplete failed: Waiter encountered a terminal failure state Status: FAILED. Reason: Transform AWS::Serverless-2016-10-31 failed with: Invalid Serverless Application Specification document. Number of errors found: 1. Resource with id [FinApiFunction] is invalid. Event with id [HttpApiEvent] is invalid. Unable to set Authorizer [MyOauth2Authorizer] on API method [x-amazon-apigateway-any-method] for path [$default] because the related API does not define any Authorizers.

### Expected result:
function with API method [x-amazon-apigateway-any-method] for path [$default] is created on API gateway with OAuth 2.0/JWT authorizer configured

### Additional environment details (Ex: Windows, Mac, Amazon Linux etc)

1. OS: Ubuntu
2. `sam --version`: 1.15.0

`Add --debug flag to command you are running`

**Comment by spirulence** [comment]
Hey, I think you're encountering this issue because you're missing the `ApiId` property on `HttpApiEvent`, not because of an issue with the SAM CLI. I haven't tried your stack myself because the meaningful indentation has been stripped from your YAML

**Comment by aahung** [comment]
(*I made an edit to make yaml formatted.)

This template is not a valid template, you can verify it using `sam validate` and you will see the same error. 

What you are trying to do here is quite similar to one of our example "HttpApi with configuration settings" and you can find it here: https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/sam-resource-httpapi.html, let me paste it at the end of this comment.

You can try to replace
```yaml
...
        HttpApiEvent:
          Type: HttpApi
          Properties:
            TimeoutInMillis: 20000
            PayloadFormatVersion: '2.0'
            Auth:
              Authorizer: MyOauth2Authorizer
...
```

with this
```yaml
...
        HttpApiEvent:
          Type: HttpApi
          Properties:
            ApiId: !Ref Api
            TimeoutInMillis: 20000
            PayloadFormatVersion: '2.0'
```

### (Example) HttpApi with configuration settings

```yaml
AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Parameters:
  StageName:
    Type: String
    Default: Prod
    
Resources:
  HttpApiFunction:
    Type: AWS::Serverless::Function
    Properties:
      InlineCode: |
          def handler(event, context):
              import json
              return {
                  "statusCode": 200,
                  "body": json.dumps(event),
              }
      Handler: index.handler
      Runtime: python3.7
      Events:
        ExplicitApi: # warning: creates a public endpoint
          Type: HttpApi
          Properties:
            ApiId: !Ref HttpApi
            Method: GET
            Path: /path
            TimeoutInMillis: 15000
            PayloadFormatVersion: "2.0"
            RouteSettings:
              ThrottlingBurstLimit: 600

  HttpApi:
    Type: AWS::Serverless::HttpApi
    Properties:
      StageName: !Ref StageName
      Tags:
        Tag: Value
      AccessLogSettings:
        DestinationArn: !GetAtt AccessLogs.Arn
        Format: $context.requestId
      DefaultRouteSettings:
        ThrottlingBurstLimit: 200
      RouteSettings:
        "GET /path":
          ThrottlingBurstLimit: 500 # overridden in HttpApi Event
      StageVariables:
        StageVar: Value
      FailOnWarnings: True

  AccessLogs:
    Type: AWS::Logs::LogGroup

Outputs:
  HttpApiUrl:
    Description: URL of your API endpoint
    Value:
      Fn::Sub: 'https://${HttpApi}.execute-api.${AWS::Region}.${AWS::URLSuffix}/${StageName}/'
  HttpApiId:
    Description: Api id of HttpApi
    Value:
      Ref: HttpApi
```

**Comment by rockey5520** [comment]
Hi @aahung ,

I found changing the template to the below structure worked. Is this the right way to construct it?

`AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Parameters:
  StageName:
    Type: String
    Default: Prod
Description: XXX

Globals:
  Function:
    Timeout: 180
  HttpApi:
    Auth:
      Authorizers:
        MyOauthAuthorizer:
          IdentitySource: $request.header.Authorization
          JwtConfiguration:
            audience:
              - https://awsgateway
            issuer: "https://xxx.xx.com/"
      DefaultAuthorizer: MyOauthAuthorizer

Resources:
  API:
    Type: AWS::Serverless::HttpApi
    Properties:
      StageName: !Ref StageName

  XFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: xxx.StreamLambdaHandler::handleRequest
      Runtime: java11
      CodeUri: CoreApi
      MemorySize: 2048
      Role: arn:aws:iam::XXXX:role/ZZZZZ
      Environment: # More info about Env Vars: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#environment-object
        Variables:
          PARAM1: VALUE
      Events:
        HttpApiEvent:
          Type: HttpApi
          Properties:
            TimeoutInMillis: 20000
            PayloadFormatVersion: '1.0'

Outputs:
  XFunctionApi:
    Description: URL for application
    Value: !Sub 'https://${ServerlessHttpApi}.execute-api.${AWS::Region}.amazonaws.com'
    Export:
      Name: XFunctionApi`

**Comment by aahung** [comment]
> Hi @aahung ,
> 
> I found changing the template to the below structure worked. Is this the right way to construct it?
> 
> https://gist.github.com/rockey5520/a654124bb6b891ce329470f1c0d63474

```
+ Add APIStage                                  AWS::ApiGatewayV2::Stage 
+ Add API                                       AWS::ApiGatewayV2::Api 
+ Add ServerlessHttpApiApiGatewayDefaultStage   AWS::ApiGatewayV2::Stage 
+ Add ServerlessHttpApi                         AWS::ApiGatewayV2::Api 
+ Add XFunctionHttpApiEventPermission           AWS::Lambda::Permission 
+ Add XFunctionRole                             AWS::IAM::Role 
+ Add XFunction                                 AWS::Lambda::Function 
```

Your template creates two APIs, I don't think it is what you want. 

Would you mind trying to write your template based on the example I sent you? Like this:

```
AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Parameters:
  StageName:
    Type: String
    Default: Prod
    
Resources:
  HttpApiFunction:
    Type: AWS::Serverless::Function
    Properties:
      InlineCode: |
          def handler(event, context):
              import json
              return {
                  "statusCode": 200,
                  "body": json.dumps(event),
              }
      Handler: index.handler
      Runtime: python3.7
      Events:
        ExplicitApi: # warning: creates a public endpoint
          Type: HttpApi
          Properties:
            ApiId: !Ref HttpApi
            Method: GET
            Path: /path
            TimeoutInMillis: 15000
            PayloadFormatVersion: "2.0"
            RouteSettings:
              ThrottlingBurstLimit: 600

  HttpApi:
    Type: AWS::Serverless::HttpApi
    Properties:
      StageName: !Ref StageName
      Tags:
        Tag: Value
      AccessLogSettings:
        DestinationArn: !GetAtt AccessLogs.Arn
        Format: $context.requestId
      DefaultRouteSettings:
        ThrottlingBurstLimit: 200
      RouteSettings:
        "GET /path":
          ThrottlingBurstLimit: 500 # overridden in HttpApi Event
      StageVariables:
        StageVar: Value
      FailOnWarnings: True
+      Auth:
+        Authorizers:
+          MyOauthAuthorizer:
+            IdentitySource: $request.header.Authorization
+            JwtConfiguration:
+              audience:
+                - https://awsgateway
+              issuer: "https://xxx.xx.com/"
+        DefaultAuthorizer: MyOauthAuthorizer

  AccessLogs:
    Type: AWS::Logs::LogGroup

Outputs:
  HttpApiUrl:
    Description: URL of your API endpoint
    Value:
      Fn::Sub: 'https://${HttpApi}.execute-api.${AWS::Region}.${AWS::URLSuffix}/${StageName}/'
  HttpApiId:
    Description: Api id of HttpApi
    Value:
      Ref: HttpApi
```
