### ISSUE TITLE
nodejs14.x support for SAM CLI

### ISSUE THREAD

**Issue by NickLiffen** [aws/aws-sam-cli#2598]
### Description:

Right now there is no support for [Node 14](https://aws.amazon.com/blogs/compute/node-js-14-x-runtime-now-available-in-aws-lambda/) and whenever I go to build my application running SAM package/build I get the following error:

```
Building codeuri: functions/sync runtime: nodejs14.x metadata: {} functions: ['SyncFunction']
--
980 |  
981 | Build Failed
982 | Error: 'nodejs14.x' runtime is not supported
```

### Steps to reproduce:

Create a SAM Function that looks like this:

```
  SyncFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: functions/sync
      Handler: index.lambdaHandler
      Runtime: nodejs14.x
 ...
```

Then try and run SAM build, package, you will see this:

```
Building codeuri: functions/sync runtime: nodejs14.x metadata: {} functions: ['SyncFunction']
--
980 |  
981 | Build Failed
982 | Error: 'nodejs14.x' runtime is not supported
```

### Observed result:

```
Building codeuri: functions/sync runtime: nodejs14.x metadata: {} functions: ['SyncFunction']
--
980 |  
981 | Build Failed
982 | Error: 'nodejs14.x' runtime is not supported
```

### Expected result:

I wold expect it to run and pass through, honouring Node 14 support 👍 

### Additional environment details (Ex: Windows, Mac, Amazon Linux etc)

1. OS: `Linux`
2. `sam --version`: `SAM CLI, version 1.16.0`
3. AWS region: `us-east-1z
