### ISSUE TITLE
Question: CORS needs to be set manually in Lambda Handler?

### ISSUE THREAD

**Issue by mRcSchwering** [aws/aws-sam-cli#2611]
### Description:

I'm not sure whether this is intentional or a bug...

From [this documentation](https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/sam-property-api-corsconfiguration.html) I got the impression I could just add some statements to my lambda function properties in the `template.yaml` in order to mock an `OPTIONS` endpoint and add CORS headers to any response.

The `OPTIONS` part seems to work, but the responses from my lambda function don't get CORS headers automatically.
I need to add a line like this in my lambda function code, to make cross-origin requests possible:

```
def form_response(body, status):
    headers = {"Access-Control-Allow-Origin": "*"}
    return {"statusCode": status, "body": json.dumps(body), "headers": headers}
```

My template.yaml is essentially:

```
AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31

Parameters:
  StackName:
    Type: String

Globals:
  Function:
    Timeout: 5

  Api:
    Cors:
      AllowMethods: "'*'"
      AllowHeaders: "'*'"
      AllowOrigin: "'*'"

Resources:
  GqlPostFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/
      Handler: graphql_post.lambda_handler
      Runtime: python3.8
      Events:
        Gql:
          Type: Api
          Properties:
            Path: /graphql
            Method: post
            RestApiId: !Ref ApiDeployment

  ApiDeployment:
    Type: AWS::Serverless::Api
    Properties:
      StageName: stage
```
I am in eu-central-1 and use 

```
$ sam --version
SAM CLI, version 1.15.0
```
