### ISSUE TITLE
`sam validate` fails when running against a SAM docker image

### ISSUE THREAD

**Issue by xirkus** [aws/aws-sam-cli#2613]
### Description:
The AWS quick start template for a docker image fails `sam validate`.

### Steps to reproduce:
1. Run `sam init`.
2. Select `2 - Image (artifact is an image uploaded to an ECR image repository)` for the package type.
3. Select a base image (I use `5 - amazon/python3.7-base` for my example).
4. Name your application
5. `cd` into your application directory and run `sam build`
6. After the build completes run `sam validate`

### Observed result:

```
% sam validate
Template provided at '/path/to/repo/sam/sam-app/template.yaml' was invalid SAM Template.
Error: [InvalidResourceException('HelloWorldFunction', "'ImageUri' must be set.")] ('HelloWorldFunction', "'ImageUri' must be set.")
```

### Expected result:
`sam validate` should be aware when a Docker image is being used as the deployment package type an validate cleanly. For example, the example project generated will successfully deploy with `sam build`.

### Additional environment details (Ex: Windows, Mac, Amazon Linux etc)

1. OS: MacOS 11.2.1
2. SAM CLI, version 1.17.0
3. AWS region: us-east-1

**Comment by xirkus** [comment]
NVM. I just realized that the default `template.yaml` does not supply a ECR. Perhaps consider adding this resource:

```
FunctionName:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      PackageType: Image
      ImageUri: !Ref FunctionECR
      Events:
        HelloWorld:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /function
            Method: get
    Metadata:
      DockerTag: python3.7-v1
      DockerContext: ./function
      Dockerfile: Dockerfile
```


It has the advantage of require less setup for starting devs and an ECR that is automatically named.
