### ISSUE TITLE
sam build/Python: Wrong package name for some sqlalchemy versions when building on Ubuntu

### ISSUE THREAD

**Issue by bobobox** [aws/aws-sam-cli#2621]
### Description:
When building a Python3 lambda function with `sqlalchemy==1.3.13` in its requirements.txt file, in an Ubuntu 18.04 based container, `sam build` fails to create a `sqlalchemy` package in `.aws-sam/build/LambdaName/`, and instead produces an unexpected `SQLAlchemy-1.3.13.data` package, which causes code trying to import `sqlalchemy` to fail. When building in a different linux container, the correct package name is created. This version of sqlalchemy does not offer a wheel for this os/platform, so an sdist gets used. However, since a simple `pip -r requirements.txt` does create the `sqlalchemy` package, it seems like a `sam build` bug.

### Steps to reproduce:
1. Create an `AWS::Serverless::Function` that imports `sqlalchemy`.

    template.yml contents:
    ```
    ---
    AWSTemplateFormatVersion: 2010-09-09
    Transform: AWS::Serverless-2016-10-31

    Resources:
      SimpleFunction:
        Type: AWS::Serverless::Function
        Properties:
          Runtime: python3.7
          MemorySize: 128
          Handler: index.handler
          CodeUri: .
          Timeout: 10
    ```
    index.py contents:
    ```
    import sqlalchemy

    def handler(event, context):
        return
    ```
    requirements.txt contents:
    ```
    sqlalchemy==1.3.13
    ```

2. In an Ubuntu 18.04 Docker container (eg. `docker run -it ubuntu:18.04`), install `aws-sam-cli` and run `sam build` on this template.
3. Check the contents of `.aws-sam/build/SimpleFunction/`, and/or try to execute `index.py` in that directory.

### Observed result:
Contents of directory are:
```
SQLAlchemy-1.3.13.data
SQLAlchemy-1.3.13.dist-info
```
Running `index.py` fails due to missing `sqlalchemy` package.

### Expected result:
Contents of directory are:
```
sqlalchemy
SQLAlchemy-1.3.13.dist-info
```
Running `index.py` succeeds.
### Additional environment details (Ex: Windows, Mac, Amazon Linux etc)

This runs successfully in many other containers, including when running `sam build -u`. There is something about the Ubuntu 18.04 container environment (have not tried Ubuntu outside of a container, so not sure if that carries over) that is causing the wrong package name to be produced by `sam build`.

1. OS: ubuntu 18.04
2. `sam --version`: SAM CLI, version 1.18.1
3. AWS region: n/a
