### ISSUE TITLE
Use externally built docker image in multiple functions

### ISSUE THREAD

**Issue by simone-pedrazzi** [aws/aws-sam-cli#2629]
### Description:

I would like to deploy a stack with multiple functions that use the same docker image that I build manually beforehand (not with sam build, so I did not set the template `Metadata`). I was basically following the example [here](https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/sam-resource-function.html#sam-resource-function--examples--imageconfig-example).  
Each function has a custom command, while entrypoint and working dir are the same (explicitly set due to other bugs I read about). Pseudo example:

```
FunctionOne:
  Type: AWS::Serverless::Function
  Properties:
    FunctionName: !Sub "function-one-${Env}"
    PackageType: Image
    ImageUri: !Sub ${Account}.dkr.ecr.${Region}.amazonaws.com/repo-name:${Tag}
    ImageConfig:
      Command: ["main.function_one"]
      EntryPoint: ["/lambda-entrypoint.sh"]
      WorkingDirectory: "/var/task/"

FunctionTwo:
  Type: AWS::Serverless::Function
  Properties:
    FunctionName: !Sub "function-two-${Env}"
    PackageType: Image
    ImageUri: !Sub ${Account}.dkr.ecr.${Region}.amazonaws.com/repo-name:${Tag}
    ImageConfig:
      Command: ["main.function_two"]
      EntryPoint: ["/lambda-entrypoint.sh"]
      WorkingDirectory: "/var/task/"
```

I skip `sam build` and `sam package` since the artifact is already pushed to the specified ECR repository.  
When I run `sam deploy` (passing also the necessary override parameters), after the changeset gets created, the cloudformation events output contains the following for each function of the stack, and then it rollbacks the deploy:
```
Please don't provide ImageConfig when the intended function PackageType is Zip.
(Service: AWSLambdaInternal; Status Code: 400; Error Code: InvalidParameterValueException; Request ID: f7293f26-122c-4295-9332-ccaac8cede70; Proxy: null)
```

I tried specifying `--image-repository` to the same ecr repo in the template, and again duplicating it for each function resource in `image_repositories` in the `samconfig.toml`
```
image_repositories = [
  "FunctionOne=123456.dkr.ecr.eu-west-1.amazonaws.com/repo-name",
  "FunctionTwo=123456.dkr.ecr.eu-west-1.amazonaws.com/repo-name",
]
```

### Observed result:

During the deploy, with `--debug` set, amongst the output I see

_Property ImageUri of FunctionOne resource is not a URL or a local image_
...
_Unable to resolve property Endpoint: OrderedDict([('Fn::GetAtt', ['FunctionOne', 'Arn'])]). Leaving as is._
...
_Found Serverless function with name='FunctionOne' and ImageUri='123456.dkr.ecr.eu-west-1.amazonaws.com/repo-name:test'_

_Changeset created successfully. arn:..._
_Waiting for stack create/update to complete_
_CloudFormation events from changeset_

ResourceStatus | ResourceType | LogicalResourceId | ResourceStatusReason
--- | --- | --- | ---
UPDATE_IN_PROGRESS | AWS::Lambda::Function | FunctionOne | -
UPDATE_FAILED | AWS::Lambda::Function | FunctionOne | Please don't provide ImageConfig when the intended function PackageType is Zip.

### Additional environment details (Ex: Windows, Mac, Amazon Linux etc)

1. OS: MacOS
2. `sam --version`: SAM CLI, version 1.18.1
3. AWS region: eu-west-1
