### ISSUE TITLE
sam local invokes httpapi with payload version 1.0 events despite payloadFormatVersion: 2.0 config

### ISSUE THREAD

**Issue by SamuelCook** [aws/aws-sam-cli#2678]
### Description:
`aws sam local start-api` sends events in the version 1.0 payload version to lambdas configured with `payloadFormatVersion: 2.0` .

### Steps to reproduce:
I've configured an HttpApi resource that delegates to a Lambda. Both the path within the OpenAPI spec used to create the HttpApi and the backing Function are configured with `payloadFormatVersion: 2.0`.

The OpenAPI spec path:
```yaml
  /mypath/{storeId}
    parameters:
      - $ref: "#/components/parameters/storeId"
    get:
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: object
      x-amazon-apigateway-integration:
        type: aws_proxy
        uri:
          Fn::Sub: arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${MyFunction.Arn}/invocations
        httpMethod: POST
        passthroughBehavior: when_no_match
        payloadFormatVersion: 2.0
```

The SAM template lambda definition:
```yaml
  MyFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: MyFunction
      CodeUri: ./js/MyFunction/
      Handler: index.handler
      Runtime: nodejs10.x
      Events:
        GetRequest:
          Type: HttpApi
          Properties:
            ApiId: !Ref ApiGateway
            Path: /mypath/{storeId}
            Method: GET
            PayloadFormatVersion: 2.0
            Auth:
              Authorizer: NONE
```

### Observed result:
Starting up the SAM environment locally with `sam local start-api` and hitting the endpoint results in the lambda being invoked with the 1.0 version of the event payload:

```
2021-03-03 19:01:34,165 | Constructed String representation of Event to invoke Lambda. Event: {
    "body": null,
    "headers": {
        "Connection": "close",
        "Host": "0.0.0.0:3000",
        "User-Agent": "Paw/3.2.2 (Macintosh; OS X/11.2.2) GCDHTTPRequest",
        "X-Forwarded-Port": "3000",
        "X-Forwarded-Proto": "http"
    },
    "httpMethod": "GET",
    "isBase64Encoded": false,
    "multiValueHeaders": {
        "Connection": [
            "close"
        ],
        "Host": [
            "0.0.0.0:3000"
        ],
        "User-Agent": [
            "Paw/3.2.2 (Macintosh; OS X/11.2.2) GCDHTTPRequest"
        ],
        "X-Forwarded-Port": [
            "3000"
        ],
        "X-Forwarded-Proto": [
            "http"
        ]
    },
    "multiValueQueryStringParameters": null,
    "path": "/mypath/{storeId}",
    "pathParameters": {
        "storeId": "foo"
    },
    "queryStringParameters": null,
    "requestContext": {
        "accountId": "123456789012",
        "apiId": "1234567890",
        "domainName": "0.0.0.0:3000",
        "extendedRequestId": null,
        "httpMethod": "GET",
        "identity": {
            "accountId": null,
            "apiKey": null,
            "caller": null,
            "cognitoAuthenticationProvider": null,
            "cognitoAuthenticationType": null,
            "cognitoIdentityPoolId": null,
            "sourceIp": "172.21.0.1",
            "user": null,
            "userAgent": "Custom User Agent String",
            "userArn": null
        },
        "path": "/mypath/{storeId}",
        "protocol": "HTTP/1.1",
        "requestId": "f6c8e16c-53fd-4122-b473-c956e76df52c",
        "requestTime": "03/Mar/2021:18:15:41 +0000",
        "requestTimeEpoch": 1614795341,
        "resourceId": "123456",
        "resourcePath": "/mypath/{storeId}",
        "stage": "STAGE"
    },
    "resource": "/mypath/{storeId}",
    "stageVariables": null,
    "version": "1.0"
}
```

### Expected result:
The payload sent to the local Lambda function should be in the 2.0 version format.

### Additional environment details (Ex: Windows, Mac, Amazon Linux etc)

1. OS: Docker/Linux/`FROM amazon/aws-cli:2.1.28`
2. `sam --version`: SAM CLI, version 1.19.1
3. AWS region: local

**Comment by mims92** [comment]
I am unable to test locally HTTP API either

**Comment by jonathanroques** [comment]
Same here with Sam version 1.22.0. HttpApi works fine but I can't use any Auth locally (it works when deployed though). 
Any ideas ?

**Comment by antmdvs** [comment]
In addition, I just observed that it sends version 1.0 of the payload when `PayloadFormatVersion` is not specified, in which case the docs say it should default to version 2.0:

- https://github.com/aws/serverless-application-model/blob/master/versions/2016-10-31.md#httpapi
- https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/sam-property-function-httpapi.html#sam-function-httpapi-payloadformatversion

**Comment by drissamri** [comment]
When using the openapi integration to set up API GW, it doesn't respect the payload version even when added in the openapi spec: 
```
x-amazon-apigateway-integration:
        uri:
          Fn::Sub: arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${NamedQueryFunction.Arn}/invocations
        payloadFormatVersion: 2.0
        httpMethod: POST
        timeoutInMillis: 30000
        type: "aws_proxy"
```
