### ISSUE TITLE
sam local-api is able to serve invalid routes

### ISSUE THREAD

**Issue by claudioc** [aws/aws-sam-cli#2706]
### Description:

The following template, with the `/e{id}` route:
```
  GetFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: handlers/get.handler
      Description: some handler
      Events:
        Api:
          Type: Api
          Properties:
            Path: /e{id}
            Method: GET
```

works, but I think it shouldn't (also according [to the documentation](https://docs.aws.amazon.com/apigateway/latest/developerguide/http-api-develop-routes.html#http-api-develop-routes.evaluation))

### Steps to reproduce:
- Define a Lambda and attach it to that route
- run `sam local start-api --warm-containers EAGER --skip-pull-image`
- open a browser and point to http://localhost:300/esomething
- the lambda will receive "something" as the "id" parameter

### Observed result:
<img width="437" alt="Screenshot 2021-03-11 at 18 23 08" src="https://user-images.githubusercontent.com/166692/110829256-33c32900-8298-11eb-9ce7-ee4a0f345274.png">

### Expected result:
I think CDK rejects that format and so API Gateway and so should SAM cli.

### Additional environment details (Ex: Windows, Mac, Amazon Linux etc)

1. OS: macOS
2. `sam --version`: `SAM CLI, version 1.20.0`
3. AWS region: eu-central-1
