### ISSUE TITLE
Saying no to create IAM roles still goes on to create it

### ISSUE THREAD

**Issue by guoliang** [aws/aws-sam-cli#2733]
### Description:
When I run
`sam deploy --guided`

And I'm at the step where it ask 
`Allow SAM CLI IAM role creation [Y/n]:`
I chose NO, but sam-cli still attempt on creating IAM roles. Is it suppose to be like that? If so how can I tell SAM that I don't want any IAM roles to be created?

### Expected result:
When I chose no, it should omit steps to create IAM roles.

**Comment by awood45** [comment]
For some clarity on this, what this is asking about is whether to set the `CAPABILITY_IAM` option when running the deploy step. If you say "no" to this option, we will exclude that and IAM role creation will be prevented.

However, if your template has settings that would create roles automatically, that will still be attempted, but you should see a deployment failure in that case. Is that what you are seeing?

**Comment by guoliang** [comment]
I used the minimal HelloWorld example which was created using  `sam init`.
And it wants to create IAM role even though I select no. So according to you I need to remove some settings in this template right so would not create IAM role?

```
AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  sam-app

  Sample SAM Template for sam-app

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 3

Resources:
  HelloWorldFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: hello-world/
      Handler: app.lambdaHandler
      Runtime: nodejs12.x
      Events:
        HelloWorld:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /hello
            Method: get

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  HelloWorldApi:
    Description: "API Gateway endpoint URL for Prod stage for Hello World function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/hello/"
  HelloWorldFunction:
    Description: "Hello World Lambda Function ARN"
    Value: !GetAtt HelloWorldFunction.Arn
  HelloWorldFunctionIamRole:
    Description: "Implicit IAM Role created for Hello World function"
    Value: !GetAtt HelloWorldFunctionRole.Arn

```

Since the above template creates IAM role, I looked through the template again and removed some parts of it which perhaps would create IAM role. I ultimately wants it to deploy my lambda to the cloud, and also create the API gateway, but perhaps that's not possible without it needs to create IAM role?
```
AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  sam-app

  Sample SAM Template for sam-app

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 3

Resources:
  HelloWorldFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: hello-world/
      Handler: app.lambdaHandler
      Runtime: nodejs12.x

Outputs:
  HelloWorldFunction:
    Description: "Hello World Lambda Function ARN"
    Value: !GetAtt HelloWorldFunction.Arn

```
The above template still wants to create IAM role btw.
