### ISSUE TITLE
Unable to resolve SSM parameters in AWS::Serverless::Function Layers

### ISSUE THREAD

**Issue by bytekast** [aws/aws-sam-cli#2743]
### Description:

Unable to resolve SSM parameters in Layers config.

### Steps to reproduce:

```
  Hello:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: dist/
      Handler: index.hello
      Runtime: nodejs14.x
      Layers:
        - !Sub '{{resolve:ssm:/layer/common-dependencies:1}}'
```

### Observed result:

```
Error: {{resolve:ssm:/layer/common-dependencies:1}} is an Invalid Layer Arn.

```

### Expected result:

SSM Parameter should be resolved.

### Additional environment details (Ex: Windows, Mac, Amazon Linux etc)

1. OS: macOS Big Sur
2. `sam --version`: SAM CLI, version 1.16.0
3. AWS region: us-east-1

`Add --debug flag to command you are running`
