### ISSUE TITLE
DynamoDB: Cannot perform more than one GSI creation or deletion in a single update

### ISSUE THREAD

**Issue by kamrankhanwastaken** [aws/aws-sam-cli#2753]
Hello,

I am receiving this error when trying to deploy using `sam deploy` to an existing environment but I keep receiving the following error:
```
DynamoDB: Cannot perform more than one GSI creation or deletion in a single update
```
I have two global secondary indexes on one table. The error seemed intuitive enough so I commented out one all but one index at a time in my template file and it still throws the same error.

I then logged in to my AWS account and opted to deleted both indexes on the table and removed all mentions of GSIs from my template file and built it again but I still keep get the same error.

I don't know if I might have messed something up by removing the indexes directly from the AWS portal instead of using the SAM CLI? Could anyone help. Would greatly appreciate any pointers on how to get my builds running again.

### Version
SAM CLI, version 1.21.1

**Comment by moelasmar** [comment]
could you please attach your template to understand more your case.

**Comment by kamrankhanwastaken** [comment]
This is the template in particular:
```
  DynamoDBTable:
    Type: "AWS::DynamoDB::Table"
    Properties:
      TableName: !Ref TableName
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
        - AttributeName: place_id
          AttributeType: S
        - AttributeName: street_name
          AttributeType: S
        - AttributeName: street_number
          AttributeType: S
      KeySchema:
        - AttributeName: id
          KeyType: HASH
      BillingMode: PAY_PER_REQUEST
      # Only one at a time GSI creation/deletion limit. Annoying I know.
      GlobalSecondaryIndexes:
        - IndexName: !Ref GoogleAutoCompleteIndex
          KeySchema:
            - AttributeName: place_id
              KeyType: HASH
          Projection:
            ProjectionType: KEYS_ONLY
        - IndexName: !Ref StreetAddressIndex
          KeySchema:
            - AttributeName: street_name
              KeyType: HASH
            - AttributeName: street_number
              KeyType: RANGE
          Projection:
            ProjectionType: INCLUDE
            NonKeyAttributes:
            - id
            - place_id
            - city
            - district
            - neighborhood
            - province
            - postal_code

**Comment by moelasmar** [comment]
I was able to create a dynamoDB table using this template
```
DynamoDBTable:
    Type: "AWS::DynamoDB::Table"
    Properties:
      TableName: !Ref TableName
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
        - AttributeName: place_id
          AttributeType: S
        - AttributeName: street_name
          AttributeType: S
        - AttributeName: street_number
          AttributeType: S
      KeySchema:
        - AttributeName: id
          KeyType: HASH
      BillingMode: PAY_PER_REQUEST
```

Then I was able to add the global indices one by one successfully
```
AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Resources:
  DynamoDBTable:
    Type: "AWS::DynamoDB::Table"
    Properties:
      TableName: testTable
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
        - AttributeName: place_id
          AttributeType: S
        - AttributeName: street_name
          AttributeType: S
        - AttributeName: street_number
          AttributeType: S
      KeySchema:
        - AttributeName: id
          KeyType: HASH
      BillingMode: PAY_PER_REQUEST
      GlobalSecondaryIndexes:
        - IndexName: GoogleAutoCompleteIndex
          KeySchema:
            - AttributeName: place_id
              KeyType: HASH
          Projection:
            ProjectionType: KEYS_ONLY
```
and finally deploying this template successfully
```
AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Resources:
  DynamoDBTable:
    Type: "AWS::DynamoDB::Table"
    Properties:
      TableName: testTable
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
        - AttributeName: place_id
          AttributeType: S
        - AttributeName: street_name
          AttributeType: S
        - AttributeName: street_number
          AttributeType: S
      KeySchema:
        - AttributeName: id
          KeyType: HASH
      BillingMode: PAY_PER_REQUEST
      GlobalSecondaryIndexes:
        - IndexName: GoogleAutoCompleteIndex
          KeySchema:
            - AttributeName: place_id
              KeyType: HASH
          Projection:
            ProjectionType: KEYS_ONLY
        - IndexName: StreetAddressIndex
          KeySchema:
            - AttributeName: street_name
              KeyType: HASH
            - AttributeName: street_number
              KeyType: RANGE
          Projection:
            ProjectionType: INCLUDE
            NonKeyAttributes:
            - id
            - place_id
            - city
            - district
            - neighborhood
            - province
            - postal_code
```
