### ISSUE TITLE
sam local invoke produces invalid ARNs for step functions using the GetAtt function

### ISSUE THREAD

**Issue by tobyDickinson** [aws/aws-sam-cli#2762]
### Description:

When using `sam local invoke` to run a Lambda locally, the `GetAtt` function is substituting an invalid ARN into an environment variable within the Lambda. It should be using a state machine ARN but is formatting it like a Lambda ARN.

When I deploy this using `sam deploy` the ARN in the environment variables for the Lambda is substituted correctly. Therefore, I believe this is a bug with the SAM CLI. Can anyone recreate this issue?

### Steps to reproduce:

**SAM CLI Version:** 1.19.1
**Template File:** `template.yaml`:
```yaml
AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: >
  Test-Template

Resources:
  TestFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/lambda
      Handler: test-function.lambdaHandler
      Runtime: nodejs14.x
      Environment:
        Variables:
          STEPFUNCTION_ARN: !GetAtt MyStepFunction.Arn

  MyStepFunction:
    Type: AWS::Serverless::StateMachine
      Properties:
        DefinitionUri: statemachine/my-step-function.asl.json
        Policies:
          - LambdaInvokePolicy:
              FunctionName: "*Someotherfunctions"
```

**Lambda Definition**`test-function.js`:
```js
export const lambdaHandler = () => console.info(process.env.STEPFUNCTION_ARN)
```

### Observed result:

```sh
$ sam local invoke --region eu-west-1 TestFunction
2021-03-24T13:02:38.017Z        62581b08-94a5-49e2-a952-58413ba7653e    INFO    arn:aws:lambda:eu-west-1:123456789012:function:MyStepFunction
```

### Expected result:

The expected output would be an ARN which was a valid step function ARN. Something like:
```
arn:aws:states:eu-west-1:123456789012:stateMachine:MyStepFunction
```

### Additional environment details (Ex: Windows, Mac, Amazon Linux etc)

1. OS: Mac OS Catalina
2. `sam --version`: 1.19.1
3. AWS region: eu-west-1

`Add --debug flag to command you are running`

**Comment by tobyDickinson** [comment]
I've found where the bug exists in the source code. The function `handle_fn_getatt` in `intrinsic_propert_resolver.py:585` handles the translation which uses the `resolve_symbols` function in `intrinsics_symbol_table.py:174`.

In the `resolve_symbols` function on line `225` we get an attribute resolver (would be `Arn` in this case).

```py
def get_default_attribute_resolver(self):
    return {"Ref": lambda logical_id: logical_id, "Arn": self.arn_resolver}
```

Therefore the `arn_resolver` is returned to the calling function on line `225` of `intrinsics_source_table.py`:

```py
def arn_resolver(self, logical_id, service_name="lambda"):
        """
        This function resolves Arn in the format
            arn:{partition_name}:{service_name}:{aws_region}:{account_id}:{function_name}

        Parameters
        -----------
        logical_id: str
            This the reference to the function name used
        service_name: str
            This is the service name used such as lambda or sns

        Return
        -------
        The resolved Arn
        """
```

As you can see the `service_name` defaults to `lambda`. Since the calling method `resolve_symbols(self, logical_id, resource_attribute, ignore_errors=false)` doesn't have the resource type of `MyStepFunction` available (`logical_id=MyStepFunction`, `resource_attribute=Arn`), it calls it using just the name therefore using the default `lambda` type.

To resolve this we need to propagate this type down the call stack to this function to resolve this issue.

**Comment by tobyDickinson** [comment]
The workaround for anyone else experiencing this issue is to use the `!Sub` function to build your ARN instead.

Your `template.yaml` becomes:
```yaml
# ...
Environment:
  Variables:
    STEPFUNCTION_ARN: !Sub arn:aws:states:${AWS::Region}:${AWS::AccountId}:stateMachine:MyStepFunction
# ...
```
