### ISSUE TITLE
Node lambda successful with sam local but fails with `cannot find module...` when deployed

### ISSUE THREAD

**Issue by DallasP9124** [aws/aws-sam-cli#2764]
I have a lambda project that I can invoke locally with `sam local invoke`. I create directory that is to resemble the packaged code for deploying in AWS.
```
build/
  - node_modules
  - custom_libs/
      - .....
  - app.js
```

And here is the *template.yml* file:
```yaml
Transform: AWS::Serverless-2016-10-31
Globals:
  Function:
    Timeout: 20
    Runtime: nodejs12.x
    
Resources:
  ReportBuilder:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: chart-build
      Handler: app.handler
      CodeUri: ./build/
```
When invoking the lambda locally, no errors are thrown and it returns expected value. However, when the build folder is zipped up and deployed, invoking that lambda will now give me this error (from cloudwatch).

```
2021-03-24T22:35:37.400Z	undefined	ERROR	Uncaught Exception 	{
    "errorType": "Runtime.ImportModuleError",
    "errorMessage": "Error: Cannot find module './lib/compat'\nRequire stack:\n- /var/task/node_modules/depd/index.js\n- /var/task/node_modules/body-parser/index.js\n- /var/task/node_modules/express/lib/express.js\n- /var/task/node_modules/express/index.js\n- /var/task/app.js\n- /var/runtime/UserFunction.js\n- /var/runtime/index.js",
    "stack": [
        "Runtime.ImportModuleError: Error: Cannot find module './lib/compat'",
        "Require stack:",
        "- /var/task/node_modules/depd/index.js",
        "- /var/task/node_modules/body-parser/index.js",
        "- /var/task/node_modules/express/lib/express.js",
        "- /var/task/node_modules/express/index.js",
        "- /var/task/app.js",
        "- /var/runtime/UserFunction.js",
        "- /var/runtime/index.js",
        "    at _loadUserApp (/var/runtime/UserFunction.js:100:13)",
        "    at Object.module.exports.load (/var/runtime/UserFunction.js:140:17)",
        "    at Object.<anonymous> (/var/runtime/index.js:43:30)",
        "    at Module._compile (internal/modules/cjs/loader.js:999:30)",
        "    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)",
        "    at Module.load (internal/modules/cjs/loader.js:863:32)",
        "    at Function.Module._load (internal/modules/cjs/loader.js:708:14)",
        "    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:60:12)",
        "    at internal/main/run_main_module.js:17:47"
    ]
}
```

I Checked the node_modules in the package and the `/depd/lib/compat` is in fact present.
This is my first lambda with node so is there some disconnection that I am missing?

Thanks for the help!

Windows 10
SAM CLI, version 1.6.2
AWS Region: us-west-2
