### ISSUE TITLE
ReservedConcurrentExecutions should accept null

### ISSUE THREAD

**Issue by aprilmintacpineda** [aws/aws-sam-cli#2788]
### Description:

I have the following map:

```yaml
Mappings:
  stageVars:
    dev:
      reservedConcurrentExecutions: null
    prod:
      reservedConcurrentExecutions: 10
```

And I use it like so:

```yaml
Globals:
  Function:
    ReservedConcurrentExecutions: !FindInMap
      - stageVars
      - !Ref Stage
      - reservedConcurrentExecutions
```

I want to set `ReservedConcurrentExecutions` to a value ONLY in production, but on development, I want to remove it, I want it to behave as if I did not set the `ReservedConcurrentExecutions`. If I set it to `0`, I will not be able to invoke my functions.

### Steps to reproduce:

create a sample app with `ReservedConcurrentExecutions: null`

### Observed result:

It throws the following error:

```
Error: Failed to create changeset for the stack: my-project-dev, ex: Waiter ChangeSetCreateComplete failed: Waiter encountered a terminal failure state Status: FAILED. Reason: [/Mappings/stageVars/dev/reservedConcurrentExecutions] 'null' values are not allowed in templates
```

### Expected result:

It should unset `ReservedConcurrentExecutions`

### Additional environment details (Ex: Windows, Mac, Amazon Linux etc)

1. OS: ubuntu-latest VM on github actions
2. `sam --version`: 
3. AWS region: 

`Add --debug flag to command you are running`

**Comment by mingkun2020** [comment]
Hi @aprilmintacpineda, could you try set the dev like this:

**Comment by aprilmintacpineda** [comment]
> Hi @aprilmintacpineda, could you try set the dev like this to see if it works for you:
> 
> ```
>     dev:
>       reservedConcurrentExecutions: ""
> ```

I will try that, thank you for the response.

**Comment by aprilmintacpineda** [comment]
I got another error, which is weird out of nowhere, which is wierd:

```
Properties validation failed for resource onUserDisconnected with message: #/Reserv edConcurrentExecutions : expected type: Integer, found: String
```

It is this function:

```
onUserDisconnected:
    Type: AWS::Serverless::Function
    Properties:
      Handler: onUserDisconnected.handler
      Policies:
        - CloudWatchLambdaInsightsExecutionRolePolicy
      FunctionName: !Join
        - '-'
        - - !Ref Stage
          - "myapp-onUserDisconnected"
```

This happened while I was reversing the change for https://github.com/aws/aws-sam-cli/issues/2887 all I did was checked out the previous template file that deployed successfully...
