### ISSUE TITLE
Displaying parameters' descriptions in guided deployments

### ISSUE THREAD

**Issue by omriza** [aws/aws-sam-cli#2789]
### Describe your idea/feature/enhancement

When using `sam deploy --guided`, I wish SAM would display parameters' descriptions (if any) like some of the built-in options. This will highly simplify guided deployments, especially when the one who wrote the template is not the one who deploys it.

e.g. for the built-in _Confirm changes_ option, SAM shows:
#Shows you resources changes to be deployed and require a 'Y' to initiate deploy
**Confirm changes before deploy** [Y/n]:

### Proposal
When running `sam deploy --guided` with this template parameter-
```
Parameters:
  MyPar:
    Type: String
    Description: Example description for parameter MyPar
    Default: MyParVal
```
SAM will show-
#Example description for parameter MyPar
**Parameter MyPar** [MyParVal]:

Things to consider:
Description should be only showed when exists.
