### ISSUE TITLE
sam deploy is ignoring environment variables configuration

### ISSUE THREAD

**Issue by epastorino** [aws/aws-sam-cli#2797]
I'm using SAM cli v1.22 on Windows 10.
I'm just trying to declare some environment variables in my template.yaml file so they are created in my lambda function.
I have something like this:

```yaml
MyFunction:
 Type: AWS::Serverless::Function
 Properties:
  CodeUri: .
  Handler: app.app
  Runtime: python3.8
  Environment:
   Variables:
    MY_VAR: some_value
```
sam deploy doesn't report any errors, but no environment variables show up in AWS console for this lambda function.

I was about to give up, but then I tried uninstalling the sam cli, got an older version (1.15) and tried again.
All my environment variables were created with their corresponding values.

I haven't tried other versions nor other OSs, so as far as I know, this seems to be an issue in v1.22 on Windows 10.
