### ISSUE TITLE
sam package does not transforms CodeUri set via global via parameters' default

### ISSUE THREAD

**Issue by FieryCod** [aws/aws-sam-cli#2836]
### Description:

Consider following template.yml in which CodeUri is set via parameter. After using `sam package --template-file template.yml --output-template-file packaged.yml --s3-bucket some-bucket --s3-prefix some-prefix --region eu-central-1` I can see that CodeUri is not transformed to S3 URL 

**template.yml**
```
AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  Example basic lambda using `holy-lambda` micro library

Parameters:
  Runtime:
    Type: String
    Default: java8
  Timeout:
    Type: Number
    Default: 40
  MemorySize:
    Type: Number
    Default: 2000
  CodeUri:
    Type: String
    Default: target/output.jar

Globals:
  Function:
    Runtime: !Ref Runtime
    Timeout: !Ref Timeout
    MemorySize: !Ref MemorySize
    CodeUri: !Ref CodeUri

Resources:
  ExampleLambdaFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: example.core.ExampleLambda
      FunctionName: ExampleLambdaFunction
      Events:
        HelloEvent:
          Type: Api
          Properties:
            Path: /
            Method: get
```

**packaged.yml**
```
AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: 'Example basic lambda using `holy-lambda` micro library

  '
Parameters:
  Runtime:
    Type: String
    Default: java8
  Timeout:
    Type: Number
    Default: 40
  MemorySize:
    Type: Number
    Default: 2000
  CodeUri:
    Type: String
    Default: build/output.jar
Globals:
  Function:
    Runtime:
      Ref: Runtime
    Timeout:
      Ref: Timeout
    MemorySize:
      Ref: MemorySize
    CodeUri:
      Ref: CodeUri
Resources:
  ExampleLambdaFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: example.core.ExampleLambda
      FunctionName: ExampleLambdaFunction
      Events:
        HelloEvent:
          Type: Api
          Properties:
            Path: /
            Method: get
      CodeUri:
        Ref: CodeUri
```

### Expected result:

I would like sam package to respect global parameters and transform template.yml correctly

### Additional environment details (Ex: Windows, Mac, Amazon Linux etc)

1. OS: Arch Linux
2. `sam --version`: 1.23.0
3. AWS region: eu-central-1

**Comment by aahung** [comment]
See #2835

**Comment by FieryCod** [comment]
My current approach is a little bit hacky:

Before using `sam package`:
1. Create temporary directory for new conrete runtime template.yml
2. Rewrite CodeUri in a that new template
3. Use the template for `sam package` command

**Comment by aahung** [comment]
SAM CLI does not handle code path well if it is in parameter's `Default`.

I think function code should be packaged if the code uri is specified in parameter's default, but here comes an open question:

should function **be built** in `sam build` if the code uri is specified in parameter's default? What if the parameter is set to some other value, are we gonna build both of them? (example see below:)

```yaml
Parameters:
  CodeUri:
    Type: String
    Default: src1

... Function:
  Properties:
    CodeUri: !Ref CodeUri
```

```sh
sam build --parameter-overrides="CodeUri=src2"  # will src1 and src2 both should be built?
```

--- 
Also I noticed a bug in `sam build` if `CodeUri` is specified in `Global:`

The `CodeUri` of SAM function should not be set after `sam build`

```yaml
# original
Globals:
  Function:
    CodeUri: !Ref CodeUri

Resources:
  Function:
    Type: AWS::Serverless::Function
    Properties:
      Handler: app2.lambda_handler
      Runtime: python3.8
```

```yaml
# built
Globals:
  Function:
    CodeUri: python-code
Resources:
  Function:
    Type: AWS::Serverless::Function
    Properties:
      Handler: app2.lambda_handler
      Runtime: python3.8
      CodeUri: Function
```
