### ISSUE TITLE
Incorrect layer output ARN in deployed AWS application

### ISSUE THREAD

**Issue by FieryCod** [aws/aws-sam-cli#2840]
### Description:

I have the following **template.yml**:

```
AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  Babashka runtime as an AWS::Serverless::Application

Resources:
  HolyLambdaBabashkaRuntime:
    Type: AWS::Serverless::Application
    Properties:
      Location:
        ApplicationId: arn:aws:serverlessrepo:eu-central-1:443526418261:applications/holy-lambda-babashka-runtime
        SemanticVersion: 0.1.17
```

which is deployed using command:

```
sam deploy --template-file template.yml --stack-name BabashkaRuntimeStackInstance --no-confirm-changeset --capabilities CAPABILITY_IAM CAPABILITY_AUTO_EXPAND
```

Application is publicly available [here](https://serverlessrepo.aws.amazon.com/applications/eu-central-1/443526418261/holy-lambda-babashka-runtime) and outputs a LayerVersion.

Part of application template.yml definition
```
  BabashkaLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      LayerName: holy-lambda-babashka-runtime
      Description: holy-lambda micro framework babashka compatible runtime layer
      ContentUri: ./holy-lambda-babashka-runtime.zip
      CompatibleRuntimes:
        - provided
      LicenseInfo: https://github.com/FieryCod/holy-lambda/tree/master/modules/holy-lambda-babashka-layer/LICENSE
      RetentionPolicy: Retain

Outputs:
  LayerVersion:
    Description: Layer ARN Reference
    Value: !Ref BabashkaLayer
```

After deployment I can spot via `aws cloudformation describe-stacks` incorrect version of layer in ARN.

```
"Outputs": [
    {
        "OutputKey": "LayerVersion",
        "OutputValue": "arn:aws:lambda:eu-central-1:443526418261:layer:holy-lambda-babashka-runtime:16",
        "Description": "Layer ARN Reference"
    }
],
"Tags": [
    {
        "Key": "serverlessrepo:semanticVersion",
        "Value": "0.0.17"
    },
    {
        "Key": "lambda:createdBy",
        "Value": "SAM"
    },
    {
        "Key": "serverlessrepo:applicationId",
        "Value": "arn:aws:serverlessrepo:eu-central-1:443526418261:applications/holy-lambda-babashka-runtime"
    }
],
```

### Steps to reproduce:
1. Run `sam deploy` on provided `template.yml`
2. Run `aws cloudformation describe-stacks`

### Expected result:
ARN should have correct version of the Layer.

### Additional environment details (Ex: Windows, Mac, Amazon Linux etc)

1. OS: Arch Linux
2. `sam --version`: 1.23.0
3. AWS region: eu-central-1
