### ISSUE TITLE
Set Lambda/Function Runtime by Parameter

### ISSUE THREAD

**Issue by GregTurner** [aws/aws-sam-cli#2915]
### Describe your idea/feature/enhancement

I wish SAM CLI would allow me to set a Lambda/Function Runtime property as a parameter like so:

```
...
Parameters:
  LambdaRuntime:
    Type: String
    Default: 'nodejs10.x'
Resources:
  MyLambdaFunction:
    Type: AWS::Serverless::Function
    Properties:
      Runtime: !Sub '${LambdaRuntime}'
...
```

### Additional Details

This is useful when doing lambda runtime upgrades, e.g., node 12 -> node 14.  We can deploy to dev/test environments and fully regression test before configuring the prod Lambdas with a newer Runtime version. 

Workarounds are available but it's not user friendly.
