### ISSUE TITLE
Sam build template.yml DefinitionUri produces different path depending on Servereless  or Stepfunctions Statemachine

### ISSUE THREAD

**Issue by mikehas** [aws/aws-sam-cli#2926]
Assuming a directory structure:

template.yml
statemahine/mystatemachine.json

template.yml contents:
```
  MyStateMachine:
    Type: AWS::Serverless::StateMachine
    Properties:
      DefinitionUri: statemachine/mystatemachine.json
```

After running 'sam build -t template.yml -b build' there are different results in build/template.yml depending on whether the serverless or stepfunctions statemachine is used.

CASE 1 - AWS::Serverless::StateMachine

build/template.yml contents:
```
  MyStateMachine:
    Type: AWS::Serverless::StateMachine
    Properties:
      DefinitionUri: ../statemachine/mystatemachine.json

```
CASE 2 - AWS::Stepfunctions::StateMachine

build/template.yml contents:
```
  MyStateMachine:
    Type: AWS::Stepfunctions::StateMachine
    Properties:
      DefinitionUri: statemachine/mystatemachine.json

```

The Stepfunctions re-writing would be our preferred method, due to deployment of the build to another AWS account and paths breaking.

Example of errors caused by incorrect path re-writing when serverless statemachine is used. Stepfunctions may not work as a workaround, currently troubleshooting.

```

Error: Unable to upload artifact ../statemachine/mystatemachine.json referenced by DefinitionUri parameter of MyStateMachine resource.
--
Parameter DefinitionUri 
of resource MyStateMachine refers to a file or folder that does 
not exist /codebuild/output/src149/src/s3/statemachine/mystatemachine.json

```
