### ISSUE TITLE
sam deploy --tags doesn't propagate tags in all resources

### ISSUE THREAD

**Issue by esteban1983cl** [aws/aws-sam-cli#2952]
### Description:
I want tag all resources created by sam, but for some resources, tags are missing. 

### Steps to reproduce:
Having the follow simple template with schedule:

<details>
<summary>Template</summary>

```yaml
AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  Tagger Function, Tag resources that are not support automatic tag, like DocumentDB, EC2 Snapshots

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 360

Resources:
  DevOpsTaggerFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: ../../tagger_function
      Handler: tagger/app.lambda_handler
      Runtime: python3.8
      Events:
        CWSchedule:
          Type: Schedule # More info about CloudWatchEvent Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#cloudwatchevent
          Properties:
            Schedule: rate(15 minutes)
            Name: DevOpsTaggerSchedule
            Description: Schedule for Trigger DevOpsTaggerFunction Lambda Function
            Enabled: True
      Policies:
        - AmazonEC2FullAccess
        - AmazonRDSFullAccess
      VpcConfig:
        SecurityGroupIds:
          - sg-aaaaaaaaaaaaaa # Default VPC Security Group
        SubnetIds: # Private Subnet's
          - subnet-aaaaaaaaaaaaaaaaa
          - subnet-bbbbbbbbbbbbbbb
          - subnet-ccccccccccccccccc

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  DevOpsTaggerFunction:
    Description: "DevOps Tagger Lambda Function ARN"
    Value: !GetAtt DevOpsTaggerFunction.Arn
  DevOpsTaggerFunctionIamRole:
    Description: "Implicit IAM Role created for DevOps Tagger function"
    Value: !GetAtt DevOpsTaggerFunctionRole.Arn
```
</details>

Running on gitlab job:

```shell
$ sam deploy --template-file ./templates/${CI_ENVIRONMENT_NAME}/package.yaml --no-fail-on-empty-changeset --debug --stack-name ${STACK_NAME} --capabilities CAPABILITY_IAM --no-confirm-changeset --s3-bucket ${BUCKET_NAME} --region $AWS_REGION --tags "${TAGS}"
2021-06-12 02:58:13,382 | Telemetry endpoint configured to be https://aws-serverless-tools-telemetry.us-west-2.amazonaws.com/metrics
2021-06-12 02:58:13,383 | Using config file: samconfig.toml, config environment: default
2021-06-12 02:58:13,383 | Expand command line arguments to:
2021-06-12 02:58:13,383 | --template_file=/builds/cencosud-ds/arquitectura-plataforma/tools/devops/aws/lambdas/tagger/templates/staging/package.yaml --stack_name=DevOpsTagger --capabilities=('CAPABILITY_IAM',) --s3_bucket=mysuperbucket.devops-tools-sam-deploy --tags={'ambiente': 'staging', 'pais': 'cl', 'ceco': 'cgo0000000', 'cuenta': 'XXXXXXXXXXXX', 'proyecto': 'Plataformas TxD', 'aplicacion': 'DevOps Tools', 'nombre': 'DevOpsTagger', 'Name': 'DevOpsTagger', 'propietario': 'esteban.avendano@cencosud.cl', 'tribe': 'Arquitectura y Plataforma', 'epm': 'opex', 'ApplicationName': 'Plataformas TxD', 'BusinessUnit': 'SHARED', 'RepoURL': 'https://gitlab.com/dolape/lambdas/tagger'} 
2021-06-12 02:58:13,764 | Property CodeUri of DevOpsTaggerFunction is already a S3 URL
	Deploying with following values
	===============================
	Stack name                   : DevOpsTagger
	Region                       : us-east-1
	Confirm changeset            : False
	Deployment s3 bucket         : mysuperbucket.devops-tools-sam-deploy
	Capabilities                 : ["CAPABILITY_IAM"]
	Parameter overrides          : {}
	Signing Profiles             : {}
Initiating deployment
=====================
2021-06-12 02:58:13,812 | No Parameters detected in the template
2021-06-12 02:58:13,833 | 1 stacks found in the template
2021-06-12 02:58:13,834 | No Parameters detected in the template
2021-06-12 02:58:13,852 | 1 resources found in the stack 
2021-06-12 02:58:13,852 | No Parameters detected in the template
Uploading to 1464e01b82d40bea499fba40263a9609.template  1352 / 1352  (100.00%)
Waiting for changeset to be created..
CloudFormation stack changeset
-------------------------------------------------------------------------------------------------
Operation                LogicalResourceId        ResourceType             Replacement            
-------------------------------------------------------------------------------------------------
* Modify                 DevOpsTaggerFunctionCW   AWS::Lambda::Permissio   Conditional            
                         SchedulePermission       n                                               
* Modify                 DevOpsTaggerFunctionCW   AWS::Events::Rule        False                  
                         Schedule                                                                 
* Modify                 DevOpsTaggerFunctionRo   AWS::IAM::Role           False                  
                         le                                                                       
* Modify                 DevOpsTaggerFunction     AWS::Lambda::Function    False                  
-------------------------------------------------------------------------------------------------
Changeset created successfully. arn:aws:cloudformation:us-east-1:XXXXXXXXXXXXX:changeSet/samcli-deploy1623466694/678889ff-3be4-48fd-b90e-db34bb88de98
2021-06-12 02:58:24 - Waiting for stack create/update to complete
CloudFormation events from changeset
-------------------------------------------------------------------------------------------------
ResourceStatus           ResourceType             LogicalResourceId        ResourceStatusReason   
-------------------------------------------------------------------------------------------------
UPDATE_IN_PROGRESS       AWS::IAM::Role           DevOpsTaggerFunctionRo   -                      
                                                  le                                              
UPDATE_COMPLETE          AWS::IAM::Role           DevOpsTaggerFunctionRo   -                      
                                                  le                                              
UPDATE_IN_PROGRESS       AWS::Lambda::Function    DevOpsTaggerFunction     -                      
UPDATE_COMPLETE          AWS::Lambda::Function    DevOpsTaggerFunction     -                      
UPDATE_COMPLETE          AWS::CloudFormation::S   DevOpsTagger             -                      
                         tack                                                                     
UPDATE_COMPLETE_CLEANU   AWS::CloudFormation::S   DevOpsTagger             -                      
P_IN_PROGRESS            tack                                                                     
-------------------------------------------------------------------------------------------------
CloudFormation outputs from deployed stack
-------------------------------------------------------------------------------------------------
Outputs                                                                                         
-------------------------------------------------------------------------------------------------
Key                 DevOpsTaggerFunction                                                        
Description         DevOps Tagger Lambda Function ARN                                           
Value               arn:aws:lambda:us-east-1:XXXXXXXXXXXXX:function:DevOpsTagger-                
DevOpsTaggerFunction-BL7MaJjA6kZx                                                               
Key                 DevOpsTaggerFunctionIamRole                                                 
Description         Implicit IAM Role created for DevOps Tagger function                        
Value               arn:aws:iam::XXXXXXXXXXX:role/DevOpsTagger-                                
DevOpsTaggerFunctionRole-1DMZBWARWYQTK                                                          
-------------------------------------------------------------------------------------------------
Successfully created/updated stack - DevOpsTagger in us-east-1
2021-06-12 02:58:55,489 | Installed version 1.24.1, current version 1.24.1
```

### Observed result:

I don't see tags on resource 
```shell
DevOpsTaggerFunctionCW   AWS::Events::Rule
```

### Expected result:

Like you say on docs for sam deploy:

--tags A list of tags to associate with the stack that is created or updated. AWS CloudFormation also propagates these tags to resources in the stack that support it.

I know maybe the Schedule object in Function doesn't support tags, but AWS::Events::Rule yes. Maybe I need create an issue in corresponding repo right ?

### Additional environment details (Ex: Windows, Mac, Amazon Linux etc)

1. OS: Docker Container with Alpine 3.13, awscli 1.19.93
2. `sam --version`: 1.24.1
3. AWS region: us-east-1

`Add --debug flag to command you are running`
