### ISSUE TITLE
AWS SAM-CLI The security token included in the request is invalid.

### ISSUE THREAD

**Issue by rvasconcelossilva** [aws/aws-sam-cli#2963]
### Description:
I am creating my first Lambda Function using AWS Toolkit and SAM-CLI and I am facing two main issues:

1. When I use a workaround and this function is getting information from AWS System Manager Parameter Store: An error occurred (UnrecognizedClientException) when calling the GetParameter operation: The security token included in the request is invalid.

I use Windows 10, Visual Studio Code, SAM CLI version 0.44 (Tried to update using the install but no success) and Python 3.8.

### Steps to reproduce:
Below is the YAML.

```
AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  research-gam-download-revenuereport

  Sample SAM Template for research-gam-download-revenuereport
# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 3

Resources:

  HelloWorldFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      Role: arn:aws:iam::123568192875:role/10-research-insights-sb-lambdaiam
      CodeUri: hello_world/
      Handler: lambda_function.lambda_handler
      Runtime: python3.8
      Events:
        HelloWorld:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /hello
            Method: get
      Layers:
        - !Ref Test

  Test:
    Type: AWS::Serverless::LayerVersion
    Properties:
      CompatibleRuntimes: 
        - python3.6
        - python3.7
        - python3.8  
      ContentUri: ../../../../../ten/ten_package.zip     
      Description: research-insights-sb-tenlayer
      LayerName: tenlayer
      LicenseInfo: MIT   
```

### Observed result:
Error 1: An error occurred (UnrecognizedClientException) when calling the GetParameter operation: The security token included in the request is invalid.

### Expected result:
I was expecting it would connect to other AWS resources as it is already with the credentials

### Additional environment details (Ex: Windows, Mac, Amazon Linux etc)

1. OS: Windows 10
2. `sam --version`: 0.44
3. AWS region: ap-southeast-2
