### ISSUE TITLE
Support request validators and request/response mappings

### ISSUE THREAD

**Issue by kadrach** [aws/aws-sam-cli#299]
It would be great if `aws-sam-local` could support the request validation features of the APIGateway and request/response mappings with Velocity templates! Alternatively a log message on local calls that these parts of the definition are being ignored :)

**Comment by brunofitas** [comment]
Hi guys. Any progress on this? This is a really important feature.
Thanks

**Comment by ejhayes** [comment]
@brunofitas @kadrach I have implemented this functionality locally https://github.com/ejhayes/aws-sam-cli. 

The velocity template mapping and JSONPath looks to be working fine, but java specific string functions like `replaceAll` will not work. For example `$util.escapeJavaScript($input.json('$.errorMessage'))` would work, but `$util.escapeJavaScript($input.json('$.errorMessage')).replaceAll("\\'","'")` would not.

Hoping to have a PR opened in the next couple days.

**Comment by brunofitas** [comment]
Thanks Eric!

**Comment by heitorlessa** [comment]
Awesome one Eric!!!

Look forward to the PR and shout out if you need a hand to us

**Comment by hanstf** [comment]
Hi, will this going to be implemented ?
also @ejhayes, is your pull request only cater the x-amazon-apigateway-integration ?
As my template is came from the CDK and something like this

```
      Integration:
        ContentHandling: CONVERT_TO_TEXT
        IntegrationHttpMethod: POST
        IntegrationResponses:
          - ResponseParameters:
              method.response.header.Access-Control-Allow-Origin: "'*'"
            ResponseTemplates:
              application/json: "{\"data\": $input.json('$')}"
            StatusCode: "200"
          - ResponseParameters:
              method.response.header.Access-Control-Allow-Origin: "'*'"
            ResponseTemplates:
              application/json: "{\"message\":\"$input.path('$.message')\"}"
            SelectionPattern: .*Exception.*|.*error.*
            StatusCode: "400"
        PassthroughBehavior: WHEN_NO_TEMPLATES
        RequestTemplates:
          image/jpeg: '{"base64Image":"$input.body","token":"$input.header.Authorization"}'
```
