### ISSUE TITLE
Need clarity on using --template-file as well as config file

### ISSUE THREAD

**Issue by danwiltshire** [aws/aws-sam-cli#3166]
### Description:
When passing `--template-file` to `sam local invoke`, configuration set within `samconfig.toml` seems to be ignored.  This is a particular problem when using AWS Toolkit within IDEs since it seems to use that argument.

Setting an explicit path to `samconfig.toml` exhibits the same problem:

```
sam local invoke MyFunction -t .aws-sam/build/template.yaml --config-file samconfig.toml
```

My use case is setting environment variables within `samconfig.toml` so users using AWS Tookit on any IDE share the same configuration.  Sadly, AWS Toolkit passes `--template-file`, causing the issue.

It should be noted that passing `--env-vars` is a workaround - but this requires configuration for each function within `.vscode/launch.json` - and this is VS Code-specific.

### Steps to reproduce:

- Populate `samconfig.toml` with required configuration, e.g.:
  ```
  env_vars = "env-vars.json"
  ```
- Run `sam build --template MyTemplate.yaml --use-container`
- Run `sam local invoke MyFunction -t .aws-sam/build/template.yaml`

### Observed result:
Configuration set within `samconfig.toml` doesn't seem to be used.

### Expected result:
Configuration set within `samconfig.toml` is used.

### Additional environment details (Ex: Windows, Mac, Amazon Linux etc)

1. OS: WSL2 (Ubuntu 20.04)
2. `sam --version`: 1.27.2
3. AWS region: eu-west-1

### Debug
```log
sam local invoke MyFunction -t .aws-sam/build/template.yaml --config-file samconfig.toml --debug
2021-08-12 10:05:23,602 | Telemetry endpoint configured to be https://aws-serverless-tools-telemetry.us-west-2.amazonaws.com/metrics
2021-08-12 10:05:23,603 | Using config file: samconfig.toml, config environment: default
2021-08-12 10:05:23,603 | Expand command line arguments to:
2021-08-12 10:05:23,603 | --template_file=/.aws-sam/build/template.yaml --function_logical_id=MyFunction --no_event --layer_cache_basedir=/home/user/.aws-sam/layers-pkg --container_host=localhost --container_host_interface=127.0.0.1 
2021-08-12 10:05:23,603 | local invoke command is called
{...}
```

### samconfig.toml
```toml
version = 0.1

[default.build.parameters]
# use_container required to avoid spurious errors such as
# Error: PythonPipBuilder:ResolveDependencies - list index out of range
use_container = "true"

[default.local_invoke.parameters]
# env_vars required to pass environment variables to the
# Lambda function image container when debugging locally.
env_vars = "env-vars.json"
```

### env-vars.json
```json
{
    "Parameters": {
        "S3_ENDPOINT_URL": "http://localhost:4566"
    },
    "MyFunction": {
        {...}
    }
}
```
