### ISSUE TITLE
sam local start-api HttpApi endpoints not returning Set-Cookie headers

### ISSUE THREAD

**Issue by hooverdc** [aws/aws-sam-cli#3168]
### Description:

When using the SAM `start-api` command, events using the HttpApi ( format 2.0) integration will not return Set-Cookie headers. Events using the format 1.0 will send the Set-Cookie headers.

### Steps to reproduce:

Using the example Python3.8 container image setup for the SAM CLI.

```python
def lambda_handler(event, context):

    return {
        "statusCode": "200",
        "cookies": [
            "mycookie=mycookie; Path=/"
        ],
        "headers": {
            "Content-Type": "text/html; charset=UTF-8",
        },
        "body": "OK"
    }
```
```yaml
 AppFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      PackageType: Image
      Events:
        RootPathV2:
          Type: HttpApi
          Properties:
            Path: /v2/
            Method: ANY
```

1. Run `sam local start-api`
2. Get `http://127.0.0.1:3000/v2/` endpoint

### Observed result:

Did not send Set-Cookie headers.

### Expected result:

Send Set-Cookie headers

### Additional environment details (Ex: Windows, Mac, Amazon Linux etc)

1. OS: MacOs
2. `sam --version`: `SAM CLI, version 1.27.2`
3. AWS region: N/A

`Add --debug flag to command you are running`
