### ISSUE TITLE
GetAtt ARN on SimpleTable returns bogus ARN

### ISSUE THREAD

**Issue by jasonmk** [aws/aws-sam-cli#3175]
### Description:
When creating a SimpleTable resource in a sam template, GetAtt TableResource.ARN returns an invalid ARN.

### Steps to reproduce:
```yaml
  # resource in template.yaml
  TableResource:
    Type: AWS::Serverless::SimpleTable
    Properties:
      PrimaryKey: 
        Name: id
        Type: String
      TableName: example-table
```

### Observed result:
Calling `!GetAtt TableResource.ARN` returns `arn:aws:lambda:us-east-1:123456789012:function:TableResource`.

Note that the ARN literally contains the account ID 123456789012.  That is NOT a placeholder for this example.

### Expected result:
Expect it to return something like `arn:aws:dynamodb:us-east-1:xxxxxxxxxxxx:table/example-table`.

### Additional environment details (Ex: Windows, Mac, Amazon Linux etc)

1. OS: N/A
2. If using SAM CLI, `sam --version`: 1.27.2
3. AWS region: us-east-1

**Comment by jasonmk** [comment]
Update from more investigation, this appears to be something specifically related to sam local (which would explain why @jfuss moved the issue here).

I will also mention that !Ref TableResource returns TableResource under sam local but appears to return example-table when deployed for real.

**Comment by ssenchenko** [comment]
While we're looking into it you can consider using `Type: AWS::DynamoDB::Table` instead. It's an AWS Cloud Formation resource which is generated when you use `AWS::Serverless::SimpleTable`,  see [here](https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/sam-specification-generated-resources-simpletable.html) 
I requires more details which you can find in this [doc](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-dynamodb-table.html). 
Here is an example:
```yaml
TableResource:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
        - AttributeName: hk
          AttributeType: S
        - AttributeName: rk
          AttributeType: S
      KeySchema:
        - AttributeName: hk
          KeyType: HASH
        - AttributeName: rk
          KeyType: RANGE
      BillingMode: PAY_PER_REQUEST
```
I don't know your use case for ARN specifically but in many cases using `!Ref` can be sufficient. For example
Somewhere in `template.yml`
```yaml
MyLambdaFunction:
    Type: AWS::Serverless::Function
    Properties:
      ...
      Policies:
        DynamoDBCrudPolicy:
          TableName: !Ref TableResource
      Environment:
        Variables:
          APP_TABLE: !Ref TableResource
```
Or add to globals
```yaml
Globals:
  Function:
    Environment:
      Variables:
        APP_TABLE: !Ref TableResource
```
And then in Lambda
```python
TABLE = boto3.resource("dynamodb").Table(os.getenv("APP_TABLE"))
```
