### ISSUE TITLE
sam build scans the entire template and builds both "AWS::Serverless::Function" and "AWS::Lambda::Function"

### ISSUE THREAD

**Issue by nagmesh** [aws/aws-sam-cli#3188]
### Description:

I would like sam to only package and build `AWS::Serverless::Function` but I see that it tries to build `AWS::Lambda::Function` in side my template as well

### Steps to reproduce:

```
AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Parameters:
  RuntimeRole:
    Type: String
    Description: Runtime role for Lambda functions
  RuntimeUri:
    Type: String
    Description: ECR URI for Lambda Function


Resources:
  HelloWorldFunction:
    Type: AWS::Serverless::Function
    Properties:
      Role: !Ref RuntimeRole
      CodeUri: functions/hello-world
      Handler: main.lambda_handler
      Runtime: python3.7
  StandAloneFunction:
    Type: AWS::Lambda::Function
    Properties:
      Role: !Ref RuntimeRole
      Code:
        ImageUri: !Ref RuntimeUri
      Handler: main.lambda_handler
      Runtime: python3.7
      
```      

### Observed result:

The lambda function is treated as SAM serverless function and entire directory is copied over

### Expected result:

I expected `HelloWorldFunction` to get packaged but `StandAloneFunction` to be left alone

### Additional environment details (Ex: Windows, Mac, Amazon Linux etc)

1. OS: macOS 11.4
2. `sam --version`: SAM CLI, version 1.28.0
3. AWS region: us-gov-west-1

`Add --debug flag to command you are running`
