### ISSUE TITLE
Are Gradle Modules Supported?

### ISSUE THREAD

**Issue by oharaandrew314** [aws/aws-sam-cli#3227]
I want to package and deploy a specific gradle module in my repo.  The folder structure is roughly like:

```
core
|  build.gradle
server
|  build.gradle
lambdas
|  build.gradle
build.gradle
lambdas.yml
settings.gradle
gradlew
gradlew.bat
gradle
|  wrapper
```

My lambdas.yml is roughly like:

```
...

Resources:
  LambdaHandler:
    Type: AWS::Serverless::Function
    Properties:
      Runtime: java11
      CodeUri: .
      Handler: com.company.service.LambdaClass
      ...

...
```

But when I build with the SAM CLI: `sam build --template-file lambdas.yml` I get a deployment package containting only the top-level gradle dependencies, and none of my own code.

I have tried various different options, such as moving the SAM template to the `lambdas` module, changing the `CodeUri` in the SAM template, and adding `--base-dir lambdas` to the build command, but they all result in various error messages about how it can't find the gradle wrapper.

Is there any way to easily support a multi-module gradle project?  I can't just add the gradle wrapper to the `lambdas` dir, because then it's no longer multi-module.

**Comment by oharaandrew314** [comment]
So the architecture you're describing sounds like it would have a self-contained gradle project and wrapper in each folder.  I was hoping to have a single multi-module gradle project, where there's a gradle wrapper at the repo's root, and multiple gradle modules within.  The modules would be like:

- `root`: common gradle configurations for the modules; no code
- `core`: data classes for request/response models
- `server`: traditional server exposing a REST API, with heavy-duty dependencies
- `lambdas`: listens for async messages and passes them to the server via REST, with light-weight dependencies

I wanted to do this in a multi-module fashion to share the `core` code into my lambda without inheriting the heavy dependencies of `server`.  I wanted SAM to deploy the artifact generated by the `lambdas` module, but it would only deploy the `root` module, which was empty; I couldn't just make `lambdas` its own self-contained gradle project with its own wrapper, because it wouldn't be able to share code with `core`.

Having said all this, I was able to bypass the issue by making my `lambdas` module into its own self-contained gradle project in its own repo; I duplicated the code I wanted to share from `core`.  I'm not saying the architecture I was hoping for is a very common or important one to support, but hopefully I've explained it well enough for you to see why someone might want to do it that way.  I understand if you don't think it's important enough to support, but if there's a simple workaround I could have used to make it work, then great.

**Comment by awood45** [comment]
Totally understood, I'm just not a Gradle expert personally so wanted to understand what you were going for in more detail.

It does sound like a variation of vendoring a dependency. For example, if you were able to depend on the code within `core` as a dependency package for `server` and `lambdas` cleanly, does that get you to the same goal of reducing code duplication?

**Comment by oharaandrew314** [comment]
Yeah, that would get me what I was hoping for.

**Comment by salvianreynaldi** [comment]
So I've used this workaround for a while

template.yaml
```yaml
  FunctionA:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: java-gradle
    Metadata:
      BuildMethod: makefile
  FunctionB:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: java-gradle
    Metadata:
      BuildMethod: makefile
```

MakeFile
```Makefile
build-FunctionA:
    ./gradlew :func-a:build
build-FunctionB:
    ./gradlew :func-b:build
```

Sadly, sam build cache doesn't work if 2+ functions share a CodeUri (https://github.com/aws/aws-sam-cli/issues/3099#issuecomment-1024581685). Hopefully SAM adds proper support for gradle multi project builds, with working build cache 👍
