### ISSUE TITLE
SAM Template multiple functions being deployed, even without code changes (PackageType: Image)

### ISSUE THREAD

**Issue by ygorth** [aws/aws-sam-cli#3236]
### Description:

SAM model with two or more functions. Always deploying all functions, including those that don't have any code modifications.

### Steps to reproduce:

- SAM template that has two more functions 
- PackageType: Image 
-  Different docker contexts and docker tags per function => DockerContext: ./folder_function1 and DockerContext: ./folder_function1
- Modified code only for the lambda inside of /folder_function1.
- Both get the modified status during deployment:
484 | -------------------------------------------------------------------------------------------------
485 | Operation                LogicalResourceId        ResourceType             Replacement
486 | -------------------------------------------------------------------------------------------------
487 | * Modify                 Function1                AWS::Lambda::Function    False
488 | * Modify                 Function2                AWS::Lambda::Function    False
489 | -------------------------------------------------------------------------------------------------

### Expected result:

If you update the code ONLY for Function1 the changeset should not have a modified status for Function2.

### Additional environment details (Ex: Windows, Mac, Amazon Linux etc)

1. `sam --version`:
SAM CLI, version 1.29.0

`Add --debug flag to command you are running`

**Comment by awood45** [comment]
Can you give an example template where you're seeing this issue? Also, what runtime are you using, and what dependencies do those functions have?

**Comment by ygorth** [comment]
Hi @awood45 apologies for the delayed response.

git clone --depth 1 --branch MY_BRANCH MY_URL
CodeBuildRuntimeVersion: 'docker: 19'

Templates:
```
  Function1:
    Type: AWS::Serverless::Function
    Properties:
      PackageType: Image
      FunctionName:
        Ref: Function1Name
...
      ImageUri: XXX.dkr.ecr.us-east-1.amazonaws.com/spn-int-ecr-lam-snstats-fun-ftppublisher:function1-2d7f1821e3ae-ftppublisher-go1.14.x
    Metadata:
      DockerTag:
        Ref: ftppublisher-go1.14.x
      DockerContext:
        Ref: 	./functions/ftp-publisher
      Dockerfile:
        Ref: Dockerfile.NPE

  Function2:
    Type: AWS::Serverless::Function
    Properties:
      PackageType: Image
      FunctionName:
...
      ImageUri: XXX.dkr.ecr.us-east-1.amazonaws.com/spn-int-ecr-lam-snstats-fun-scapfriendly:function2-58bcddbc8c1f-scapfriendly-go1.14.x
    Metadata:
      DockerTag:
        Ref: scapfriendly-go1.14.x
      DockerContext:
        Ref: ./functions/scheduled/capfriendly
      Dockerfile:
        Ref: Dockerfile.NPE
```

Function 1 (go.mod):
```
module github.com/f1/ftp-publisher

go 1.14

require (
	github.com/aws/aws-lambda-go v1.20.0
	github.com/aws/aws-sdk-go v1.36.2
	github.com/newrelic/go-agent/v3 v3.13.0
	github.com/newrelic/go-agent/v3/integrations/nrlambda v1.2.0
	github.com/streadway/amqp v1.0.0
)
```

Function 2 (go.mod):
```
module github.com/f2/capfriendly

go 1.14
require (
	 github.com/streadway/amqp v1.0.0
	 github.com/aws/aws-lambda-go v1.20.0
     github.com/aws/aws-sdk-go v1.36.2
     github.com/newrelic/go-agent/v3 v3.13.0
     github.com/newrelic/go-agent/v3/integrations/nrlambda v1.2.0
)
```
