### ISSUE TITLE
StageName only works with hard-coded value

### ISSUE THREAD

**Issue by specious** [aws/aws-sam-cli#3247]
Defining an `AWS::Serverless::API` resource with a dynamically constructed `StageName` produces a  resource instance as if the StageName is empty.

If the `StageName` value is hard-coded, the result is as expected:

```yaml
Resources:
  API:
    Type: AWS::Serverless::Api
    Properties:
      StageName: dev
      Auth:
        Authorizers: []
``` 

Deployment produces a `AWS::ApiGateway::Stage` resource with logical resource id `APIdevStage`.

If the `StageName` property value is changed to a dynamic reference like `!Ref <parameter>` or `!Join ...` or `!Sub "..."`, then the change set generated has the resource logical id as `APIStage` rather than `API<StageName>Stage`.

For example, making a change to the template like this:

```diff
 Resources:
   API:
     Type: AWS::Serverless::Api
     Properties:
-      StageName: dev
+      StageName: !Join [ "-", ["custom", "stagename"] ]
       Auth:
         Authorizers: []
``` 

Produces a deployment changeset like:

```
Initiating deployment
=====================
Uploading to myapp-backend/70b7c6f9a46ab95003c219b6ead729e9.template  8056 / 8056  (100.00%)

Waiting for changeset to be created..

CloudFormation stack changeset
-------------------------------------------------------------------------------------------------------------
Operation                   LogicalResourceId           ResourceType                Replacement               
-------------------------------------------------------------------------------------------------------------
+ Add                       APIDeployment8310cb78c0     AWS::ApiGateway::Deployme   N/A                       
                                                        nt                                                    
+ Add                       APIStage                    AWS::ApiGateway::Stage      N/A                                                                               
* Modify                    API                         AWS::ApiGateway::RestApi    False                     
- Delete                    APIDeploymentab53ec644d     AWS::ApiGateway::Deployme   N/A                       
                                                        nt                                                    
- Delete                    APIdevStage                 AWS::ApiGateway::Stage      N/A                                                                              
-------------------------------------------------------------------------------------------------------------

Changeset created successfully. arn:aws:cloudformation:us-east-1:999999999999:changeSet/samcli-deploy1630975525/3d58e01a-a563-452c-a5f2-df297c3026d0


Previewing CloudFormation changeset before deployment
======================================================
Deploy this changeset? [y/N]:
```

Tested with various SAM versions, including latest from git:

```
$ sam --version
SAM CLI, version 1.30.0
```

Platform: Arch Linux

**Comment by specious** [comment]
The use case I ran into this with is wanting to set the stage name based on a parameter value:

```yaml
Resources:

  API:
    Type: AWS::Serverless::Api
    Properties:
      Name: myapp-api
      StageName: !Ref DeploymentStage
      Auth:
        Authorizers: []

Parameters:
  DeploymentStage:
    Description: Deployment stage
    Type: String
    Default: dev
```

The parameter in general is set and works correctly in other contexts such as:

```yaml
Resources:

  MyDB:
    Type: AWS::RDS::DBInstance
    Properties:
      DBInstanceIdentifier: !Sub "${DBName}-${DeploymentStage}"
```
