### ISSUE TITLE
sam-beta-cdk cannot pass environment variables

### ISSUE THREAD

**Issue by s-dschro** [aws/aws-sam-cli#3276]
Assume you have a cdk script like:

```js
const table = new dynamodb.Table(scope, 'table', {
  partitionKey: {
    type: dynamodb.AttributeType.STRING,
    name: 'id',
  },
  billingMode: dynamodb.BillingMode.PAY_PER_REQUEST,
  tableName: 'table',
});

const func = lambda.Function(scope, `func`, {
  runtime: lambda.Runtime.NODEJS_14_X,
  handler: index.handler,
  code: lambda.AssetCode.fromAsset(assetPath),
  environment: {
    TABLE_NAME: table.name
  },
});
```

a call of `sam-beta-cdk local start-api ...` and the corresponding http endpoint, sam throws a `ResourceNotFoundException`, even if the table (or the whole cdk-stack) was already deployed to AWS in advance. Why is sam not able to pass those environment variables to my local lambda function?

**Comment by hoffa** [comment]
Thanks for raising this.

Full reproduction for posterity:

```bash
sam init --name sam-app --package-type Image --base-image amazon/nodejs14.x-base
```

And replace `lib/aws-sam-cli-cdk-hello-world-stack.js` with:

```js
const cdk = require("@aws-cdk/core");
const lambda = require("@aws-cdk/aws-lambda");
const dynamodb = require("@aws-cdk/aws-dynamodb");
const path = require("path");

class AwsSamCliCdkHelloWorldStack extends cdk.Stack {
  constructor(scope, id, props) {
    super(scope, id, props);

    const table = new dynamodb.Table(this, "table", {
      partitionKey: {
        type: dynamodb.AttributeType.STRING,
        name: "id",
      },
    });

    const func = new lambda.Function(this, "func", {
      runtime: lambda.Runtime.NODEJS_14_X,
      handler: 'app.lambdaHandler',
      code: lambda.Code.fromAsset(path.join(__dirname, '..', 'hello-world')),
      environment: {
        TABLE_NAME: table.name,
        FOO: "bar",
      },
    });
  }
}

module.exports = { AwsSamCliCdkHelloWorldStack };
```

**Comment by hawflau** [comment]
`name` doesn't seem to be a right attribute of the `Table` class. Instead, it should be `tableName` ([CDK docs](https://docs.aws.amazon.com/cdk/api/latest/docs/@aws-cdk_aws-dynamodb.Table.html#tablename))

If you change it to `table.tableName` for the Lambda env var, and run `cdk synth`, you'll see the Lambda env var `TABLE_NAME` being populated correctly:
```yaml
funcC3A0C2E2:
    Type: AWS::Lambda::Function
    Properties:
      Code:
        S3Bucket:
          Ref: AssetParameters93f10cacaa705b67b2eb0461409d5c585c67dfe059884e37d918164508e208a6S3Bucket0D72FC8F
        S3Key:
          Fn::Join:
            - ""
            - - Fn::Select:
                  - 0
                  - Fn::Split:
                      - "||"
                      - Ref: AssetParameters93f10cacaa705b67b2eb0461409d5c585c67dfe059884e37d918164508e208a6S3VersionKey8C53F873
              - Fn::Select:
                  - 1
                  - Fn::Split:
                      - "||"
                      - Ref: AssetParameters93f10cacaa705b67b2eb0461409d5c585c67dfe059884e37d918164508e208a6S3VersionKey8C53F873
      Role:
        Fn::GetAtt:
          - funcServiceRoleA96CCB44
          - Arn
      Environment:
        Variables:
          TABLE_NAME:
            Ref: table8235A42E
          FOO: bar
      Handler: app.lambdaHandler
      Runtime: nodejs14.x
    DependsOn:
      - funcServiceRoleA96CCB44
    Metadata:
      aws:cdk:path: CdkIssue3276Stack/func/Resource
      aws:asset:path: asset.93f10cacaa705b67b2eb0461409d5c585c67dfe059884e37d918164508e208a6
      aws:asset:property: Code
```

That being said, `sam-beta-cdk local invoke` won't be able to reach your DynamoDB Table even if you have the table created on AWS, because we do not have full Ref resolvers on every resource. To work around this, please consider the two options:

### Workaround 1 - use `--env-vars` option in your `local [invoke|start-api|start-lambda]` command.
See [here](https://github.com/aws/aws-sam-cli/issues/1604) for details.

### Workaround 2 - use `--cdk-context` option
This option requires you to update your function in the cdk script:
```javascript
const testTableName = this.node.tryGetContext('test_table_name');

const func = lambda.Function(scope, `func`, {
  runtime: lambda.Runtime.NODEJS_14_X,
  handler: index.handler,
  code: lambda.AssetCode.fromAsset(assetPath),
  environment: {
    TABLE_NAME: testTableName ? testTableName : table.tableName 
  },
});
```
Then you can run the command like this - `sam-beta-cdk local invoke --cdk-context test_table_name=MyTableName`
