### ISSUE TITLE
SAM CLI 1.33 Cannot Resolve ECR Container Images (Gets 404)

### ISSUE THREAD

**Issue by curtis-trynow-io** [aws/aws-sam-cli#3329]
### Description:

After upgrading from 1.32 to 1.33 both locally and in CI/CD pipelines, our `sam build --use-container` processes are failing with:

```
samcli.local.docker.manager.DockerImagePullFailedException: Could not find public.ecr.aws/sam/build-python3.8:latest-x86_64 image locally and failed to pull it from docker.
```

Indeed, this image does not exist, and I suspect it is because of the architecture suffix `-x86_64` which previously was not used.  If you use just `latest`, it is fine, but adding that results in nothing being found.

### Steps to reproduce:

Make a new directory, add a template file with:

```
AWSTemplateFormatVersion: 2010-09-09
Transform:
  - AWS::Serverless-2016-10-31
Resources:
  someFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./src
      Handler: handler.handler
      MemorySize: 128
      Runtime: python3.8
      Timeout: 5
```

and run `sam build --use-container`.  I doubt you even need `CoreUri` but rushing to get this submitted.  It really just needs to be something to pull the Python build image.

### Observed result:

https://pastebin.com/raw/vPFNxjiD

I don't think you need debug output for this one.  The image does not exist.  You can try pulling it with a plain:

```
docker pull public.ecr.aws/sam/build-python3.8:latest-x86_64
```

### Expected result:

The image exists and can be pulled.

### Additional environment details (Ex: Windows, Mac, Amazon Linux etc)

1. OS: macOS but also happens in Linux docker-in-docker containers
2. `sam --version`: 1.33
3. AWS region: not specific

`Add --debug flag to command you are running`
