### ISSUE TITLE
Way to specify build arguments for go, such as -ldflags

### ISSUE THREAD

**Issue by aubelsb2** [aws/aws-sam-cli#3419]
### Describe your idea/feature/enhancement

Often when debugging I want to know what version and commit I'm looking at in the logs, or presented by the API. One way of doing this is to embed the details from the envirnoment into the application, ie passing these as ldflags

    // -X main.version=${Version} -X main.commit=${Commit} -X main.date=${CommitDate}

Will allow you to access the values from inside the application.

### Proposal

I propose extending the "Metadata" componet to include "BuilderArgs" or something along those lines, which would be added to the builder. Then the values can be routed into sam in the usual ways. ie:

```

Resources:
  function1:
    Type: AWS::Serverless::Function
    Properties:
      Handler: handler
      CodeUri: lambda
      Runtime: go1.x
    Metadata:
      BuilderArgs: !Sub "-ldflags \"-X main.version=${Version} -X main.commit=${Commit} -X main.date=${CommitDate}\""
```
