### ISSUE TITLE
Hot reloading not working for go lambdas?

### ISSUE THREAD

**Issue by uccmen** [aws/aws-sam-cli#353]
Is it just me or hot-reloading doesn't work for lambdas written in golang?

cmd
```
aws-sam-local local start-api
```
hello/main.go
```go
package main

import (
	"github.com/aws/aws-lambda-go/events"
	"github.com/aws/aws-lambda-go/lambda"
)

type Response struct {
	Message string `json:"message"`
}

func Handler(request events.APIGatewayProxyRequest) (events.APIGatewayProxyResponse, error) {
	return events.APIGatewayProxyResponse{
		Body:       "Go Serverless v1.0! Your function executed successfully!",
		StatusCode: 200,
	}, nil
}
func main() {
	lambda.Start(Handler)
}
```

template.yml
```yaml
AWSTemplateFormatVersion : '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: A hello world application.
Resources:
  HelloFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: bin/hello
      Runtime: go1.x
      Events:
        Vote:
          Type: Api
          Properties:
            Path: /hello
            Method: get
```
