### ISSUE TITLE
sam build not use correct path for the deploy

### ISSUE THREAD

**Issue by giammbo** [aws/aws-sam-cli#3536]
### Description:
During the ```sam build```, by default all files (lambda and layer) are stored/builded inside the ```.aws-sam``` directory. Unfortunately during the ```sam deploy``` the files inside the ```.aws-sam```  are not used for the deploy.

### Steps to reproduce:
./template.yaml
```  LambdaLayer:
    Type: AWS::Serverless::LayerVersion
    UpdateReplacePolicy: Retain
    DeletionPolicy: Retain
    Properties:
      CompatibleRuntimes: [python3.8]
      ContentUri: dependencies/
      Description: The Lambda Layer
      LayerName: Lambda-Layer
      RetentionPolicy: Delete
    Metadata:
      BuildMethod: python3.8

  LambdaFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/
      Description: Lambda Function
      FunctionName: Lambda-function
      Tracing: Active
      Layers:
        - !Ref LambdaLayer
   ```

./samconfig.toml
```version=0.1

[default.global.parameters]
s3_bucket = "bucket-s3"
s3_prefix = "exp/lambda-function"
capabilities = "CAPABILITY_NAMED_IAM CAPABILITY_AUTO_EXPAND"
stack_name = "lambda-function"
tags = "CloudFormed=true Project=lambda-function"
parameter_overrides = "Name=lambda-function CWLogsRetention=3"
region = "eu-west-1"

[dev.global.parameters]
s3_bucket = "bucket-s3"
s3_prefix = "dev/lambda-function"
capabilities = "CAPABILITY_NAMED_IAM CAPABILITY_AUTO_EXPAND"
stack_name = "lambda-function"
tags = "CloudFormed=true Project=lambda-function"
parameter_overrides = "Name=lambda-function CWLogsRetention=3"
```

./dependencies/requirements.txt
```
pandas
```

Project tree

```.
├── README.md
├── dependencies
│   └── requirements.txt
├── samconfig.toml
├── src
│   └── lambda_function.py
└── template.yaml
```

1) Run ```sam build``` inside the directory and you will have builded files inside the ```.aws-sam``` :

```
.├── .aws-sam
│   ├── build
│   │   ├── LambdaFunction
│   │   │   ├── lambda_function.py
│   │   │   └── utils.py
│   │   ├── LambdaLayer
│   │   │   └── python
│   │   └── template.yaml
│   ├── build.toml
│   └── deps
│       ├── 3a42abe5-8a10-46dd-9267-b4a07e3c1413
│       │   ├── pandas
│       │   ├── pandas-1.2.5.dist-info
│       │   ├── six-1.16.0.dist-info
│       │   ├── six.py
│       │   └── sqlalchemy
│       └── f016c04e-83ab-4230-bd27-7c812da43ad9
│           ├── pandas
│           ├── pandas-1.2.5.dist-info
│           ├── psycopg2
│           ├── six-1.16.0.dist-info
│           ├── six.py
│           └── sqlalchemy
├── README.md
├── dependencies
│   └── requirements.txt
├── samconfig.toml
├── src
│   └── lambda_function.py
└── template.yaml
```
2) Run ```sam deploy```. 
3) Download from the CLI or the AWS console the zip with the content of you Layer
4) Unzip and you will have only the ```requirements.txt```inside the dependencies folder

### Expected result:
The Expected result is to have the Layer version deployed from the .aws-sam directory and not from the source directory

### Additional environment details (Ex: Windows, Mac, Amazon Linux etc)

1. OS: Macos 11.8.1, i have also tryed Ubuntu 20.04
2. `sam --version`: SAM CLI, version 1.36.0
3. AWS region: eu-west-1

**Comment by maslick** [comment]
why have you closed the issue? I am experiencing the same behavior.

**Comment by giammbo** [comment]
@maslick  try to run `sam package` before `sam deploy`. This fix for me

**Comment by maslick** [comment]
@giammbo I thought `sam package` already gets invoked by `sam deploy`. In other words sam package is sort of deprecated. Proof: https://stackoverflow.com/a/63061658/2996867

**Comment by giammbo** [comment]
@maslick yes i know, but unfortunately the only working way for me is to run sam package before the deploy. Could you try?, if the sam package fix your problem i will reopen the issue.

**Comment by maslick** [comment]
`sam package` didn't work for me. neither `sam package` nor `sam deploy` pushes my Layer to s3, just the `requirements.txt` file.

```
aws --version
aws-cli/1.22.28 Python/3.9.7 Linux/5.10.75-flatcar botocore/1.23.28
```

```
sam --version
SAM CLI, version 1.36.0
```

**Comment by giammbo** [comment]
@maslick this is my configuration, maybe can help you:

template.yaml:
``` yaml
---
AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'

Parameters:

  CWLogsRetention:
    AllowedValues: [1, 3, 5, 7, 14, 30, 60, 90, 120, 150, 180, 365, 400, 545, 731, 1827, 3653]
    Type: Number

  Namespace:
    Type: String

  ProjectName:
    Description: 'Insert the project name'
    Type: String

Globals:
  Function:
    Handler: lambda_function.lambda_handler
    MemorySize: 128
    Runtime: python3.8
    Timeout: 30

Resources:

  LambdaFunctionLogGroup:
    UpdateReplacePolicy: Delete
    DeletionPolicy: Delete
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub '/aws/lambda/${LambdaFunction}'
      RetentionInDays: !Ref CWLogsRetention

  LambdaLayer:
    Type: AWS::Serverless::LayerVersion
    UpdateReplacePolicy: Retain
    DeletionPolicy: Retain
    Properties:
      CompatibleRuntimes: [python3.8]
      ContentUri: dependencies/
      Description: !Sub 'The Lambda Layer ${ProjectName}'
      LayerName: !Sub '${Namespace}-${ProjectName}'
      RetentionPolicy: Delete
    Metadata:
      BuildMethod: python3.8

  LambdaFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/
      Description: !Sub '${Namespace}-${ProjectName}'
      FunctionName: !Sub '${Namespace}-${ProjectName}'
      Tracing: Active
      Layers:
        - !Ref LambdaLayer
      Role: !GetAtt LambdaRole.Arn

  LambdaRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: 'Allow'
            Principal:
              Service:
                - 'lambda.amazonaws.com'
            Action:
              - 'sts:AssumeRole'
      ManagedPolicyArns:
        - 'arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole'
      RoleName: !Sub '${Namespace}-${ProjectName}-lambda'
```
samconfig.toml
```
version=0.1

[default.global.parameters]
s3_bucket = "sam.deploys"
s3_prefix = "exp/project_1"
capabilities = "CAPABILITY_NAMED_IAM CAPABILITY_AUTO_EXPAND"
stack_name = "project_1"
tags = "CloudFormed=true Environment=experiments Project=project_1"
parameter_overrides = "Namespace=company ProjectName=project_1 CWLogsRetention=3"
region = "eu-west-1"

[dev.global.parameters]
s3_bucket = "sam.deploys"
s3_prefix = "dev/project_1"
capabilities = "CAPABILITY_NAMED_IAM CAPABILITY_AUTO_EXPAND"
stack_name = "project_1"
tags = "CloudFormed=true Environment=development Project=project_1"
parameter_overrides = "Namespace=company ProjectName=project_1 CWLogsRetention=3"
region = "eu-west-1"
```
tree from root folder:
```
.
├── .cfnlintrc.yaml
├── .gitignore
├── .gitlab-ci.yml
├── README.md
├── dependencies
│   └── requirements.txt
├── requirements-dev.txt
├── samconfig.toml
├── src
│   ├── lambda_function.py
│   └── utils.py
├── template.yaml
└── tests
    └── test.json
``` 

and when i deploy i just run:

sam build
sam package --config-env $ENVIRONMENT
sam deploy --config-env $ENVIRONMENT


FYI
sam --version
SAM CLI, version 1.36.0
