### ISSUE TITLE
sam local 1.37.0 fails to execute lambda function if aws:cdk:path metadata is set

### ISSUE THREAD

**Issue by spalladino** [aws/aws-sam-cli#3585]
### Description:

When invoking a function in a local api gateway started via `sam local`, if the function has a `aws:cdk:path` metadata entry set, then SAM fails to invoke it with a `ApiProposalCreate not found. Possible options in your template: ['ExternalApi']` (where `ApiProposalCreate` is the logical function name), even if it reports that the function was mounted while initializing with a `Mounting ApiProposalCreate at http://127.0.0.1:4010/proposals [POST]`.

We started seeing this error since we updated to SAM 1.37.0.

### Workaround:

Manually removing `aws:cdk:path` from the generated yaml template fixes the issue.

### Steps to reproduce:

- Set up a CDK stack that creates an `AWS::Serverless::Api` and a `AWS::Serverless::Function`
- Convert it to yaml using `cdk synth --versionReporting=false > stacks/external-api.yaml`
- Run it using `sam local start-api --template-file stacks/external-api.yaml`
- Invoke the function locally via curl

### Observed result:

The HTTP request fails with a 502, and the sam log shows:

```
[local:external-api] 2022-01-14 11:19:30,065 | Constructed String representation of Event to invoke Lambda. Event: {...}
[local:external-api] 2022-01-14 11:19:30,065 | ApiProposalCreate not found. Possible options in your template: ['ExternalApi']
```

### Expected result:

The function is invoked successfully, as it happened up until 1.36.0.

### Additional environment details (Ex: Windows, Mac, Amazon Linux etc)

1. OS: Ubuntu 20.04
2. `sam --version`: 1.37.0
3. AWS region: local

### Template being used

```yaml
Transform:
  - AWS::Serverless-2016-10-31
Resources:
  ExternalApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName:
        Ref: Stage
      MethodSettings:
        - ResourcePath: /*
          LoggingLevel: INFO
          DataTraceEnabled: true
          HttpMethod: "*"
      Name:
        Fn::Sub: ${AWS::StackName}-external-api
      TracingEnabled: true
    Metadata:
      aws:cdk:path: ExternalApi/ExternalApi
  ApiProposalCreate:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ../api/build/proposalApi
      Handler: index.createHandler
      Runtime: nodejs12.x
      Events:
        Handler:
          Properties:
            Method: POST
            Path: /proposals
            RestApiId:
              Ref: ExternalApi
          Type: Api
      FunctionName:
        Fn::Sub: ${AWS::StackName}-api-proposal-create
      MemorySize: 512
      Timeout: 20
    Metadata:
      aws:cdk:path: ExternalApi/ApiProposalCreate
```
