### ISSUE TITLE
AutoPublishAlias not updating version on code change

### ISSUE THREAD

**Issue by ahurlburt** [aws/aws-sam-cli#3684]
I started adding AutoPublishAlias into several function definitions in my sam template so I could make use of provisioned concurrency.

I am seeing some strange behaviour where now updates to the code and redeployment is not resulting in a new update of a version.

Here are some screenshots showing the lambda (when the code was updated) and the version (when it was updated)

![image](https://user-images.githubusercontent.com/16481642/155244786-8c8f4c40-2edf-45de-8899-e258d2110f63.png)

![image](https://user-images.githubusercontent.com/16481642/155244798-58f3e5df-389f-443b-8875-c2272d935fc4.png)

Here is relevant snippet from template:

```
    Properties:
      CodeUri: XXX/
      Handler: yyy.zzz
      Tracing: Active
      Layers:
        - !Ref DependencyLayer
      Runtime: python3.8
      FunctionName: !Sub ${StageEnvironment}_rest_order_handler_1
      AutoPublishAlias: Live
      ProvisionedConcurrencyConfig:
        !If [ProdDeployment, ProvisionedConcurrentExecutions: 1, !Ref AWS::NoValue]
```

Am i missing something? Do i need to do something to ensure there are updates to the version on deploy?

**Comment by CoshUS** [comment]
Hey @ahurlburt,
Can you provide the output of running sam with --debug flag?

**Comment by erashdan** [comment]
+1

**Comment by smathez** [comment]
I'm facing the same problem, with lambda code packaged as zip files stored on an S3 bucket.
For greater readability of our templates, the versions are defined in Mappings, and we refer to them using the FindInMap function.

Example of template:


```
AWSTemplateFormatVersion: '2010-09-09'
Transform:
    - AWS::Serverless-2016-10-31
Description: XXX
Mappings:
    Lambdas:
        authorizer:
            package: ecs-commons-lambda-authorizer-1.3.0
        mpf:
            package: ecs-mpf-lambda-1.2.4
...
Globals:
    Function:
        Runtime: nodejs18.x
        AutoPublishAlias: live
        Tracing: Active
        CodeUri:
            Bucket: !Ref lambdaS3Bucket
...
    MpfTriggerFunction:
        Type: AWS::Serverless::Function
        Properties:
            Handler: index.handler
            CodeUri:
                Key: !FindInMap [Lambdas, mpf, package]
            FunctionName: 'xxx-eventTrigger'
            Events:
                MpfEvent:
                    Type: EventBridgeRule
                    Properties:
                        EventBusName: eventBusXXX
                        Pattern:
                            detail-type:
                                - prefix: 'XXX/'
```

If I change the package in the mapping, lambda function is updated but not my alias/version, so the event rule is always pointing to the previous version :
```
-------------------------------------------------------------------------------------------------------------------------------------------------------------
Operation                               LogicalResourceId                       ResourceType                            Replacement                           
-------------------------------------------------------------------------------------------------------------------------------------------------------------
* Modify                                MpfTriggerFunctionRole                  AWS::IAM::Role                          False                                 
* Modify                                MpfTriggerFunction                      AWS::Lambda::Function                   False                                 
-------------------------------------------------------------------------------------------------------------------------------------------------------------
```

But if I don't use the mapping anymore and update the `CodeUri.Key `part like that, everything is working fine : 
```
    MpfTriggerFunction:
        Type: AWS::Serverless::Function
        Properties:
            Handler: index.handler
            CodeUri:
                Key: !FindInMap [Lambdas, mpf, package]
```

```
CloudFormation stack changeset
-------------------------------------------------------------------------------------------------------------------------------------------------------------
Operation                               LogicalResourceId                       ResourceType                            Replacement                           
-------------------------------------------------------------------------------------------------------------------------------------------------------------
+ Add                                   MpfTriggerFunctionVersione5e43cd2e8     AWS::Lambda::Version                    N/A                                   
* Modify                                MpfTriggerFunctionAliaslive             AWS::Lambda::Alias                      False                                 
* Modify                                MpfTriggerFunction                      AWS::Lambda::Function                   False                                 
- Delete                                MpfTriggerFunctionVersion5a618a3a55     AWS::Lambda::Version                    N/A                                   
-------------------------------------------------------------------------------------------------------------------------------------------------------------
```

_SAM CLI, version 1.101.0 on linux, region eu-west-1_
