### ISSUE TITLE
HttpApiCorsConfiguration AllowOrigins does not support multiple origins

### ISSUE THREAD

**Issue by dannymoscoso** [aws/aws-sam-cli#3719]
### Description:

Using AWS SAM locally AllowOrigins does not work as expected, it concats the list and does not choose the correct origin

### Current Template:

```
  HttpApi:
    Type: AWS::Serverless::HttpApi
    Properties:
      CorsConfiguration:
        AllowOrigins:
          - "http://localhost:3000"
          - "http://localhost:3002"
        AllowHeaders:
          - "*"
        AllowMethods:
          - "*"
        MaxAge: 43200
        AllowCredentials: true
```

### Observed result:

![image](https://user-images.githubusercontent.com/24723683/157202795-cadb29e1-7f24-4d76-986d-419418ebae7e.png)

### Expected result:

API Gateway allows multiple origins, SAM local works differently

**Comment by NWBY** [comment]
Experiencing the same issues here. Chrome and other browsers require `Access-Control-Allow-Origin` to have a single value. If the browser receives a concatenated list such as: `http://localhost:3001,http://localhost:3002` it errors with
```
Access to fetch at 'http://127.0.0.1:3000/users' from origin 'http://localhost:3001' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: The 'Access-Control-Allow-Origin' header contains multiple values 'https://dropz.karbonx.app,http://localhost:3001', but only one is allowed. Have the server send the header with a valid value, or, if an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.
```

**Comment by jeffrey-anderson** [comment]
Not sure what more info you need. Works:
```
      CorsConfiguration:
        AllowOrigins:
          - http://localhost:3000
```
Does not work:
```
      CorsConfiguration:
        AllowOrigins:
          - http://localhost:3000
          - http:test.example.com
```
Recreating is easy, just put more than one origin in the SAM template then attempt to test locally.

**Comment by NWBY** [comment]
Any update on this issue? I'm still having to edit my `template.yaml` when working locally, then changing it back when deploying to production 😞

**Comment by alnaranjo** [comment]
Any update on this issue? Just experienced it today

**Comment by diegoddox** [comment]
I'm facing the same issue with the latest version of the cli

**Comment by imhwli** [comment]
I have similar issues using mapping. I got "Resource handler returned message: "Unable to parse the CORS configuration"

```
Mappings:
  mymap:
    urllinks:
      dev:
          - http://localhost:3000
          - http:test.example.com
``` 

```
    Type: AWS::Serverless::HttpApi
     Properties:
        CorsConfiguration:
           AllowOrigins: !FindInMap [ mymap, urllinks, dev ]
```
