### ISSUE TITLE
When working with a nested SAM stack, I cannot import a Lambda Layer exported from another stack locally.

### ISSUE THREAD

**Issue by ahmednmourad** [aws/aws-sam-cli#3731]
### Description:

I have a nested SAM application, where layers are created in one template and attempted to be referenced in another template when running `sam local start-[api|lambda]` and invoking the function I still get "Cannot find module" error, So it does seem that sam doesn't try to build the layer locally when referenced from a nested stack.

### Steps to reproduce:

Here are my templates:

`layers.template.yml`
```
AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Resources:
  Mysql2Layer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      LayerName: mysql2
      ContentUri: lambda/layers/mysql2
      CompatibleRuntimes:
        - nodejs14.x
      RetentionPolicy: Retain
Outputs:
  Mysql2LayerARN:
    Description: ARN of the Shared Layer
    Value: !Ref Mysql2Layer
```

`template.yml`
```
AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Resources:
  Layer:
    Type: "AWS::Serverless::Application"
    Properties:
      Location: "./layers.template.yml"

  LambdaFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: lambda/functions/hello-world
      Handler: app.lambdaHandler
      Runtime: nodejs14.x
      Layers:
        - !GetAtt Layer.Outputs.Mysql2LayerARN
      Events:
        HelloWorld:
          Type: Api
          Properties:
            Path: /hello
            Method: get
```
Now run `sam local start-api` and invoke the lambda function

### Observed result:

Error: Cannot find module 'mysql2'

### Expected result:

Being able to import the layer from the nested stack while running locally.

### Output of `sam --version`
SAM CLI, version 1.36.0

`Add --debug flag to command you are running`
