### ISSUE TITLE
sam build and sam package don't support same CodeUris

### ISSUE THREAD

**Issue by chizou** [aws/aws-sam-cli#3760]
### Description:
`sam package` allows specifying individual files for the `CodeUri`, like so:
```
  TokenVerifier:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: token_verify.py
      Handler: token_verify.lambda_handler
      Runtime: python3.7
      Timeout: 60
```

However, if I try to run `sam build` on it, I get the following error:
```
Build Failed
Error: PythonPipBuilder:CopySource - [Errno 20] Not a directory: '/home/github/app/token_verify.py'
```

### Steps to reproduce:
run `sam build`

### Observed result:
I receive the error described above

### Expected result:
sam build completes

### Additional environment details (Ex: Windows, Mac, Amazon Linux etc)

1. OS: WSLv2
2. `sam --version`: SAM CLI, version 1.40.1
3. AWS region: ue-east-1
