### ISSUE TITLE
AWS SAM custom domain fails when using !Ref

### ISSUE THREAD

**Issue by mikeborozdin** [aws/aws-sam-cli#3778]
If I'm defining a custom domain as a standalone resource that I'm referencing with `!Ref` my deployment fails. But if I use the same details for a nested object it works. Any idea why?

> Custom Domains only works if both DomainName and CertificateArn are provided.

```
ApiDomain:
  Type: AWS::ApiGateway::DomainName
  Properties:
    DomainName: api.mydomain.com
    CertificateArn: "arn:aws:acm:blah-blah"
    Route53:
      HostedZoneName: "mydomain.com."

MyApi:
  Type: AWS::Serverless::Api
  Properties:
    StageName: Prod
    Cors: "'*'"
    Domain: !Ref ApiDomain
```

But if I nested the domain object - it magically works:

```
MyApi:
  Type: AWS::Serverless::Api
  Properties:
    StageName: Prod
    Cors: "'*'"
    Domain:
      DomainName: api.mydomain.com
      CertificateArn: "arn:aws:acm:blah-blah"
      Route53:
        HostedZoneName: "mydomain.com."
```

### Additional environment details (Ex: Windows, Mac, Amazon Linux etc)

1. `sam --version`: `1.36.0`
2. AWS region: `eu-west-1`
