### ISSUE TITLE
Layers exceeds the maximum allowed size but size is in limits

### ISSUE THREAD

**Issue by ldaume** [aws/aws-sam-cli#3784]
### Description:
I have staging and prod AWS environments. I started to use layers for my node dependencies and everything is working well on staging. I finished some work and when I want to publish everything on prod the update fails with:
`Resource handler returned message: Function code combined with layers exceeds the maximum allowed size of 262144000 bytes. The actual size is 356068374 bytes.`

But this size doesn't make sense because if I publish everything without layers, **the size is 24.3 MB**. The downloaded layer size on staging is 23.6 MB (zip) and 175.2 MB (unzipped folder).

Size on prod
![grafik](https://user-images.githubusercontent.com/6170434/129877799-556f7984-2af2-45ec-b8cd-439e6dd1e7dd.png)

Size on staging
![grafik](https://user-images.githubusercontent.com/6170434/129878090-41b586f1-1754-4f8d-ab28-25c0b2586acc.png)

Layer size downloaded from AWS (staging)
![grafik](https://user-images.githubusercontent.com/6170434/129878172-45e7e524-3abf-4798-b682-cb519951ff0a.png)

### Steps to reproduce:

Just build and deploay with SAM using a template.yml.

template.yml
```yml
AWSTemplateFormatVersion: 2010-09-09

...

Transform:
  - AWS::Serverless-2016-10-31
 
Globals:
  Function:
    Runtime: nodejs14.x
    MemorySize: 256
    Timeout: 90
    Tracing: Active
    Layers:
      - !Ref NodeAppLayer
   ...

...

NodeAppLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      Description: Layer for this app
      ContentUri: dependencies/
      CompatibleRuntimes:
        - nodejs14.x
      RetentionPolicy: Delete
    Metadata:
      BuildMethod: nodejs14.x

...
```

### Observed result:
Resource handler returned message: Function code combined with layers exceeds the maximum allowed size of 262144000 bytes. The actual size is 356068374 bytes.

### Expected result:
Same behaviour on different AWS environments and correct file sizes.

### Additional environment details (Ex: Windows, Mac, Amazon Linux etc)
1. OS: Ubuntu Ubuntu 20.04.2 LTS (GNU/Linux 5.4.0-81-generic x86_64)
2. If using SAM CLI, `sam --version`: 1.28.0
3. AWS region: eu-central-1
