### ISSUE TITLE
sam local start-api gives CORS error when CORS are enabled

### ISSUE THREAD

**Issue by redhouse877** [aws/aws-sam-cli#3864]
### Description:
I am using AWS CDK (Typescript) and running SAM local start-api to spin up a RESTful API tied to lambda resolvers and am running into a CORS issue when trying to hit the API from a browser.

#### CDK config:

```
import { Construct } from 'constructs';
import {
  IResource,
  LambdaIntegration,
  MockIntegration,
  PassthroughBehavior,
  RestApi,
} from 'aws-cdk-lib/aws-apigateway';
import {
  NodejsFunction,
  NodejsFunctionProps,
} from 'aws-cdk-lib/aws-lambda-nodejs';
import { Runtime } from 'aws-cdk-lib/aws-lambda';

import { join } from 'path';
import * as lambda from 'aws-cdk-lib/aws-lambda';
import * as s3 from 'aws-cdk-lib/aws-s3';
import * as ec2 from 'aws-cdk-lib/aws-ec2';
import * as rds from 'aws-cdk-lib/aws-rds';
import * as cdk from 'aws-cdk-lib';

export function addCorsOptions(apiResource: IResource) {
  apiResource.addMethod(
    'OPTIONS',
    new MockIntegration({
      integrationResponses: [
        {
          statusCode: '200',
          responseParameters: {
            'method.response.header.Access-Control-Allow-Headers':
              "'Content-Type,X-Amz-Date,Authorization,X-Api-Key,X-Amz-Security-Token,X-Amz-User-Agent'",
            'method.response.header.Access-Control-Allow-Origin': "'*'",
            'method.response.header.Access-Control-Allow-Credentials':
              "'false'",
            'method.response.header.Access-Control-Allow-Methods':
              "'OPTIONS,GET,PUT,POST,DELETE'",
          },
        },
      ],
      passthroughBehavior: PassthroughBehavior.NEVER,
      requestTemplates: {
        'application/json': '{"statusCode": 200}',
      },
    }),
    {
      methodResponses: [
        {
          statusCode: '200',
          responseParameters: {
            'method.response.header.Access-Control-Allow-Headers': true,
            'method.response.header.Access-Control-Allow-Methods': true,
            'method.response.header.Access-Control-Allow-Credentials': true,
            'method.response.header.Access-Control-Allow-Origin': true,
          },
        },
      ],
    }
  );
}

export class FrontendService extends Construct {
  constructor(scope: Construct, id: string) {
    super(scope, id);

    const vpc = new ec2.Vpc(this, 'HospoFEVPC');
    const cluster = new rds.ServerlessCluster(this, 'AuroraHospoFECluster', {
      engine: rds.DatabaseClusterEngine.AURORA_POSTGRESQL,
      parameterGroup: rds.ParameterGroup.fromParameterGroupName(
        this,
        'ParameterGroup',
        'default.aurora-postgresql10'
      ),
      defaultDatabaseName: 'hospoFEDB',
      vpc,
      scaling: {
        autoPause: cdk.Duration.seconds(0),
      },
    });

    const bucket = new s3.Bucket(this, 'FrontendStore');

    const nodeJsFunctionProps: NodejsFunctionProps = {
      environment: {
        BUCKET: bucket.bucketName,
        CLUSTER_ARN: cluster.clusterArn,
        SECRET_ARN: cluster.secret?.secretArn || '',
        DB_NAME: 'hospoFEDB',
        AWS_NODEJS_CONNECTION_REUSE_ENABLED: '1',
      },
      runtime: Runtime.NODEJS_14_X,
    };

    const loginLambda = new NodejsFunction(this, 'loginFunction', {
      entry: 'dist/lambda/login.js',
      memorySize: 1024,
      ...nodeJsFunctionProps,
    });

    const loginIntegration = new LambdaIntegration(loginLambda);

    const api = new RestApi(this, 'frontend-api', {
      restApiName: 'Frontend Service',
      description: 'This service serves the frontend.',
    });

    const loginResource = api.root.addResource('login');
    loginResource.addMethod('POST', loginIntegration);
    addCorsOptions(loginResource);
  }
}
```

#### lambda resolver (login.js)

```
export async function handler(event: any, context: any) {
    return {
      statusCode: 200,
      headers: { 'Access-Control-Allow-Origin': '*' },
      body: JSON.stringify(body),
    };
}
```

### Observed result:
When running locally using `sam start local-api` I get a CORS error mentioning it does not pass preflight. This error only occurs locally, when the lambda is eployed to AWS I do not get any CORS errors

### Expected result:

With the `Access-Control-Allow-Origin` header set in the lambda response and mock integration for the options request I would expect it to not give me any CORS errors

### Additional environment details (Ex: Windows, Mac, Amazon Linux etc)

I am on SAM version 1.46.0 on the latest Ubuntu distribution. I have also tried configuring CORS via the CDK RestApi config like so:

```
new apigateway.RestApi(this, 'api', {
  defaultCorsPreflightOptions: {
    allowOrigins: apigateway.Cors.ALL_ORIGINS,
    allowMethods: apigateway.Cors.ALL_METHODS // this is also the default
  }
})
```

But it just gives me the following error:
![lIIl3](https://user-images.githubusercontent.com/51175884/167446138-0add5bce-4d78-47c7-ba20-53f5ac32535e.png)

**Comment by jfuss** [comment]
@redhouse877 Something is not wired up correctly for SAM CLI to work. The error given is "Function name is required" which has nothing to do with CORS. 

I looks like you have a mock integration setup for API Gateway? If my understanding is correct, that is not supported locally. SAM CLI supports proxy events [docs](https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/serverless-sam-cli-using-start-api.html). With mock events, there is no local function to call, which is why it is not supported.

**Comment by redhouse877** [comment]
@jfuss Apologies I have updated my example code in my initial post to map it to the `/login` path to make the screenshot clearer. 
You can see below the `/login` path maps to the loginIntegration which is just a regular node lambda

    const loginResource = api.root.addResource('login');
    loginResource.addMethod('POST', loginIntegration);

**Comment by redhouse877** [comment]
The way I understand it, the recommended method for enabling CORS is to use the following config when setting up a REST API:

```
new apigateway.RestApi(this, 'api', {
  defaultCorsPreflightOptions: {
    allowOrigins: apigateway.Cors.ALL_ORIGINS,
    allowMethods: apigateway.Cors.ALL_METHODS
  }
})
```

The above code when compiled to a `yaml` template file for SAM CLI to consume when spinning up a local API gives out this for the `OPTIONS` request that is generated automatically with all `POST` calls:

```
  FrontendfrontendapiloginOPTIONSDFA81F90:
    Type: AWS::ApiGateway::Method
    Properties:
      HttpMethod: OPTIONS
      ResourceId:
        Ref: FrontendfrontendapiloginE4E074CB
      RestApiId:
        Ref: FrontendfrontendapiD91ABA9E
      AuthorizationType: NONE
      Integration:
        IntegrationResponses:
          - ResponseParameters:
              method.response.header.Access-Control-Allow-Headers: "'Content-Type,X-Amz-Date,Authorization,X-Api-Key,X-Amz-Security-Token,X-Amz-User-Agent'"
              method.response.header.Access-Control-Allow-Origin: "'http://localhost:3000'"
              method.response.header.Vary: "'Origin'"
              method.response.header.Access-Control-Allow-Methods: "'OPTIONS,GET,PUT,POST,DELETE,PATCH,HEAD'"
              method.response.header.Access-Control-Allow-Credentials: "'true'"
            StatusCode: "204"
        RequestTemplates:
          application/json: "{ statusCode: 200 }"
        Type: MOCK
      MethodResponses:
        - ResponseParameters:
            method.response.header.Access-Control-Allow-Headers: true
            method.response.header.Access-Control-Allow-Origin: true
            method.response.header.Vary: true
            method.response.header.Access-Control-Allow-Methods: true
            method.response.header.Access-Control-Allow-Credentials: true
          StatusCode: "204"
    Metadata:
      aws:cdk:path: dev/Frontend/frontend-api/Default/login/OPTIONS/Resource
```

I see here that the `Type` is set to `MOCK` which you mention is unsupported by SAM CLI. Seeing as this is the recommended way of enabling CORS with the CDK, I am unsure how I am supposed to get `POST` endpoints running locally as they will surely always run into this CORS issue?
