### ISSUE TITLE
Bug: sam build --use-container doesn't correctly build golang containers

### ISSUE THREAD

**Issue by shearn89** [aws/aws-sam-cli#3894]
### Description:

Project layout:

```
Admin:~/environment/testGoFunction $ tree .
.
├── hello-world
│   ├── cmd
│   │   └── helloWorld
│   │       └── main.go
│   ├── go.mod
│   └── go.sum
└── template.yaml
```

Template:

```
AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Resources:
  HelloWorldFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: hello-world/cmd/helloWorld
      Handler: helloWorld
      Runtime: go1.x
      Architectures:
        - x86_64
```

main.go:

```
package main

import (
	"github.com/aws/aws-lambda-go/lambda"
)

func handler() (map[string]string, error) {
	return map[string]string{
		"status": "ok",
	}, nil
}

func main() {
	lambda.Start(handler)
}
```

Trying to build a simple golang lambda using the `package/cmd/binaryName/main.go` style of CLI programs.

Running `sam build` works fine and correctly builds the binary and finds it.

Running `sam build --use-container` complains it can't find `go.mod`.

Changing the CodeURI path to include the top level folder complains `no Go files in...`

### Steps to reproduce:

1. Create the structure detailed above.
2. Try sam build, check it works
3. Try sam build -u, see it fail

### Observed result:

As above

### Expected result:

`sam build -u` should work the same way `sam build` does.

Should the Go builder be running `go build ./...` to descend into subdirectories? Or does `--use-container` need to copy more files to the build container?

### Additional environment details (Ex: Windows, Mac, Amazon Linux etc)

1. OS: cloud9, Amazon Linux 2: 4.14.276-211.499.amzn2.x86_64 #1 SMP Wed Apr 27 21:08:48 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
4. `sam --version`: 1.33.0
5. AWS region: eu-west-2

`Add --debug flag to command you are running`

**Comment by shearn89** [comment]
Looks like you can work around it:

Add a Makefile in `hello-world`:

```
build-HelloWorldFunction:
	GOOS=linux GOARCH=amd64 go build -o helloWorld cmd/helloWorld/main.go
	cp ./helloWorld $(ARTIFACTS_DIR)/
```

Then change the template:
```
AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Resources:
  HelloWorldFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: hello-world/
      Handler: helloWorld
      Runtime: go1.x
      Architectures:
        - x86_64
    Metadata:
      BuildMethod: makefile
```

Output:

```
dmin:~/environment/testGoFunction $ rm -rf .aws-sam
Admin:~/environment/testGoFunction $ sam build -u
Starting Build inside a container
Building codeuri: /home/ec2-user/environment/testGoFunction/hello-world runtime: go1.x metadata: {'BuildMethod': 'makefile'} architecture: x86_64 functions: ['HelloWorldFunction']

Fetching public.ecr.aws/sam/build-go1.x:latest-x86_64 Docker container image......
Mounting /home/ec2-user/environment/testGoFunction/hello-world as /tmp/samcli/source:ro,delegated inside runtime container

Build Succeeded

Built Artifacts  : .aws-sam/build
Built Template   : .aws-sam/build/template.yaml

Commands you can use next
=========================
[*] Invoke Function: sam local invoke
[*] Deploy: sam deploy --guided
    
Running CustomMakeBuilder:CopySource
Running CustomMakeBuilder:MakeBuild
Current Artifacts Directory : /tmp/samcli/artifacts
GOOS=linux GOARCH=amd64 go build -o helloWorld cmd/helloWorld/main.go
cp ./helloWorld /tmp/samcli/artifacts/
Admin:~/environment/testGoFunction $ tree .aws-sam
.aws-sam
├── build
│   ├── HelloWorldFunction
│   │   └── helloWorld
│   └── template.yaml
└── build.toml

2 directories, 3 files
```

**Comment by torresxb1** [comment]
Thanks for bringing this to our attention, we will be investigating it further.
And thanks for providing a workaround as well!

**Comment by gauntface** [comment]
I recently ran into this is when trying to work around a glibc version issue between sam 1.56.1 and my OS (Fedora).

Fedora was using a version of glibc that sam wasn't able to use and getting the older version for sam was a non-trivial task.

My issue has been resolved by upgrading to sam 1.58.0 but being able to build with --use-container would have been a perfect solution.

**Comment by gauntface** [comment]
@shearn89 thank you for your work around, was able to use it for my project.

I had to change the CodeUri to the root of my repo for each of my functions to get the go.mod file to get picked up the same as it did with `sam build`: https://www.gaunt.dev/blog/2022/glibc-error-with-aws-sam-and-go/

**Comment by mndeveci** [comment]
Hi there,

This issue is been fixed with latest version of SAM CLI. In order to work with this setup, you need to provide `main.go` function in the `Handler` property, and `CodeUri` should point to root folder of your project. For the original example, the resource should be defined like this;

```
Resources:
  HelloWorldFunction:
    Type: AWS::Serverless::Function 
    Properties:
      CodeUri: hello-world
      Handler: cmd/helloWorld
      Runtime: go1.x
```

and `sam build -u` can execute successfully.
