### ISSUE TITLE
Feature request or question: How can I pass shared parameter in each environment

### ISSUE THREAD

**Issue by misogihagi** [aws/aws-sam-cli#3931]
### Describe your idea/feature/enhancement

Is there a way to share the parameters?
I want a global section for each environment.

like
```toml
 version=0.1
[global]
 s3_bucket = "my-source-bucket"
 region = "us-west-2"

 [dev.deploy.parameters]
 stack_name = "my-app-stack-dev"
 s3_prefix = "my-s3-prefix-dev"

 [prod.deploy.parameters]
 stack_name = "my-app-stack-prod"
 s3_prefix = "my-s3-prefix-prod"

```

this means like below

```toml
 version=0.1

 [dev.deploy.parameters]
 stack_name = "my-app-stack-dev"
 s3_prefix = "my-s3-prefix-dev"
 s3_bucket = "my-source-bucket"
 region = "us-west-2"

 [prod.deploy.parameters]
 stack_name = "my-app-stack-prod"
 s3_prefix = "my-s3-prefix-prod"
 s3_bucket = "my-source-bucket"
 region = "us-west-2"
```
