### ISSUE TITLE
Is there a suggested practice for accessing SecretsManager from a "sam local start-api" context?

### ISSUE THREAD

**Issue by ceberz** [aws/aws-sam-cli#3963]
In my lambda I'm invoking the SecretsManager very straightforwardly:

```javascript
const smClient = new AWS.SecretsManager();

// further down . . .

const secretResponse = await smClient
      .getSecretValue({
        SecretId: process.env.MY_SECRET_ARN,
      })
      .promise()
```

This works when deployed. In my template I've made sure the lambda has the correct permissions (several things (like "Events") left out for readability):

```yaml
MyFunction:
    Type: AWS::Serverless::Function
    Properties:
      Environment:
        Variables:
          MY_SECRET_ARN: !Ref MySecretArn
      PackageType: Zip
      Policies:
        - AWSLambdaBasicExecutionRole
        - AWSSecretsManagerGetSecretValuePolicy:
            SecretArn: !Ref MySecretArn
```

It makes sense why I should be getting an error on the call to SecretsManager ("The security token included in the request is expired"), but is there a way that I _ought_ to be setting this up so that I can enjoy running the lambdas locally when I'm developing?
