### ISSUE TITLE
Feature request: Packaging source bundles of Elastic Beanstalk

### ISSUE THREAD

**Issue by binchoo** [aws/aws-sam-cli#4001]
### Packaging and uploading Elastic Beanstalk's source bundles
Hi, I am trying to package and upload a source bundle for my Elastic Beanstalk application via SAM CLI.

I thought this idea was possible because `sam package --help` said it could package the `AWS::ElasticBeanstalk::ApplicationVersion::SourceBundle`.
```bash
$ sam package --help

 The following resources and their property locations are supported.
 ...
 Resource : AWS::ElasticBeanstalk::ApplicationVersion | Location : SourceBundle
 ...
```

Below is the template that I used.
```yaml
Resources:
  ...
  MyApplicationVersion:
    Type: AWS::ElasticBeanstalk::ApplicationVersion
    Properties:
      ApplicationName: !Ref MyApplication
      SourceBundle: !Sub ./.aws-sam/build/${AWS::StackName}-${ArchiveVersion}.jar
```

`sam deploy` with this template caused an exception complaining about the value of the SourceBundle.
[The specification](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-beanstalk-sourcebundle.html) defines `S3Bucket` and `S3Key` properties in `SoureceBundle`, but mine has none of them.
```
Value of property SourceBundle must be an object.
The following resource(s) failed to create: [MyApplicationRole, MyApplicationVersion]. 
Rollback requested by user.
```

I doubt that `sam deploy` can package a source bundle without a capability to point to local source files.

If packaging for Elastic Beanstalk is already possible, I'd like to know some docs or tutorials relating to it.
If not, I hope this feature is supported by SAM CLI.

**Comment by binchoo** [comment]
Hi @mildaniel. I appreciate. 
As you noted, I shouldn't have included any intrinsic function within the `SourceBundle` value.

After I pointed a file explicitly, SAM CLI successfully uploaded it to the sam-cli-managed bucket, and the version of my beanstalk application was updated.

```yaml
  MySkillApplicationVersion:
    Type: AWS::ElasticBeanstalk::ApplicationVersion
    Properties:
      ApplicationName: !Ref MyApplication
      SourceBundle: application-1.0.0.jar
```

Additionally, here are the deployment steps I follow:
1. Run `sam build` in order to copy the template.yaml into `.aws-sam/build` directory.
2. Run some gradle tasks that build and move a fat-jar into the sam build directory.
3. `sam deploy` to upload the jar and update my application.

I close the issue. Thanks @midaniel for taking care of this.
