### ISSUE TITLE
BUG: HttpApiCorsConfiguration AllowOrigins does not support CommaDelimitedList parameter locally

### ISSUE THREAD

**Issue by gauntface** [aws/aws-sam-cli#4026]
### Description:
I've just hit this as well but spotted a slightly different behavior between cloudformation and SAM.

The following will not work when run via SAM locally

```
Parameters:
  GatewayCorsOrigins:
    Type: CommaDelimitedList
    Default: []

Resources:
 ApiGatewayApi:
  Type: AWS::Serverless::HttpApi
  Properties:
    CorsConfiguration:
      AllowMethods:
        - OPTIONS
        - GET
        - POST
      AllowOrigins: !Ref GatewayCorsOrigins
      AllowHeaders:
        - Authorization
```
The logs output `CORS Property AllowOrigins was not fully resolved. Will proceed as if the Property was not defined.`

However, if I change `AllowOrigins: !Ref GatewayCorsOrigins` for:

```
AllowOrigins:
  - !Ref GatewayCorsOrigins
```
Then SAM local will work with the CORs configuration **BUT** CloudFormation will not deploy anything.

### Steps to reproduce:
Create a template file with a parameter defining the cors origins like so:

```
Parameters:
  GatewayCorsOrigins:
    Type: CommaDelimitedList
    Default: []

Resources:
 ApiGatewayApi:
  Type: AWS::Serverless::HttpApi
  Properties:
    CorsConfiguration:
      AllowMethods:
        - OPTIONS
        - GET
        - POST
      AllowOrigins: !Ref GatewayCorsOrigins
      AllowHeaders:
        - Authorization
```

### Observed result:
CORs does not work locally: `CORS Property AllowOrigins was not fully resolved. Will proceed as if the Property was not defined.`

### Expected result:
CORs would work for the defined origins.

### Additional environment details (Ex: Windows, Mac, Amazon Linux etc)

1. OS: Linux - Fedora
2. `sam --version`: SAM CLI, version 1.50.0
3. AWS region: N/A

**Comment by gauntface** [comment]
NOTE: This may be similar to #3719 but I raised a separate issue in case the use of parameters was the issue I'm facing vs support for multiple origins.

**Comment by mndeveci** [comment]
Thanks for reporting this issue. I've tried to re-produce it with following template & function.

template
```
AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Globals:
  Function:
    Timeout: 3

Parameters:
  GatewayCorsOrigins:
    Type: CommaDelimitedList
    Default: []

Resources:
  HelloWorldFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: hello_world/
      Handler: app.lambda_handler
      Runtime: python3.9
      Events:
        HelloWorld:
          Type: HttpApi
          Properties:
            ApiId: ApiGatewayApi
            Path: /hello
            Method: get

  ApiGatewayApi:
    Type: AWS::Serverless::HttpApi
    Properties:
      CorsConfiguration:
        AllowMethods:
          - OPTIONS
          - GET
          - POST
        AllowOrigins: !Ref GatewayCorsOrigins
        AllowHeaders:
          - Authorization
```

function code:
```
import json


def lambda_handler(event, context):

    return {
        "statusCode": 200,
        "body": json.dumps({
            "message": "hello world",
        }),
    }
```

And after running `sam local start-api` I am making the following `curl` call and I am getting following result;
```
curl 'http://localhost:3000/hello' -X 'OPTIONS' -i
HTTP/1.0 200 OK
Access-Control-Allow-Origin: 
Access-Control-Allow-Methods: GET,OPTIONS,POST
Access-Control-Allow-Headers: Authorization
Content-Length: 0
Server: Werkzeug/1.0.1 Python/3.8.13
Date: Thu, 07 Jul 2022 14:32:03 GMT
```

If I update default values for `GatewayCorsOrigins` I am getting list of origins in the header above.

Please let me know if I am missing something here.

Thanks!

**Comment by gauntface** [comment]
The only different I can imagine is that I'm using golang instead of python, but I wouldn't expect that to make a different to the gateway and CORs

**Comment by mndeveci** [comment]
That shouldn't make a difference, what is the response you got when you try to invoke it locally?

**Comment by gauntface** [comment]
Closing as it's most likely that I'm holding sam cli wrong.

**Comment by gauntface** [comment]
Running into this still.

Template:
```
Resources:
  ApiGatewayApi:
    Type: AWS::Serverless::HttpApi
    Properties:
      StageName: "example-stage"
      CorsConfiguration:
        AllowMethods:
          - OPTIONS
          - GET
          - POST
        AllowOrigins: !Ref GatewayCorsOrigins
        AllowHeaders:
          - Authorization
```

cURL response:
```
curl 'http://localhost:3001/hello' -X 'OPTIONS' -i
HTTP/1.0 200 OK
Access-Control-Allow-Methods: GET,OPTIONS,POST
Access-Control-Allow-Headers: Authorization
Content-Length: 0
Server: Werkzeug/1.0.1 Python/3.7.10
Date: Fri, 22 Jul 2022 17:26:30 GMT
```

The main difference in curl output between https://github.com/aws/aws-sam-cli/issues/4026#issuecomment-1177717814 and mine is `Access-Control-Allow-Origin: ` is not returned in my output.
