### ISSUE TITLE
AWS::Serverless::HttpApi's authorizers are missing AuthorizerResultTtlInSeconds field

### ISSUE THREAD

**Issue by andresmiguel** [aws/aws-sam-cli#4066]
I've created an HTTP Api Gateway using `AWS::Serverless::HttpApi`. I've also created an **Authorizer** using the `Auth` property. However, there is no `AuthorizerResultTtlInSeconds` to cache the Authorizer's result as in `AWS::ApiGatewayV2::Authorizer`.
This is the relevant part from my SAM template:
```yaml
  MyHttpApiGateway:
    Type: AWS::Serverless::HttpApi
    Properties:
      Auth:
        DefaultAuthorizer: RESTRequestAuthorizer
        Authorizers:
          RESTRequestAuthorizer:
            FunctionArn: !GetAtt RESTAuthorizerFunction.Arn
            AuthorizerPayloadFormatVersion: 2.0
            EnableSimpleResponses: true
```
