### ISSUE TITLE
Feature request: Move DockerTag ahead and put random string to the end of the generated image tag

### ISSUE THREAD

**Issue by weipingxia** [aws/aws-sam-cli#4078]
### Describe your idea/feature/enhancement

I wish SAM CLI would generate image tag in the format of `<FuncLabel>-<DockerTag>-<RandomSuffix>` rather than the current format - `<FuncLabel>-<RandomInfix>-<DockerTag>`. That way I can leverage the ECR image lifecycle to clean up obsolete images by specifying particular `tagPrefixList`. The current format doesn't apply tagPrefixList option.

E.g. Given the following metadata of the lambda function:
```
HelloWorldFunction:
  Type: 'AWS::Lambda::Function'
  Properties:
    ...
  Metadata:
    DockerContext: X/sam/test/hello_world
    DockerTag: python3.9-v1
    Dockerfile: Dockerfile
```

Generate docker tag as - `helloworldfunction-python3.9-v1-ffffff111111`

### Proposal

Change the default format to `<FuncLabel>-<DockerTag>-<RandomSuffix>`  or provide additional configuration to specify the tag prefix in metadata. E.g. DockerTagPrefix: xxx

```
HelloWorldFunction:
  Type: 'AWS::Lambda::Function'
  Properties:
    ...
  Metadata:
    DockerContext: X/sam/test/hello_world
    Dockerfile: Dockerfile
    DockerTagPrefix: myimageprefix
```

The above would generate docker tag as -  `myimageprefix-ffffff111111`, disregard the DockerTag option. (DockerTag and DockerTagPrefix can be mutual-exclusive).

### Additional Details

Discussion chain in Premium Support CASE 10376090461
