### ISSUE TITLE
Bug: Wrong handler mapping after esbuild

### ISSUE THREAD

**Issue by santiperone** [aws/aws-sam-cli#4082]
### Description:
  When running esbuild on a Lambda function, the output doesn't mantain the same folder structure as the enry points, and this remains unchange in the built template, resulting in SAM not finding the lambda Handler:

### Steps to reproduce:
Project structure:
```
- package.json
- template.yaml
-- src
--- functions
---- FunctionName
----- app.js
--- utils
---- some-util.js
```

Template.yaml:
```
FunctionName:
    Type: AWS::Serverless::Function
    Metadata:
      BuildMethod: esbuild
    Properties:
      Handler: src/functions/FunctionName/app.Handler
      Events:
        HttpEvent:
          ....
```

### Observed result:
code is budled to FunctionName folder in .aws-build resulting in:
```
- .aws-build
-- build
--- template.yaml
--- FunctionName
---- app.js
```
However, the built template results in:

```
FunctionName:
    Type: AWS::Serverless::Function
    Metadata:
      BuildMethod: esbuild
    Properties:
      CodeUri: FunctionName
      Handler: src/functions/FunctionName/app.Handler
      Events:
        HttpEvent:
          ....
```

Resulting in an error since FunctionName/src/functions/FunctionName/app.Handler

### Expected result:
Handler in built template should match esbuild output. I.E: 

```
FunctionName:
    Type: AWS::Serverless::Function
    Metadata:
      BuildMethod: esbuild
    Properties:
      CodeUri: FunctionName
      Handler: app.Handler
      Events:
        HttpEvent:
          ....
```
