### ISSUE TITLE
Bug: CORS Support in start-api

### ISSUE THREAD

**Issue by sravimohan** [aws/aws-sam-cli#4161]
## "sam local start-api" does not return cors headers in the lambda responses.

This issue was marked as fixed and closed in [https://github.com/aws/aws-sam-cli/issues/323](https://github.com/aws/aws-sam-cli/issues/323).  but seems to have regressed and is no longer working any more.

The options request correctly returns the CORS headers.  But the lambda response does not include "access-control-allow-origin" header.

The only workaround is to also manually include "access-control-allow-origin" header in the lambda responses.  

Pl. note its works fine when deployed without any workaround.

```
$ sam --version
SAM CLI, version 1.55.0
```

minimal repo for reproducing issue
[https://github.com/sravimohan/bug-aws-sam-cli-4161](https://github.com/sravimohan/bug-aws-sam-cli-4161)

template.yml
```
AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31

Globals:
  Function:
    Timeout: 3
    Runtime: nodejs16.x
    Architectures:
      - x86_64

  HttpApi:
    CorsConfiguration:
      AllowHeaders:
        - Content-Type
        - Authorization
        - Access-Control-Allow-Origin
      AllowMethods:
        - HEAD
        - OPTIONS
        - GET
        - POST
      AllowOrigins:
        - http://localhost:3010

Resources:
  HelloWorldFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: hello-world/
      Handler: app.lambdaHandler
      Events:
        HelloWorld:
          Type: HttpApi
          Properties:
            Path: /hello
            Method: GET
```

function
```
let response;

exports.lambdaHandler = async (event, context) => {
    try {
        response = {
            'statusCode': 200,
            // work around for cors issue
            // headers: {
            //     "Access-Control-Allow-Origin": "http://localhost:3010",
            // },
            'body': JSON.stringify({
                message: 'hello world',
            })
        }
    } catch (err) {
        console.log(err);
        return err;
    }

    return response
};
```
