### ISSUE TITLE
Bug: `sam build` continues even if Typsecript compilation fails

### ISSUE THREAD

**Issue by JoshMcCullough** [aws/aws-sam-cli#4162]
### Description:
After adding an intentional TS error (e.g. renamed a variable without refactoring), and running `sam build`, I'm told "Build Succeeded". Running `tsc` directly shows the error correctly.

My directory structure is as follows:

```
<root>
 |--> app
 |     |--> node_modules
 |     |--> src
 |     |     |--> app.ts    # and other TS files
 |     |--> package.json    # and other config files
 |     |--> tsconfig.json
 |--> node_modules          # for building e.g. rimraf
 |--> package.json          #   ^^
 |--> samconfig.toml
 |--> template.yaml
```

I run `sam build` from the root dir. In `template.yml` I have this (partial example):

```yaml
  Function:
    Type: AWS::Serverless::Function
    # ...
    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        Minify: false
        Target: es2020
        Sourcemap: true
        EntryPoints:
          - src/app.ts
```

To work around this, I have a wrapper shell script in which I call the `build` function to run `tsc` before `sam build` (partial example):

```shell
#!/bin/bash
set -e

function build() {
    clean
    (cd app; npx tsc) # `sam build` seems to continue even if TSC fails ... ?
    sam build "$@"
    validate
}

"$@"
```

So I start the build via `./scripts.sh build`.

### Steps to reproduce:
Create a simple Typescript / SAM project. Add a line of code which causes `tsc` to fail. Run `sam build` and observe that it _does not_ indicate failure.

### Observed result:
`sam build` does not report `tsc` errors / does not abort the build process on such errors.

### Expected result:
`sam build` should abort the process if `tsc` fails.

### Additional environment details (Ex: Windows, Mac, Amazon Linux etc)

1. OS: Manjaro Linux
2. `sam --version`: 1.55.0
3. AWS region: N/A
