### ISSUE TITLE
Bug: Defining resource with name "Bucket" causes chaos.

### ISSUE THREAD

**Issue by JoshMcCullough** [aws/aws-sam-cli#4163]
### Description:
Including a resource in the `template.yaml` named "Bucket" seems to (perhaps?) conflict with some internal term, and results in references to this resource not working correctly.

### Steps to reproduce:
Add a resource named "Bucket" and reference it from another resource, e.g. as an environment variable, and the output the value of that environment variable in your app's script:

#### `template.yaml`

```yaml
AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Resources:
  Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: test
  
  Role:
    Type: AWS::IAM::Role
    Properties:
      RoleName: test
      AssumeRolePolicyDocument:
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
            Action:
              - sts:AssumeRole
      Policies:
        - PolicyName: bucket_write
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              Effect: Allow
              Action: s3:PutObject
              Resource: !Sub ${Bucket.Arn}/*
  
  Function:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: app/
      Handler: app.run
      Runtime: nodejs16.x
      FunctionName: test
      Role: !GetAtt Role.Arn
      Architectures:
        - x86_64
      Environment:
        Variables:
          BUCKET: !Select [6, !Split [':', !GetAtt Bucket.Arn]]
    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        Minify: false
        Target: es2020
        Sourcemap: true
        EntryPoints:
          - src/app.ts
```

#### `src/app.ts`

```ts
export const run = async (): Promise<APIGatewayProxyResult> => {
  console.log(`BUCKET IS: ${process.env.BUCKET}`);
});
```

Output:

```shell
BUCKET IS: "Bucket"
```

#### Fixing It

Changing all references to `Bucket` in `template.yml` to e.g. `TargetBucket` gives the expected result:

```shell
BUCKET IS: "TargetBucket"
```

### Observed result:
Naming a resource "Bucket" results in strange behavior.

### Expected result:
The resource name "Bucket" should be allowed / should work, or should cause `sam build` to fail.

### Environment

1. OS: Manjaro Linux
2. `sam --version`: 1.55.0
3. AWS region: N/A
