### ISSUE TITLE
Feature request: AWS::LanguageExtensions support

### ISSUE THREAD

**Issue by jdel** [aws/aws-sam-cli#4172]
### Describe your idea/feature/enhancement

I wish SAM CLI would handle the new AWS::LanguageExtensions transform as specified in the documentation: https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-languageextension-transform.html

Example template:
```yml
AWSTemplateFormatVersion: 2010-09-09
Transform:
  - AWS::LanguageExtensions
  - AWS::Serverless-2016-10-31

Parameters:
  Environment:
    Type: String
    Default: dev
    AllowedValues:
      - dev
      - prod

Conditions:
  IsProd: !Equals [!Ref Environment, prod]

Resources:
  Bucket:
    Type: AWS::S3::Bucket
    DeletionPolicy: !If [IsProd, Retain, Delete]
    UpdateReplacePolicy: !If [IsProd, Retain, Delete]
```

`AWS CLI`, version 2.7.7 succeeds with:
```
❯ aws cloudformation deploy --stack-name test-language-extension --template-file sam/test-template.yml

Waiting for changeset to be created..
Waiting for stack create/update to complete
Successfully created/updated stack - test-language-extension
```

`SAM CLI`, version 1.55.0 fail with:
```
sam deploy --stack-name test-language-extension --template-file sam/test-template.yml
Traceback (most recent call last):
[... redacted stack trace ...]
  File "/usr/local/Cellar/aws-sam-cli/1.55.0/libexec/lib/python3.8/site-packages/samcli/lib/samlib/wrapper.py", line 70, in run_plugins
    raise InvalidSamDocumentException(
samcli.commands.validate.lib.exceptions.InvalidSamDocumentException: [InvalidTemplateException('Every DeletionPolicy member must be a string.')] Every DeletionPolicy member must be a string.
```

### Proposal

Implement the same changes as `aws-cli` and `cfn-lint`

For reference, the releases/announcements from both tools 
  - https://github.com/aws-cloudformation/cfn-lint/compare/v0.62.0..v0.63.0
  - https://github.com/aws/aws-cli/issues/3825#issuecomment-1231608258

Things to consider:
The order of the transforms is important and using multiple transforms is currently broken in `cfn-lint` https://github.com/aws-cloudformation/cfn-lint/issues/2346

### Additional Details

No additional details
