### ISSUE TITLE
Feature request: Add AWS Glue support

### ISSUE THREAD

**Issue by conao3** [aws/aws-sam-cli#4220]
### Describe your idea/feature/enhancement

Add missing AWS Glue support.

Lambda and Glue python shell offer similar functionality for users. Users can simply use it as a time-unlimited Lambda and run powerful ETL with per-minute billing, without the need for a server.

On the other hand, Lambda has SAM support but Glue does not. My particular problem is that Lambda's `InlineCode` does not work with Glue, so can you please support Glue with SAM?

```
  FunctionSampleA:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub ${Prefix}-SampleA
      Runtime: python3.8
      Handler: index.handler
      InlineCode: |
        def handler(event, context):
          print(event)
          return dict(event, a=42)
```
```
  JobSampleA:
    Type: AWS::Glue::Job
    Properties:
      Name: !Sub ${Prefix}-SampleA
      Role: !Ref RoleGlueArn
      GlueVersion: "1.0"
      MaxCapacity: 0.0625
      Command:
        Name: pythonshell
        PythonVersion: 3
        ScriptLocation: !Sub s3://${BucketScript}/python/glue_sample.py  # Save Python as a file and upload manually
```

### Proposal

`InlineCode` and `Policies` (and more!) support like Lambda ( `AWS::Serverless::Function` ) for AWS Glue.

### Additional Details

None
