### ISSUE TITLE
Bug: Sam Init Fails TypeError: unhashable type: 'dict' When passing !Ref or !Sub values into AWS::Serverless::Function Environment Variables

### ISSUE THREAD

**Issue by joeterlecki** [aws/aws-sam-cli#4285]
### Description:

When passing in string substitution for AWS::Serverless::Function into the Environment Variables config SAM init throws a stack trace for YAML helper. 

### Steps to reproduce:

sam deploy --resolve-s3 --template-file template.yaml --region us-east-1 --force-upload --config-env dev

  LambdaFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub "lambda-${Environment}"
      Environment:
        Variables:
          !Ref DynamoCacheDBTable: "7"
      Architectures:
        - !Ref LambdaArchitecture

This configuration does not work and also using !Sub throws the same result:
  LambdaFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub "lambda-${Environment}"
      Environment:
        Variables:
          !Sub "dynamo_cache_table_${Environment": 7
      Architectures:
        - !Ref LambdaArchitecture

The dynamo db table is defined as:

### Expected result:

Expected the

### Additional environment details (Ex: Windows, Mac, Amazon Linux etc)

1. OS:
2. `sam --version`:
3. AWS region:

`Add --debug flag to command you are running`

**Comment by AffiTheCreator** [comment]
any update on this issue?

**Comment by joeterlecki** [comment]
2 years and counting

**Comment by SudoCerb** [comment]
Hello...anyone there?

**Comment by dfiliakin** [comment]
Happen to me due to the following:
``` YAML
InstanceLaunchTemplate:
    Type: AWS::EC2::LaunchTemplate
    ...
    UserData: !Base64 | # <- here, my IDE was messing with newlines as a part of autoformatting 
          Fn::Sub: |
            #!/bin/bash
```
I solved it using AWS Infrastructure Composer
https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/infrastructure-composer-for-cloudformation.html

I copy-pasted my template and tried to build layout out of it. Got an error with an exact line number
