### ISSUE TITLE
Bug: Sam sync adds an extra nodejs directory to the path of the lambda layer

### ISSUE THREAD

**Issue by RobertMarton1985** [aws/aws-sam-cli#4304]
### Description:
We have a sam project with lambda functions and layers written in nodejs14.x.
We are currently working on using sam sync to speed up development. When we start the project with sam sync it starts properly but the lambdas fail to use the functions provided in the layers.
We started investigating the issue and downloaded the layer's code with the following command:
aws lambda get-layer-version --layer-name #LAYER_NAME# --version-number #LAYER_VERSION# --query Content.Location --output text

It turned out that when we use sam sync it adds an extra nodejs directory into the path of the layer.
Layer content when deployed with sam deploy:
layer.zip/nodejs/node_modules/...

Layer content when deployed with sam sync:
layer.zip/nodejs/nodejs/node_modules/...

### Steps to reproduce:
Create a layer with AWS::Serverless::LayerVersion and set the ContentUri to a local folder

### Observed result:
sam sync adds an extra nodejs directory to the path of a nodejs14.x lambda layer

### Expected result:
sam sync should create the same layer as sam deploy.

### Additional environment details (Ex: Windows, Mac, Amazon Linux etc)

1. OS: Windows 10
2. `sam --version`: SAM CLI, version 1.60.0
3. AWS region: eu-west-1

**Comment by lucashuy** [comment]
Hi thanks for raising this issue! Can you provide snippet of your template with the `AWS::Serverless::LayerVersion` resource while we investigate?

**Comment by RobertMarton1985** [comment]
This is the problematic Layer:

```yaml
  DummyLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      LayerName: dummy-layer
      Description: Dummy functions
      ContentUri: src/common/dummy/
    Metadata:
      BuildMethod: nodejs14.x
```

We don't build the layer, but if the Metadata part is not there then sam sync throws an error even though it should be optional:

`
Syncing Layer DummyLayer...
Layer <samcli.lib.providers.sam_function_provider.SamFunctionProvider object at 0x000002026967FD90> is missing BuildMethod Metadata.
Code sync encountered an error.
Traceback (most recent call last):
  File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\samcli\lib\sync\sync_flow_executor.py", line 342, in _sync_flow_execute_wrapper
    dependent_sync_flows = sync_flow.execute()
  File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\samcli\lib\sync\sync_flow.py", line 310, in execute
    self.gather_resources()
  File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\samcli\lib\sync\flows\layer_sync_flow.py", line 224, in gather_resources
    self._build_context.collect_build_resources(self._layer_identifier),
  File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\samcli\commands\build\build_context.py", line 493, in collect_build_resources
    self._collect_single_buildable_layer(resource_identifier, result)
  File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\samcli\commands\build\build_context.py", line 581, in _collect_single_buildable_layer
    raise MissingBuildMethodException(f"Build method missing in layer {resource_identifier}.")
samcli.commands.build.exceptions.MissingBuildMethodException: Build method missing in layer DummyLayer.
`

**Comment by mndeveci** [comment]
@RobertMarton1985 just to confirm your use case, layer definition does not have a `BuildMethod` defined in `Metadata`, is that correct? Something like this;

```
 DummyLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      LayerName: dummy-layer
      Description: Dummy functions
      ContentUri: src/common/dummy/
```
