### ISSUE TITLE
Bug: Cannot use intrinsic "Fn::If:" function on CodeUri property of AWS::Serverless::Function resource

### ISSUE THREAD

**Issue by ceberz** [aws/aws-sam-cli#4308]

**Comment by mndeveci** [comment]
Thanks for reporting this issue.

SAM and SAM CLI has some basic intrinsics support and unfortunately it doesn't cover all cases at the moment.

I will be discussing this issue with the team to find a path forward.

**Comment by bmckinle** [comment]
Any update on this issue?  I'm still seeing it using cdk synth and then using sam local start ...<generted cdk template>.

**Comment by josephmfaulkner** [comment]
I'm having the exact same problem now (almost three whole years after this was originally reported). My goal is to conditionally use an S3 bucket. Like so: 

```
  SpringBootLambdaFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: SpringBootAPIHandler
      Handler: com.javatechie.StreamLambdaHandler::handleRequest
      Runtime: java21

      CodeUri: 
        !If
          - IsLocalDevEnv
          - Bucket: hot-reload
            Key: $HOST_LAMBDA_DIR/lambda-functions/restApi/target/spring-boot-rest-api-lambda
          - ./lambda-functions/restApi
```
Yet, this is always what gets generated, regardless of what IsLocalDevEnv evaluates as: 
```
  SpringBootLambdaFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: SpringBootAPIHandler
      Handler: com.javatechie.StreamLambdaHandler::handleRequest
      Runtime: java21
      CodeUri: SpringBootLambdaFunction
```

Has anyone been able to at least identify a workaround for this?
