### ISSUE TITLE
Feature request: Allow sam deploy to deploy lambdas with existing container images

### ISSUE THREAD

**Issue by seongkk** [aws/aws-sam-cli#4347]
### Describe your idea/feature/enhancement

Currently, with `sam deploy`, sam uploads(pushes) image that is going to be used based on what is specified in `Metadata` and it does it for all the lambda function resources within a template.yaml. We'd like to have our own CI, pre-built container image built and pushed up in ECR and just have sam use the specified image, rather than pushing/tagging it on deploy.

### Proposal

`--skip-pushing-image true` should skip the image build/push part, and just have sam use the image specified as `ImageUri` in template.yaml to deploy the lambdas.

Things to consider:

**Comment by mndeveci** [comment]
Hi there,

It is actually available to skip image pushing part, and deploy your function directly. In order to do that, you need to set `ImageUri` property of your function with the ECR image URI. Something like this;

```
HelloWorldFunction:
    Type: AWS::Serverless::Function 
    Properties:
      PackageType: Image
      ImageUri: 1234567890.dkr.ecr.us-west-2.amazonaws.com/my-ecr-repo/hello-world-function:my-latest-tag
```

Then when you are deploying your application, you can provide `--resolve-image-repos` flag to deploy your stack directly, without uploading any image to ECR.

`sam deploy --resolve-image-repos`

Please let us know if that doesn't fix your use case.

**Comment by seongkk** [comment]
@mndeveci thanks for the feed back. For the deploy part, I did confirm that I was able to use existing image with --resolve-image-repos. 

One more question I had is - we are trying to follow this workflow.

Sam build --> Sam deploy

where for sam build our docker config in `template.yaml` looks like follow:
```
myFunction:
    Type: AWS::Serverless::Function 
    Properties:
      PackageType: Image
      ImageUri: !Sub 1234567890.dkr.ecr.us-west-2.amazonaws.com/my-ecr-repo/hello-world-function:${myFunctionTag}
```

However, when we run `sam build`, the ImageUri in .aws-sam/build/template.yaml  becomes something like:
```
ImageUri: myfunction-23f2c3642457-v1
```

And my assumption is that sam build derives some tag mechanism from the metadata.

Current workaround i can think of is:

sam build --> replace image_uri from .aws-sam/build/template.yaml --> sam deploy --resolve-image-repos.

Would there be a better way where we can tell sam to ignore building its own imageuri when already specified in template.yaml?

Again ,thank you for your inputs!

**Comment by mndeveci** [comment]
If you are already building your image and publish it to ECR repo through another pipeline, then you don't need to define metadata for your function. So if you change your function to this, `sam build` should also work;

```
myFunction:
    Type: AWS::Serverless::Function 
    Properties:
      PackageType: Image
      ImageUri: !Sub 1234567890.dkr.ecr.us-west-2.amazonaws.com/my-ecr-repo/my-function:${DockerTagVersion}
```
