### ISSUE TITLE
Guidance on switching functions on API gateway to container image based lambda

### ISSUE THREAD

**Issue by seongkk** [aws/aws-sam-cli#4438]
Description

Changing a lambda function from zip based to container image based requires recreation of the lambda function - that is, it's not something that we can make a configuration for for existing zip based image.

We have several API gateways referencing current zip based lambda functions as such.

```
  EventsApi:
    Type: AWS::Serverless::Api
    Properties:
      Name: !Sub ${AWS::StackName}-Events
      StageName: !Sub ${StageEnv}
      EndpointConfiguration:
        Type: !If [ REGIONAL, EDGE ]
      Auth:
        DefaultAuthorizer: Auth
        Authorizers:
          Auth:
            FunctionArn: !GetAtt EventAuthorizer.Arn
            Identity:
              Header: Authorization
              ReauthorizeEvery: 900
  EventAuthorizer:
    Type: AWS::Serverless::Function
    Properties:
      Handler: event.authorizer.lambda_handler
      FunctionName: !Sub ${AWS::StackName}-EventAuthorizer
```

What is the best/recommended practice on changing that lambda into container image based functions? 
Just adding `PackageType: Image` to lambda resource block did not seem to work with an error message saying it can not be changed, but needs re-creation. 
 
One other way I can think of is creating a new duplicate lambda that is container image based and make the API gateway reference that new lambda, but I was wondering if there would be a better way for us to do this since we have many large number of functions that we manage.
