### ISSUE TITLE
Sam deploy fails without any change (Unrecognized resource types: [AWS::Lambda::Permission])

### ISSUE THREAD

**Issue by tho-masn** [aws/aws-sam-cli#4492]
Without changing anything in the template, the `sam deploy` command just stopped working.
I'm deploying in the `eu-central-1` region, but the deployment fails because of the following error:

```Error: Failed to create/update the stack: my-stack-name, An error occurred (ValidationError) when calling the GetTemplateSummary operation: Template format error: Unrecognized resource types: [AWS::Lambda::Permission]```

After I got the error I've upgraded aws-sam-cli from 1.65.0 to 1.66.0, but it still fails.
Just saw there was a similar issue some time ago, with a slightly different error: https://github.com/aws/aws-sam-cli/issues/3768

Seems like this kind of issue appears and disappears magically. Does anyone else experience this behaviour? As I've successfully deployed the same application about an hour before it started to fail, I guess the template is fine.

**UPDATE 2022-12-19:**
This is the command used to deploy the stack:
```sam deploy --stack-name my-stack-name --region eu-central-1 --template-file template.yaml --s3-bucket=xyz --profile=my-profile --capabilities CAPABILITY_NAMED_IAM```

The template header looks like this:
```
AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  my-stack-name
  Sample SAM Template for lambda-nodejs16.x 
Globals:
  Function:
    Timeout: 10
    Environment:
      Variables:
        # Some environment variables

Resources:
  # All the resources
```

The error is still the same since I've posted this issue, although there was 1 try over the weekend, where the deploy was running half through and then exited. Unfortunately I don't have the error log from this deploy anymore.
