### ISSUE TITLE
Bug: Metadata.Sourcemap: true clobbers NODE_OPTIONS env var

### ISSUE THREAD

**Issue by ianwremmel** [aws/aws-sam-cli#4513]
### Description:

I use `NODE_OPTIONS` to load a file of OpenTelemetry hooks prior to loading the app's main script. Thanks to the way the OpenTelemtry and ADOT Lambda layers work, set of hooks need to be loaded with `--require` or it won't have a chance to alter the default behavior. 

```yml
Globals:
  Function:
    Environment:
      Variables:
        NODE_OPTIONS: '--require ./telemetry --trace-warnings'
```

When coupled with the following esbuild metadata, however, those `NODE_OPTIONS` never make it to the lambda

```yml
    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        EntryPoints:
        - index
        Sourcemap: true
```

### Observed result:

Lambda's `NODE_OPTIONS` environment variable is ` --enable-source-maps`

It appears the if I include `--enable-source-maps` in the global `NODE_OPTIONS` environment variable, things work as desired, but this is definitely surprising behavior. Given there's a leading space in the final template for each function's NODE_OPTIONS, I suspect the original author of this code assumed the global `NODE_OPTIONS` and the per-function `NODE_OPTIONS` would be concatenated, but they do not appear to be.

### Expected result:

Lambda's `NODE_OPTIONS` environment variable is `--require ./telemetry --trace-warnings --enable-source-maps`

### Additional environment details (Ex: Windows, Mac, Amazon Linux etc)

1. OS:
2. `sam --version`:
3. AWS region:

`Add --debug flag to command you are running`

**Comment by moelasmar** [comment]
Thanks @ianwremmel for raising this issue. I will try to reproduce this issue, and investigate it the root cause.
It will be helpful if you can provide a sample template/project to use it in the investigation.

**Comment by ianwremmel** [comment]
`template.yml`:

```yaml
AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Globals:
  Function:
    Environment:
      Variables:
        NODE_OPTIONS: '--require ./telemetry --trace-warnings'
Resources:
  FnPing:
    Type: AWS::Serverless::Function
    Properties:
      Handler: index.handler
      Runtime: nodejs18.x
      CodeUri: ./src
      MemorySize: 128
      Timeout: 10
      Events:
        Ping:
          Type: Api
          Properties:
            Path: /ping
            Method: get
      Policies:
        - AWSLambdaBasicExecutionRole
    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        EntryPoints:
        - index
        Sourcemap: true
```

`src/index.js`:

```js
exports.handler = function (event, context) {
  return JSON.stringify({
    pong: true
  });
}
```

Run `sam build` to produce this template:


`.aws-sam/build/template.yml`:

```yaml
AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Globals:
  Function:
    Environment:
      Variables:
        NODE_OPTIONS: --require ./telemetry --trace-warnings
Resources:
  FnPing:
    Type: AWS::Serverless::Function
    Properties:
      Handler: index.handler
      Runtime: nodejs18.x
      CodeUri: FnPing
      MemorySize: 128
      Timeout: 10
      Events:
        Ping:
          Type: Api
          Properties:
            Path: /ping
            Method: get
      Policies:
      - AWSLambdaBasicExecutionRole
      Environment:
        Variables:
          NODE_OPTIONS: ' --enable-source-maps'
    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        EntryPoints:
        - index
        Sourcemap: true
      SamResourceId: FnPing
```

Note that there are two different `NODE_OPTIONS` and the one on the function overwrites the one on globals. Given the leading space, I assume someone thought they would be concatenated.
