### ISSUE TITLE
Bug: when deploying with 1.67.0 causes missing go binary in lambda

### ISSUE THREAD

**Issue by nathani-axis** [aws/aws-sam-cli#4519]
### Description:

When deploying with current latest release, Sam will successfully deploy a lambda, but the lambda has no go binary attached to it. When trying to call the lambda, I get an error:
`fork/exec /var/task/<binary-name>: permission denied: PathError null` where <binary-name> is the name of the go binary.

### Steps to reproduce:

- build a working go binary (tried with both `go build` and `sam build`, doesn't matter)
- write a working simple go lambda template, which takes the go binary
- install aws-sam-cli (we do that with the setup-sam github action, grabbing latest release)
- run:
```
sam deploy \
            --no-fail-on-empty-changeset \
            --stack-name <stack-name> \
            --template-file template.yaml \
            --role-arn <role-arn>
```
- send a query to the lambda
- get error: `fork/exec /var/task/<binary-name>: permission denied: PathError null`, query returns 500.

### Observed result:

We get error `fork/exec /var/task/<binary-name>: permission denied: PathError null` when calling the broken lambda. I can provide --debug output if needed, though we were not running it while we were having the issue. Cloud formation or Sam don't complain and show all green though.

The issue doesn't always happen, it's a little random. Sometimes it works, sometimes it doesn't. We had pretty much the same issue about a short year ago, but the issue stopped happening suddendly. Now it's back.

### Expected result:

The lambda deploys with the updated binary, and has access to it.

Everything *seems* to be working correctly in sam versions 1.53.0 and 1.66.0

### Additional environment details (Ex: Windows, Mac, Amazon Linux etc)

1. OS: linux, latest github workflow ubuntu versions
2. `sam --version`: 1.67.0
3. AWS region: eu-west-1

**Comment by moelasmar** [comment]
thanks @nathani-axis for raising the issue. Could you please provide the debug logs for the `sam deploy` command, and also provide a sample for the template you used for deployment.
I need to understand how do you refer to the binary artifact in the lambda function properties, and also the location of this binary locally.

**Comment by nathani-axis** [comment]
Here's a template example that works with SAM versions 1.53.0 and 1.66.0 but not 1.67.0
```yaml
AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Dummy template for fork/exec bug

Resources:

  DummyFunctionRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: DummyFunctionRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: "Allow"
            Principal:
              Service:
                - lambda.amazonaws.com
            Action:
              - "sts:AssumeRole"
      Policies:
        - PolicyName: lambda-policy
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              # Various needed actions

  DummyFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: DummyFunction
      Timeout: 30
      MemorySize: 256
      CodeUri: ./build
      Handler: gobinary
      Runtime: go1.x
      Role: !GetAtt DummyFunctionRole.Arn
      Environment:
        Variables:
          # Various needed variables
      Events:
        ApiOptionsEvent:
          Type: HttpApi
          Properties:
            Path: /{proxy+}
            Method: ANY
            ApiId: <ApiId>
```

I'll see if I can recreate the bug with the --debug flag
