### ISSUE TITLE
Error: Failed to parse template: unacceptable character #x0000: special characters are not allowed   in "<unicode string>", position 0 

### ISSUE THREAD

**Issue by hamdan-hassan** [aws/aws-sam-cli#4526]
### Description:
I tried to run my sam python docker image locally but I am getting the above error. I tried check my yaml file for any whitespace or syntax error but found nothing. I also tried changing the yaml file encoding and still getting the same error. What is strange is even if i delete the yaml file i am getting the sam error. I dont know if the issue is coming from the yaml file or not

### Steps to reproduce:
$ sam init with the following choices:
Template: 1 - AWS Quick Start Templates
Quick Start template: 1 - Hello World Example
Runtime: 12 - python3.9
Package type: 1 - Image
Template 2 - Hello World Example
X-Ray tracing, CloudWatch: no
sam build
sam local start-api

### Observed result:

![Screenshot 2023-01-01 123728](https://user-images.githubusercontent.com/51380872/210170795-22da31a0-23e0-4de4-9839-2eef6aad274c.png)

### Additional environment details

1. OS: Windows 10
2. `sam --version`: SAM CLI, version 1.67.0
3. AWS region: us-east 1

This is my template.yaml file

```
AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: >
  python3.9

  Sample SAM Template for summarization-v2-lambda

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 30
    MemorySize: 3008

Resources:
  HelloWorldFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      PackageType: Image
      Architectures:
        - x86_64
      Events:
        Root:
          Type: Api
          Properties:
            Path: /
            Method: get
        SummarizeAI:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /summarize_t5
            Method: post
        SummarizeArticle:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /summarize_article
            Method: post
        SummarizeTextRank:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /summarize_textrank
            Method: post
        SummarizeParagraphs:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /summarize_paragraphs
            Method: post
    Metadata:
      Dockerfile: Dockerfile
      DockerContext: ./app
      DockerTag: python3.9-v1

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  RootApi:
    Description: "API Gateway endpoint URL for Prod stage for Root route"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/"
  SummarizeAIApi:
    Description: "API Gateway endpoint URL for Prod stage for Hello World function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/summarize_t5/"
  SummarizeArticleApi:
    Description: "API Gateway endpoint URL for Prod stage for Hello World function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/summarize_article/"
  SummarizeTextRankApi:
    Description: "API Gateway endpoint URL for Prod stage for Hello World function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/summarize_textrank/"
  SummarizeParagraphsApi:
    Description: "API Gateway endpoint URL for Prod stage for Hello World function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod//summarize_paragraphs/"
  HelloWorldFunction:
    Description: "Hello World Lambda Function ARN"
    Value: !GetAtt HelloWorldFunction.Arn
  HelloWorldFunctionIamRole:
    Description: "Implicit IAM Role created for Hello World function"
    Value: !GetAtt HelloWorldFunctionRole.Arn

````
