### ISSUE TITLE
ESBuild builds only the Lambda handler without other files like service, provider, etc

### ISSUE THREAD

**Issue by Maoragai12** [aws/aws-sam-cli#4544]
### Description:
I'm using the `aws-sam-cli` ESBuild option to build my Lambda. I use it in the `template.yaml`:

```
    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        Minify: true
        Target: "es2020"
        Sourcemap: true
        EntryPoints: 
          - src/handler/handler.ts
```
My project tree:

```
| services
  | order-service
│     ├─ src
│     │  ├─ config
│     │  │  └─ config.ts
│     │  ├─ handler
│     │  │  └─ handler.ts
│     │  ├─ provider
│     │  │  ├─ provider.ts
│     │  ├─ service
│     │  │  └─ service.ts
|  template.yaml 
```

When I build the function with the following command, I get the build folder only with the handler, without the rest of the files:

```
sam build --template services/order-service/template.yaml --parameter-overrides EnvType={args.EnvType} --beta-features --build-dir=.aws-sam/build/order-service --debug
```

### Observed result:
I get build only with the Lambda's handler:

<img width="344" alt="Screenshot 2023-01-06 at 4 10 25" src="https://user-images.githubusercontent.com/67845335/210915665-2fb5286f-7ca3-486d-8d50-0a8f5b05322a.png">

In the `handler.map` file, I can see all the relevant functions and logic from other files, but I can't see that in the `handler` file. 

### Expected result:
I expect to get a build with all the relevant files. 

### Additional environment details (Ex: Windows, Mac, Amazon Linux etc)

1. OS: MacOS Ventura 13.0.1
2. `sam --version`: SAM CLI, version 1.65.0
3. AWS region: us-east-1
