### ISSUE TITLE
[Tracking] SAM CLI developer experience updates

### ISSUE THREAD

**Issue by praneetap** [aws/aws-sam-cli#4639]
We are working on continuously improving developer experience on the SAM CLI. Feel free to post your thoughts here, or link to other issues you have created that map to DX improvements. Follow the issue by clicking 👍🏽 to see our progress.

## In Flight
* https://github.com/aws/aws-sam-cli/pull/4628
* https://github.com/aws/aws-sam-cli/discussions/4591

**Comment by igorlg** [comment]
Suggestion for `samconfig.toml` - Support setting up cross-environment parameters:

At the moment, it is possible to set parameters common to all sections _of any given environment_ in the `[<environment>.global.parameters]` section, e.g.:

```toml
[dev.global.parameters]
stack_name = "my-app-dev"
resolve_s3 = true

[dev.build.parameters]
use_container = true

[dev.deploy.parameters]
parameter_overrides = "Environment=\"dev\""
```

However, when defining multiple environments in `samconfig.toml`, there are cases where the same config key/value needs to be set across all environments. Today, this requires duplication and is potentially error-prone.

It would be great if one could set common parameters **across environments** only once. These could be applied to specific SAM subcommands (e.g. _deploy_, _build_), or all subcommands, like the current behaviour of _global_:

```toml
[ALL.build.parameters]
use_container = true
resolve_s3 = true

[dev.global.parameters]
stack_name = "my-app-dev"

[dev.deploy.parameters]
# [...]

[prod.global.parameters]
stack_name = "my-app-prod"

[prod.deploy.parameters]
# [...]
```
