### ISSUE TITLE
Bug: sam local invoke - generate-event

### ISSUE THREAD

**Issue by fade2black** [aws/aws-sam-cli#4710]
sam version 1.73.0

I run `sam local generate-event sns notification`
which generates the following event
```{
  "Records": [
    {
      "EventSource": "aws:sns",
      "EventVersion": "1.0",
      "EventSubscriptionArn": "arn:aws:sns:us-east-1::ExampleTopic",
      "Sns": {
        "Type": "Notification",
        "MessageId": "95df01b4-ee98-5cb9-9903-4c221d41eb5e",
        "TopicArn": "arn:aws:sns:us-east-1:123456789012:ExampleTopic",
        "Subject": "example subject",
        "Message": "example message",
        "Timestamp": "1970-01-01T00:00:00.000Z",
        "SignatureVersion": "1",
        "Signature": "EXAMPLE",
        "SigningCertUrl": "EXAMPLE",
        "UnsubscribeUrl": "EXAMPLE",
        "MessageAttributes": {
          "Test": {
            "Type": "String",
            "Value": "TestString"
          },
          "TestBinary": {
            "Type": "Binary",
            "Value": "TestBinary"
          }
        }
      }
    }
  ]
}
```

However, my lambda triggered by SNS+SQS receives a different payload (in terms of keys):
For example, I receive `body` instead of `SNS`.

**Comment by lucashuy** [comment]
Hi, thanks for raising this issue. By receiving a different payload, did you mean receiving a different event definition than what was passed in? I was not able to reproduce this issue with the following steps:

1. `sam init --name test-app --runtime python3.8 --app-template hello-world --no-interactive --dependency-manager pip`
2. update `hello_world/app.py` to `print(event)`
3. `sam local generate-event sns notification > event.json`
4. `sam build`
5. `sam local invoke -e event.json`
6. observed result:
```Invoking app.lambda_handler (python3.8)
Local image is up-to-date
Using local image: public.ecr.aws/lambda/python:3.8-rapid-x86_64.

Mounting /Users/lucashuy/githubissues/app-templates/342/sam2/.aws-sam/build/HelloWorldFunction as /var/task:ro,delegated inside runtime container
START RequestId: 719639d2-0a2b-4a4d-8983-fcdf45bcc9ac Version: $LATEST
{'Records': [{'EventSource': 'aws:sns', 'EventVersion': '1.0', 'EventSubscriptionArn': 'arn:aws:sns:us-east-1::ExampleTopic', 'Sns': {'Type': 'Notification', 'MessageId': '95df01b4-ee98-5cb9-9903-4c221d41eb5e', 'TopicArn': 'arn:aws:sns:us-east-1:123456789012:ExampleTopic', 'Subject': 'example subject', 'Message': 'example message', 'Timestamp': '1970-01-01T00:00:00.000Z', 'SignatureVersion': '1', 'Signature': 'EXAMPLE', 'SigningCertUrl': 'EXAMPLE', 'UnsubscribeUrl': 'EXAMPLE', 'MessageAttributes': {'Test': {'Type': 'String', 'Value': 'TestString'}, 'TestBinary': {'Type': 'Binary', 'Value': 'TestBinary'}}}}]}
END RequestId: 719639d2-0a2b-4a4d-8983-fcdf45bcc9ac
REPORT RequestId: 719639d2-0a2b-4a4d-8983-fcdf45bcc9ac  Init Duration: 0.91 ms  Duration: 594.75 ms     Billed Duration: 595 ms      Memory Size: 128 MB     Max Memory Used: 128 MB
{"statusCode": 200, "body": "{\"message\": \"hello world\"}"}%
``` 

Are you able to provide a sample template, or steps that show that reproduce what you are experiencing?

**Comment by lucashuy** [comment]
I used the Ruby sample hello world template and modified the template to include a SNS trigger so that it looks like this:
```
Resources:
  HelloWorldFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: hello_world/
      Handler: app.lambda_handler
      Runtime: ruby2.7
      Architectures:
        - x86_64
      Events:
        HelloWorld:
          Type: Api
          Properties:
            Path: /hello
            Method: get
        SNSTopicEvent:
          Type: SNS
          Properties:
            Topic: !Ref SimpleTopic
  SimpleTopic:
    Type: AWS::SNS::Topic
```
I also modified the source file by adding `put event` so that I can view the event input in the logs. I deployed this template and went to the AWS SNS console to manually send a message, however the event body included the `Sns` key like the generated event did.
```
2023-02-14T11:58:29.408-08:00    {"Records"=>[{"EventSource"=>"aws:sns", "EventVersion"=>"1.0", "EventSubscriptionArn"=>"arn:aws:sns:us-east-1:703605443375:gh4710ruby-SimpleTopic-5kEn2WUIxWFd:0ecd23b1-855a-4319-b952-5402cab73c51", "Sns"=>{"Type"=>"Notification", "MessageId"=>"1287c0af-7977-5a8c-82c4-9cca93536bb1", "TopicArn"=>"arn:aws:sns:us-east-1:703605443375:gh4710ruby-SimpleTopic-5kEn2WUIxWFd", "Subject"=>nil, "Message"=>"hello world", "Timestamp"=>"2023-02-14T19:58:28.981Z", "SignatureVersion"=>"1", "Signature"=>"< signature removed >", "SigningCertUrl"=>"< signing cert removed >", "UnsubscribeUrl"=>"< url removed >", "MessageAttributes"=>{"mystring"=>{"Type"=>"String", "Value"=>"myvalue"}}}}]}
```

Is there a set of steps or sample templates I can use to try to reproduce this?

**Comment by fade2black** [comment]
What I have:
SNS, SQS (standard) polling from the SNS

Template:
```yaml
MyWorker:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./src
      Handler: handler.Handler.process
      Runtime: ruby2.7
      Architectures:
        - x86_64
      MemorySize: 1024
      Timeout: 900
      Events:
         MySQS:
           Type: SQS
           Properties:
             Queue: !GetAtt MySqsQueue.Arn
             BatchSize: 5

MySqsQueue:
    Type: AWS::SQS::Queue
    Properties:
       VisibilityTimeout: 3000
```

How I send (from another Ruby app, event sources):
```ruby
client = Aws::SNS::Client.new
client.publish(
   topic_arn: "<my-sns-arn>",
   message: JSON.generate(ids: ids_array)
)
```
This is what I get (real log from AWS production env by `logger.info event` inside the lambda handler)
```
I, [2023-02-14T20:19:37.462190 #8]  INFO 353e983a-9dcd-5fbc-a602-c45f72da2347 -- :{
  "Records"=>
  [{
    "messageId"=>"0f895a42-ad61-4205-a9c2-58de83680d64", 
    "receiptHandle"=>"*******************",
    "body"=>"{\n  \"Type\" : \"Notification\",\n  \"MessageId\" : \"****************\",\n  \"TopicArn\" : \"arn:aws:sns:eu-central-1:***********\",\n  \"Message\" : \"{\\\"ids\\\":[\\\"678\\\",\\\"901\\\",\\\"234\\\",\\\"567\\\",\\\"890\\\"]}\",\n  \"Timestamp\" : \"2023-02-14T20:19:37.098Z\",\n  \"SignatureVersion\" : \"1\",\n  \"Signature\" : \"***************\",\n  \"SigningCertURL\" : \"https://sns.eu-central-1.amazonaws.com/SimpleNotificationService-*************\",\n  \"UnsubscribeURL\" : \"https://sns.eu-central-1.amazonaws.com/?Action=Unsubscribe&SubscriptionArn=arn:aws:sns:*********\"\n}",
    "attributes"=>{"ApproximateReceiveCount"=>"1", "SentTimestamp"=>"***********", "SenderId"=>"************", "ApproximateFirstReceiveTimestamp"=>"1676405977152"}, 
    "messageAttributes"=>{}, 
    "md5OfBody"=>"***********",
    "eventSource"=>"aws:sqs",
    "eventSourceARN"=>"arn:aws:sqs:eu-central-1:*******", "awsRegion"=>"eu-central-1"
    }]
}
```
