### ISSUE TITLE
SAM CLI Build Fails with Error "NETSDK1194: The "--output" option isn't supported when building a solution" when packaging .NET 6 Lambda application

### ISSUE THREAD

**Issue by SamKiwi2021** [aws/aws-sam-cli#4748]
Description: 

I encountered an error while using the SAM CLI to package my AWS Lambda application built with .NET 6 in a SAM pipeline. I created a build YAML file using sam pipeline and ran it in GitHub Actions, but the sam build command failed with the following error message:

```bash
*********** start ***************
Run sam build --template ${SAM_TEMPLATE}

	SAM CLI now collects telemetry to better understand customer needs.

	You can OPT OUT and disable telemetry collection by setting the
	environment variable SAM_CLI_TELEMETRY=0 in your shell.
	Thanks for your help!

	Learn More: https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/serverless-sam-telemetry.html

Building codeuri: /home/runner/work/guardian/guardian/src/Sidebar runtime: dotnet6 metadata: {} architecture: x86_64 functions: SidebarFunction
Running DotnetCliPackageBuilder:GlobalToolInstall
You can invoke the tool using the following command: dotnet-lambda
Tool 'amazon.lambda.tools' (version '5.6.3') was successfully installed.
Running DotnetCliPackageBuilder:RunPackageAction
Amazon Lambda Tools for .NET Core applications (5.6.3)
Project Home: https://github.com/aws/aws-extensions-for-dotnet-cli, https://github.com/aws/aws-lambda-dotnet
	
Executing publish command
... invoking 'dotnet publish', working folder '/home/runner/work/guardian/guardian/src/Sidebar/bin/Release/net6.0/publish'
... dotnet publish "/home/runner/work/guardian/guardian/src/Sidebar" --output "/home/runner/work/guardian/guardian/src/Sidebar/bin/Release/net6.0/publish" --configuration "Release" --framework "net6.0" --runtime linux-x64 /p:GenerateRuntimeConfigurationFiles=true --self-contained False 
... publish: MSBuild version 17.5.0-preview-23061-01+040e2a90e for .NET
... publish:   Determining projects to restore...
... publish:   Restored /home/runner/work/guardian/guardian/src/Sidebar/Sidebar.csproj (in 1.02 sec).
... publish: /usr/share/dotnet/sdk/7.0.200/Current/SolutionFile/ImportAfter/Microsoft.NET.Sdk.Solution.targets(36,5): error NETSDK1194: The "--output" option isn't supported when building a solution. [/home/runner/work/guardian/guardian/src/Sidebar/Sidebar.sln]
Failed to create application package

Build Failed
Error: DotnetCliPackageBuilder:RunPackageAction - Dotnet CLI Failed: 
Error: Process completed with exit code 1.

*********** end ***************

Title: SAM CLI Build Fails with Error "NETSDK1194: The "--output" option isn't supported when building a solution" when packaging .NET 6 Lambda application

Description: I encountered an error while using the SAM CLI to package my AWS Lambda application built with .NET 6. When I ran sam build, the command failed with the following error message:

vbnet
Copy code
error NETSDK1194: The "--output" option isn't supported when building a solution.
The full error log is as follows:

vbnet
Copy code
... publish: /usr/share/dotnet/sdk/7.0.200/Current/SolutionFile/ImportAfter/Microsoft.NET.Sdk.Solution.targets(36,5): error NETSDK1194: The "--output" option isn't supported when building a solution. [/home/runner/work/guardian/guardian/src/Sidebar/Sidebar.sln]
Failed to create application package
Build Failed
Error: DotnetCliPackageBuilder:RunPackageAction - Dotnet CLI Failed: 
Error: Process completed with exit code 1.
It appears that the issue is related to the --output option, which is not supported when building a solution. However, this option is being used during the dotnet publish command that is executed as part of the sam build process.

Steps to reproduce:

Build an AWS Lambda application using .NET 6
Run sam build to package the application
Observe the error message shown above
Expected behavior: The sam build command should complete successfully and generate a package for the Lambda application.

Actual behavior: The sam build command fails with the error message shown above.

Workaround: Remove the --output option from the dotnet publish command that is being executed as part of the sam build process. This option is not supported when building a solution, and removing it should allow the sam build command to complete successfully.

```

My application built with .NET 6 has been working without issues for the past year, until this issue occurred recently. Upon checking some posts, I found out that the default version of SAM CLI may have been upgraded to .NET 7, causing a compatibility issue. However, I am not sure how to configure SAM CLI to use .NET 6 instead of the default version.

### Additional environment details (Ex: Windows, Mac, Amazon Linux etc)

1. OS: ubuntu-latest (Github Action container)
2. `sam --version`:  it should be the latest one. cuz I use `aws-actions/setup-sam@v2` in the Github Actions container.

**Comment by SamKiwi2021** [comment]
I found a temporary solution in my case where I discovered that the GitHub Actions runner had three different versions of .NET installed, as shown below:

- 6.0.406
- 7.0.103
- 7.0.200

So, I removed .NET 7, and my original workflow started working correctly.
here is my configuration.

```
            ...
            - uses: actions/checkout@v3
            - uses: actions/setup-dotnet@v3
              with:
                  dotnet-version: "6.0.x"
            - uses: actions/setup-python@v4
              with:
                  python-version: "3.10"
            - uses: aws-actions/setup-sam@v2

            - name: List dotnet SDK versions
              run: ls /usr/share/dotnet/sdk

            - name: Remove dotnet SDK versions
              run: sudo rm -r /usr/share/dotnet/sdk/7.0.103 /usr/share/dotnet/sdk/7.0.200

            - name: Build resources
              run: sam build --template ${SAM_TEMPLATE}
              
              ....
```
