### ISSUE TITLE
Feature request: SAM Connector Suggestions

### ISSUE THREAD

**Issue by allanchua101** [aws/aws-sam-cli#4810]
### Describe your idea/feature/enhancement

Seeing multi-destination connector update was really awesome! However, there are a few more opportunities to improve this feature IMHO.

1. Support for destination types is limited
2. We could still reduce the number of lines required to define connectors in batch.

### Proposal

1. Add support for the following services:
   - Secrets manager
   - SSM parameter
   - SES
   - Rekognition
   - KMS
   - CloudWatch
   - CodeCommit
   - CodePipeline
   - CodeBuild
   - CodeDeploy
   - Firehose
2. We could reduce number of lines if we can get hold of the following syntax:

```yaml
  GetStripePrices:
    Type: AWS::Serverless::Function
    WriteConnectors:
      - Id: SampleTableA
      - Id: SampleTableB
      - Arn: arn:aws:secretsmanager:ap-southeast-1::secret:sample-credential-Lw92LOwe
    ReadConnectors:
      - Id: SampleTableA
      - Id: SampleTableB
      - Arn: arn:aws:secretsmanager:ap-southeast-1::secret:sample-credential-Lw92LOwe
```

Cheers guys!
