### ISSUE TITLE
Bug: How to fix "Dynamic require of "*" is not supported" when using esbuild to deploy Typescript in esm format

### ISSUE THREAD

**Issue by peejayess** [aws/aws-sam-cli#4827]
### Description:
I am deploying a Typescript lambda in esm format using the SAM esbuild feature and at runtime I am getting the "Dynamic require of "*" is not supported" where * are the node built in packages.  In my case, this is being caused by the @opensearch-project package but it could be caused by any cjs package using the node inbuilt packages.

This appears to be a well known [problem](https://github.com/evanw/esbuild/issues/1921) with esbuild, with many suggested workarounds but no apparent fix.  One of the many suggested fixes is to add a banner: `import { createRequire } from 'module';const require = createRequire(import.meta.url);` but banner is not one of the SAM esbuild build properties.

Are there any suggested work arounds for this?  

### Steps to reproduce:
SAM esbuild meta:
```
Metadata:
      BuildMethod: esbuild
      BuildProperties:
        Format: esm 
        Minify: false
        OutExtension:
          - .js=.mjs
        Target: "es2022"
        Sourcemap: true        
        EntryPoints: 
          - src/search_objects/search_objects.ts
```

My search_objects typescript handler has an import:
`import { Client } from "@opensearch-project/opensearch";`

### Observed result:
```
ERROR	Uncaught Exception 	
{
    "errorType": "Error",
    "errorMessage": "Dynamic require of \"events\" is not supported",
    "stack": [
        "Error: Dynamic require of \"events\" is not supported",
        "    at file:///var/task/search_objects.mjs:13:9",
        "    at node_modules/@opensearch-project/opensearch/index.js (/private/var/folders/qv/s3dr8wns2wb13nhymcbbpp580000gn/T/tmpdohwfrfl/node_modules/@opensearch-project/opensearch/index.js:33:26)",
        "    at __require2 (file:///var/task/search_objects.mjs:19:51)",
        "    at <anonymous> (/private/var/folders/qv/s3dr8wns2wb13nhymcbbpp580000gn/T/tmpdohwfrfl/node_modules/@opensearch-project/opensearch/index.mjs:31:17)",
        "    at ModuleJob.run (node:internal/modules/esm/module_job:194:25)"
    ]
}
```

### Expected result:
The imports of node inbuilt packages to work correctly

### Additional environment details (Ex: Windows, Mac, Amazon Linux etc)
sam --info:
```
{
  "version": "1.76.0",
  "system": {
    "python": "3.8.13",
    "os": "macOS-13.2.1-arm64-arm-64bit"
  },
  "additional_dependencies": {
    "docker_engine": "Not available",
    "aws_cdk": "Not available",
    "terraform": "Not available"
  }
}
```

**Comment by mndeveci** [comment]
Thanks for reporting this @peejayess !

Can you provide an example that you are able yo build your function without using `sam build`? I am trying to see if there are additional parameters that we can pass down to esbuild to make it work for your use case.

**Comment by peejayess** [comment]
> Thanks for reporting this @peejayess !
> 
> Can you provide an example that you are able yo build your function without using `sam build`? I am trying to see if there are additional parameters that we can pass down to esbuild to make it work for your use case.

I resolved this yesterday be using esbuild outside of SAM and then just using SAM to load the artifacts. 

My esbuild config was:  

```
let result = await esbuild.build({
    bundle: true,
    platform: "node",
    format: "esm",
    outExtension: { ".js": ".mjs" },
    target: "es2022",    
    minify: false,
    sourcemap: true,
    outdir: "./deploy/dist",
    outbase: "./src/handlers",
    // Fix for https://github.com/evanw/esbuild/pull/2067
    banner: {
        js: "import { createRequire } from 'module'; const require = createRequire(import.meta.url);",
      },
    entryPoints: [
        './src/handlers/searchObjects/searchObjects.ts'
    ],       
})
```

As you can see, it looks like it would be achievable in SAM if the banner config property was added

**Comment by mildaniel** [comment]
This issue should be covered by https://github.com/aws/aws-lambda-builders/pull/498 since you will be able to add the banner flag to your SAM CLI configuration.

**Comment by DanHarman** [comment]
@mildaniel Is there an example of how to do this? On my limited skim of the PR it seemed to have explicit definitions for supported commands and what type they were  and 'banner' is not one of them?

```
   Metadata: # Manage esbuild properties
      BuildMethod: esbuild
      BuildProperties:
        Minify: true
        Sourcemap: true
        Target: "node18"
        Format: esm
        OutExtension: # Undocumented
          - .js=.mjs
        banner:
          js: import { createRequire } from 'module'; const require = createRequire(import.meta.url);
```
```
Building codeuri: /Users/dan/dev/next-valentines/backend/lambda runtime: nodejs18.x metadata: {'BuildMethod':
'esbuild', 'BuildProperties': {'Minify': True, 'Sourcemap': True, 'Target': 'node18', 'Format': 'esm',
'OutExtension': ['.js=.mjs'], 'banner': {'js': "import { createRequire } from 'module'; const require =
createRequire(import.meta.url);"}}} architecture: x86_64 functions: ConnectToDbFunction
Running NodejsNpmEsbuildBuilder:CopySource
Running NodejsNpmEsbuildBuilder:CopySource
Running NodejsNpmEsbuildBuilder:CopySource
Running NodejsNpmEsbuildBuilder:LinkSource
Running NodejsNpmEsbuildBuilder:LinkSource
Running NodejsNpmEsbuildBuilder:NpmInstall
Running NodejsNpmEsbuildBuilder:EsbuildBundle
Running NodejsNpmEsbuildBuilder:EsbuildBundle
Running NodejsNpmEsbuildBuilder:EsbuildBundle

Build Failed
Error: NodejsNpmEsbuildBuilder:EsbuildBundle - ('Failed to determine the type of the configuration: %s', {'js': "import { createRequire } from 'module'; const require = createRequire(import.meta.url);"})
```

**Comment by bretta-seerist** [comment]
@DanHarman This worked for me with the @opensearch-project package.

```
    Metadata: # Manage esbuild properties
      BuildMethod: esbuild
      BuildProperties:
        Format: esm
        Minify: false
        Target: "es2020"
        Sourcemap: true
        OutExtension:
        - .js=.mjs
        EntryPoints: 
        - src/handlers/foo.ts
        Banner:
        - js=import { createRequire } from 'module'; const require = createRequire(import.meta.url);

```

**Comment by DanHarman** [comment]
@bretta-seerist Thanks so much that worked!

**Comment by boringContributor** [comment]
Still facing this problem tbh.

```
 ApiHandlerFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: lambda/ApiHandlerFunction/
      Handler: src/index.handler
      Runtime: nodejs18.x
      Architectures:
        - arm64
      Environment:
        Variables:
          MOCK_ENABLED: !Ref MockEnabled
          UNLEASH_PROXY_URL: !Ref UnleashProxyUrl
          UNLEASH_PROXY_SECRET: !Ref UnleashProxySecret
      
    Metadata: # Manage esbuild properties
      BuildMethod: esbuild
      BuildProperties:
        Format: esm
        Minify: true
        Target: "es2020"
        Sourcemap: true
        OutExtension:
        - .js=.mjs
        EntryPoints: 
        - src/index.ts 
        Banner:
        - js=import { createRequire } from 'module'; const require = createRequire(import.meta.url);
```

this is my simplified template.yml.
I'm using `sam cli 1.95`

When I deploy I get this error:

```
{
    "errorType": "Error",
    "errorMessage": "Dynamic require of \"crypto\" is not supported",
    "stack": [
        "Error: Dynamic require of \"crypto\" is not supported",
        "    at file:///var/task/index.mjs:1:383",
        "    at <anonymous> (/tmp/tmp6npjxgkx/node_modules/@aws-lambda-powertools/logger/src/Logger.ts:1:1)",
        "    at file:///var/task/index.mjs:1:495",
        "    at <anonymous> (/tmp/tmp6npjxgkx/node_modules/@aws-lambda-powertools/logger/src/index.ts:2:1)",
        "    at file:///var/task/index.mjs:1:495",
        "    at <anonymous> (/tmp/tmp6npjxgkx/src/lambda/powertools.ts:1:24)",
        "    at ModuleJob.run (node:internal/modules/esm/module_job:194:25)"
    ]
}
```
