### ISSUE TITLE
No response from invoke container

### ISSUE THREAD

**Issue by brandonmchone23** [aws/aws-sam-cli#4833]
template.yaml file--

```yaml
AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Parameters:
  ProjectName:
    Type: String
Resources:
  unitproject2-brandonmchone23-datastore:
    Type: AWS::S3::Bucket
    Properties:
      BucketName:
        Fn::Join:
        - ''
        - - Ref: unitproject2-brandonmchone23-datastore
          - -datastore
  createdepartment:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ..\..\build\distributions\Application.zip
      Handler: com.kenzie.unit.two.iam.lambda.CreateDepartment
      Runtime: java11
      Description: create department
      MemorySize: 512
      Timeout: 60
      Policies:
      - AWSLambdaBasicExecutionRole
      - AWSLambda_ReadOnlyAccess
      - AWSXrayWriteOnlyAccess
      - AWSLambdaVPCAccessExecutionRole
      - AmazonS3FullAccess
      Tracing: Active
      Environment:
        Variables:
          BucketName:
            Ref: unitproject2-brandonmchone23-datastore
  createuser:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ..\..\build\distributions\Application.zip
      Handler: com.kenzie.unit.two.iam.lambda.CreateUser
      Runtime: java11
      Description: create user
      MemorySize: 512
      Timeout: 60
      Policies:
      - AWSLambdaBasicExecutionRole
      - AWSLambda_ReadOnlyAccess
      - AWSXrayWriteOnlyAccess
      - AWSLambdaVPCAccessExecutionRole
      - AmazonS3FullAccess
      Tracing: Active
      Environment:
        Variables:
          BucketName:
            Ref: unitproject2-brandonmchone23-datastore
  createrole:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ..\..\build\distributions\Application.zip
      Handler: com.kenzie.unit.two.iam.lambda.CreateRole
      Runtime: java11
      Description: create role
      MemorySize: 512
      Timeout: 60
      Policies:
      - AWSLambdaBasicExecutionRole
      - AWSLambda_ReadOnlyAccess
      - AWSXrayWriteOnlyAccess
      - AWSLambdaVPCAccessExecutionRole
      - AmazonS3FullAccess
      Tracing: Active
      Environment:
        Variables:
          BucketName:
            Ref: unitproject2-brandonmchone23-datastore
  getdepartments:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ..\..\build\distributions\Application.zip
      Handler: com.kenzie.unit.two.iam.lambda.GetDepartments
      Runtime: java11
      Description: get departments
      MemorySize: 512
      Timeout: 60
      Policies:
      - AWSLambdaBasicExecutionRole
      - AWSLambda_ReadOnlyAccess
      - AWSXrayWriteOnlyAccess
      - AWSLambdaVPCAccessExecutionRole
      - AmazonS3FullAccess
      Tracing: Active
      Environment:
        Variables:
          BucketName:
            Ref: unitproject2-brandonmchone23-datastore
  getusers:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ..\..\build\distributions\Application.zip
      Handler: com.kenzie.unit.two.iam.lambda.GetUsers
      Runtime: java11
      Description: get users
      MemorySize: 512
      Timeout: 60
      Policies:
      - AWSLambdaBasicExecutionRole
      - AWSLambda_ReadOnlyAccess
      - AWSXrayWriteOnlyAccess
      - AWSLambdaVPCAccessExecutionRole
      - AmazonS3FullAccess
      Tracing: Active
      Environment:
        Variables:
          BucketName:
            Ref: unitproject2-brandonmchone23-datastore
  getroles:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ..\..\build\distributions\Application.zip
      Handler: com.kenzie.unit.two.iam.lambda.GetRoles
      Runtime: java11
      Description: get roles
      MemorySize: 512
      Timeout: 60
      Policies:
      - AWSLambdaBasicExecutionRole
      - AWSLambda_ReadOnlyAccess
      - AWSXrayWriteOnlyAccess
      - AWSLambdaVPCAccessExecutionRole
      - AmazonS3FullAccess
      Tracing: Active
      Environment:
        Variables:
          BucketName:
            Ref: unitproject2-brandonmchone23-datastore
  assignusertorole:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ..\..\build\distributions\Application.zip
      Handler: com.kenzie.unit.two.iam.lambda.AssignUserToRole
      Runtime: java11
      Description: create user role
      MemorySize: 512
      Timeout: 60
      Policies:
      - AWSLambdaBasicExecutionRole
      - AWSLambda_ReadOnlyAccess
      - AWSXrayWriteOnlyAccess
      - AWSLambdaVPCAccessExecutionRole
      - AmazonS3FullAccess
      Tracing: Active
      Environment:
        Variables:
          BucketName:
            Ref: unitproject2-brandonmchone23-datastore
  getuserroles:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ..\..\build\distributions\Application.zip
      Handler: com.kenzie.unit.two.iam.lambda.GetUserRoles
      Runtime: java11
      Description: get user roles
      MemorySize: 512
      Timeout: 60
      Policies:
      - AWSLambdaBasicExecutionRole
      - AWSLambda_ReadOnlyAccess
      - AWSXrayWriteOnlyAccess
      - AWSLambdaVPCAccessExecutionRole
      - AmazonS3FullAccess
      Tracing: Active
      Environment:
        Variables:
          BucketName:
            Ref: unitproject2-brandonmchone23-datastore
  canwarehouseuserpackitem:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ..\..\build\distributions\Application.zip
      Handler: com.kenzie.unit.two.warehouse.lambda.CanUserPackItem
      Runtime: java11
      Description: can warehouse user pack item
      MemorySize: 512
      Timeout: 60
      Policies:
      - AWSLambdaBasicExecutionRole
      - AWSLambda_ReadOnlyAccess
      - AWSXrayWriteOnlyAccess
      - AWSLambdaVPCAccessExecutionRole
      - AmazonS3FullAccess
      Tracing: Active
      Environment:
        Variables:
          BucketName:
            Ref: unitproject2-brandonmchone23-datastore
  viewemployeepaycheck:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ..\..\build\distributions\Application.zip
      Handler: com.kenzie.unit.two.employee.lambda.ViewEmployeePayCheck
      Runtime: java11
      Description: can user view employee paycheck
      MemorySize: 512
      Timeout: 60
      Policies:
      - AWSLambdaBasicExecutionRole
      - AWSLambda_ReadOnlyAccess
      - AWSXrayWriteOnlyAccess
      - AWSLambdaVPCAccessExecutionRole
      - AmazonS3FullAccess
      Tracing: Active
      Environment:
        Variables:
          BucketName:
            Ref: unitproject2-brandonmchone23-datastore
  caninvoiceclient:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ..\..\build\distributions\Application.zip
      Handler: com.kenzie.unit.two.warehouse.lambda.CanInvoiceClient
      Runtime: java11
      Description: can warehouse user pack item
      MemorySize: 512
      Timeout: 60
      Policies:
      - AWSLambdaBasicExecutionRole
      - AWSLambda_ReadOnlyAccess
      - AWSXrayWriteOnlyAccess
      - AWSLambdaVPCAccessExecutionRole
      - AmazonS3FullAccess
      Tracing: Active
      Environment:
        Variables:
          BucketName:
            Ref: unitproject2-brandonmchone23-datastore
```

Image of issue on terminal in Intellij
![image](https://user-images.githubusercontent.com/113073952/223589443-36ac5f2e-db47-4809-9e91-a8576ac52407.png)
