### ISSUE TITLE
Bug: sam validate does not support language extension 

### ISSUE THREAD

**Issue by napso** [aws/aws-sam-cli#4835]
### Description:
sam validate command does not support AWS Language Extensions although it was mentioned to be patched in version 1.56.1. 

Also mentioned [here](https://github.com/aws/aws-sam-cli/issues/4172#issuecomment-1411180370)

### Steps to reproduce:
1. Create a new project with Poetry: `poetry new sam-validate-test`
2. Install aws-sam-cli: `poetry add aws-sam-cli`
3. Create a new SAM template with AWS Language Extensions support: 

such as: 
```yaml
AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::LanguageExtensions'

Parameters:
...

Resources:
  TestBucket:
  Type: AWS::S3::Bucket
  Properties:
  ... 
    UpdateReplacePolicy: !If [IsDevDeployment, "Delete", "Retain"]
    DeletionPolicy: !If [IsDevDeployment, "Delete", "Retain"]
```

4. Validate the SAM template with SAM CLI: `sam validate -t template.yaml`

### Observed result:
The command fails with the following error message:

Error: [InvalidTemplateException('Every DeletionPolicy member must be a string.')] Every DeletionPolicy member must be a string.

### Expected result:
There should be no error message 

### Additional environment details (Ex: Windows, Mac, Amazon Linux etc)

SAM CLI, version 1.76.0

```
❯ sam --info
{
  "version": "1.76.0",
  "system": {
    "python": "3.9.5",
    "os": "Linux-5.10.16.3-microsoft-standard-WSL2-x86_64-with-glibc2.31"
  },
  "additional_dependencies": {
    "docker_engine": "Not available",
    "aws_cdk": "2.53.0 (build 7690f43)",
    "terraform": "Not available"
  }
}

```
