### ISSUE TITLE
Bug: When referencing dynamodb in template and invoking local lambda, TableName is not passed as value.

### ISSUE THREAD

**Issue by mejenborg** [aws/aws-sam-cli#4905]
### Description:
When running sam local invoke on a template, containing an AWS::DynamoDB::Table resource, with a TableName property, and an AWS::Serverless::Function, with environment variable referencing the DynamoDB. The resource name is returned and not the table name.

### Steps to reproduce:
Create a template.yaml containing an AWS::DynamoDB::Table resource, with a TableName property, and an AWS::Serverless::Function resource, with an Environment/Variables/DYNAMODB_TABLE referencing the dynamodb.

```
MyLambdaFunction:
    Type: AWS::Serverless::Function
    Properties:
        ...
        Environment:
            Variables:
              DYNAMODB_TABLE: !Ref MyDynamoDb
...

MyDynamoDb:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: MyTable
```

### Observed result:
DYNAMODB_TABLE environment variable contains "MyDynamoDb" 

### Expected result:
DYNAMODB_TABLE environment variable should contain "MyTable" 

### Additional environment details (Ex: Windows, Mac, Amazon Linux etc)

1. OS: MacOS / Windows (tested on both)
2. `sam --version`: SAM CLI, version 1.71.0
3. AWS region: eu-west-1 (though irrelevant)

```
{
  "version": "1.71.0",
  "system": {
    "python": "3.8.16",
    "os": "macOS-12.6-x86_64-i386-64bit"
  },
  "additional_dependencies": {
    "docker_engine": "20.10.20",
    "aws_cdk": "Not available",
    "terraform": "1.3.7"
  }
}
```
