### ISSUE TITLE
Build Lambda in Container and Debug in VSCode with F5

### ISSUE THREAD

**Issue by IRIElogic** [aws/aws-sam-cli#4914]
As we are running on Windows we have encountered issues with Python packages picking up windows specific modules and failing once in the Lambda.  This led to a requirement to build and test a lambda locally running under an environment exactly like the actual Amazon Linux.  

For this we chose to build the package from a cloudformation template using docker then deploy to the server using sam which is working well.  What I need is to be able to make some code changes, hit F5 in VSCode to build, and debug locally from the local container.  The build is fine but I cannot figure out the correct template.json and launch.json to achieve this.

So far the lambda specific part of my template looks like
```
NielsenAzurePumpLambdaFunction:
    Type: AWS::Serverless::Function
    DependsOn:
    - NielsenAzurePumpLambdaExecutionRole
    Properties:
      PackageType: Image
      CodeUri: code/
      Handler: app.lambda_handler
      ImageUri: "code/app.lambda_handler"
      FunctionName: !Sub "${AWS::StackName}-NielsenAzurePumpLambdaFunction"
      Role: !GetAtt NielsenAzurePumpLambdaExecutionRole.Arn
      Runtime: python3.9
      Description: "Lambda to deliver Nielsen data to the Azure environment"
      Timeout: 900
      MemorySize: 1024
      Environment:
        Variables:
          NOTIFY_QUEUE:
            Ref: SQSQueueName
          AZURE_SAS_TOKEN:
            Ref: AzureSasTokenName
          AZURE_KEY_EXTENSION:
            Ref: AzureKeyExtension
      VpcConfig:
        SecurityGroupIds:
          - !Ref VpcSecurityGroupId
        SubnetIds: !Ref VpcSubnetIds
    Metadata:
      Dockerfile: Dockerfile
      DockerContext: ./code
      DockerTag: v1
    DebugConfig:
        Enabled: true
        DebuggerPath: "/usr/bin/python3.9"
        DebugArgs: "-m ptvsd --host 127.0.0.1 --port 5858 --wait"
        DebugPorts: [5858]

```
With my launch.json
```
{
    "configurations": [
      {
        "name": "NielsenAzurePump in a container",
        "type": "aws-sam",
        "request": "direct-invoke",
        "invokeTarget": {
          "target": "template",
          "templatePath": "${workspaceFolder}/template.yaml",
          "logicalId": "NielsenAzurePumpLambdaFunction"
        },
        "lambda": {
          "payload": {
            "json": {
              "Records": [
                {
                  "eventVersion": "2.0",
                  "eventSource": "aws:s3",
                  "awsRegion": "us-east-1",
                  "eventTime": "1970-01-01T00:00:00.000Z",
                  "eventName": "ObjectCreated:Put",
                  "userIdentity": {
                    "principalId": "EXAMPLE"
                  },
                  "requestParameters": {
                    "sourceIPAddress": "127.0.0.1"
                  },
                  "responseElements": {
                    "x-amz-request-id": "EXAMPLE123456789",
                    "x-amz-id-2": "EXAMPLE123/5678abcdefghijklambdaisawesome/mnopqrstuvwxyzABCDEFGH"
                  },
                  "s3": {
                    "s3SchemaVersion": "1.0",
                    "configurationId": "testConfigRule",
                    "bucket": {
                      "name": "example-bucket",
                      "ownerIdentity": {
                        "principalId": "EXAMPLE"
                      },
                      "arn": "arn:aws:s3:::example-bucket"
                    },
                    "object": {
                      "key": "test%2Fkey",
                      "size": 1024,
                      "eTag": "0123456789abcdef0123456789abcdef",
                      "sequencer": "0A1B2C3D4E5F678901"
                    }
                  }
                }
              ]
            }
          },
          "environmentVariables": {
            "BUCKET_ENDPOINT": "https://127.0.0.1/JustForTesting"
          },
          "runtime": "python3.9"
        }
      }
    ]
}
```
Any assistance on how to configure the debugger correctly for the container would be greatly appreciated.

**Comment by moelasmar** [comment]
Thanks @IRIElogic for raising this question.
I need to raise this issue with the IDE team, as it seems debugging an Image lambda function is not supported through the `aws-sam` launch configuration type.

But, you can still debug it, but you need to do all the following changes manually:
 - update the requirements.txt file to add the `ptvsd` package.
 - update your lambda function code to add the following lines:
 ```
import ptvsd

ptvsd.enable_attach(address=('0.0.0.0', 9999), redirect_output=True)
ptvsd.wait_for_attach()
 ```
 - update the `launch.json` with the following config:
 ```
      {
            "name": "Python: Remote Attach",
            "type": "python",
            "request": "attach",
            "address": "127.0.0.1",
            "port": 5858,
            "localRoot": "${workspaceFolder}/code",
            "remoteRoot": "/var/task",
            "protocol": "inspector",
            "stopOnEntry": false,
            "justMyCode": true
        },
 ```
 - run `sam local invoke` with `-d 5858` option 
 - then form vscode you can start the `Python: Remote Attach` debugging

In the template file, you do not need this section
```
    DebugConfig:
        Enabled: true
        DebuggerPath: "/usr/bin/python3.9"
        DebugArgs: "-m ptvsd --host 127.0.0.1 --port 5858 --wait"
        DebugPorts: [5858]
```
