### ISSUE TITLE
Lambda Proxy integration stopped working after updating to macOS Ventura

### ISSUE THREAD

**Issue by carly-cloud** [aws/aws-sam-cli#4966]
### Description:
After we update to macOS Ventura our Lambda {proxy+} integration does not work locally anymore. It does not find the matching path and ends up with 403 Missing Authentication Token.

If we run the same code with macOS Monterey everything works as expected and we are reaching our code.

Using the full path like `/api/getsomething` works as well.

We use SAM to start our lambda API locally.

This is the SAM template yaml:

```
Events:
    Root:
      Type: Api
      Properties:
        RestApiId: !Ref ApiGatewayApi
        Path: /
        Method: GET
    Proxy:
      Type: Api
      Properties:
        RestApiId: !Ref ApiGatewayApi
        Path: '/{proxy+}'
        Method: ANY
```

### Additional environment details:

1. OS: macOS Ventura 13.3
2. `sam --version`: 17.8
3. AWS region: eu-central-1
