### ISSUE TITLE
Using SAM local start-api for CDK local testing with Cognito users pool Authorizer

### ISSUE THREAD

**Issue by csotomon** [aws/aws-sam-cli#5209]
I have a CDK application and want to use the AWS SAM CLI to test my AWS CDK Lambda function locally.

We have an HTTP API resource using Cognito user pool as an authorizer. However, when I run the` sam local start-api -t ./cdk.out/jai-jpm-dev-Stack.template.json` command, I receive the following error:

Authorizer 'jaijpmdevapiCognitoAuthorizer172F7FD0' with type 'JWT' is currently not supported. Only
Lambda Authorizers of type REQUEST are supported for API Gateway V2.
Linking authorizer skipped for route '/hello', authorizer 'jaijpmdevapiCognitoAuthorizer172F7FD0' is
unsupported or not found
Mounting jai-jpm-dev-hello-lambda at http://127.0.0.1:3000/hello [DELETE, GET, HEAD, OPTIONS, PATCH,
POST, PUT]

Isn't Cognito user pool supported by SAM for CDK local testing, or how can I fix this?"

here is the SAM generated template

```yaml
Resources:
  jaijpmdevuserpool5DCB4580:
    Type: AWS::Cognito::UserPool
    Properties:
      AccountRecoverySetting:
        RecoveryMechanisms:
        - Name: verified_email
          Priority: 1
      AdminCreateUserConfig:
        AllowAdminCreateUserOnly: true
      AutoVerifiedAttributes:
      - email
      EmailVerificationMessage: The verification code to your new account is {####}
      EmailVerificationSubject: Verify your new account
      MfaConfiguration: 'OFF'
      Schema:
      - AttributeDataType: String
        Mutable: true
        Name: tenant
      SmsVerificationMessage: The verification code to your new account is {####}
      UsernameAttributes:
      - email
      UserPoolName: jai-jpm-dev
      UserPoolTags:
        environment: DEV
        project: JPM
      VerificationMessageTemplate:
        DefaultEmailOption: CONFIRM_WITH_CODE
        EmailMessage: The verification code to your new account is {####}
        EmailSubject: Verify your new account
        SmsMessage: The verification code to your new account is {####}
    UpdateReplacePolicy: Retain
    DeletionPolicy: Retain
    Metadata:
      aws:cdk:path: jai-jpm-dev-Stack/jai-jpm-dev-userpool/Resource
  jaijpmdevuserpooljaijpmdevwebclient336D4449:
    Type: AWS::Cognito::UserPoolClient
    Properties:
      UserPoolId:
        Ref: jaijpmdevuserpool5DCB4580
      AllowedOAuthFlows:
      - implicit
      - code
      AllowedOAuthFlowsUserPoolClient: true
      AllowedOAuthScopes:
      - aws.cognito.signin.user.admin
      - openid
      - email
      - profile
      CallbackURLs:
      - http://localhost:4200/
      ClientName: jai-jpm-dev-webclient
      LogoutURLs:
      - http://localhost:4200/
      SupportedIdentityProviders:
      - Ref: jaijpmdevgoogle248CA623
      - COGNITO
    Metadata:
      aws:cdk:path: jai-jpm-dev-Stack/jai-jpm-dev-userpool/jai-jpm-dev-webclient/Resource
  jaijpmdevuserpooljaijpmdevdomain8B4EB1FC:
    Type: AWS::Cognito::UserPoolDomain
    Properties:
      Domain: jai-jpm-dev
      UserPoolId:
        Ref: jaijpmdevuserpool5DCB4580
    Metadata:
      aws:cdk:path: jai-jpm-dev-Stack/jai-jpm-dev-userpool/jai-jpm-dev-domain/Resource
  jaijpmdevgoogle248CA623:
    Type: AWS::Cognito::UserPoolIdentityProvider
    Properties:
      ProviderName: Google
      ProviderType: Google
      UserPoolId:
        Ref: jaijpmdevuserpool5DCB4580
      AttributeMapping:
        email: email
        family_name: family_name
        given_name: given_name
        picture: picture
      ProviderDetails:
        client_id: XXXXXXXXX
        client_secret: XXXXXXXXXX
        authorize_scopes: profile email openid
    Metadata:
      aws:cdk:path: jai-jpm-dev-Stack/jai-jpm-dev-google/Resource
  jaijpmdevhellolambdaServiceRole79E14CC6:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
        - Action: sts:AssumeRole
          Effect: Allow
          Principal:
            Service: lambda.amazonaws.com
        Version: '2012-10-17'
      ManagedPolicyArns:
      - Fn::Join:
        - ''
        - - 'arn:'
          - Ref: AWS::Partition
          - :iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
      Tags:
      - Key: environment
        Value: DEV
      - Key: project
        Value: JPM
    Metadata:
      aws:cdk:path: jai-jpm-dev-Stack/jai-jpm-dev-hello-lambda/ServiceRole/Resource
  jaijpmdevhellolambda8CDCBDB4:
    Type: AWS::Lambda::Function
    Properties:
      Code:
        ImageUri: jaijpmdevhellolambda8cdcbdb4:latest
      Role:
        Fn::GetAtt:
        - jaijpmdevhellolambdaServiceRole79E14CC6
        - Arn
      FunctionName: jai-jpm-dev-hello-lambda
      PackageType: Image
      Tags:
      - Key: environment
        Value: DEV
      - Key: project
        Value: JPM
    DependsOn:
    - jaijpmdevhellolambdaServiceRole79E14CC6
    Metadata:
      DockerBuildArgs: {}
      DockerContext: /iac/cdk.out/asset.aff2bcffe57e1bc89387a2fcbd34c4895185413b2e368e6bff83b77e50ed0ec2
      Dockerfile: Dockerfile
      SamNormalized: true
      SamResourceId: jai-jpm-dev-hello-lambda
      aws:asset:dockerfile-path: Dockerfile
      aws:asset:path: ../../cdk.out/asset.aff2bcffe57e1bc89387a2fcbd34c4895185413b2e368e6bff83b77e50ed0ec2
      aws:asset:property: Code.ImageUri
      aws:cdk:path: jai-jpm-dev-Stack/jai-jpm-dev-hello-lambda/Resource
  jaijpmdevapi2C4AB04D:
    Type: AWS::ApiGatewayV2::Api
    Properties:
      Name: jai-jpm-dev-api
      ProtocolType: HTTP
      Tags:
        environment: DEV
        project: JPM
    Metadata:
      aws:cdk:path: jai-jpm-dev-Stack/jai-jpm-dev-api/Resource
  jaijpmdevapiDefaultStage9F8E99D4:
    Type: AWS::ApiGatewayV2::Stage
    Properties:
      ApiId:
        Ref: jaijpmdevapi2C4AB04D
      StageName: $default
      AutoDeploy: true
      Tags:
        environment: DEV
        project: JPM
    Metadata:
      aws:cdk:path: jai-jpm-dev-Stack/jai-jpm-dev-api/DefaultStage/Resource
  jaijpmdevapiANYhelloHelloIntegration44B98ADF:
    Type: AWS::ApiGatewayV2::Integration
    Properties:
      ApiId:
        Ref: jaijpmdevapi2C4AB04D
      IntegrationType: AWS_PROXY
      IntegrationUri:
        Fn::GetAtt:
        - jaijpmdevhellolambda8CDCBDB4
        - Arn
      PayloadFormatVersion: '2.0'
    Metadata:
      aws:cdk:path: jai-jpm-dev-Stack/jai-jpm-dev-api/ANY--hello/HelloIntegration/Resource
  jaijpmdevapiANYhelloHelloIntegrationPermission50D806E0:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunction
      FunctionName:
        Fn::GetAtt:
        - jaijpmdevhellolambda8CDCBDB4
        - Arn
      Principal: apigateway.amazonaws.com
      SourceArn:
        Fn::Join:
        - ''
        - - 'arn:'
          - Ref: AWS::Partition
          - ':execute-api:'
          - Ref: AWS::Region
          - ':'
          - Ref: AWS::AccountId
          - ':'
          - Ref: jaijpmdevapi2C4AB04D
          - /*/*/hello
    Metadata:
      aws:cdk:path: jai-jpm-dev-Stack/jai-jpm-dev-api/ANY--hello/HelloIntegration-Permission
  jaijpmdevapiANYhello67EC5447:
    Type: AWS::ApiGatewayV2::Route
    Properties:
      ApiId:
        Ref: jaijpmdevapi2C4AB04D
      RouteKey: ANY /hello
      AuthorizationType: JWT
      AuthorizerId:
        Ref: jaijpmdevapiCognitoAuthorizer172F7FD0
      Target:
        Fn::Join:
        - ''
        - - integrations/
          - Ref: jaijpmdevapiANYhelloHelloIntegration44B98ADF
    Metadata:
      aws:cdk:path: jai-jpm-dev-Stack/jai-jpm-dev-api/ANY--hello/Resource
  jaijpmdevapiCognitoAuthorizer172F7FD0:
    Type: AWS::ApiGatewayV2::Authorizer
    Properties:
      ApiId:
        Ref: jaijpmdevapi2C4AB04D
      AuthorizerType: JWT
      Name: CognitoAuthorizer
      IdentitySource:
      - $request.header.Authorization
      JwtConfiguration:
        Audience:
        - Ref: jaijpmdevuserpooljaijpmdevwebclient336D4449
        Issuer:
          Fn::Join:
          - ''
          - - https://cognito-idp.
            - Ref: AWS::Region
            - .amazonaws.com/
            - Ref: jaijpmdevuserpool5DCB4580
    Metadata:
      aws:cdk:path: jai-jpm-dev-Stack/jai-jpm-dev-api/CognitoAuthorizer/Resource
  CDKMetadata:
    Type: AWS::CDK::Metadata
    Properties:
      Analytics: v2:deflate64:H4sIAAAAAAAA/11RTW/CMAz9LdzTUNhlxzEQG7eq087ItF7xaOMqSUFd1P++pB9TtJOfn1+en5ytfE6lS1fwMElR3pKaLtJ9WChuwlNnV3ClyLJ0nwZ1xlyL/Zf6wwvY14TKxqOZWdoDN0AqFszM0p5KLyfbZ5rvVKJ+Y65qjB/8VwyihuZSgnQHLm6oTw1UeOxUYYnHTTHOUDdkjO8GQdBIl/PkHuogsNBnMAatkZHZLjBhJnNs2fgz6P4VDApoqQKLD+jvW+m8y66lYObvVo2uJ2Wx0rBsz7mzI7/r7JU1/fj0g8jRcKcLFOOe8JZUNcqXgcd7ViXZMXeaQN1eQaarl/m31qHGYWaFe7e2DZlCnUIFNMUIKM43auNcWe8btX6Sm1RuNqtvQ5Tozt++QZlP9RfRa2JwNgIAAA==
    Metadata:
      aws:cdk:path: jai-jpm-dev-Stack/CDKMetadata/Default
    Condition: CDKMetadataAvailable
Conditions:
  CDKMetadataAvailable:
    Fn::Or:
    - Fn::Or:
      - Fn::Equals:
        - Ref: AWS::Region
        - af-south-1
      - Fn::Equals:
        - Ref: AWS::Region
        - ap-east-1
      - Fn::Equals:
        - Ref: AWS::Region
        - ap-northeast-1
      - Fn::Equals:
        - Ref: AWS::Region
        - ap-northeast-2
      - Fn::Equals:
        - Ref: AWS::Region
        - ap-south-1
      - Fn::Equals:
        - Ref: AWS::Region
        - ap-southeast-1
      - Fn::Equals:
        - Ref: AWS::Region
        - ap-southeast-2
      - Fn::Equals:
        - Ref: AWS::Region
        - ca-central-1
      - Fn::Equals:
        - Ref: AWS::Region
        - cn-north-1
      - Fn::Equals:
        - Ref: AWS::Region
        - cn-northwest-1
    - Fn::Or:
      - Fn::Equals:
        - Ref: AWS::Region
        - eu-central-1
      - Fn::Equals:
        - Ref: AWS::Region
        - eu-north-1
      - Fn::Equals:
        - Ref: AWS::Region
        - eu-south-1
      - Fn::Equals:
        - Ref: AWS::Region
        - eu-west-1
      - Fn::Equals:
        - Ref: AWS::Region
        - eu-west-2
      - Fn::Equals:
        - Ref: AWS::Region
        - eu-west-3
      - Fn::Equals:
        - Ref: AWS::Region
        - me-south-1
      - Fn::Equals:
        - Ref: AWS::Region
        - sa-east-1
      - Fn::Equals:
        - Ref: AWS::Region
        - us-east-1
      - Fn::Equals:
        - Ref: AWS::Region
        - us-east-2
    - Fn::Or:
      - Fn::Equals:
        - Ref: AWS::Region
        - us-west-1
      - Fn::Equals:
        - Ref: AWS::Region
        - us-west-2
Parameters:
  BootstrapVersion:
    Type: AWS::SSM::Parameter::Value<String>
    Default: /cdk-bootstrap/hnb659fds/version
    Description: Version of the CDK Bootstrap resources in this environment, automatically
      retrieved from SSM Parameter Store. [cdk:skip]
Rules:
  CheckBootstrapVersion:
    Assertions:
    - Assert:
        Fn::Not:
        - Fn::Contains:
          - - '1'
            - '2'
            - '3'
            - '4'
            - '5'
          - Ref: BootstrapVersion
      AssertDescription: CDK bootstrap stack version 6 required. Please run 'cdk bootstrap'
        with a recent version of the CDK CLI.
```
