### ISSUE TITLE
Feature request: --image-repository should not be always required when PackageType is Image

### ISSUE THREAD

**Issue by vangnd** [aws/aws-sam-cli#5372]
### Describe your idea/feature/enhancement

I came across an issue that we use PackageType is Image, however we don't actually build/use image from docker file, it is pulling image straight from ECR so we don't want to define --image-repository at time of deployment.

```yaml
GreetingFunctionUseDocker:
    Type: AWS::Serverless::Function
    Properties:
      PackageType: Image
      ImageUri: xxxxxxxxxx.dkr.ecr.us-west-2.amazonaws.com/greeting:latest
```

### Proposal

Only require ECR when building image from docker file.

Things to consider:
1. Will this require any updates to the [SAM Spec](https://github.com/awslabs/serverless-application-model)
