### ISSUE TITLE
Path is removed from Handler

### ISSUE THREAD

**Issue by ruiwei** [aws/aws-sam-cli#5429]
### Description:
I'm using the "datadg-lambda-js" as a layer. 
`Handler: /opt/nodejs/node_modules/datadog-lambda-js/handler.handler`
The latest version 1.89.0 removed the path and changed it to just "handler.handler"
Version 1.71.0 works

### Additional environment details (Ex: Windows, Mac, Amazon Linux etc)

1. OS: Linux
2. `sam --version`: 1.89.0
3. AWS region: us-east-1

**Comment by hnnasit** [comment]
Hi @ruiwei, could you elaborate more on the issue and provide example/steps for us to help further?

**Comment by ruiwei** [comment]
This is the partial of my template.yaml file:

`Parameters:
  DataDogLayers:
    Description: DataDog layers 
    Type: CommaDelimitedList 
    Default: "arn:aws:lambda:us-east-1:464622532012:layer:Datadog-Node16-x:93, arn:aws:lambda:us-east-1:464622532012:layer:Datadog-Extension:44"   

Resources:
  functionName:
    Type: AWS::Serverless::Function
    Properties:
      Policies: !FindInMap [EnvTypeMap, !Ref EnvType, LambdaPolicyArn]
      **Handler: /opt/nodejs/node_modules/datadog-lambda-js/handler.handler**
      Environment: 
        Variables:
          DD_LAMBDA_HANDLER: src/handlers/institutions.handler
      Timeout: 180
      FunctionName: !Sub ${AWS::StackName}-institutions
      Layers: !Ref DataDogLayers
    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        Minify: true
        Target: es2020
        Sourcemap: true
        EntryPoints:
          - src/handlers/institutions.ts`

After deployed by version 1.89.0, The path is removed from "handler", it should be "/opt/nodejs/node_modules/datadog-lambda-js/handler.handler", not "handler.handler".

**Comment by ruiwei** [comment]
This is the partial of my template.yml.

```
Parameters:
  DataDogLayers:
    Description: DataDog layers 
    Type: CommaDelimitedList 
    Default: "arn:aws:lambda:us-east-1:464622532012:layer:Datadog-Node16-x:93, arn:aws:lambda:us-east-1:464622532012:layer:Datadog-Extension:44"   

Resources:
  functionName:
    Type: AWS::Serverless::Function
    Properties:
      Policies: !FindInMap [EnvTypeMap, !Ref EnvType, LambdaPolicyArn]
      Handler: /opt/nodejs/node_modules/datadog-lambda-js/handler.handler
      Environment: 
        Variables:
          DD_LAMBDA_HANDLER: src/handlers/institutions.handler
      Timeout: 180
      FunctionName: !Sub ${AWS::StackName}-institutions
      Layers: !Ref DataDogLayers
    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        Minify: true
        Target: es2020
        Sourcemap: true
        EntryPoints:
          - src/handlers/institutions.ts  	
```

After deployed by version 1.89.0, **"/opt/nodejs/node_modules/datadog-lambda-js/handler.handler"** changed to just **"handler.handler"**.
