### ISSUE TITLE
Name not defined for resource of type EventBridgeRule  

### ISSUE THREAD

**Issue by garretwilson** [aws/aws-sam-cli#5542]
I had a very straightforward CloudFormation template, containing a Lambda that listened to EventBridge events with the detail type "FooBar". It looked like this

```yaml
  MyEventBus:
    Type: AWS::Events::EventBus
    Properties:
      Name: my-event-bus

  MyFunction:
    Type: AWS::Lambda::Function

…

  MyEventRule:
    Type: AWS::Events::Rule
    Properties:
      Name: !Sub "${AWS::StackName}-my-rule"
      EventBusName: !Ref MyEventBus
      EventPattern:
        detail-type: ["FooBar"]
      Targets:
        - Id: !Ref MyFunction
          Arn: !GetAtt MyFunction.Arn
```

"Use SAM," they said. "SAM will make things easier." So I converted it to SAM. I put the magic stuff at the top:

```yaml
AWSTemplateFormatVersion: 2010-09-09
Transform:
  - AWS::LanguageExtensions
  - AWS::Serverless-2016-10-31
```

Then I "simplified" the function definition (except for the `CodeUri` stuff, which I had to turn into a kludge to work around #5532):

```yaml
  MyFunction:
    Type: AWS::Lambda::Function
    Properties:
      …
      Events:
        Trigger:
          Type: EventBridgeRule
          Properties:
            Name: !Sub "${AWS::StackName}-my-rule"
            EventBusName: !Ref MyEventBus
            Pattern:
              detail-type: ["FooBar"]
            Target:
              Id: !Ref MyFUnction
```

We are truly far from rocket science at this point. But SAM doesn't like that. I do a `sam deploy` and get this:

> `Error: Failed to create changeset for the stack: my-stack, ex: Waiter ChangeSetCreateComplete failed: Waiter encountered a terminal failure state: For expression "Status" we matched expected path: "FAILED" Status: FAILED. Reason: Transform AWS::Serverless-2016-10-31 failed with: Invalid Serverless Application Specification document. Number of errors found: 1. Resource with id [MyFunctionTrigger] is invalid. property Name not defined for resource of type EventBridgeRule`

Please tell me this is not (again!) what I think it is. Please tell me I am making some mistake and I have screwed up the conversion. Please tell me I'm being slow this morning and have made a typo or something. Please tell me this is not SAM again making things "simple" for me and wasting my day to file bugs.

Please, I want the mistake to be mine. I would welcome it.

**Comment by garretwilson** [comment]
> Please, I want the mistake to be mine. I would welcome it.

It appears unfortunately that I made no mistake and this is yet again SAM getting horribly confused when I try to do anything interesting—that is, anything in real life that doesn't appear as an example in a tutorial.

I commented out the `Name`:

```yaml
  MyFunction:
    Type: AWS::Lambda::Function
    Properties:
      …
      Events:
        Trigger:
          Type: EventBridgeRule
          Properties:
            #TODO bring back when https://github.com/aws/aws-sam-cli/issues/5542 is fixed: Name: !Sub "${AWS::StackName}-my-rule"
            EventBusName: !Ref MyEventBus
            Pattern:
              detail-type: ["FooBar"]
            Target:
              Id: !Ref MyFUnction
```

(Funny, my SAM template is becoming full such lines: "bring back when bug XXX is fixed".)

And that allowed it to deploy.

Unfortunately, it looks like SAM won't let me use a simple `Fn::Sub` in the name of an `EventBridgeRule`—something that is like a 1.5 on a scale of 1–10 for "complexity".

People, seriously. I mean this is every day. I haven't even tried to do anything complicated with SAM yet!

I want to be a team player. Why don't you hire me and let me help you fix all these problems? I'm serious. Completely serious. Bring me on board. I'll work with you to make it work. And not just work, but make it solid.
