### ISSUE TITLE
Bug: Inconsistent behavior of REST/HTTP resolver in local environment.

### ISSUE THREAD

**Issue by rubenfonseca** [aws/aws-sam-cli#5579]
### Description:

Inconsistent behavior of REST/HTTP resolver in local environment.

This issue was raised by a Powertools for AWS Lambda (Python) here https://github.com/aws-powertools/powertools-lambda-python/issues/2765

SAM template

```
    Api:
        Type: AWS::Serverless::Api
        Properties:
            StageName: prod

    HttpApi:
        Type: AWS::Serverless::HttpApi
        Properties:
            StageName: prod

    HelloWorldFunction:
        Type: AWS::Serverless::Function
        Properties:
            Events:
                HelloPath:
                    Type: HttpApi
                    Properties:
                        RestApiId: !Ref Api
                        ApiId: !Ref HttpApi
                        Path: /hello
                        Method: GET
```

### Steps to reproduce:

- Create a SAM template application from 1 - AWS Quick Start Templates then 3 - Hello World Example with Powertools for AWS Lambda then python3.10. See: [tinti/sam-api-httpapi](https://github.com/tinti/sam-api-httpapi)

- Add explicit Api and HttpApi resources with StageName: prod property to the template.

- Reference the Api or HttpApi resource in the Lambda's event source.

- Start local api with sam local start-api

- Test with and without StageName: prod doing `curl -v -X GET --silent localhost:3000/hello`

### Observed result:

| Type  | Stage | Expected path | Current path |
| - | - | - | - |
| RestApi  | $default  | /hello | /hello |
| RestApi  | prod  | /hello | /hello |
| HttpApi  | $default  | /hello | /hello |
| HttpApi  | prod  | /hello | /o|

### Expected result:

In both cases when running `sam local start-api` both API gateway instances should try to match /hello.

### Additional environment details (Ex: Windows, Mac, Amazon Linux etc)

```
{
  "version": "1.92.10",
  "system": {
    "python": "3.8.17",
    "os": "macOS-13.4.1-arm64-arm-64bit"
  },
  "additional_dependencies": {
    "docker_engine": "24.0.4",
    "aws_cdk": "2.84.0 (build f7c792f)",
    "terraform": "Not available"
  },
  "available_beta_feature_env_vars": [
    "SAM_CLI_BETA_FEATURES",
    "SAM_CLI_BETA_BUILD_PERFORMANCE",
    "SAM_CLI_BETA_TERRAFORM_SUPPORT",
    "SAM_CLI_BETA_RUST_CARGO_LAMBDA"
  ]
}

```
