### ISSUE TITLE
Bug: SAM does not write Layer build results to `build.toml`

### ISSUE THREAD

**Issue by davidjb** [aws/aws-sam-cli#5585]
### Description:

Starting with an empty environment (e.g. no `.aws-sam` directory or no `.aws-sam/build.toml` file), attempting to build a layer by itself:

```sh
sam build --cached --use-container MyLayer
```

does not result in the layer's build results being written to `.aws-sam/build.toml`. In fact, this file does not even get created. 

This means that subsequent calls to the same build command will not use the cache, despite cached files being created in `.aws-sam/cache` and that a problem such as #5507 cannot be worked around.  

### Steps to reproduce:

1. Remove any `.aws-sam` directory or `.aws-sam/build.toml` file
2. Define a Layer such as:
   ```yaml
   DecoderLayer:
     Type: AWS::Serverless::LayerVersion
     Properties:
       ContentUri: layers/mylayer/
       CompatibleRuntimes:
         - provided.al2
     Metadata:
       BuildMethod: makefile
   ```

   ```make
  build-MyLayer:
        mkdir "$(ARTIFACTS_DIR)/bin"
        echo 'dummy' > "$(ARTIFACTS_DIR)/bin/dumy"
   ```

3. Build that layer with: `sam build --cached --use-container MyLayer`
4. Observe that no `.aws-sam/build.toml` file is created.
5. Try and re-run `sam build` command and layer will not have been cached.

### Observed result:

```sh
```

### Expected result:

Layer to be cached and recorded, available for subsequent runs of `sam build`.

### Additional environment details (Ex: Windows, Mac, Amazon Linux etc)

```json
{
  "version": "1.93.0",
  "system": {
    "python": "3.10.6",
    "os": "Linux-5.19.0-1022-aws-x86_64-with-glibc2.35"
  },
  "additional_dependencies": {
    "docker_engine": "20.10.24",
    "aws_cdk": "Not available",
    "terraform": "Not available"
  },
  "available_beta_feature_env_vars": [
    "SAM_CLI_BETA_FEATURES",
    "SAM_CLI_BETA_BUILD_PERFORMANCE",
    "SAM_CLI_BETA_TERRAFORM_SUPPORT",
    "SAM_CLI_BETA_RUST_CARGO_LAMBDA"
  ]
}
```

**Comment by mildaniel** [comment]
Thanks for reporting. I was able to reproduce this and we welcome contributions if you'd like to help fix this issue!

**Comment by moelasmar** [comment]
@davidjb , the steps you mentioned as a workaround does not work on my side. My findings is SAM CLI does not write to `build.toml` file even if exist in case if SAM CLI was invoked to build specific resources:

https://github.com/aws/aws-sam-cli/blob/46c374f79c4a21869cd02423f91bd0eda1dbee79/samcli/lib/build/app_builder.py#L264

https://github.com/aws/aws-sam-cli/blob/d8418011244a6c21aa63093f8963713288801986/samcli/lib/build/build_graph.py#L320-L321

https://github.com/aws/aws-sam-cli/blob/d8418011244a6c21aa63093f8963713288801986/samcli/lib/build/build_graph.py#L442-L479

I will check with the team if this was done on purpose.

**Comment by moelasmar** [comment]
I checked this issue with the team, and we confirmed that SAM CLI does not create the `build.toml` file when ASM CLI build specific resources, because we do not create the build graph in this case, and so we will not be able to create the `build.toml` file.

The work around for this issue now is to first run `sam build --cached` which will create the `build.toml` file, and then the subsequent `sam build --cached <<specific resource>>` commands executions will check the cached build of this resource, and skipped it if it is already cached.

**Comment by davidjb** [comment]
@moelasmar So the issue is trying to reach a point where a `sam build --cached` can succeed in the first place, especially given other issues such as https://github.com/aws/aws-sam-cli/issues/5280.

It may be possible to change configurations and hack things up until `sam build` yields an entry in `build.toml`, but I'm thinking that a more reliable workaround is to generate a fake resource entry into `build.toml`, such as:

```toml
[layer_build_definitions.00000000-0000-0000-0000-000000000000]
layer_name = "MyLayer"
codeuri = "/path/to/layers/mylayer"
build_method = "makefile"
compatible_runtimes = ["provided.al2"]
architecture = "arm64"
source_hash = "fake"
manifest_hash = ""
layer = "MyLayer"
```

Once this exists, then running `sam build --cached <<specific resource>>` updates `source_hash` correctly after that. Provided the UUID is any fake value, this appears to work.

Could a similar strategy be added into `sam` itself? For layer in particular, there are no dependencies or build graphs, just that resource itself, so outputting the layer's config alone would be sufficient to solve this problem.
