### ISSUE TITLE
Bug: `sam build` does not rename executables to `bootstrap` when using `provided.al2`

### ISSUE THREAD

**Issue by pkit** [aws/aws-sam-cli#5781]
### Description:

See the title.

### Steps to reproduce:

Use a perfectly normal template for `go1.x`
```
Globals:
  Function:
    Timeout: 5
    MemorySize: 128
    Runtime: go1.x

Resources:
  HelloWorldFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: "hello-world"
      CodeUri: ./api/hello-world/
      Handler: main
      Events:
        CatchAll:
          Type: Api
          Properties:
            Path: /hello
            Method: GET
```
Then change it to `provided.al2`
```
Globals:
  Function:
    Timeout: 5
    MemorySize: 128
    Runtime: provided.al2

Resources:
  HelloWorldFunction:
    Type: AWS::Serverless::Function
    Metadata:
      BuildMethod: go1.x
    Properties:
      FunctionName: "hello-world"
      CodeUri: ./api/hello-world/
      Handler: main
      Events:
        CatchAll:
          Type: Api
          Properties:
            Path: /hello
            Method: GET
```

### Observed result:

- go1.x: works fine
- provided.al2: `sam build` produces executable with the name `main` instead of `bootstrap` and it fails to run with `Server error` for obvious reasons

### Expected result:

Expected to work.
Renaming all the executables to `bootstrap` immediately fixes the problem.

Just FYI: I'm not gonna convert **every** function into a full package with `go.mod` and friends, just because `sam build` cannot rename.
