### ISSUE TITLE
How to use sam local invoke using Java 17

### ISSUE THREAD

**Issue by dehan-jl** [aws/aws-sam-cli#5862]
So I'm following this guide from quarkus: https://quarkus.io/guides/aws-lambda on developing an AWS lambda. After doing a `./gradlew build` and then a `sam invoke local`, I'm getting the following error:
```
Caused by: java.lang.UnsupportedClassVersionError: com/example/lambda/Person has been compiled by a more recent version of the Java Runtime (class file version 61.0), this version of the Java Runtime only recognizes class file version
s up to 55.0
```
Earlier in the logs I can see
```
Invoking io.quarkus.amazon.lambda.runtime.QuarkusStreamHandler::handleRequest (java11)
```

So as far as I can tell, sam is invoking the lambda using java11, but the code was compiled for java17. Is there any way I can tell sam to use java17 and not java11?

If I do a native build, `sam invoke local` works perfectly fine, but I'd like to get non-native builds running and setting the build target to java11 is not an option.

**Comment by hawflau** [comment]
@dehan-jl Thanks for raising the issue. Could you please provide the SAM template that you use in the `sam local invoke` command run?

**Comment by dehan-jl** [comment]
@hawflau This is the `sam local invoke` template that is provided with the Quarkus starter code.

```yaml
AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: AWS Serverless Quarkus - quarkus-amazon-lambda-common-deployment
Globals:
  Api:
    EndpointConfiguration: REGIONAL
    BinaryMediaTypes:
      - "*/*"

Resources:
  QuarkusLambda:
    Type: AWS::Serverless::Function
    Properties:
      Handler: io.quarkus.amazon.lambda.runtime.QuarkusStreamHandler::handleRequest
      Runtime: java11
      CodeUri: function.zip
      MemorySize: 256
      Timeout: 15
      Policies: AWSLambdaBasicExecutionRole
```
