### ISSUE TITLE
AWS SAM with !ImportValue and !Ref cannot use together

### ISSUE THREAD

**Issue by KaralinaDubitskaya** [aws/aws-sam-cli#5884]
I have a Lambda function to deploy using AWS SAM. In some way, I cannot build stack if I set up layers using `!ImportValue` and `!Ref` together. If I comment one of them, it builds without errors.

```
Parameters:
  LoggingLayerARN:
    Type: AWS::SSM::Parameter::Value<String>
    Default: /some/parameter
   
TestLambda:
    Type: AWS::Serverless::Function
    Properties:
      Layers:
        - !ImportValue AnotherStackLayer
        - !Ref SSMParameterLayerARN
```

The error I've got:

`Layer References need to be of type 'AWS::Serverless::LayerVersion' or 'AWS::Lambda::LayerVersion'`

**Comment by mndeveci** [comment]
Thanks for reporting the issue.

I've verified that it is failing if you define both `!ImportValue` and `!Ref` at the same time. The problem is, when running `sam build`, it is looking for resolved `!Ref` intrinsics (`Val` instead of `{'Ref': 'Val'}`), and if it finds unresolved `!Ref` intrinsic, the build fails.

This won't happen if you just use `!Ref` because then it can resolve the value and continues build process.

And this also won't happen if you use `!ImportValue` because even though it can't resolve the intrinsic, `sam build` skips those layers.

I will be taking this to the team to see how we can resolve this issue.

In the meantime, as a workaround, can you try to build with following resource definition which is not affected with this error;
```
Parameters:
  LoggingLayerARN:
    Type: AWS::SSM::Parameter::Value<String>
    Default: /some/parameter
   
TestLambda:
    Type: AWS::Serverless::Function
    Properties:
      Layers:
        - !ImportValue AnotherStackLayer
        - !Join [ '', [!Ref SSMParameterLayerARN]]
```
