### ISSUE TITLE
Feature request: Customize `LayerVersion` caching / update condition

### ISSUE THREAD

**Issue by sansmoraxz** [aws/aws-sam-cli#5885]
I have a lambda where I am using poety to manage my dependencies. I am using a Makefile to create the layer
```make
PY ?= python
POETRY ?= poetry
PIP ?= pip

build-BackendFunctionLayer:
    mkdir -p "$(ARTIFACTS_DIR)/python"
    $(POETRY) export --format=requirements.txt > requirements.txt
    $(PIP) install -r requirements.txt -t "$(ARTIFACTS_DIR)/python" \
        --implementation cp --platform manylinux2014_x86_64 --only-binary=:all: --
```

Using the following in sam template:
```yaml
BackendFunctionLayer:
Type: AWS::Serverless::LayerVersion
Metadata:
    BuildMethod: makefile
    BuildArchitecture: amd64
Properties:
    ContentUri: .
    CompatibleArchitectures:
    - x86_64
    CompatibleRuntimes:
    - python3.10
```

However this does trigger a rebuild for the layer everytime I make a code change. I would like `sam build` to skip the layer build if the package manager files in this case being `pyproject.toml` and `poetry.lock` has not changed.

### Proposal

Maybe some condition to the script itself to check if the config files have changed and if not skip the build.

```yaml
BackendFunctionLayer:
Type: AWS::Serverless::LayerVersion
Metadata:
    BuildMethod: makefile
    BuildArchitecture: amd64
Properties:
    ContentUri: .
    CompatibleArchitectures:
    - x86_64
    CompatibleRuntimes:
    - python3.10
    Condition:
        CheckFiles:
        - pyproject.toml
        - poetry.lock
```

**Comment by mndeveci** [comment]
Thanks for creating the issue and suggestion.

I think some part of this slowness comes from the fact that, `Makefile` builds happen in a temporary directory every time SAM CLI builds. For that reason, subsequent ones are not benefiting from any underlying caching or incremental builds.

We are working on a project which will allow users to use existing source folders for building their functions. Once that is implemented, the performance of your builds should be improved as well (assuming poetry does some caching under the hood).

You can track the project here: https://github.com/aws/aws-sam-cli/issues/4571

**Comment by sansmoraxz** [comment]
Increased build speed can certainly be a benefit, but that's not the issue here.

I want a way to control when `sam build` skips building certain components if they are not changed.

For example, if the pacman file and the lock file are not changed, we can reuse the existing built layer. `manifest_hash` probably already does that.

However, here's how it looks like in `.aws-sam/build.toml`

```toml
[layer_build_definitions.6fe3c20f-6b61-4f23-b771-df1a3c159e3f]
layer_name = "BackendFunctionLayer"
codeuri = "/home/<USER>/<PROJECT>"
build_method = "makefile"
compatible_runtimes = ["python3.10"]
architecture = "amd64"
source_hash = "4f40dba34e00005ff74952bd856bc82738278cbc2e3d30988cf433c42816f2a3"
manifest_hash = ""
layer = "BackendFunctionLayer"
```
