### ISSUE TITLE
I try to build and deploy new lambda function but function missing

### ISSUE THREAD

**Issue by thanakiat-h** [aws/aws-sam-cli#6124]
I have issue with a `sam build `when I add FunctionC on sam debug log it show only 2 function (A and B) but FunctionC not showing
,and I try to deploy using `sam deploy` it stuck on UPDATE PROGRESS of LambdaFunction

before I using sam cli version 1.3.xx , and now I already update sam cli to latest version  1.99.0 still not working

MyTemplate like this 

```
  FunctionA:
    Type: AWS::Serverless::Function 
    DependsOn: MyRole
    Properties:
      CodeUri: ../functions/payment
      Handler: webhook.lambda_handler
      Layers:
        - !Ref /MyLayer 
      Runtime: python3.8
      Architectures:
        - x86_64
      Role: !GetAtt MyRole.Arn
    Metadata:
      FunctionName: FunctionA

  FunctionB:
    Type: AWS::Serverless::Function #
    DependsOn: MyRole
    Properties:
      CodeUri: ../functions/payment
      Handler: my_functions.create_checkout_session
      Layers:
        - !Ref /MyLayer 
      Runtime: python3.8
      Architectures:
        - x86_64
      Role: !GetAtt MyRole.Arn
    Metadata:
      FunctionName: FunctionB
  FunctionC: 
    Type: AWS:Serverless:Function
    DependsOn: MyRole
    Properties:
      CodeUri: ../functions/payment
      Handler: new.lambda_handler
      Layers:
        - !Ref /MyLayer
      Runtime: python3.8
      Architectures:
        - x86_64
      Role: !GetAtt MyRole.Arn
    Metadata:
      FunctionName: FunctionC
```

**Comment by thanakiat-h** [comment]
I try to copy FunctionC to FunctionD and build again 

now it's working and I remove FunctionC and using FunctionD instead,
still don't know what issue but working now kub

```
 FunctionA:
    Type: AWS::Serverless::Function 
    DependsOn: MyRole
    Properties:
      CodeUri: ../functions/payment
      Handler: webhook.lambda_handler
      Layers:
        - !Ref /MyLayer 
      Runtime: python3.8
      Architectures:
        - x86_64
      Role: !GetAtt MyRole.Arn
    Metadata:
      FunctionName: FunctionA

  FunctionB:
    Type: AWS::Serverless::Function #
    DependsOn: MyRole
    Properties:
      CodeUri: ../functions/payment
      Handler: my_functions.create_checkout_session
      Layers:
        - !Ref /MyLayer 
      Runtime: python3.8
      Architectures:
        - x86_64
      Role: !GetAtt MyRole.Arn
    Metadata:
      FunctionName: FunctionB
  FunctionC: 
    Type: AWS:Serverless:Function
    DependsOn: MyRole
    Properties:
      CodeUri: ../functions/payment
      Handler: new.lambda_handler
      Layers:
        - !Ref /MyLayer
      Runtime: python3.8
      Architectures:
        - x86_64
      Role: !GetAtt MyRole.Arn
    Metadata:
      FunctionName: FunctionC
  FunctionD: 
    Type: AWS:Serverless:Function
    DependsOn: MyRole
    Properties:
      CodeUri: ../functions/payment
      Handler: new.lambda_handler
      Layers:
        - !Ref /MyLayer
      Runtime: python3.8
      Architectures:
        - x86_64
      Role: !GetAtt MyRole.Arn
    Metadata:
      FunctionName: FunctionD
```
