### ISSUE TITLE
Bug: EventBridge "Combined template" approach does not work as documented

### ISSUE THREAD

**Issue by Joymaker** [aws/aws-sam-cli#6252]
### Description:
Following the Combined Template description of [this documentation](https://docs.aws.amazon.com/eventbridge/latest/userguide/eb-use-sam.html#eb-combined-template), I built this Lambda function in my template.yaml file as follows, believing that it would automatically create an EventBridge rule out of the material here. In fact, no such rule was created, I deployed and there is no rule named OnBatchJobStateChange or anything of the sort.
A rule type of CloudWatchRule doesn't work either.

```
AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Globals:  # More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
  Function:
    Timeout: 15
    Tracing: Active
  Api:
    TracingEnabled: true
BlastDbUpdaterFunction:
    _comment: "runs as needed to keep our data base updated to the state of batch jobs"
    Type: AWS::Serverless::Function
    Properties:
      PackageType: Image
      Architectures:
      - x86_64
      CodeUri: /
      ImageConfig:
        Command:
        - blast-db-updater.lambda_handler
      ImageUri:   BlastDbUpdaterFunction:latest
    Events:
      Trigger:
        Type: EventBridgeRule 
        Properties:
          RuleName: OnBatchJobStateChange
          Pattern:
            source:
              - aws.batch
            detail-type:
              - Batch Job State Change                
    Metadata:
      Dockerfile: Dockerfile
      DockerContext: .
      DockerTag: python3.11-v1
```
Minimal lambda source:
```
def lambda_handler(event, _context):
    print(json.dumps("Eventbridge event:",event))

```

### Steps to reproduce:
sam build
sam deploy

### Observed result:
ATTACHED AS FILE BECAUSE THE OUTPUT IS TOO LONG

NB:  My actually template involves 5 Lambda functions, hence more output

[Sam debug output for issue.txt](https://github.com/aws/aws-sam-cli/files/13328945/Sam.debug.output.for.issue.txt)

### Expected result:
EventBridge console shows a new rule.

### Additional environment details (Ex: Windows, Mac, Amazon Linux etc)

1. OS: MacOS 10.6
2. `sam --version`: SAM CLI, version 1.99.0
3. AWS region: us-west-2

```
% sam --info
{
  "version": "1.99.0",
  "system": {
    "python": "3.8.13",
    "os": "macOS-11.6-x86_64-i386-64bit"
  },
  "additional_dependencies": {
    "docker_engine": "Not available",
    "aws_cdk": "Not available",
    "terraform": "Not available"
  },
  "available_beta_feature_env_vars": [
    "SAM_CLI_BETA_FEATURES",
    "SAM_CLI_BETA_BUILD_PERFORMANCE",
    "SAM_CLI_BETA_TERRAFORM_SUPPORT",
    "SAM_CLI_BETA_RUST_CARGO_LAMBDA"
  ]
}
```
