### ISSUE TITLE
Error when running sam local invoke (Sandbox.Failure)

### ISSUE THREAD

**Issue by gustavofreze** [aws/aws-sam-cli#6438]
I'm building and then invoking my lambda function locally. When I do this, I encounter the error log below:

```shell
2023-12-12 02:22:12,867 | Starting a timer for 10 seconds for function 'Xpto'                                                                               
START RequestId: aa44dfa6-ec8f-4149-a65e-98e75e84458e Version: $LATEST
11 Dec 2023 23:22:13,330 [ERROR] (rapid) Init failed InvokeID= error=Runtime exited without providing a reason
11 Dec 2023 23:22:13,330 [ERROR] (rapid) Invoke failed error=Runtime exited without providing a reason InvokeID=b17a6eea-8d8f-4ee6-bbd7-db0a8de2fb96
11 Dec 2023 23:22:13,331 [ERROR] (rapid) Invoke DONE failed: Sandbox.Failure
2023-12-12 02:22:13,333 | Failed to deserialize response from RIE, returning the raw response as is 
```

I didn't find any specific references on how to proceed.

I will provide what I believe is relevant to the problem. I've already checked that `main.py` is not being called. That is, the error occurs before executing the code.

**Project structure**: 

```
xpto/
┣ .aws/
┣ .aws-sam/
┣ event/
┣ src/
┃ ┗ main.py
┣ Dockerfile
┣ Makefile
┣ requirements.txt
┣ samconfig.toml
┗ template.yml
```

My **Dockerfile**:

```dockerfile
FROM python:3.11-alpine

ENV AWS_PROFILE="default"
ENV AWS_CONFIG_FILE="/app/.aws/config"
ENV SAM_CLI_TELEMETRY=0

ENV VIRTUAL_ENV="/opt/venv"
ENV PATH="${VIRTUAL_ENV}/bin:${PATH}"
ENV PIP_PATH="${VIRTUAL_ENV}/bin/pip"

WORKDIR /app

COPY src src
COPY .aws .aws
COPY requirements.txt requirements.txt

RUN python -m venv ${VIRTUAL_ENV} \
    && ${PIP_PATH} install --no-cache-dir --upgrade pip \
    && ${PIP_PATH} install --no-cache-dir --upgrade wheel awscli aws-sam-cli \
    && ${PIP_PATH} install --no-cache-dir --upgrade -r requirements.txt

CMD ["python", "-m", "src.main"]
```

My **template.yml**:

```yaml
AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Globals:
  Function:
    Timeout: 10
    MemorySize: 1024

Resources:
  Xpto:
    Type: AWS::Serverless::Function
    Properties:
      Layers:
        - !Ref Dependencies
      Runtime: python3.11
      ImageUri: xpto:latest
      PackageType: Image
      FunctionName: xpto
      Architectures:
        - x86_64
      Events:
        AtEveryMinute:
          Type: Schedule
          Properties:
            Enabled: true
            ScheduleExpression: rate(1 minute)
      Environment:
        Variables:
          TZ: "America/Sao_Paulo"
    Metadata:
      DockerTag: latest
      Dockerfile: Dockerfile
      DockerContext: .
      SamResourceId: Xpto
    Policies:
      - AWSLambdaBasicExecutionRole

  Dependencies:
    Type: AWS::Serverless::LayerVersion
    Properties:
      ContentUri: .
      RetentionPolicy: Retain
      CompatibleRuntimes:
        - python3.11
    Metadata:
      BuildMethod: python3.11
      SamResourceId: Dependencies
      BuildArchitecture: x86_64
```

My **samconfig.toml**:

```toml
version = 0.1

[default]
[default.global]
[default.global.parameters]
stack_name = "xpto"

[default.build]
[default.build.parameters]
cached = false
parallel = true
use_container = true
skip_pull_image = true

[default.sync]
[default.sync.parameters]
watch = true

[default.validate]
[default.validate.parameters]
lint = true

[default.local_invoke]
[default.local_invoke.parameters]
event = "event/event.json"
profile = "default"
no_event = false
```

My data in **.aws**: 

- **config** file:
```
[default]
output = json
region = us-east-1
```

And finally, the command I execute in my **makefile**:

```makefile
SAM_BUILD = sam build
SAM_INVOKE = sam local invoke Xpto --debug
LAMBDA_IMAGE = xpto:latest
GENERATE_EVENT = python -m event.create_event

invoke:
	@docker run -it --rm -v /var/run/docker.sock:/var/run/docker.sock -v ${PWD}:/app -w /app --network=host \
        ${LAMBDA_IMAGE} sh -c "${SAM_BUILD} && ${GENERATE_EVENT} && ${SAM_INVOKE}"
```
