### ISSUE TITLE
Bug: sam delete works with global parameters defined in toml, but not yaml

### ISSUE THREAD

**Issue by rhbecker** [aws/aws-sam-cli#6449]
### Description:

The `sam delete` command cannot seem to find parameters defined in a `global` section of `samconfig.yaml` (but the same parameters specified in `samconfig.toml` work fine).

### Steps to reproduce:

These commands work fine with both `toml` and `yaml` editions of `samconfig` ...

```shell
sam build --config-env test
```
```shell
sam deploy --config-env test
```

This command works fine with the `toml` edition, but not the `yaml` edition of `samconfig` ...

```shell
sam delete --config-env test
```

Example toml file ...

```toml
version = 0.1

[test.global.parameters]
confirm_changeset = true
image_repositories = [ ]
parameter_overrides = [ ]
region = "us-west-2"
s3_bucket = "build-artifacts-REDACTED-ID"
s3_prefix = "cloudformation/sam-cli/test"
stack_name = "test"
template = ".dev/tests/test.yaml"
```

Example yaml file ...

```yaml
version: 0.1
test:
  global:
    parameters:
      confirm_changeset: true
      image_repositories: []
      parameter_overrides: []
      region: us-west-2
      s3_bucket: build-artifacts-REDACTED-ID
      s3_prefix: cloudformation/sam-cli/test
      stack_name: test
      template: .dev/tests/test.yaml
```

### Observed result:

Executing `sam delete --config-env test` with the `yaml` edition of `samconfig` results in a prompt ...

> Enter stack name you want to delete

... but `stack_name` _is_ specified.

If I play along, and execute ...

```shell
sam delete --config-env test --stack-name test
```

... it deletes the stack, but then can't find the parameters it needs to use to find the template in S3 ...

> Warning: Cannot resolve s3 bucket information from command options , local config file or cloudformation template. Please use --s3-bucket next time and delete s3 files manually if required.

### Expected result:

Configuration specified via `yaml` should function in an equivalent manner to configuration specified via `toml`.

### Additional environment details (Ex: Windows, Mac, Amazon Linux etc)

1. OS: Ubuntu via WSL on Windows 10
2. `sam --version`: 1.105.0
3. AWS region: us-west-2

```
# Paste the output of `sam --info` here
{
  "version": "1.105.0",
  "system": {
    "python": "3.11.3",
    "os": "Linux-5.15.90.1-microsoft-standard-WSL2-x86_64-with-glibc2.31"
  },
  "additional_dependencies": {
    "docker_engine": "Not available",
    "aws_cdk": "Not available",
    "terraform": "Not available"
  },
  "available_beta_feature_env_vars": [
    "SAM_CLI_BETA_FEATURES",
    "SAM_CLI_BETA_BUILD_PERFORMANCE",
    "SAM_CLI_BETA_TERRAFORM_SUPPORT",
    "SAM_CLI_BETA_RUST_CARGO_LAMBDA"
  ]
}
```
