### ISSUE TITLE
Bug: AWS::Serverless::Function Policies partly not applied

### ISSUE THREAD

**Issue by ehuebner** [aws/aws-sam-cli#6499]
With sam I deploy a nodejs application that writes a file to S3. Unfortunately all policies I add to my lambda function to grand access to S3 are not deployed. The deployment of the stack works without any error message but the `S3CrudPolicy` is not applied. It looks like they are just ignored. I also tried `S3FullAccessPolicy` and `S3WritePolicy` but they do not get deployed either.
The `CloudWatchLambdaInsightsExecutionRolePolicy` and `SQSSendMessagePolicy` are successfully deployed and I can see them in the AWS frontend.
When I add `S3FullAccessPolicy` in the frontend, I am able to successfully execute my code and write from my lambda function to S3.

What am I doing wrong?

Here is the snipped from the CF template:
```
MyFunc:
        Type: AWS::Serverless::Function
        Properties:
            CodeUri: dist/src/useCases/MyFunc/
            Handler: MyFunc.handler
            Runtime: nodejs20.x
            MemorySize: 1024
            Timeout: 99
            Policies:
                - CloudWatchLambdaInsightsExecutionRolePolicy
                - S3CrudPolicy:
                    BucketName: 'my-bucket'
                - SQSSendMessagePolicy:
                    QueueName: !GetAtt MyQueue.QueueName
            Events:
                Api:
                    Type: Api
                    Properties:
                        Path: /my-func
                        Method: POST
                        RestApiId:
                            Ref: ApiGateway
```
This is how I run sam for the lambda stack:
```
sam deploy --template-file template.yml --stack-name MyCodeStack --no-confirm-changeset --resolve-s3 --region eu-central-1 --capabilities CAPABILITY_IAM
```

Here is the snipped from the CF template of the S3 bucket, it is a separate stack in the same account:
```
MyBucket:
        Type: AWS::S3::Bucket
        DeletionPolicy: Delete
        Properties:
            OwnershipControls:
                Rules:
                - ObjectOwnership: ObjectWriter
            BucketName: my-bucket
```
This is how I run sam for the S3 stack:
```
sam deploy --template-file template_s3.yml --stack-name MyBucketStack --no-confirm-changeset --resolve-s3 --region eu-central-1 --capabilities CAPABILITY_IAM
```

I am using sam cli on MacOS 14.1.2:
`SAM CLI, version 1.103.0`
