### ISSUE TITLE
Bug: Creates unnecessary AWSLambdaVPCAccessExecutionRole  role

### ISSUE THREAD

**Issue by fade2black** [aws/aws-sam-cli#6553]
### Description:
SAM seems to add `AWSLambdaVPCAccessExecutionRole` simply because it detects the `VpcConfig` without checking the condition. 

### Steps to reproduce:

I create a simple hello-world lambda function as following:

```yaml
AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Parameters:
  SecurityGroupIds:
    Type: String
    Default: ""
  SubnetIds:
    Type: String
    Default: ""

Conditions:
  AlwaysFalseCondition: !Equals 
    - "123"
    - "345"

Resources:
  WorkerFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: HelloWorld
      PackageType: Image
      Architectures:
        - x86_64
      MemorySize: 2048
      Timeout: 30
      VpcConfig:
        !If 
          - AlwaysFalseCondition
          -  
            SecurityGroupIds: !Split [ ",", !Ref SecurityGroupIds ] 
            SubnetIds: !Split [ ",", !Ref SubnetIds ] 
          - !Ref AWS::NoValue
    Metadata:
        DockerTag: mytag
        DockerContext: ./lib
        Dockerfile: Dockerfile
```

and deploy it as following
```bash
sam build
sam deploy --config-env dev --resolve-image-repos --no-confirm-changeset --no-fail-on-empty-changeset
```
### Observed result:

When it successfully finishes deployment I go to my lambda function and check `Configuration` -> `VPC`. There is no associated security group or subnet. However, when I check the created role it contains two AWS Managed Policies:
- AWSLambdaBasicExecutionRole
- AWSLambdaVPCAccessExecutionRole

### Expected result:
Because the condition under the `VpcConfig` section is always false, it does not associate the lambda with a subnet and a security group as expected. I also expect the sam not to add unnecessary permission `AWSLambdaVPCAccessExecutionRole` because I don't associate the lambda with any VPC. Nevertheless, it adds  `AWSLambdaVPCAccessExecutionRole`.

### Additional environment details (Ex: Windows, Mac, Amazon Linux etc)

1. OS: macOS,  Sonoma 14.2
2. `sam --version`: 1.105.0
3. AWS region: eu-central-1
