### ISSUE TITLE
Question: different buckets

### ISSUE THREAD

**Issue by fade2black** [aws/aws-sam-cli#6581]
When I generate a pipeline using `sam pipeline ...` it guides me through a process by asking questions. One of them is about bucket (for prod env). I enter a bucket name `mybucket123` and the SAM adds the following lines inside `codepipeline.yml` file
```yaml
...
Parameters:
  ProdArtifactBucket:
    Type: String
    Default: "mybucket123"
.... 
```
and associates `ProdArtifactBucket` with the `ENV_BUCKET` env var.

It also creates two buckets (with corresponding policies):

```yaml
  ...
  PipelineArtifactsBucket:
    Type: AWS::S3::Bucket
    DeletionPolicy: Retain
    UpdateReplacePolicy: Retain
    Properties:
    ...

  PipelineArtifactsLoggingBucket:
    Type: AWS::S3::Bucket
    DeletionPolicy: Retain
    UpdateReplacePolicy: Retain
    Properties:
    ...
```
and uses the bucket I entered for `sam deploy` command 
```bash
sam deploy --stack-name ${ENV_STACK_NAME}
                    --template ${ENV_TEMPLATE}
                    --capabilities CAPABILITY_IAM
                    --region ${ENV_REGION}
                    --s3-bucket ${ENV_BUCKET}
                   ...
```
So my question is: why does SAM ask for a bucket (for artifacts) if it creates a new one to download code, etc? Can't we just use the newly created bucket for `sam deploy`?
