### ISSUE TITLE
Bug: SAM Doesn't recognize changes related to intrinsic functions

### ISSUE THREAD

**Issue by shivushedad** [aws/aws-sam-cli#6610]
### Description:
I am trying to update my template from using `!Join` to `!Sub` and when I run `sam build` I can clearly see the changed template under `.aws-sam\build\template.yaml` file; however when I run `sam deploy` (with all the required arguments) I get `Error: No changes to deploy. Stack stack-test is up to date`

### Steps to reproduce:
Created a sample stack template to reproduce this.
1. Initial template:
```
AWSTemplateFormatVersion: 2010-09-09
Transform: AWS::Serverless-2016-10-31
Description: sample stack configuration
Parameters:
  ProjectName:
    Type: String
    Description: The name of the project
    Default: test-oauth-connection
  OktaTokenURL:
    Type: String
    Description: The Okta token URL
    Default: https://okta.com/oauth2/default/v1/token
  APISecretKey:
    Type: String
    Description: The secret key for the legacy API
    Default: api-secret-key

Resources:
  OAuthConnection:
    Type: AWS::Events::Connection
    Properties:
      Name: !Join
        - '-'
        - - !Ref ProjectName
          - oauth-connection
      AuthorizationType: OAUTH_CLIENT_CREDENTIALS
      AuthParameters:
        OAuthParameters:
          ClientParameters:
            ClientID: !Join
              - ':'
              - - '{{resolve:secretsmanager'
                - !Ref APISecretKey
                - 'SecretString:client_id}}'
            ClientSecret: !Join
              - ':'
              - - '{{resolve:secretsmanager'
                - !Ref APISecretKey
                - 'SecretString:client_secret}}'
          AuthorizationEndpoint: !Ref OktaTokenURL
          HttpMethod: POST
          OAuthHttpParameters:
            BodyParameters:
              - Key: grant_type
                Value: client_credentials
                IsValueSecret: false
              - Key: client_id
                Value: !Join
                  - ':'
                  - - '{{resolve:secretsmanager'
                    - !Ref APISecretKey
                    - 'SecretString:client_id}}'
                IsValueSecret: false
```
2. Run the `sam deploy` command with the template above and stack gets created successfully. However one observation is that the string `'SecretString:client_id}}'` somehow shows up without quotes when I look at the template on AWS Console Cloudformation service (This probably is a separate issue, due to this whenever I do an update to the stack I get an error: `Error: Failed to create changeset for the stack For expression "Status" we matched expected path: "FAILED" Status: FAILED. Reason: Template error: every Fn::Join object requires two parameters, (1) a string delimiter and (2) a list of strings to be joined or a function that returns a list of strings (such as Fn::GetAZs) to be joined.`).
3. Go ahead and swap `!Join` calls to `!Sub`. Example below:
```
Key: client_id
Value: !Sub
  - '{{resolve:secretsmanager:${APISecretVar}:SecretString:client_id}}'
  - APISecretVar: !Ref APISecretKey
```
4. Do `sam build` and `sam deploy`.

### Observed result:
I get an error when sam tries to create change-set `Error: No changes to deploy. Stack stack-test is up to date`

### Expected result:
Expecting to see it update the stack with latest template as I am now using a different intrinsic function.

### Additional environment details (Ex: Windows, Mac, Amazon Linux etc)

1. OS: Windows
6. `sam --version`: `SAM CLI, version 1.108.0`
7. AWS region: us-east-1

```
{
  "version": "1.108.0",
  "system": {
    "python": "3.11.7",
    "os": "Windows-10-10.0.19045-SP0"
  },
  "additional_dependencies": {
    "docker_engine": "24.0.6",
    "aws_cdk": "Not available",
    "terraform": "1.6.5"
  },
  "available_beta_feature_env_vars": [
    "SAM_CLI_BETA_FEATURES",
    "SAM_CLI_BETA_BUILD_PERFORMANCE",
    "SAM_CLI_BETA_TERRAFORM_SUPPORT",
    "SAM_CLI_BETA_RUST_CARGO_LAMBDA"
  ]
}
```

`Add --debug flag to command you are running`
