### ISSUE TITLE
Is FullAccess Role secure?

### ISSUE THREAD

**Issue by fade2black** [aws/aws-sam-cli#6671]
I generate a pipeline using `sam` CLI which creates the following role:

```yml
PipelineStackCloudFormationExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          Action: "sts:AssumeRole"
          Effect: Allow
          Principal:
            Service: cloudformation.amazonaws.com
      Policies:
        - PolicyName: GrantCloudFormationFullAccess
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action: '*'
                Resource: '*'
```
and used (assumed) like this
```yml
  - Name: CreateChangeSet
     ActionTypeId:
        Category: Deploy
        Owner: AWS
        Provider: CloudFormation
        Version: "1"
      Configuration:
         ActionMode: CHANGE_SET_REPLACE 
         RoleArn: !GetAtt PipelineStackCloudFormationExecutionRole.Arn
         StackName: !Ref AWS::StackName
         ChangeSetName: !Sub ${AWS::StackName}-ChangeSet
         TemplatePath: SourceCodeAsZip::codepipeline.yml
         Capabilities: CAPABILITY_NAMED_IAM
      InputArtifacts:
          - Name: SourceCodeAsZip
      RunOrder: 1
```
Is it secure to deploy and use such pipeline?
