### ISSUE TITLE
Bug: No new Lambda Versions are deployed with Lambda configurations changes 

### ISSUE THREAD

**Issue by mriccia** [aws/aws-sam-cli#7102]
### Description:

When there is a SAM template with a Lambda function property `AutoPublishAlias`, I expect that changes to the Lambda function will publish a new Lambda Version.
However, it seems that a new Version is not published in certain scenarios, if there are no code changes. For example: changes to the Logging configuration, and changes to the description.

### Steps to reproduce:

1. `sam build && sam deploy` a SAM project with a Lambda function with the `AutoPublishAlias` set
2. Make changes to the Logging configuration
3. `sam build && sam deploy` the project again

### Observed result:

The Lambda configuration has changed, however there's no new version published

### Expected result:

A new Lambda Version is published and the Alias is updated

### Additional environment details (Ex: Windows, Mac, Amazon Linux etc)

1. OS: Mac OS
4. `sam --version`: SAM CLI, version 1.115.0  
5. AWS region: `eu-west-2`

```
sam --info --debug
{ 
  "version": "1.115.0",
  "system": {
    "python": "3.12.3",
    "os": "macOS-14.4.1-arm64-arm-64bit"
  },
  "additional_dependencies": {
    "docker_engine": "25.0.3",
    "aws_cdk": "2.139.0 (build 2699ffd)",
    "terraform": "1.4.2"
  },
  "available_beta_feature_env_vars": [
    "SAM_CLI_BETA_FEATURES",
    "SAM_CLI_BETA_BUILD_PERFORMANCE",
    "SAM_CLI_BETA_TERRAFORM_SUPPORT",
    "SAM_CLI_BETA_RUST_CARGO_LAMBDA"
  ]
}

```

`Add --debug flag to command you are running`

**Comment by lucashuy** [comment]
Hi, thanks for opening this issue. Unfortunately I'm not able to produce the issue following these steps:
## 1. Initial state
1. `sam init` a hello world NodeJS function
2. modify the function to look something like this:
```
Resources:
  HelloWorldFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: hello-world/
      Handler: app.lambdaHandler
      Runtime: nodejs20.x
      Architectures:
        - x86_64
      Description: "foo1"
      VersionDescription: "bar1"
      AutoPublishAlias: gh7102alias
```
3. `sam build`
4. `sam deploy`

This deploys successfully with a Lambda version 1.

## 2. Adding `LoggingConfig` and update description
1. modify the function
```
Resources:
  HelloWorldFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: hello-world/
      Handler: app.lambdaHandler
      Runtime: nodejs20.x
      Architectures:
        - x86_64
      Description: "foo2"
      VersionDescription: "bar2"
      AutoPublishAlias: gh7102alias
      LoggingConfig:
          ApplicationLogLevel: DEBUG
          LogFormat: JSON
          SystemLogLevel: DEBUG
```
2. `sam build`
3. `sam deploy`

I can see that the description for the original function's description is updated, along with the version's description. Additionally, a new Lambda version was published with the new logging changes to the original function.

**Comment by mriccia** [comment]
Hello @lucashuy , thanks for the prompt response.
What's triggering the new version deployment in the steps you shared is the `VersionDescription`. 
Without `VersionDescription` I can consistently see the Lambda Configuration being updated, without a new version being published.
Please can you test with the following steps?

## Initial state

1. `sam init` a hello world NodeJS function
2. modify the function to look something like this:
```
Resources:
  HelloWorldFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: hello-world/
      Handler: app.lambdaHandler
      Runtime: nodejs20.x
      Architectures:
        - x86_64
      Description: "foo1"
      AutoPublishAlias: gh7102alias
```
3. `sam build`
4. `sam deploy`

This deploys successfully with a Lambda version 1.

## Adding LoggingConfig and update description

1. modify the function
```
Resources:
  HelloWorldFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: hello-world/
      Handler: app.lambdaHandler
      Runtime: nodejs20.x
      Architectures:
        - x86_64
      Description: "foo2"
      AutoPublishAlias: gh7102alias
      LoggingConfig:
          ApplicationLogLevel: DEBUG
          LogFormat: JSON
          SystemLogLevel: DEBUG
```
2. `sam build`
3. `sam deploy`

I can see that the description and logging configuration for the original function are updated, but there isn't a new Lambda Version published.
