### ISSUE TITLE
Feature request: Support for Python requirements files with different names

### ISSUE THREAD

**Issue by eruvanos** [aws/aws-sam-cli#7180]
### Describe your idea/feature/enhancement

I am using [rye](https://rye.astral.sh/) to manage my dependencies.
While the tool is pretty new, it basically generates a `requirements.txt` called `requirements.lock`.

I wish the AWS Lambda Builders would allow to specify the manifest file within the MetaData, so I could direct it to `requirements.lock` file instead of `requirements.txt`

### Proposal

Add details on how to add this to the product.

### Additional Details

Example configuration I could imagine.

```
  BrokerFunction:
    Type: AWS::Serverless::Function
    Metadata:
      Manifest: requirements.lock
```
