### ISSUE TITLE
"sam build" feedback: Don't fail if dependency manifest (requirements.txt) is not found

### ISSUE THREAD

**Issue by sanathkr** [aws/aws-sam-cli#784]
**Description:**
`sam build` always looks for the presence of a dependency manifest like requirements.txt. If it is not present, the command fails. Customers without any dependencies might not have a manifest. 

One recommendation was to resolve dependencies if a manifest is present, if not skip. This will create false-positives where customers can `sam build` and it didn't resolve dependencies because it was looking for manifest in the wrong location. We can print a warning if we did not find any dependency manifest so customers will know what is happening.

As a workaround, customers can always create an empty manifest - `requirements.txt` so SAM CLI continues to work.

**Comment by brysontyrrell** [comment]
I just hit this too testing out `sam build`. It shouldn't be assumed that every Lambda will have a requirements.txt file.

**Comment by superwese** [comment]
especially if the function refers to external sources
```yaml 
MyLambda:
    Type: AWS::Serverless::Function
    Properties:
      Handler: requeue.handler
      Runtime: python2.7
      CodeUri:
        Bucket: !Ref 'SharedSourcesBucket'
        Key: 'sqs/requeue.zip'
```
