### ISSUE TITLE
Feature request: Add region config to `default.global.parameters`

### ISSUE THREAD

**Issue by niklas-palm** [aws/aws-sam-cli#7841]
### Describe your idea/feature/enhancement

I wish SAM CLI would add the region configuration to `default.global.parameters` in the `samconfig.toml`.

Currently, when using `sam init´ the samconfig is generated based on the user input, and the only property in `default.global.parameters` is the stack_name. The region parameter is added under `default.deploy.parameters` which means that all `sam deploy` commands will use the specified region. However, `sam sync` uses the default region in the local installation of the AWS CLI configuration, which causes a lot of misstakes and deployments to the wrong region.

### Proposal

Add region to `default.global.parameters` to ensure all deployment using `sam sync` use the same configured region.

Things to consider:
1. Will this require any updates to the [SAM Spec](https://github.com/awslabs/serverless-application-model)
No.

**Comment by roger-zhangg** [comment]
Thanks for reaching out. Currently the region is read from the `~/.aws/config` by default if not provided in parameter. I do think adding region in samconfig.toml could improve UX in few cases and we always welcome contribution. If you already have few thoughts in mind, feel free to draft a PR for this feature. Thank you

**Comment by niklas-palm** [comment]
My pleasure. 
The region is read from `~/.aws/config` unless it's specified in the `samconfig`, which it is if the user uses `--guided`with the first deploy and stores the parameters.

During `sam deploy --guided`, the user is prompted with setting defaults:

```bash
	Setting default arguments for 'sam deploy'
	=========================================
	Stack Name [test]: 
	AWS Region [eu-west-1]: 
	#Shows you resources changes to be deployed and require a 'Y' to initiate deploy
	Confirm changes before deploy [Y/n]: 
	#SAM needs permission to be able to create roles to connect to the resources in your template
	Allow SAM CLI IAM role creation [Y/n]: 
	#Preserves the state of previously provisioned resources when an operation fails
	Disable rollback [y/N]: 
	HelloWorldFunction has no authentication. Is this okay? [y/N]: y
	Save arguments to configuration file [Y/n]: 
	SAM configuration file [samconfig.toml]: 
	SAM configuration environment [default]: 
```

This produces the below config: 

```toml
# More information about the configuration file can be found here:
# https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/serverless-sam-cli-config.html
version = 0.1

[default.global.parameters]
stack_name = "test"

[default.build.parameters]
cached = true
parallel = true

[default.validate.parameters]
lint = true

[default.deploy.parameters]
capabilities = "CAPABILITY_IAM"
confirm_changeset = true
resolve_s3 = true
s3_prefix = "test"
region = "eu-west-1"
image_repositories = []

[default.package.parameters]
resolve_s3 = true

[default.sync.parameters]
watch = true

[default.local_start_api.parameters]
warm_containers = "EAGER"

[default.local_start_lambda.parameters]
warm_containers = "EAGER"
```

The region is specified in `default.deploy.parameters` which means all future `sam deploy` will use that region. 
`sam sync`, however, will use the region specified in `~/.aws/config`. 

This is not a desired behaviour.

Given me limited exposure to building CLIs with Click, I can't really identify where in the source code the samconfig is generated, and where a deploy with the `--guided` flag would write to that it. If you point me in the right direction I can have a look.
