### ISSUE TITLE
Bug: Fails to validate valid CloudFormation syntax

### ISSUE THREAD

**Issue by scolebrook** [aws/aws-sam-cli#7881]
### Description:
`sam validate` relies on `cfn-lint`. SAM currently uses 1.20.1. Current version with up to date CloudFormation schema is 1.22.4. Example use case is adding the new PointInTimeRecoverySpecification.RecoveryPeriodInDays property to a DynamoDB table resource. `cfn-lint` 1.22.4 validates the template. SAM 1.132.0 doesn't, giving the following error message (generated mostly by the out of date `cfn-lint`):
```
[[E3002: Resource properties are invalid] (Additional properties are not allowed ('RecoveryPeriodInDays' was unexpected)) matched 151]
Error: Linting failed. At least one linting rule was matched to the provided template.
```
#7827 Did not resolve the issue.

### Steps to reproduce:
Add the following resource to an otherwise valid SAM template:
```yaml
  table:
    Type: "AWS::DynamoDB::Table"
    Properties:
      TableName: "MyTable"
      AttributeDefinitions:
        - AttributeName: "pk"
          AttributeType: "S"
      KeySchema:
        - AttributeName: "pk"
          KeyType: "HASH"
      PointInTimeRecoverySpecification:
        PointInTimeRecoveryEnabled: true
        RecoveryPeriodInDays: 7
```
Run `sam validate`.

### Observed result:
Error message.

### Expected result:
Passing validation.

### Additional environment details (Ex: Windows, Mac, Amazon Linux etc)
```json
{
  "version": "1.133.0",
  "system": {
    "python": "3.11.10",
    "os": "macOS-15.3-x86_64-i386-64bit"
  },
  "additional_dependencies": {
    "docker_engine": "Not available",
    "aws_cdk": "2.26.0 (build a409d63)",
    "terraform": "1.10.5"
  },
  "available_beta_feature_env_vars": [
    "SAM_CLI_BETA_FEATURES",
    "SAM_CLI_BETA_BUILD_PERFORMANCE",
    "SAM_CLI_BETA_TERRAFORM_SUPPORT",
    "SAM_CLI_BETA_RUST_CARGO_LAMBDA"
  ]
}
```

**Comment by mbfreder** [comment]
Hi, thanks for reporting this. This validation error is occurring because your SAM CLI (v1.133.0) is using an outdated CloudFormation specification that doesn't recognize the `RecoveryPeriodInDays` property, which is a valid and relatively recent addition to DynamoDB tables. The simplest solution is to update your SAM CLI to the latest version (v1.135.0).

After updating, please try running sam validate again. The latest version should include updated CloudFormation specifications that recognize the RecoveryPeriodInDays property.

**Comment by vicheey** [comment]
I am able to run `sam validate` successfully for the following template using SAM
```
sam --version
SAM CLI, version 1.134.0
```

```
AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31

Resources:
  table:
    Type: "AWS::DynamoDB::Table"
    Properties:
      TableName: "MyTable"
      AttributeDefinitions:
        - AttributeName: "pk"
          AttributeType: "S"
      KeySchema:
        - AttributeName: "pk"
          KeyType: "HASH"
      PointInTimeRecoverySpecification:
        PointInTimeRecoveryEnabled: true
        RecoveryPeriodInDays: 7

```
