### ISSUE TITLE
Question: Can't deploy “AWS::Notifications::*” Resource?

### ISSUE THREAD

**Issue by DogFortune** [aws/aws-sam-cli#7911]
Hi.

I would like to deploy an “AWS::Notifications::*” resource in SAM. 
But I get the following error and cannot deploy it.

```
[[E3006: Validate the CloudFormation resource type] (Resource type 'AWS::Notifications::NotificationConfiguration' does not exist in 'us-east-1') matched 282,
[E3006: Validate the CloudFormation resource type] (Resource type 'AWS::Notifications::EventRule' does not exist in 'us-east-1') matched 288,
[E3006: Validate the CloudFormation resource type] (Resource type 'AWS::Notifications::ChannelAssociation' does not exist in 'us-east-1') matched 307,
[E3006: Validate the CloudFormation resource type] (Resource type 'AWS::NotificationsContacts::EmailContact' does not exist in 'us-east-1') matched 312]
Error: Linting failed. At least one linting rule was matched to the provided template.
```

SAM does not support the “AWS::Notifications::*” resource?

## Environment
- SAM CLI, version 1.134.0

**Comment by DogFortune** [comment]
@seshubaws OK. SAM template attached.

```yaml
AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: UserNotification
Resources:
  Configuration1:
    Type: AWS::Notifications::NotificationConfiguration
    Properties:
      Name: hogenotification1
      Description: hogehoge
      AggregationDuration: SHORT
  Rule1:
    Type: AWS::Notifications::EventRule
    Properties:
      NotificationConfigurationArn: !Ref Configuration1
      Source: aws.cloudwatch
      EventPattern: |
        {
          "detail": {
            "state": {
              "value": [
                "ALARM"
              ]
            }
          }
        }
      EventType: "CloudWatch Alarm State Change"
      Regions:
        - ap-northeast-1
  Channel1:
    Type: AWS::Notifications::ChannelAssociation
    Properties:
      Arn: !Ref Email1
      NotificationConfigurationArn: !Ref Configuration1
  Email1:
    Type: AWS::NotificationsContacts::EmailContact
    Properties:
      Name: Notify
      EmailAddress: example.com
```

Running `sam validate` should reproduce this.
