### ISSUE TITLE
aws cloudformation package should preserve comments and order

### ISSUE THREAD

**Issue by ranman** [aws/aws-sam-cli#8]
Given the `template.yaml`:
```yaml
AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Resources:
  # This is a comment
  VotesTable:
    Type: AWS::Serverless::SimpleTable
  VoteSpacesTabs:
    # this is another comment
    Type: AWS::Serverless::Function
    Properties:
      Handler: lambda_function.lambda_handler
      Policies: AmazonDynamoDBFullAccess
      Runtime: python3.6
      Environment:
        Variables:
          TABLE_NAME:
            Ref: VotesTable
      Events:
        Vote:
          Properties:
            Method: post
            Path: /
          Type: Api
      Timeout: 10
```

And the command:
`aws cloudformation package --template-file `pwd`/template.yaml --s3-bucket ranman-code --output-template-file package.yaml`

package.yaml should have:
```yaml
AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Resources:
  # This is a comment
  VotesTable:
    Type: AWS::Serverless::SimpleTable
  VoteSpacesTabs:
    # this is another comment
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: s3://ranman-code/97402a11ac040008e15358ccc872f799
      Handler: lambda_function.lambda_handler
      Policies: AmazonDynamoDBFullAccess
      Runtime: python3.6
      Environment:
        Variables:
          TABLE_NAME:
            Ref: VotesTable
      Events:
        Vote:
          Properties:
            Method: post
            Path: /
          Type: Api
      Timeout: 10
```

Instead it has:

```yaml
AWSTemplateFormatVersion: '2010-09-09'
Resources:
  VoteSpacesTabs:
    Properties:
      CodeUri: s3://ranman-code/97402a11ac040008e15358ccc872f799
      Environment:
        Variables:
          TABLE_NAME:
            Ref: VotesTable
      Events:
        Vote:
          Properties:
            Method: post
            Path: /
          Type: Api
      Handler: lambda_function.lambda_handler
      Policies: AmazonDynamoDBFullAccess
      Runtime: python3.6
      Timeout: 10
    Type: AWS::Serverless::Function
  VotesTable:
    Type: AWS::Serverless::SimpleTable
Transform: AWS::Serverless-2016-10-31
```
