### ISSUE TITLE
Bug: Environment variables from --env-vars file not injected

### ISSUE THREAD

**Issue by mikeesto** [aws/aws-sam-cli#8046]
### Description:
`sam local invoke` and `sam local start-api` fail to inject environment variables specified via the `--env-vars` (or `-n`) JSON file into the local Lambda execution environment. This seems to occur even with the simplest possible application. 

Perhaps I have misunderstood something? 😓 

### Steps to reproduce:
I've created a minimal SAM application in a new directory:

```python
# app.py
import os
import json

def lambda_handler(event, context):
    my_var = os.environ.get("MY_TEST_VARIABLE")
    another_var = os.environ.get("ANOTHER_TEST_VARIABLE")
    all_vars = dict(os.environ)

    print(f"MY_TEST_VARIABLE: {my_var}")
    print(f"ANOTHER_TEST_VARIABLE: {another_var}")
    print("--- ALL ENV VARS IN LAMBDA ---")
    print(json.dumps(all_vars, indent=2))
    print("------------------------------")

    return {
        "statusCode": 200,
        "body": json.dumps({
            "message": "Hello from simple test",
            "my_test_variable": my_var,
            "another_test_variable": another_var
        }),
    }
```

```yaml
# template.yaml
AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Resources:
  SimpleFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: app.lambda_handler
      Runtime: python3.12
      CodeUri: .
      Events:
        HelloWorld:
          Type: HttpApi
          Properties:
            Path: /hello
            Method: get
```

```json
{
  "SimpleFunction": {
    "MY_TEST_VARIABLE": "Hello from env.json!",
    "ANOTHER_TEST_VARIABLE": "This is another test variable."
  }
}
```

Run `sam build`.

Attempt to invoke lambda locally with environment variables from JSON file: `sam local invoke SimpleFunction -n env_vars_test.json --event event.json --debug`

### Observed result:
The `--debug` output from `sam local invoke` (and `sam local start-api`) suggests that SAM CLI does not find or apply the environment variables:

```
2025-05-24 11:45:44,263 | Invoking app.lambda_handler (python3.12)
2025-05-24 11:45:44,263 | No environment variables found for function 'SimpleFunction' 
2025-05-24 11:45:44,263 | Environment variables data found for specific function in standard format
```
I don't really understand how to reconcile the second and third lines?

The Python print statements from `app.py` confirm the variables are not set:

```
START RequestId: 4e8d8866-d99e-4fcf-993d-276ce4252cc3 Version: $LATEST
MY_TEST_VARIABLE: None
ANOTHER_TEST_VARIABLE: None
--- ALL ENV VARS IN LAMBDA ---
{
  "AWS_LAMBDA_FUNCTION_VERSION": "$LATEST",
  "AWS_EXECUTION_ENV": "AWS_Lambda_python3.12",
  "HOSTNAME": "1d0040595e25",

...etc
```

### Expected result:
When running `sam local invoke SimpleFunction -n env_vars_test.json --event event.json`, the environment variables `MY_TEST_VARIABLE` and `ANOTHER_TEST_VARIABLE` (and any others defined in `env_vars_test.json` for SimpleFunction) should be set.

I was imagining the print statements to show:

```
MY_TEST_VARIABLE: Hello from env.json!
ANOTHER_TEST_VARIABLE: This is another test variable.
```

### Additional environment details (Ex: Windows, Mac, Amazon Linux etc)

1. OS: Debian
2. `sam --version`: SAM CLI, version 1.137.1 . I also tried version 1.139.0 on another machine.

```
michael@debian-ad-api:~/sam_env_test$ sam --info
{
  "version": "1.137.1",
  "system": {
    "python": "3.11.10",
    "os": "Linux-6.13.7-orbstack-00283-g9d1400e7e9c6-aarch64-with-glibc2.36"
  },
  "additional_dependencies": {
    "docker_engine": "28.1.1",
    "aws_cdk": "Not available",
    "terraform": "Not available"
  },
  "available_beta_feature_env_vars": [
    "SAM_CLI_BETA_FEATURES",
    "SAM_CLI_BETA_BUILD_PERFORMANCE",
    "SAM_CLI_BETA_TERRAFORM_SUPPORT",
    "SAM_CLI_BETA_PACKAGE_PERFORMANCE",
    "SAM_CLI_BETA_RUST_CARGO_LAMBDA"
  ]
}
```

**Comment by geophpherie** [comment]
It doesn't really scream at you from the docs but:

> Environment variable file
> 
> To declare environment variables locally that override values defined in your templates, do the following:
> 
> 1. Create a JSON file that contains the environment variables to override.
> 
> 2. Use the --env-vars argument to override values defined in your templates.

With the key point being _that override values defined in your templates_. So basically for it to work it can only override existing env vars that are in the template, not inject new ones. So you need to update your template to first have environment vars that can be overridden i.e:

```yml
      Events:
        HelloWorld:
          Type: HttpApi
          Properties:
            Path: /hello
            Method: get
      Environment:
        Variables:
          MY_TEST_VARIABLE: ""
          ANOTHER_TEST_VARIABLE: ""

```

with that I get:

```terminal
MY_TEST_VARIABLE: Hello from env.json!
ANOTHER_TEST_VARIABLE: This is another test variable.
--- ALL ENV VARS IN LAMBDA ---
```
