### ISSUE TITLE
Generic Build Proposal

### ISSUE THREAD

**Issue by j** [aws/aws-sam-cli#858]
Putting a quick list of what was discussed in #samdev.

The builder implementation is great and `sam build` is exactly what we need.  It seems to be missing the ability to go above and beyond typical build solutions.  The builder (for node.js) as it stands expects the function code to build for the exact runtime.  The issue is that most people use updated versions of node.js (or typescript) and deploy to older node.js runtimes that Lambda supports, as well as a majority of people need more advanced building.  Popular tools like https://github.com/zeit/ncc, https://webpack.js.org/, gulp, browserify, babel, etc, etc, help build stuff that can compile down to AWS Lambda specific versions, perform minification, optimize images, etc, etc.  It would be great if anyone who uses sam can also build using the tools they wish.  We personally use serverless with functions that utilize webpack (react apps), and typescript (tsc -b).

I'm proposing a more generic builder solution for anyone to implement their own build functionality that other Lambda deployment tools have.

## Apex Up (https://up.docs.apex.sh/)
Up has an .upignore and up.json file.  The up.json file can contain custom build commands:
```json
{
  "name": "app",
  "hooks": {
    "build": "browserify --node app.js > server.js",
    "clean": "rm server.js"
  }
}
```

## Serverless
There are tons of build plugins for serverless (typescript, webpack, browserify, etc, etc)

# Sam Proposal
It'd be awesome if we can take from what's been around for a while and that people are used to and implement it.  Automated builds is awesome, but not flexible.  If each lambda function could contain their own build directions, that'd make it more flexible.

#### template.yaml
```yaml
Resources:
    FunctionOne:
        Type: AWS::Serverless::Function
        Properties:
            CodeUri: one/
            Build:
                PreBuild: "npm install"
                Build: " npm run build"
                PostBuild: "npm install --production"
                Exclude:
                    - src/**
                    - node_modules/.bin/**
                    - node_modules/foo/.bin/bar
            Handler: one.handler
            Runtime: nodejs8.10
            Events:
                One:
                    Type: Api
                    Properties:
                        Path: /one
                        Method: get
    FunctionTwo:
        Type: AWS::Serverless::Function
        Properties:
            CodeUri: two/
            Build:
                PreBuild: "npm install"
                Build: " npm run build"
                PostBuild: "npm install --production"
            Handler: two.handler
            Runtime: nodejs8.10
            Events:
                Two:
                    Type: Api
                    Properties:
                        Path: /two
                        Method: get
```

#### OR sam.json & .samignore files contained in the function directory (not preferred)
```json
{
  "scripts": {
    "prebuild": "PUPPETEER_SKIP_CHROMIUM_DOWNLOAD=true npm install",
    "build": "tsc -b",
    "postbuild": "npm install --production"
  }
}
```
Example of excluding everything and cherry picking what's needed.. you should be able to do the opposite of this too.
```
**
!dist/**
!node_modules/**
!.env
!shared/**
node_modules/some-package/.bin/some-large-unneeded-file
```

You can go even further and look at `scripts.build` inside of package.json and do this in the NPM builder, but I think keeping it simple would be best.

I'm more in favor with keeping everything inside of template.yaml if possible.
